### ISSUE TITLE
Confused Documentation

### ISSUE THREAD

**Issue by johndodev** [sendgrid/docs#1005]
Hello

The page https://sendgrid.com/docs/User_Guide/Email_Deliverability/Subscription_Tracking/suppressions_vs_unsubscribes.html says *Group Unsubscribes do not currently trigger Event Webhook events.* but the page https://sendgrid.com/docs/API_Reference/Webhooks/event.html says it does.

Also, the doc menu is a little bit confusing to me since *Subscription tracking* seems to share some similarity with *Supression Tracking*. 

Thanks for your work !

**Comment by mbernier** [comment]
Yes, apologies. This has been rectified!
