### ISSUE TITLE
Enumerated list of SPF & DKIM field options on Parse Webhook

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#1016]

**Comment by thinkingserious** [comment]
Hello @jacobmovingfwd,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
