### ISSUE TITLE
Event Webhook page has no description of timestamp property

### ISSUE THREAD

**Issue by vanillajonathan** [sendgrid/docs#1026]
https://sendgrid.com/docs/API_Reference/Webhooks/event.html

There is no description of the `timestamp` property.

**Comment by mbernier** [comment]
Thank you! I have it on the list of things to add to this page (including explaining ALL of the return fields)

**Comment by mbernier** [comment]
https://sendgrid.com/docs/Glossary/timezone.html has covered this, I believe.
