### ISSUE TITLE
Rendering on Document Page has unescaped header tags

### ISSUE THREAD

**Issue by estsauver** [sendgrid/docs#1053]
See: 

https://github.com/sendgrid/docs/blob/develop/source/Integrate/libraries.md

which was linked to from the docs page.

**Comment by estsauver** [comment]
Here's the page which had the link there: https://sendgrid.com/docs/Integrate/libraries.html

The text was in:
```
If you create a library, please let us know, by adding your library to this page.
```

**Comment by mbernier** [comment]
Since our docs are open source, you can edit our page and add your library to it. I think the wording could be improved so I will fix that up this morning.

**Comment by estsauver** [comment]
This issue isn't about adding any library to the page. Your markdown has unescaped tags {% anchor h2 %} that should be something along the lines of either "##" at the start of the line or underlining using --------/==========.

**Comment by mbernier** [comment]
We are using Jekyll, which has support for liquid tags. With that support, we have added a header tag that allows us to generate linked header tags from the {% anchor h2 %} liquid tag. 

While proper markdown would be... proper, this liquid tags give us some extra functionality.
