### ISSUE TITLE
v2 api  category list malformed

### ISSUE THREAD

**Issue by asiSendGrid** [sendgrid/docs#1114]
the current call `https://api.sendgrid.com/api/stats.get.json` will only return stats.. If you add the `list=true` you will retrieve the entire list of categories. Below is how I got the call to work

```
curl -X "POST" "https://api.sendgrid.com/api/stats/get.json?api_user=Sg_Credential&api_key=Sg_Credential&list=true" \
    -H "Content-Type: application/json" \
    -H "Accept: application/json"
```

**Comment by thinkingserious** [comment]
Hello @asiSendGrid,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
