### ISSUE TITLE
v3 Subuser API - additional FYI information

### ISSUE THREAD

**Issue by asiSendGrid** [sendgrid/docs#1134]
As of right now, the customer can only create a Subuser with the Primary Login of the Parent account. It would be a lot of help if we can have a disclaimer of this. Perhaps mentioning that **"API Keys & Multiple Credentials"** will not be accepted for the Subuser creation. [Create-Subuser-POST](https://sendgrid.com/docs/API_Reference/Web_API_v3/subusers.html#Create-Subuser-POST)

**Comment by mbernier** [comment]
When do we expect this to change?

**Comment by thinkingserious** [comment]
Hello @asiSendGrid,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
