### ISSUE TITLE
API Keys & sub-users

### ISSUE THREAD

**Issue by chrissnell** [sendgrid/docs#1139]
We currently use sub-user usernames and passwords to authenticate to Sendgrid SMTP servers.  This gives us reporting through the portal.  If we switch to using API keys, I'm guessing we lose sub-user reporting.   How can we avoid this?   Is there a way to tie one API key to one sub-user account?

https://sendgrid.com/docs/Classroom/Send/api_keys.html

**Comment by chrissnell** [comment]
OK, digging deeper, I realized that I would have to log on as each sub-user and generate a key.  Perhaps the docs can be updated to make this more clear.

**Comment by mbernier** [comment]
You can generate API Keys via the API as well - so you don't have to do this manually. 
https://sendgrid.com/docs/API_Reference/Web_API_v3/API_Keys/index.html
