### ISSUE TITLE
Integrate with SendGrid

### ISSUE THREAD

**Issue by HaythemYahyaoui** [sendgrid/docs#1175]
https://sendgrid.com/docs/Integrate/index.html
hi,
im in period of integration and testing, and now i got this notification
Your account has been suspended for review. Please respond to the email sent to your contact address on file: "ecole@jeminscrisenligne.net"
but i didn receive any message on my mailbox "ecole@jeminscrisenligne.net"
thanks

**Comment by mbernier** [comment]
Please email support@sendgrid.com for more information. This is due to our provisioning process and it just means that you may have a request for more information from our support team.
