### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by HaythemYahyaoui** [sendgrid/docs#1176]
https://sendgrid.com/docs/Integrate/Code_Examples/php.html
hi,
i have error (Use of undefined constant CURL_SSLVERSION_TLSv1_2): 
curl_setopt($session, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
i know that is the version of the php is outdate.
there's another alternative?
thanks

**Comment by mbernier** [comment]
@eddiezane

**Comment by eddiezane** [comment]
It's unadvised, but you can leaving it out or using an alternative from [here](http://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html).

**Comment by thinkingserious** [comment]
Hello @HaythemYahyaoui,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
