### ISSUE TITLE
Associate Domains - repeating parameters

### ISSUE THREAD

**Issue by adinanistor** [sendgrid/docs#1196]
Hello everyone,

While checking for the API  v3 calls for associating domain whitelabel to subusers:

https://sendgrid.com/docs/API_Reference/Web_API_v3/Whitelabel/domains.html#Associate-Domain-POST

I see repeating the parameters "custom_spf" and "default" (same name, same type, failry the same description).
![documentation](https://cloud.githubusercontent.com/assets/2391866/8700890/3df7b244-2b17-11e5-9ac8-d2287228c413.png)

Are those parameters repeating by mistake? or do they mean different things?
Thank you all!

**Comment by thinkingserious** [comment]
Hello @adinanistor,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
