### ISSUE TITLE
Wrong link to API Key documentation

### ISSUE THREAD

**Issue by adinanistor** [sendgrid/docs#1200]
Hello everyone,

It would seem that the link for [API KEY](https://sendgrid.com/Classroom/Send/api_keys.html) from within our article "Contacts API":

https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/api.html

resolves as: https://sendgrid.com/Classroom/Send/api_keys.html.
The link I find works on this subject, is instead:
https://sendgrid.com/docs/Classroom/Send/api_keys.html.

If the last link is the correct one, please update this article link to API Key.
Thank you!

**Comment by thinkingserious** [comment]
Hello @adinanistor,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
