### ISSUE TITLE
Node.js

### ISSUE THREAD

**Issue by ej500** [sendgrid/docs#1206]
https://sendgrid.com/docs/Integrate/Code_Examples/nodejs.html

I have  succeeded to implement sendgrid  in azure  with code as described in this example.
https://chriztalk.wordpress.com/2014/05/22/email-reports-from-sql-azure/ 

In this example the content in the  parameter  "MailBody"  is  a variable retrived from a store procedure in a azure sql database.  I  hope you can  extend the example and show how  the other parameters in this example (to, from, and subject)  can be retrived as variables in the store procedure too.

**Comment by thinkingserious** [comment]
Hello @ej500,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
