### ISSUE TITLE
Mail Settings Needs Essentials Alerts

### ISSUE THREAD

**Issue by ryanruppe** [sendgrid/docs#1216]
Some of the Mail Settings options are not available to Lite and Essentials accounts (for instance: Address Whitelist), but this is not documented on https://sendgrid.com/docs/User_Guide/Settings/mail.html

**Comment by mbernier** [comment]
Thanks! I'll get this on the list.

**Comment by thinkingserious** [comment]
Hello @ryanruppe,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
