### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ohhdear** [sendgrid/docs#1227]
https://sendgrid.com/docs/User_Guide/Transactional_Email/unsubscribes.html has a broken link to the global unsub page. 

Should be something like app.sendgrid.com/suppressions/global_unsubscribes

**Comment by thinkingserious** [comment]
Hello @ohhdear,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
