### ISSUE TITLE
Deliveries - deferred

### ISSUE THREAD

**Issue by davidna** [sendgrid/docs#1241]
https://sendgrid.com/docs/Glossary/deliveries.html

i've searched the knowledgebase and i do not see a lifecycle diagram of a message.
![screen shot 2015-08-21 at 1 37 05 pm](https://cloud.githubusercontent.com/assets/1616742/9418554/be96212e-4809-11e5-9119-70ac3a3cb448.png)

if there is one, please point me to it - thanks!

**Comment by thinkingserious** [comment]
Hello @davidna,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
