### ISSUE TITLE
Marketing Email API Overview

### ISSUE THREAD

**Issue by thirdeze** [sendgrid/docs#1243]
Dear Manangements

I got your contact from mailBoy managements,
I bought their email amail mass sender but its sending is too slow and i requested an option.

and their software has an internal SMPT 
So i suggested to get SMTP username and password to your from SendGrid credentials so that i can Set the server host name to with my personal smtp.

My Connection is SSL all i wnat to know is do you sell SMPT? And how much will it cost me to get it working with port 465 then i need it SMTO LOGIN NAME AND SMTP LOGIN PASSWORD.

Thanks
Mr.Eze
+27787240564
Email:Thirdeze@gmail.com

**Comment by thinkingserious** [comment]
Hello @thirdeze,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
