### ISSUE TITLE
SMTP API Validator: category is not of type array

### ISSUE THREAD

**Issue by KrunchMuffin** [sendgrid/docs#1262]
```
{"category": "dogs"}
```

The array is optional so it should not thrown an error.

**Comment by thinkingserious** [comment]
Hello @KrunchMuffin,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
