### ISSUE TITLE
SendGrid.SmtpApi.IHeader' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by grozario** [sendgrid/docs#1266]
Hope you can help with an issue.

I have used some C# code generated by the SendGrid code workshop in VS2010. I used NuGet to install the SendGridMail and SendGrid.SMTPApi libraries and my project references them. On compiling I get the error:

SendGrid.SmtpApi.IHeader' is defined in an assembly that is not referenced.

and 

The type 'SendGrid.SmtpApi.IHeader' is defined in an assembly that is not referenced. You must add a reference to assembly 'SendGrid.SmtpApi, Version=1.1.3.0, Culture=neutral, PublicKeyToken=55aa52d3c3c0d2b2'.   

on the line:

myMessage.Header.SetTo(new List<string>()...

Everything else compiles fine, and when I use intellisense it shows that SetTo is available on myMessage.header.

Cheers - Gerard

**Comment by thinkingserious** [comment]
Hello @grozario,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
