### ISSUE TITLE
C# - SendGrid C# library example not accurate

### ISSUE THREAD

**Issue by Vitoc456** [sendgrid/docs#1267]
On the page at the link below, I don't believe the top code snippet is accurate anymore.  It looks like the Web constructor was made private, so on line 15 you now (I'm assuming here) have to call Web.GetInstance and pass in the credentials.

https://sendgrid.com/docs/Integrate/Code_Examples/csharp.html

**Comment by thinkingserious** [comment]
Hello @Vitoc456,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
