### ISSUE TITLE
Using the Web API

### ISSUE THREAD

**Issue by bpneal** [sendgrid/docs#1275]
https://sendgrid.com/docs/API_Reference/Web_API/using_the_web_api.html

When making a `GET` to `https://api.sendgrid.com/v3/categories/stats?...` with valid parameters and credentials. I get the following invalid error if one of the categories doesn't exist.

`{"error":"failed to get category data: unexpected end of JSON input"}`

**Comment by ehedaya** [comment]
+1

**Comment by thinkingserious** [comment]
Hello @bpneal,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
