### ISSUE TITLE
Incorrect URLs in Bounces API

### ISSUE THREAD

**Issue by mgrijalva** [sendgrid/docs#1296]
For the bounces API all the URLs have "v3" repeated twice:

```
GET https://api.sendgrid.com/v3/v3/suppression/bounces?start_time={start_time}&end_time={end_time} HTTP/1.1
```

should be

```
GET https://api.sendgrid.com/v3/suppression/bounces?start_time={start_time}&end_time={end_time} HTTP/1.1
```

https://sendgrid.com/docs/API_Reference/Web_API_v3/bounces.html

**Comment by To-da** [comment]
Same problem here:
https://github.com/sendgrid/docs/blob/develop/source/API_Reference/Web_API_v3/user.apiblueprint#L63

**Comment by thinkingserious** [comment]
Hello @mgrijalva,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
