### ISSUE TITLE
Github header positioning shifts page content

### ISSUE THREAD

**Issue by FMJansen** [sendgrid/docs#1311]
When scrolling, the positioning of the Github header changes from the initial position to `fixed`. This leaves a gap in the page where the banner used to be, making the content jump up. 

https://sendgrid.com/docs/Integrate/Code_Examples/python.html

**Comment by thinkingserious** [comment]
Hello @FMJansen,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
