### ISSUE TITLE
Cancel Scheduled Sends formatting issue

### ISSUE THREAD

**Issue by dtjm** [sendgrid/docs#1339]
This page renders slightly off under the "Batch IDs" header: https://sendgrid.com/docs/API_Reference/Web_API_v3/cancel_schedule_send.html

screenshot: https://www.dropbox.com/s/oij1h9cn1qgqmr2/Screenshot%202015-10-26%2011.21.52.png?dl=0

I was going to submit a PR but the source looks fine:
https://github.com/sendgrid/docs/blob/develop/source/API_Reference/Web_API_v3/cancel_schedule_send.apiblueprint#L14-L20

**Comment by thinkingserious** [comment]
Hello @dtjm,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
