### ISSUE TITLE
Enforced TLS Patch example is incomplete

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#1354]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Settings/enforced_tls.html#-PATCH
Example does not include any URI parameters

**Comment by thinkingserious** [comment]
Hello @jacobmovingfwd,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
