### ISSUE TITLE
Email Activity

### ISSUE THREAD

**Issue by Webcoda** [sendgrid/docs#1363]
https://sendgrid.com/docs/User_Guide/email_activity.html

Email activity view is pretty much useless in case where lots of messages are sent to the same recipient. All I see is a list of messages but I cannot confirm if particular message has been sent.
Email subject column is required to see what message that is and I should be able to search by email subject as well as recipient.

Example:
Order is processed which generates a number of emails to the customer e.g. Registration, Order Confirmation, Order Vouchers. Looking at the log it is not possible to see which of these emails has been sent and which did not.

This is even more problematic with system addresses e.g. all order confirmations are sent to the administrator. It is not possible to confirm if particular order confirmation has been sent to administrator as email and date stamp are not enough to pinpoint the message.

Thanks,
Oleg

**Comment by thinkingserious** [comment]
Hello @Webcoda,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
