### ISSUE TITLE
Zapier missing Firebase "Add Child Record" trigger used in Firebase-Sendgrid tutorial

### ISSUE THREAD

**Issue by sbrown345** [sendgrid/docs#1491]
https://sendgrid.com/docs/Integrate/Tutorials/Zapier/sending_when_new_firebase_child_records_added.html

Zapier seems to have removed the "Add Child Record" Firebase trigger so this tutorial doesn't work.

https://zapier.com/zapbook/firebase/
https://web.archive.org/web/20150324221128/https://zapier.com/zapbook/firebase/

Now there's only the "Update value at this path" trigger.

**Comment by sbrown345** [comment]
Oh, I wrote that too soon. If I go directly to https://zapier.com/zapbook/firebase/sendgrid/29752/firebase-added-a-child-record-to-sendgrid-send-email/ it's still available.

**Comment by Kesymaru** [comment]
This options is not available anymore, i do not know why Zapier removed it but looks like when you are composing the zap there are not triggers available for firebase

**Comment by sbrown345** [comment]
I got an email from Zapier a few days ago with some more detail (I've highlighted important bits):

> We're reaching out because one of your Zaps is using a Firebase Trigger. Unfortunately, these Triggers may not work going forward.
> 
> **The Firebase team no longer officially supports the webhooks that Zapier used to set Firebase Zaps into motion. Because we cannot guarantee that Zaps using Firebase Triggers will function correctly, these options have been hidden for new Zaps.**
> 
> **However, we did not turn off any existing Zaps that are using Firebase Triggers. These Zaps should be used at your own risk.** You can see which of your Zaps are using Firebase by visiting your dashboard.
> 
> If you're searching for a Firebase alternative, take a look at our integrations for Knack and Airtable, two popular database apps. We're also building our own short-term storage app called Storage by Zapier—it's in beta, but you can test it out here.
> 
> We're truly sorry about any headaches this might cause. **The Firebase team is working on an API that would give us more reliable access to trigger data, but there's no timetable at this point. When they launch the new API we'll look at rebuilding these Firebase Triggers.**
> 
> If you have any questions about using Firebase with Zapier, or setting up an alternative, don't hesitate to reply to this email—our support team is happy to lend a hand.
> 
> - Bryan Helmig, CTO of Zapier

**Comment by pandaiolo** [comment]
FYI an official answer from Firebase as well: https://groups.google.com/forum/#!topic/firebase-talk/-6lZEuoO52U

I guess the internal Google Cloud solution might be the future way to integrate to Zappier, a kind of "Google Cloud Functions" for Firebase - but it's in pre-alpha at the moment.

**Comment by thinkingserious** [comment]
Hello @sbrown345,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
