### ISSUE TITLE
Event Webhook

### ISSUE THREAD

**Issue by brightcode** [sendgrid/docs#1533]
The webhook JSON examples in the documentation suggest that the "tls" parameter is a string, but in reality it is a number. It also states that "cert_error" is present in all events, but I haven't seen it so far.

https://sendgrid.com/docs/API_Reference/Webhooks/event.html

**Comment by thinkingserious** [comment]
Hello @brightcode,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
