### ISSUE TITLE
Global Suppressions

### ISSUE THREAD

**Issue by nrlucaroni** [sendgrid/docs#1540]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/global_suppressions.html
- Argument descriptions don’t make sense to the command being executed
  - ‘Retrieve a Global Suppression’ describes that the email parameter is “[t]he email to delete”.
- ~~Return response sample doesn’t make sense to the intent of the command being executed~~
  - ~~The response to the ‘Retrieve a Global Suppression’ (which has an email parameter), returns a list of emails. It’s unclear how that list relates to the command —it seems it was copied from previous command. It was my original understanding that this command just returned a list of global suppressions and had no arguments.~~
- ~~The Return response does not match the documentation~~
  - ~~Running the ‘Retrieve a Global Suppression’ returns a JSON blob with a “suppressions” field that isn’t described in the documentation.~~
- ~~The commands do not work (return 404)~~
  - ~~The delete command returns 404 Page Not Found~~

The POST command does work.
#1512 doesn't seem to resolve the issue either.

**Comment by nrlucaroni** [comment]
the correct command is,

https://api.sendgrid.com/v3/asm/suppressions/global/{email}

**Comment by thinkingserious** [comment]
Hello @nrlucaroni,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
