### ISSUE TITLE
Undelivered Email

### ISSUE THREAD

**Issue by francesco1119** [sendgrid/docs#1551]
hello, I have a question for you.

We provide a software for cinemas which also involve tickets sale.

Many times customers enter a wrong e-mail address and as consequence we receive a mail from no-reply@sendgrid.net with title "Undelivered Mail Returned to Sender" and as attach the e-mail that the customer hasn't received.
As this attach also contains the cinema e-mail I would like to redirect those e-mails to the relatives cinemas and theaters.

Can you guide me through the steps to deploy this? 
I couldn't find any tips about this subject on your Knowledgebase, neither on GitHub.

Thank you

https://sendgrid.com/docs/Glossary/undelivered_email.html

**Comment by thinkingserious** [comment]
Hello @francesco1119,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
