### ISSUE TITLE
$HTTP_RAW_POST_DATA is deprecated, but used in example code

### ISSUE THREAD

**Issue by alexzabolotny** [sendgrid/docs#1566]
https://sendgrid.com/docs/API_Reference/Webhooks/event.html page features example code for dumping webhook requests into a file. It uses deprecated global variable $HTTP_RAW_POST_DATA which should not be used. Please refer to PHP docs: http://php.net/manual/en/reserved.variables.httprawpostdata.php

**Comment by thinkingserious** [comment]
Hello @alexzabolotny,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
