### ISSUE TITLE
Parse API return resource not found error

### ISSUE THREAD

**Issue by awwa** [sendgrid/docs#1569]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Webhooks/parse.html

The endpoint 'https://api.sendgrid.com/v3/webhooks/parse/settings' returns an error '{"errors":[{"field":null,"message":"resource not found"}]}'.

**Comment by thinkingserious** [comment]
Hello @awwa,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by l3x** [comment]
@awwa Did you find a solution?  I'm getting the same error when executing:

`response = sg.client.mail._('send').post(request_body: mail.to_json)`

Prior to that erroneous line:
```
    from = SendGrid::Email.new(email: message_vo.manager_email)
    to = SendGrid::Email.new(email: message_vo.receiver_email)
    subject = message_vo.email_subject
    text_message = SendGrid::Content.new(
        type: 'text/plain',
        value: message_vo.email_message
    )
    html_message = SendGrid::Content.new(
        type: 'text/html',
        value: "<strong>Content</strong><br/>#{message_vo.email_message}"
    )
    mail = SendGrid::Mail.new(from,
                              subject,
                              to,
                              text_message)
```

Thanks!
