### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by jaycom** [sendgrid/docs#1572]
https://sendgrid.com/docs/User_Guide/SendGrid_for_Mobile/index.html

HI, I find that the google image size too large. It's 800px

**Comment by thinkingserious** [comment]
Hello @jaycom,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
