### ISSUE TITLE
Contacts API Delete Segment and List

### ISSUE THREAD

**Issue by gorums** [sendgrid/docs#1578]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html

ApiV3 deleteSegment and deleteList dont delete the recipients associated by default like the documentation specified.

**Comment by thinkingserious** [comment]
Hello @gorums,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
