### ISSUE TITLE
API Update Segment 

### ISSUE THREAD

**Issue by gorums** [sendgrid/docs#1579]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Update-a-Segment-PATCH

I create a list and create a segment associated with the list. Then when i try to update the segment with the same list_id the response is "List id is not a valid integer".

**Comment by thinkingserious** [comment]
Hello @gorums,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
