### ISSUE TITLE
Campaigns API

### ISSUE THREAD

**Issue by gorums** [sendgrid/docs#1581]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/campaigns.html

I don't see any api to get the sender_id

**Comment by PavelOlin** [comment]
+1, I don't see any api to get the sender_id too. 
And can't create campaign completely by api call, because sender_id unknown. 
And can't send campaign, because sender_id is blank.

**Comment by BigaDev** [comment]
You can get the sender_id from the URL when you are in the sender on the UI. Head to http://send.gd/1rg4yUP  and edit your sender, it will be in the URL.

**Comment by thinkingserious** [comment]
Hello @gorums,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
