### ISSUE TITLE
Bounces

### ISSUE THREAD

**Issue by amstel54** [sendgrid/docs#1587]
https://sendgrid.com/docs/User_Guide/Suppressions/bounces.html
I think this is wrong...so just forwarding for your review:
"Searching Bounces by Date
In the top right corner, you will see a calendar icon. Click this and choose the unsubscribe dates you would like to search between. Your recipient list will refresh, showing the recipients who unsubscribed between these dates."

**Comment by thinkingserious** [comment]
Hello @amstel54,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
