### ISSUE TITLE
spamreport is incorrect in the Event Webhook API

### ISSUE THREAD

**Issue by awwa** [sendgrid/docs#1594]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Webhooks/event.html
`spamreport` is incorrect.
It seems `spam_report` is correct.

**Comment by thinkingserious** [comment]
Hello @awwa,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
