### ISSUE TITLE
Event Webhook

### ISSUE THREAD

**Issue by mopinion** [sendgrid/docs#1596]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Webhooks/event.html

There's v3/v3 in the urls (double)

**Comment by thinkingserious** [comment]
Hello @mopinion,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
