### ISSUE TITLE
Inbound Parse Webhook

### ISSUE THREAD

**Issue by vrinek** [sendgrid/docs#1597]
https://sendgrid.com/docs/API_Reference/Webhooks/parse.html

The interface in the embedded Vimeo video looks totally different to what I see. Is it out-of-date by any chance?

**Comment by thinkingserious** [comment]
Hello @vrinek,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
