### ISSUE TITLE
Sendwithus doesn't exist on partner page anymore?

### ISSUE THREAD

**Issue by gvohra** [sendgrid/docs#1635]
https://sendgrid.com/docs/Classroom/Track/Collecting_Data/sendwithus.html

**Comment by thinkingserious** [comment]
Hello @gvohra,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
