### ISSUE TITLE
Code Examples Index

### ISSUE THREAD

**Issue by GreenAsJade** [sendgrid/docs#1639]
https://sendgrid.com/docs/Integrate/Code_Examples/index.html

The Heroku Addons entry for this plugin says that Scala is supported.

However, there are no Scala examples or doco that I can find?

**Comment by awwa** [comment]
[Here](https://github.com/SendGridJP/sendgridjp-scala-example/blob/master/src/main/scala/SendGridScalaExample.scala) is the example for scala.

**Comment by GreenAsJade** [comment]
Thanks!
