### ISSUE TITLE
Joomla

### ISSUE THREAD

**Issue by kraymitchell** [sendgrid/docs#1640]
https://sendgrid.com/docs/Integrate/Open_Source_Apps/joomla.html

Should also add SMTP Security and SMTP port information for Joomla as these are required too.

**Comment by thinkingserious** [comment]
Hello @kraymitchell,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
