### ISSUE TITLE
Unsubscribe Groups

### ISSUE THREAD

**Issue by danielcompton** [sendgrid/docs#1642]
https://sendgrid.com/docs/User_Guide/Suppressions/advanced_suppression_manager.html

> When a user unsubscribes from a type of email being sent to them at the sender account level, SendGrid will suppress all of your attempts at sending this type of email to that user. This means that the contact information is still in your contact database or you can send this contact’s email via the API. Regardless, emails will not be sent to this contact’s email.

This sentence didn't make sense: "This means that the contact information is still in your contact database or you can send this contact’s email via the API. "

**Comment by danielcompton** [comment]
Also, further down the page:

> The emails should not be enclosed in quotes and should be NOT be formatted like fname lname <email@example.com>

**Comment by eschallock** [comment]
Thank you very much for your feedback! Any input from our users is always appreciated. We've added this issue to our backlog, but unfortunately we are in the middle of several other projects that are preventing us from improving this page right away.

In the meantime, do you have a specific question that we might be able to help you with?

**Comment by danielcompton** [comment]
No specific question, it was just confusingly worded.

**Comment by eschallock** [comment]
I completely agree, and will strive to get this rewritten as soon as I'm allotted the bandwidth. Despite the confusion, I'm glad you were able to piece together the information that you needed.

Again, thank you for bringing this to our attention. We will work to improve this page as soon as we are able.

**Comment by thinkingserious** [comment]
Hello @danielcompton,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by danielcompton** [comment]
The docs are still confusingly worded here.
