### ISSUE TITLE
Update Ruby on Rails docs to include info/link about using an API key rather than SendGrid credentials

### ISSUE THREAD

**Issue by mikejarema** [sendgrid/docs#1645]
The [RoR docs](https://sendgrid.com/docs/Integrate/Frameworks/rubyonrails.html) would benefit from having a short snippet describing or linking [how to use an API key](https://sendgrid.com/docs/Classroom/Send/How_Emails_Are_Sent/api_keys.html#-Via-SMTP) in place of a user's sendgrid credentials when sending via SMTP.

This would've saved me 10-15 minutes of effort integrating.

**Comment by thinkingserious** [comment]
Hello @mikejarema,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
