### ISSUE TITLE
API v3 Overview

### ISSUE THREAD

**Issue by jkibble** [sendgrid/docs#1646]
https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html

The v3 API calls return header of text/html when they are actually sending json.

**Comment by thinkingserious** [comment]
Hello @jkibble,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
