### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by jwisener** [sendgrid/docs#1658]
There is no code showing how to get the attachments, I don't care about the number of attachments, I need to be able to save the attachments.

https://sendgrid.com/docs/Integrate/Code_Examples/Webhook_Examples/csharp.

**Comment by thinkingserious** [comment]
Hello @jwisener,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by jwisener** [comment]
You can completely remove as no one ever responded In a year. We decided to
use another provider.
