### ISSUE TITLE
There has to be a way to see the email content and subject in Activity view

### ISSUE THREAD

**Issue by darky2004** [sendgrid/docs#1703]
Coming from Mandrill, this is unacceptable gap in functionality.  At the very least, the email subject line has to be available.

**Comment by thinkingserious** [comment]
Hello @darky2004,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
