### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by ToMaple2** [sendgrid/docs#1729]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/templates.html

In the Requests shown for transactional templates involving a specific template, the URL given is shown with a colon (:) before the template_id, supposedly to indicate a real template id should be given. This is not consistent with other places in the documentation (e.g. Marketing Campaigns) where the indicator for a substituting a real id uses braces (e.g. {template_id}).

**Comment by thinkingserious** [comment]
Hello @ToMaple2,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
