### ISSUE TITLE
Code Example - C# Deliver() should be DeliverAsync()

### ISSUE THREAD

**Issue by FabienLavocat** [sendgrid/docs#1735]
In the file https://github.com/sendgrid/docs/blob/develop/source/Integrate/Code_Examples/csharp.md
The line:
`transportWeb.Deliver(myMessage).Wait();`

Should be:
`transportWeb.DeliverAsync(myMessage).Wait();`

**Comment by thinkingserious** [comment]
+1

**Comment by mbernier** [comment]
@thinkingserious do we have an issue on the C# library? If so, can you link it here and close this issue?

**Comment by thinkingserious** [comment]
That is a v2 issue, and it is correctly documented in the repo: https://github.com/sendgrid/sendgrid-csharp/tree/b27983a8f3d84a9d28972f2720cca0315ad9fe32#how-to-send-an-email

**Comment by thinkingserious** [comment]
Hello @FabienLavocat,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
