### ISSUE TITLE
DKIM

### ISSUE THREAD

**Issue by zolee1** [sendgrid/docs#1740]
Links to DKIM support pages are broken on
https://sendgrid.com/docs/Glossary/dkim.html

For example: Set up custom DKIM

**Comment by eschallock** [comment]
@zolee1 Thanks for the feedback! This has actually already been brought to our attention today, and I've already made the necessary changes to resolve those old links. Once we're able to deploy the changes you'll find that the links point to the appropriate locations.

**Comment by thinkingserious** [comment]
Hello @zolee1,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
