### ISSUE TITLE
Billing Info and FAQs

### ISSUE THREAD

**Issue by gracemanasseh** [sendgrid/docs#1741]
https://sendgrid.com/docs/Classroom/Basics/Billing/billing_info_and_faqs.html

Dear Support,

I have been trying to purchase essentials plan (100,000) emails per month using credit card but getting the following message:

13 - Referral: CALL AUTH CENTER

I have contacted my bank and they said there is nothing wrong and no transaction is appearing on the credit card.
If you can please advise and what the issue might be.

The SendGrid account I'm upgrading is orthodoxdaily.

Thank You,
Grace Manasseh

**Comment by thinkingserious** [comment]
Hello @gracemanasseh,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
