### ISSUE TITLE
Inbound Parse Webhook: Attachment-info link is not formatted correctly

### ISSUE THREAD

**Issue by ealter** [sendgrid/docs#1742]
https://sendgrid.com/docs/API_Reference/Webhooks/parse.html

The docs currently read:

<pre>A JSON string containing the attachmentX (see below) keys with another JSON string as the value. This string will contain the keys *filename*, which is the name of the file (if it was provided) and *type*, which is the [media type](http://en.wikipedia.org/wiki/Internet_media_type) of the file.</pre>

Note that "media type" is not a link, but shows the markdown formatting for links instead. It should be a proper link.

**Comment by thinkingserious** [comment]
Hello @ealter,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
