### ISSUE TITLE
Inbound Parse Webhook does not give the data types of the payload

### ISSUE THREAD

**Issue by ealter** [sendgrid/docs#1754]
https://sendgrid.com/docs/API_Reference/Webhooks/parse.html

The English documentation is great, but it is unclear what the exact json structure of each part of it is (for example, are the headers a dictionary or a list?). It'd be great if the documentation included an example payload.

**Comment by thinkingserious** [comment]
Hello @ealter,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
