### ISSUE TITLE
Section Tags Classroom is very confusing

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#1762]
https://github.com/sendgrid/docs/blob/develop/source/Classroom/Build/Add_Content/substitution_and_section_tags.md

This documentation is very confusing, and has technical errors. Should be reformatted to provide and Example JSON & Resulting Body for each setup.

**Comment by thinkingserious** [comment]
Hello @jacobmovingfwd,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by jacobmovingfwd** [comment]
still an issue. https://sendgrid.com/docs/Classroom/Build/Add_Content/substitution_and_section_tags.html

It's just a pseudo-random selection of json & sub tags. no overall "resulting body" examples, no explanation of what the example is showing.

**Comment by ksigler7** [comment]
@jacobmovingfwd thanks for opening this back up! I've added it to our internal backlog.

**Comment by kylearoberts** [comment]
I have requested a pull where I made the necessary changes here https://github.com/sendgrid/docs/pull/2959

**Comment by ksigler7** [comment]
thanks Kyle!!
