### ISSUE TITLE
"Invalid emails" should instead be called "Invalid email addresses"

### ISSUE THREAD

**Issue by aossikine** [sendgrid/docs#1766]
When referring to email addresses, you should not call them "emails" because "emails" are messages, not addresses. This is confusing. For example, I am currently looking for a way to delete outgoing emails from the queue if they've been deferred for too long. I come across the following API endpoint (and documentation):
https://sendgrid.com/docs/API_Reference/Web_API_v3/invalid_emails.html
And on first look, I think it does exactly what I need. But instead, it's  for managing invalid email ADDRESSES, not the actual messages.

For an email-related service, the terminology needs to be very clear about what is a message and what is an address.

This is present elsewhere in the docs btw - the above is just an example.

**Comment by thinkingserious** [comment]
Hello @aossikine,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by aossikine** [comment]
Wow, you guys close tickets simply because you haven't bothered addressing them in 90 days? It's definitely still an issue, though a very minor one. I was just trying to help you make your service better...

**Comment by aossikine** [comment]
(besides this being open for over a year, not 90 days)
