### ISSUE TITLE
Magento

### ISSUE THREAD

**Issue by gpietersma** [sendgrid/docs#1787]
https://sendgrid.com/docs/Integrate/Open_Source_Apps/magento.html

I spent a lot of time trying to figure this out. After several attempts I tried changing the port to 465 and SSL Security to SSL

I can see the forums others who have had the same problem. So perhaps it is worth noting in your setup guide.
Greg

**Comment by thinkingserious** [comment]
Hello @gpietersma,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
