### ISSUE TITLE
Account Under Review / Suspended

### ISSUE THREAD

**Issue by ABIECOM** [sendgrid/docs#1798]
Apparently my account is suspended ... could you tell me why? I did notice that something happened yesterday and about 13,000 emails were sent. This is *not* due to anything I have done. Perhaps this is the reason? Could you tell me which credentials were utilized? if it was the AAJTECH one, I have already deleted it this morning. I think one of my employees used it and posted it in a public place (GitHub) and someone saw it (probably). I'm just guessing what it may have been. Please let me know, and what do I need to do in order to re-activate my account? Thanks. Alex. Telephone: 561-309-1955.

**Comment by jrsteele23** [comment]
Hi ABIECOM,

I don't work for SendGrid but, it wounds like that indeed is why you may have had your account suspended, especially if the spam or bounce rate was high. I'm guessing you were trying to find a quick avenue to determine what happened. Emailing support@sendgrid.com is the optimal way to do this for future issues.

Cheers!
