### ISSUE TITLE
Testing your connectivity to SendGrid's SMTP relay using Telnet

### ISSUE THREAD

**Issue by jimsander** [sendgrid/docs#1805]
https://sendgrid.com/docs/Classroom/Troubleshooting/Delivery_Issues/testing_your_connectivity_to_sendgrids_smtp_relay_using_telnet.html

This can be augmented with a command line method for encoding, and being clear that newlines must be suppressed

i.e echo -n "yourname" | base64

**Comment by thinkingserious** [comment]
Hello @jimsander,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
