### ISSUE TITLE
Scheduling Parameters don't work

### ISSUE THREAD

**Issue by cjmochrie** [sendgrid/docs#1808]
https://sendgrid.com/docs/API_Reference/SMTP_API/scheduling_parameters.html

Using the Python API setting this header either results in a JSON Parsing error (if the send_at parameter is an integer) or has no effect on delivery time (if cast to a string).

I am calling set_headers on my message before sending with the SendGrindClient as follows: message.set_headers({'send_at': calendar.timegm(datetime.utcnow().utctimetuple()) + 100}). 
The header is being attached to the message, but the API responds with a 400: "(400, b'{"errors":["JSON in headers could not be parsed"],"message":"error"}')".

I'm not sure if I am using set_headers() correctly or if I am misinterpreting the SMTP API itself.

When I form the header as follows: `{'send_at': str(calendar.timegm(datetime.utcnow().utctimetuple()) + 100)}` I receive a 200, but the email is sent immediately (so the header has no effect).

Technical details:

sendgrid-python Version: 1.6.22 and 2.2.1
Python Version: 3.4.4

**Comment by thinkingserious** [comment]
Hello @cjmochrie,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
