### ISSUE TITLE
Request Body Parameters section mistakes

### ISSUE THREAD

**Issue by zygimantas** [sendgrid/docs#1822]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Request Body Parameters section contains these mistakes:
1. Indentation is wrong for "type" and "value". These should in inside "content".
2. "categories" type is "array of integers". Shoudn't it be "array of strings"? In description there is information about category names, which should be strings.

**Comment by thinkingserious** [comment]
Hello @zygimantas,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
