### ISSUE TITLE
API v3 mail & template_id

### ISSUE THREAD

**Issue by zygimantas** [sendgrid/docs#1823]
If I use template_id, I am forced to include `"content": {"type": "text/html", "value": "-"}`
Otherwise it does not pass validation.

**Expected behavior:** "content" should be optional if template_id is provided.

**Comment by po5i** [comment]
+1

**Comment by thinkingserious** [comment]
Hello @zygimantas,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @zygimantas,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @zygimantas,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @zygimantas,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @zygimantas,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
