### ISSUE TITLE
Unable to resend decliend provision email

### ISSUE THREAD

**Issue by ivrh** [sendgrid/docs#1847]
This page my_provision_was_declined_what_should_i_do.md does not specify if the email that this entire function depends on is lost or not received (for whatever reason). Would be great to point out how to re-send such email.

**Comment by thinkingserious** [comment]
Hello @ivrh,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @ivrh,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @ivrh,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @ivrh,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @ivrh,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
