### ISSUE TITLE
Sendgrid IP 167.89.12.138 blacklisted

### ISSUE THREAD

**Issue by philwiebe** [sendgrid/docs#1871]
I'm having emails not getting through because sendgrid IP 167.89.12.138 is showing on some blacklists.  Can you resolve this?

![image](https://cloud.githubusercontent.com/assets/19732362/15782384/06d24828-2978-11e6-9679-71affa627f50.png)

http://www.whois.com/whois/167.89.12.138

**Comment by jrsteele23** [comment]
Hi Phil, I know you're probably just trying to find a way to contact SendGrid about the issue you're experiencing. This github project is for SendGrid documenation. You're best bet to get this resolved is to email SendGrid support directly at support@sendgrid.com.

**Comment by philwiebe** [comment]
Hi Justin, thank you for letting me know.  I will do that.  So sorry.  I did not realize :(

**Comment by thinkingserious** [comment]
Hello @philwiebe,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @philwiebe,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @philwiebe,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @philwiebe,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @philwiebe,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by dgaspar** [comment]
I'm glad I've ran into this closed issue!

Here we are, __4__ years later, and Sendgrid still relies on this very same blocked 167.89.12.138 IP, and it remains unable to deliver emails to msft's inbox etc.
Related: https://turunen.ee/sendgrids-shared-ip-problem/

It seems that the guideline you'll get from support is to start paying pay for a top tier subscription with dedicated IP, in order to be able to send emails _with confidence_ (slogan).
