### ISSUE TITLE
Classroom links in API reference not working

### ISSUE THREAD

**Issue by idimensionz** [sendgrid/docs#1888]
I was reviewing the documentation for the new Mail endpoint in the Web API V3 ( (https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html) and tried to follow a couple of the "classroom" links provided in the details but the links were broken (i.e. they went to a 404 page not found error page).

If the classroom pages exist at another location, please fix the links.
If the classroom pages aren't ready yet, it would be more helpful to not have the links so we don't waste our time trying to access pages which aren't available (i.e. bad UX).

**Comment by thinkingserious** [comment]
Hello @idimensionz,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @idimensionz,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @idimensionz,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @idimensionz,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by thinkingserious** [comment]
Hello @idimensionz,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
