### ISSUE TITLE
Outdated: "How to change the password for your SendGrid add-on via Azure"

### ISSUE THREAD

**Issue by Jehoel** [sendgrid/docs#1943]
https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/how_to_change_the_password_for_your_sendgrid_add_on_via_azure.html

The Azure Portal does not list a "Reset password" option - only a "Change password" form which requires your current SendGrid password. There does not seem to be a way to actually reset a SendGrid password.

To clarify: this is a bug report I'm filing on GitHub because the bug is outdated/incorrect technical documentation, this is not a support request (so don't close this Issue unless it's fixed!)

**Comment by thinkingserious** [comment]
Hello @Jehoel,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by Jehoel** [comment]
Reopened as https://github.com/sendgrid/docs/issues/2709

**Comment by Jehoel** [comment]
> In an attempt to clear out our backlog, we are closing out issues over 90 days old. If this is still an issue, please feel free to reopen it. 

This is a very unwise policy. Bug reports are not like customer support tickets where an inactivity deadline results in auto-closure. This bug is only inactive because SendGrid has not even looked at it.

I have re-filed this issue as #2709 as I lack the necessary permissions to re-open this specific issue.
