### ISSUE TITLE
Where do Feedback answers get sent/stored

### ISSUE THREAD

**Issue by carlos-mg89** [sendgrid/docs#1952]
Hi guys, 

I've been playing around and testing the Sendgrid documentation project, so we can use it in the company where I'm currently working. So far so good, it looks very promising and easy to use/customize.

There is only one issue I haven't been able to clear out by myself, although I've spent some time checking out the documentation and the code. **Where do the feedback answers (Yes and No) that are shown at the end of the documentation pages get stored?** I thought there would be an email or a local database in the project where I could track that down, but haven't really found anything (I thought in the config file there would be something). Is it maybe because you let us deal with that, so we can process those answers as we wish?

Thanks in advance, and thanks for the project, it definitely looks awesome!

**Comment by thinkingserious** [comment]
Hello @carlos-mg89,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
