### ISSUE TITLE
Suppressions

### ISSUE THREAD

**Issue by awwa** [sendgrid/docs#1965]
This [endpoint](https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/suppressions.html) does not follow the RESTful design pattern.
`POST https://api.sendgrid.com/v3/asm/groups/:group_id/suppressions/search HTTP/1.1`

Because this feature does not create any resources. This returns email addresses.
Should this use GET verb?

**Comment by thinkingserious** [comment]
Hello @awwa,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
