### ISSUE TITLE
Document controlling Multiple IPs by using Subuser

### ISSUE THREAD

**Issue by nquinlan** [sendgrid/docs#197]
As mentioned by Jacob here: http://community.sendgrid.com/sendgrid/topics/using_multiple_ips

**Comment by thinkingserious** [comment]
Hello @nquinlan,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
