### ISSUE TITLE
Bounce Forwarding and Gmail

### ISSUE THREAD

**Issue by adamjakab** [sendgrid/docs#1973]
[https://sendgrid.com/docs/Classroom/Track/Bounces/bounce_forwarding_and_gmail.html](https://sendgrid.com/docs/Classroom/Track/Bounces/bounce_forwarding_and_gmail.html)
- Are you sure this doc is updated? - I have received the bounced mail forwarded by sendgrid (in the Spam folder) but there is no "daemon" word anywhere in the forwarded message.

**Comment by thinkingserious** [comment]
Hello @adamjakab,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
