### ISSUE TITLE
Can't log in to your account?

### ISSUE THREAD

**Issue by p7742777** [sendgrid/docs#1989]
Have the same issue for both of my accounts. I have 2 factor login and not getting the text messages...

HELP!!!

My accounts are:

customercare@autoloanoptions.com
noreply@autoloanoptions.com

**Comment by thinkingserious** [comment]
Hello @p7742777,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
