### ISSUE TITLE
Inbound Parse Webhook element type error

### ISSUE THREAD

**Issue by secesh** [sendgrid/docs#1991]
https://sendgrid.com/docs/API_Reference/Webhooks/parse.html

dkim value is not a JSON string. I've seen the following invalid values:

> "dkim": "{@glennhotel-com.20150623.gappssmtp.com : pass}"
> "dkim": "none"

Notice in the first example, it's JSONish, but it's not properly encoded (missing quotes around key and value) thus any attempt to parse the string as JSON will fail.

**Comment by thinkingserious** [comment]
Hello @secesh,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
