### ISSUE TITLE
Sendgrid sends attachment (a file) instead of message body

### ISSUE THREAD

**Issue by ilearnio** [sendgrid/docs#2000]
I'm trying to set up Sendgrid for sending emails via API. When I executed this example from the [docs](https://sendgrid.com/docs/Classroom/Send/How_Emails_Are_Sent/api_keys.html):

```bash
curl --request POST \
  --url https://api.sendgrid.com/v3/mail/send \
  --header 'authorization: Bearer YOUR_API_KEY_GOES_HERE' \
  --data '{"personalizations":[{"to":["recipient@example.com"]}],"from":"sender@example.com","subject":"Hello, World!","content":[{"type":"string","value":"Heya!"}]}'
```

It gave me a couple of errors but I managed how to fix them myself. So my request currently looks like so (I guess docs should be fixed as well):

```bash
curl --request POST \
  --url https://api.sendgrid.com/v3/mail/send \
  --header 'authorization: Bearer API_KEY' \
  --header "content-type: application/json" \
  --data '{"personalizations":[{"to":[{"email":"my@email.com"}]}],"from":{"email":"no-reply@ilearn.io"},"subject":"Hello, World!","content":[{"type":"html","value":"Heya!"}]}'
```

It is working but when I receive the email I'm getting an attachment instead of the content for some reason http://take.ms/Qp2ne. Can you help?

Thank you!

**Comment by ilearnio** [comment]
Fixed by setting `text/html` as content type

**Comment by thinkingserious** [comment]
Thanks for sharing the solution with us!
