### ISSUE TITLE
CURL example for sending attachment not working on PHP 5.6+

### ISSUE THREAD

**Issue by luqmansungkar** [sendgrid/docs#2009]
`'files['.$fileName.']' => '@'.$filePath.'/'.$fileName` are no longer supported in PHP 5.6 and up. It takes me some times to figure out the problem. Maybe you can include the example that using CURLFile for those who use PHP 5.6+.
Here are some example:
https://stackoverflow.com/questions/25934128/curl-file-uploads-not-working-anymore-after-upgrade-from-php-5-5-to-5-6
http://barrycarlyon.co.uk/wordpress/2015/10/04/php5-6-curl-and-file-uploads/

And here is the docs page:
https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/php.html

**Comment by thinkingserious** [comment]
Hello @luqmansungkar,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
