### ISSUE TITLE
Sendgrid v3 API

### ISSUE THREAD

**Issue by mijphys** [sendgrid/docs#2018]
I have another issue beyond just the general complaints.  The following produces a 400 Bad Request error.  I know this is an issue with the Sendgrid API because this code raises an HTTP Error - the request is never even sent to Sendgrid.  How did you people manage to screw up a thin wrapper around python_http_client?

I don't even want to hear the response or fix for this.  I am going to cancel my service for Sendgrid.  I won't be using them anymore and I will be using Mailgun exclusively.

self.sg = sendgrid.SendGridAPIClient(apikey='myAPIkey')
def send_sendgrid_email(self, to_email, to_name, from_email, from_name, subject, text, html):
		msg_data = {
			"from": {
				"name": from_name,
				"email": from_email
			},
			"personalizations": [
				{
					"to": [
						{
							"name": to_name,
							"email": to_email
						}
					],
					"subject": subject
				}
			],
			"content": [
				{
					"type": "text/html",
					"value": html
				},
				{
					"type": "text/plain",
					"value": text
				}
			]
		}
        return self.sg.client.mail.send.post(request_body=msg_data)

**Comment by thinkingserious** [comment]
@mijphys,

The code looks good and I can not reproduce the error on my end without access to the values you are passing the `send_sendgrid_email` function.

Feel free to reach out to dx@sendgrid.com if you can share the data in those variables.

To retrieve the error returned from SendGrid: https://github.com/sendgrid/sendgrid-python/blob/troubleshooting/TROUBLESHOOTING.md#error-messages (I know this is not ideal and we are working on a better error handling system)
