### ISSUE TITLE
When is "recently"?

### ISSUE THREAD

**Issue by ptmkenny** [sendgrid/docs#2021]
In email_was_deferred_due_to_the_following_reasons_ip_deferrals_messages.md, it says "We’ve recently updated the infrastructure that handles the actual sending of mail off to it’s intended recipients, specifically updated in regards to sending rate."

When is "recently"?  My site suddenly stopped sending emails through SendGrid, and I'm trying to figure out what changed-- when you update your platform, please write the date when it actually happened; it's very helpful in troubleshooting.

**Comment by mbernier** [comment]
Can you please reach out to our support team at support@sendgrid.com? You have posted this to our open source documentation repo!
