### ISSUE TITLE
My provision was declined, but I can't receive any email tell me why?

### ISSUE THREAD

**Issue by tuanwebaby** [sendgrid/docs#2022]
https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/my_provision_was_declined_what_should_i_do.html

Dear Sendgrid,

I'm waiting your email tell me why my provision was declined, but didn't have any email in my mailbox. Please help me check that issue!

Thanks

**Comment by mbernier** [comment]
Can you please reach out to support@sendgrid.com? You have posted this question to our documentation team, not our support team.

**Comment by tuanwebaby** [comment]
Sorry and thank you! I will contact with support team.

Thanks
