### ISSUE TITLE
Update: How to change the password for your SendGrid add-on via Azure

### ISSUE THREAD

**Issue by qin-nz** [sendgrid/docs#2079]
https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/how_to_change_the_password_for_your_sendgrid_add_on_via_azure.html

There is no reset password in my portal.
And I can't see my password now in [new portal](https://portal.azure.com) .

I can only see my password in [old portal](https://manage.windowsazure.com/)

![image](https://cloud.githubusercontent.com/assets/6998071/17526040/1cd351d0-5e98-11e6-92a9-7aa83d7109dd.png)
![image](https://cloud.githubusercontent.com/assets/6998071/17526066/3bfd41ec-5e98-11e6-8d23-7cb894a92309.png)

**Comment by thinkingserious** [comment]
Hello @qin-nz,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
