### ISSUE TITLE
Inbound Parse Webhook

### ISSUE THREAD

**Issue by djkz** [sendgrid/docs#2106]
https://sendgrid.com/docs/API_Reference/Webhooks/parse.html 

Link to Setting Up The Inbound Parse Webhook  returns 404.

**Comment by eschallock** [comment]
@djkz I have a change in place to repair that link. It should be functioning correctly this afternoon.

In the meantime, here is a direct link to that page: https://sendgrid.com/docs/Classroom/Basics/Inbound_Parse_Webhook/setting_up_the_inbound_parse_webhook.html

Thanks!
