### ISSUE TITLE
Magento

### ISSUE THREAD

**Issue by sparxit** [sendgrid/docs#2108]
Here your recommended plugin doesnt work with Magento 2.0
Please update this page accordingly. the extension you are recommending is not compatible with magento 2.0 yet. Please ask original author if they are going to update it else, please give some alternative for the case of Magento 2.0
I am going to try https://packagist.org/packages/yukoff/magento2-sendgrid-smtp?q= for now in my project requirement, will update in case that worked.

Thanks
https://sendgrid.com/docs/Integrate/Open_Source_Apps/magento.html

**Comment by mariusrusu** [comment]
@sparxit SendGrid is in the process of developing a plug-in compatible with Magento 2.0. We will make it available as soon as it's ready. Stay tuned!

**Comment by thinkingserious** [comment]
Hello @sparxit,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
