### ISSUE TITLE
Why Event API?

### ISSUE THREAD

**Issue by ostegm** [sendgrid/docs#2117]
The[ link to the event kit](https://github.com/sendgrid/eventkit) is broken from [this page](https://sendgrid.com/docs/Classroom/Basics/API/why_event_api.html) (near the bottom). 

Is it possible to update with a working link?

**Comment by eschallock** [comment]
@ostegm Sorry we have an old link on that page! This should be the repo you're looking for: https://github.com/sendgrid/eventkit-rails

I'll make sure to update the page you referenced with the current URL.
