### ISSUE TITLE
Mail pr. hour?

### ISSUE THREAD

**Issue by Visue** [sendgrid/docs#2131]
Hi - we have a membersite with 7.000+ members. We use mailpoet along with sendgrid to send out mails to them, but we only send 120 mails pr. hour - and that is far to slow when we need to communicate to the members... How can we increase mails send pr. hours without loosing to many? And what is maximum...

**Comment by thinkingserious** [comment]
Hello @Visue,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
