### ISSUE TITLE
IP Pools

### ISSUE THREAD

**Issue by KyleGobel** [sendgrid/docs#2174]
https://sendgrid.com/docs/API_Reference/Web_API_v3/IP_Management/ip_pools.html

Not seeing the docs on adding an IP to a pool, tried using one of the client libraries you guys have but getting a forbidden, access not allowed when trying to an IP address to the pool.

The IP is whitelabeled in our send grid account.  Can you guys provide more info on how to use the IP Pools?

**Comment by KyleGobel** [comment]
Update:

The docs for adding an IP to an IP Pool is in the IP Management section.
Also the scopes required for this call are not possible to grant through the send grid console.  You have to add the required scopes using the api using your account with basic authentication (your un and pw) to your api key.

I think you guys could make this flow a little easier.  Probably just adding those scopes into the sendgrid web console, and on the ip pools docs page a link back to the ip management section and note indicating info for adding ips to the pools is located there

**Comment by eschallock** [comment]
@KyleGobel 

I definitely agree that this flow could be made much easier, and apologize for the confusion! Your suggestion to link between our IP Management and IP Pools documentation is spot on - I'll make sure that we make this happen as soon as possible.

As for the limited scopes on API Keys created in the UI - this is something that we're looking into and should have resolved sometime soon. Unfortunately I can't make any promises right now, but this is a known issue.

Thank you!

**Comment by morgen-peschke** [comment]
Related to this flow, is it possible to create an API key that can be used to grant the scopes? We'd like to limit the exposure of the username and password.

Having created an API key with all of the `api_key.*` scopes, an attempt to assign the `ips.*` scopes fails with the following message:

```json
{
    "errors": [
        {
            "field": null,
            "message": "unauthorized scopes: [ips.assigned.read ips.read ips.pools.create ips.pools.delete ips.pools.read ips.pools.update ips.pools.ips.create ips.pools.ips.delete ips.warmup.create ips.warmup.delete ips.warmup.read]"
        }
    ]
}
```

**Comment by thinkingserious** [comment]
Hello @KyleGobel,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
