### ISSUE TITLE
Event Webhook

### ISSUE THREAD

**Issue by ddemetri** [sendgrid/docs#2175]
https://sendgrid.com/docs/API_Reference/Webhooks/event.html

Can multiple webhooks be used?  Please clarify that point.

**Comment by thinkingserious** [comment]
Hello @ddemetri,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
