### ISSUE TITLE
Scheduling Parameters

### ISSUE THREAD

**Issue by jblok** [sendgrid/docs#2176]
If I create a mail using the `/v3/mail/send` endpoint and specify a `send_at` timestamp for say 2 days in the future, BUT the user has unsubscribed in that 2 day period, it seems the mail still sends.

Is this expected? What is the best way around this?

https://sendgrid.com/docs/API_Reference/SMTP_API/scheduling_parameters.html

Kind regards

**Comment by thinkingserious** [comment]
Hello @jblok,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
