### ISSUE TITLE
Testing your connectivity to SendGrid's SMTP relay using Telnet

### ISSUE THREAD

**Issue by Kilili** [sendgrid/docs#2191]
https://sendgrid.com/docs/Classroom/Troubleshooting/Delivery_Issues/testing_your_connectivity_to_sendgrids_smtp_relay_using_telnet.html

get 451 Authentication failed

---

CMD sequence

telnet smtp.sendgrid.net 587
220 SG ESMTP service ready at ismtpd0002p1sjc2.sendgrid.net
ehlo
250-smtp.sendgrid.net
250-8BITMIME
250-PIPELINING
250-SIZE 31457280
250-STARTTLS
250-AUTH PLAIN LOGIN
250 AUTH=PLAIN LOGIN
auth login
334 VXNlcm5hbWU6
a2lsaWxp [as BASE64 encoded SendGrid username kilili]
334 UGFzc3dvcmQ6
[the BASE64 encoded SendGrid password]
451 Authentication failed: Could not authenticate

Connection to host lost.

**Comment by thinkingserious** [comment]
Hello @Kilili,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by socketpy** [comment]
i got some issues

**Comment by socketpy** [comment]
im so sorry i'd resolved it, i'd added mail server's IP Address into Whitelisted IP Addresses

Thank you

**Comment by ksigler7** [comment]
@socketpy - cool, glad you resolved it! If you have any more issues in the future, please reach out to our awesome support team! They're great at troubleshooting individual items - you can reach them by logging into https://support.sendgrid.com.
