### ISSUE TITLE
Postfix

### ISSUE THREAD

**Issue by garyebersole** [sendgrid/docs#2199]
https://sendgrid.com/docs/Integrate/Mail_Servers/postfix.html

Note that this solution won't work if Amavis has been configured on a Postfix mail server (most folks should have Amavis set up for spam filtering and anti-virus protection). For the answer which should be easy to add to your docs, see...

http://serverfault.com/questions/598343/postfix-ignores-relayhost

Hope this helps. Overall, your instructions only took a few minutes to re-configure my Postfix installation but much longer to resolve this issue.

Gary

**Comment by thinkingserious** [comment]
Hello @garyebersole,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
