### ISSUE TITLE
API v3 Basic Auth

### ISSUE THREAD

**Issue by felix-engelmann** [sendgrid/docs#2202]
As in #2184 , it would be nice to mention the possiblity to access the API with Basic Auth to have elevated permissions, e.g. to be able to change token permissions. A paragraph like that would be helpful:

To access the API with the elevated permissions of the full user account, for example to change the permission scope of an API Key, you can also access the API with basic HTTP authentication. More information about basic auth can be found [here](https://sendgrid.com/blog/magic-behind-basic-http-authentication/).

```
{% codeblock lang:bash %} curl -X "GET" "https://api.sendgrid.com/v3/api_keys" -H "Authorization: Basic base64encoded.user:password-HERE" -H "Content-Type: application/json" {% endcodeblock %}
```

**Comment by thinkingserious** [comment]
Hello @felix-engelmann,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
