### ISSUE TITLE
How do I whitelist emails to keep them from dropping?

### ISSUE THREAD

**Issue by bob-hinrichs** [sendgrid/docs#2222]
https://sendgrid.com/docs/Classroom/Deliver/Undeliverable_Email/how_do_i_keep_emails_from_dropping.html

This page makes it sound like this feature is available to us, but it is not, unless I am somehow not finding it.  We are using essentials plan.  Can the documentation explain the requirements for this feature?

**Comment by Zaftula** [comment]
Hey Bob,

There should be any plan restrictions on this feature, it should be up at the top of the list of options under: https://app.sendgrid.com/settings/mail_settings

Would you mind giving that link a click and letting me know what you see?

**Comment by bob-hinrichs** [comment]
Thank you!  I do not see such an option on that page.  Here is what I see:
![screen shot 2016-11-08 at 4 41 17 pm](https://cloud.githubusercontent.com/assets/3832840/20120390/3ec5ed94-a5d2-11e6-846a-830e2e7e2e1d.png)

**Comment by Zaftula** [comment]
Thanks for taking a look! Strange. It depends on what your actual plan is in the system, If you're interested in digging deeper, I'd recommend giving us a shout at support.sendgrid.com so an agent can get your username and take a look in the backend.

**Comment by thinkingserious** [comment]
Hello @bob-hinrichs,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
