### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by DannyLee12** [sendgrid/docs#2237]
Running the example code throws the following exception:

`AttributeError: 'module' object has no attribute 'SendGridClient'`

https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/python.html

**Comment by thinkingserious** [comment]
Hello @DannyLee12,

What version of the Python library are you using?

I'm guessing that you are using a version of our library that does not support v2. In that case, [this would be the example](https://sendgrid.com/docs/Integrate/Code_Examples/v3_Mail/python.html) you would use.

**Comment by DannyLee12** [comment]
Thanks, I'm using the latest version which I assume is version 3 and it works fine. Should be in big block letters on your FAQ: **If you get AttributeError: 'module' object has no attribute 'SendGridClient', you are using V3**

Otherwise, if possible, can you add the following code to your code example. I think that many if not all people who use this need to send mails to multiple addresses.

```
        sg = sendgrid.SendGridAPIClient(apikey=SENDGRID_API)
        from_email = Email('x@y.com', 'workflow')
        content = Content("text/plain", text)
        to_email = Email('y@z.com', 'Daniel Lee')

        mail = Mail(from_email, subject, to_email, content)

        # Add Other email addresses to the Personalization class
        personalization = Personalization()
        personalization.add_to(Email('1.2@x.co.za', 'Test Account 1'))
        personalization.add_to(Email('2.3@x.co.za', 'Test Account 2'))
        personalization.add_to(Email('5.6@x.com', 'Test Account 3'))

        # Add the personalization class to the mail class
        mail.add_personalization(personalization)

        # Send mail and get info
        response = sg.client.mail.send.post(request_body=mail.get())
```
Think about it, I can do it in a PR but this Issue is closed regardless.

**Comment by thinkingserious** [comment]
Hi @DannyLee12,

Thanks for the follow up!

Regarding your multiple email example, could you please lend your vote to [this issue](https://github.com/sendgrid/sendgrid-python/issues/225), to help bump it up the queue?

Regarding the documentation change, I'd like to get feedback on @eschallock on that one.

Could you also please describe your path to that page? I think that will help us think about the overall workflow. Thanks!
