### ISSUE TITLE
Symfony

### ISSUE THREAD

**Issue by krvajalmiguelangel** [sendgrid/docs#2238]
https://sendgrid.com/docs/Integrate/Frameworks/symfony.html
The yml configuration file lacks of proper indentation.

**Comment by thinkingserious** [comment]
Hello @krvajalmiguelangel,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
