### ISSUE TITLE
Transactional Email

### ISSUE THREAD

**Issue by ozomer** [sendgrid/docs#2246]
https://sendgrid.com/docs/User_Guide/Transactional_Email/index.html

Please add a code example for how to send a Transactional Email

**Comment by thinkingserious** [comment]
Hello @ozomer,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
