### ISSUE TITLE
Documentation is missing list of required permissions.

### ISSUE THREAD

**Issue by morgen-peschke** [sendgrid/docs#2248]
As there does not appear to be a section of the web interface for managing the IP pools, I'm doing this via curl.

This is workable, for the most part, as I can create and list the pools using an API key that has the "Manage IPs" permission.

I cannot use that API key to list IP addresses - it's returning `403 FORBIDDEN`, with an "access forbidden" error message. There doesn't appear to be a permission which clearly should provide access to this functionality, and the documentation is silent.

Please update the docs so that each endpoint includes the permissions required to use the functionality listed.

https://sendgrid.com/docs/API_Reference/Web_API_v3/IP_Management/ip_addresses.html

**Comment by thinkingserious** [comment]
Hello @morgen-peschke,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
