### ISSUE TITLE
CURL example doesn't work.

### ISSUE THREAD

**Issue by sabondano** [sendgrid/docs#2252]
The CURL example here doesn't work as advertised:
https://github.com/sendgrid/docs/blob/develop/source/Classroom/Send/How_Emails_Are_Sent/api_keys.md

**Comment by thinkingserious** [comment]
Hello @sabondano,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
