### ISSUE TITLE
Email rejected with a code (415) and link that do not exist in the docs

### ISSUE THREAD

**Issue by morgen-peschke** [sendgrid/docs#2270]
We had a message rejected with a 415 (Unsupported Media Type) and a link to the documentation.

The issue is the link points to a section which does not exist and the field property in the error is not set so it's unclear where the invalid UTF8 was encountered.

Full response body:
```
{
    "errors": [
        {
            "field": null,
            "help": "http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#-Encoding-Errors",
            "message": "Invalid UTF8 in request"
        }
    ]
}
```

**Comment by mbernier** [comment]
Hey! Sorry about that. We're looking into this and will get it into the docs.

**Comment by morgen-peschke** [comment]
Thank you for looking into this.

When you have more information on what's causing the rejection, can you update us? This is causing issues with our ability to send emails using the v3 API.

**Comment by mbernier** [comment]
My guess is that this is related to an attachment. If you are adding an attachment, please check that the content of the attachment is UTF8 encoded before you send.

**Comment by morgen-peschke** [comment]
We traced back one of the rejected requests, and it appears that the offending character was part of the body of the html message. 

Why that field wasn't specified in the error message is probably another issue. This particular text was part of a template that we render on our side to html, before passing on to SendGrid. The template in question sends without issue using the v2 endpoint, but I've got a support ticket open on that issue so that should hopefully be fixed soon.

**Comment by eschallock** [comment]
@morgen-peschke @mbernier SendGrid currently validates each v3 Mail Send payload in its entirety (including attachments) before any other processing is completed, so we are unable to identify which specific field was encoded incorrectly.

**Comment by morgen-peschke** [comment]
@eschallock Thank you for the insight. If I understand this correctly, the implication is that unicode characters are not allowed in any part of the request?

**Comment by eschallock** [comment]
@morgen-peschke Happy to help, and I'm sorry that our error message didn't provide the details you needed for debugging.

To answer your question above: everything in your request/payload (including attachments) must be UTF-8 encoded.

**Comment by morgen-peschke** [comment]
@eschallock Thank you for the clarification, I think I can fix the error on our side. It looks like the encoding was not set up as it should have been.

**Comment by thinkingserious** [comment]
Hello @morgen-peschke,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
