### ISSUE TITLE
Cancel Scheduled Sends Documentation Improvement

### ISSUE THREAD

**Issue by kylemiller** [sendgrid/docs#2289]
https://sendgrid.com/docs/API_Reference/Web_API_v3/cancel_schedule_send.html

> Cancel or pause a scheduled send

What is the difference between cancel and pause?  Is there one?  How long can a batch be "paused"?

> Delete the cancellation/pause of a scheduled send.

What is the outcome of this request?  If a "cancellation/pause" is deleted, will the emails be sent?  Or will the batch be deleted and no longer be scheduled?

Overall this page is confusing and could benefit from some more details.

**Comment by andersnm** [comment]
Related question; how long is a batch_id usable? 

Am getting a successful response using "Validate Batch ID" API call with a batch_id from November 2016 (today is January 2017), but mails aren't delivered when using this batch_id. And there is no cancellation/pause associated with it

**Comment by thinkingserious** [comment]
Hello @kylemiller,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
