### ISSUE TITLE
Update Fastly Documentation

### ISSUE THREAD

**Issue by mattcone** [sendgrid/docs#2318]
Fastly is switching to its [new user interface](https://www.fastly.com/blog/introducing-next-generation-fastly-control-panel) on November 17. The [documentation on SendGrid's website](https://sendgrid.com/docs/Classroom/Build/Add_Content/content_delivery_networks.html#-Using-Fastly) should be updated to match the new interface. We've opened pull request #2304 with the recommended changes. 

Thanks for looking into this!

**Comment by mbernier** [comment]
Thanks for raising the issue! 

I made a request on the PR, let's discuss there and then we can update this issue accordingly.

Thank you!!

**Comment by eschallock** [comment]
The necessary updates have been made in https://github.com/sendgrid/docs/pull/2323.

Thanks for the collaboration @mattcone and @mbernier !
