### ISSUE TITLE
Sendmail

### ISSUE THREAD

**Issue by ssayre** [sendgrid/docs#2328]
https://sendgrid.com/docs/Integrate/Mail_Servers/sendmail.html

Setting up sendmail on centos6 was exactly as described per your docs.
However, authentication errors pursued, which prevented connections until I installed cyrus-sasl-plain.

`yum install cyrus-sasl-plain`

errors in `/var/log/maillog` looked like this:
```
STARTTLS=client, relay=smtp.sendgrid.net., version=TLSv1/SSLv3, verify=FAIL, cipher=AES128-GCM-SHA256, bits=128/128
AUTH=client, available mechanisms do not fulfill requirements
AUTH=client, relay=smtp.sendgrid.net., temporary failure, connection abort
```

I suggest adding this check as a suggestion for folks.

**Comment by mbernier** [comment]
I have added a note here https://github.com/sendgrid/docs/pull/2329

Thank you!
