### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by kmayer** [sendgrid/docs#2356]
https://sendgrid.com/docs/User_Guide/Suppressions/index.html#L36

> If you are sending email through SendGrid and have the Subscription Tracking setting turned on,

shouldn't it be

> If you are sending email through SendGrid and have the Subscription Tracking setting turned _off_,

[emphasis added]

**Comment by thinkingserious** [comment]
Hello @kmayer,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
