### ISSUE TITLE
Seeing a delay with your first few sends?

### ISSUE THREAD

**Issue by pmackay** [sendgrid/docs#2401]
https://sendgrid.com/docs/Classroom/Send/When_Emails_Are_Sent/seeing_a_delay_with_your_first_few_sends.html

This could be clearer if it gave an indication of how many emails this delay could affect, before the delay is reduced.

**Comment by thinkingserious** [comment]
Hello @pmackay,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
