### ISSUE TITLE
API Keys

### ISSUE THREAD

**Issue by markine** [sendgrid/docs#2405]
https://sendgrid.com/docs/Classroom/Send/How_Emails_Are_Sent/api_keys.html

The curl post example is broken. Please update with the one here: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/curl_examples.html

**Comment by thinkingserious** [comment]
Hello @markine,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
