### ISSUE TITLE
Transactional Templates Overview

### ISSUE THREAD

**Issue by adamreisnz** [sendgrid/docs#2418]
https://sendgrid.com/docs/User_Guide/Transactional_Templates/index.html

This page needs documentation around what the template format is, how to use substitutions, whether or not iterating through data is supported, etc. etc. Can't manage to find this information anywhere.

**Comment by thinkingserious** [comment]
Hello @adamreisnz,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs

**Comment by adamreisnz** [comment]
Yep still an issue!
