### ISSUE TITLE
Node.js example code is incomplete

### ISSUE THREAD

**Issue by idelara** [sendgrid/docs#2424]
https://sendgrid.com/docs/Integrate/Code_Examples/v3_Mail/nodejs.html

The code is not being rendered correctly. Some semicolons and parenthesis are missing.

![screen shot 2017-01-11 at 1 13 16 pm](https://cloud.githubusercontent.com/assets/8979839/21866618/cd385a3a-d7ff-11e6-9677-6d0c3be76ad9.png)

**Comment by thinkingserious** [comment]
Thanks! You are correct and I've added this to our backlog for a fix.

For my own reference to fix: https://github.com/sendgrid/sendgrid-nodejs#with-mail-helper-class

**Comment by thinkingserious** [comment]
Fixed: https://gist.github.com/sendgrid-gists/069d788aefb7853706f424cbdfd7ee3c
