### ISSUE TITLE
What is my sending/originating IP address with Sendgrid?

### ISSUE THREAD

**Issue by djneely** [sendgrid/docs#2426]
https://sendgrid.com/docs/Classroom/Basics/Account/what_is_my_sending_originating_ip_address_with_sendgrid.html

According to this documentaiton I'm supposed to be able to determine the outbound IP Sendgrid is using to send email. However that information does appear to be available in my Settings. I'm attempting to Whitlelist the IP with Google as Google is now bouncing the emails sent into our domain. We were flagged as spam due to another site on our servers that was hacked and has since been resolved.

**Comment by thinkingserious** [comment]
Hello @djneely,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
