### ISSUE TITLE
How to set up bounce forwarding to go to the email's FROM address

### ISSUE THREAD

**Issue by gi-x-2** [sendgrid/docs#2456]
https://sendgrid.com/docs/Classroom/Track/Bounces/how_to_set_up_bounce_forwarding_to_go_to_the_emails_from_address.html

bounce forward reports tell the recipient to contact SendGrid Support.  When my customers send out an email and it bounces and sends them a bounce report, I would like it to let them know to contact me.  Having them contact SendGrid support is kind of a dead end for them, since they are not your end user, I am.  Maybe it would be possible to have a field to enter contact information to be used in bounce reports when the "send bounce report to from address" option is selected.

**Comment by thinkingserious** [comment]
Hello @gi-x-2,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
