### ISSUE TITLE
Sandbox Mode

### ISSUE THREAD

**Issue by usulix** [sendgrid/docs#2460]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/sandbox_mode.html

Here is my sandbox response : 

{"errors":[{"message":"Bad Request","field":null,"help":null}]}

Totally and completely useless!!!!!

**Comment by thinkingserious** [comment]
Hello @usulix,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
