### ISSUE TITLE
Creating domain whitelabel with assigning subuser.

### ISSUE THREAD

**Issue by kikutaro** [sendgrid/docs#2469]
Hi,

When I used the API v3 for creating domain whitelabel with assigning subuser, I found that two request attributes "username", "ips" are not listed in the table on the document. 
https://sendgrid.com/docs/API_Reference/Web_API_v3/Whitelabel/domains.html#Create-a-Domain-POST
<img src="https://cloud.githubusercontent.com/assets/5179168/22576026/8f86dec8-e9fc-11e6-88bf-39158f05a30e.png" width="500">
I was wondering if you could add the two request attributes descriptions in the table. 

Thanks,

**Comment by thinkingserious** [comment]
Hello @kikutaro,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
