### ISSUE TITLE
Post data in creating category

### ISSUE THREAD

**Issue by bfarayev** [sendgrid/docs#2474]
POST Data is given as `api_user=your_sendgrid_username&api_key=your_sendgrid_password&category=CATEGORY` but it should be sent as a URL parameter. 

`category.md` needs corrections.

**Comment by thinkingserious** [comment]
Hello @bfarayev,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
