### ISSUE TITLE
Incorrect response from Inbound Parse POST

### ISSUE THREAD

**Issue by nickrivadeneira** [sendgrid/docs#2485]
Your [docs show](https://github.com/sendgrid/docs/blob/6942e566d414409c1421cc2d3409d217522d0d8d/source/API_Reference/Web_API_v3/Webhooks/parse.apiblueprint#L57) that a successful response from a POST to `/user/webhooks/parse/settings` should have a status of `201`. I've been getting `200`s instead.

Since `201` is the correct response for a successful create, I didn't open a PR since it seems like the API should change, not the docs.

**Comment by thinkingserious** [comment]
Hello @nickrivadeneira,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
