### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by Jakobovski** [sendgrid/docs#2489]
https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/custom_fields.html

Can you please add how to use custom fields in templates to this page, or at least a link to some page that instructs on how to use custom fields?

Thanks

**Comment by thinkingserious** [comment]
Hello @Jakobovski,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
