### ISSUE TITLE
BadRequest: When sending an attachment

### ISSUE THREAD

**Issue by Angry-Leprechaun** [sendgrid/docs#2490]
I get a Bad Request response. The Code functions without the msg.AddAttachment line.

    public static async Task sendEmail()
    {
        var apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY", EnvironmentVariableTarget.User);
        var client = new SendGridClient(apiKey);
        var from = new EmailAddress("donotreply@address.com");
        var subject = "Subject";
        var to = new EmailAddress("to@address.com");
        var body = "Email Body";
        var msg = MailHelper.CreateSingleEmail(from, to, subject, body, null);
        msg.AddAttachment(@"C:\Test\test.zip", "Test");
        var response = await client.SendEmailAsync(msg);

        Console.WriteLine(response.StatusCode);
        Console.ReadLine();
    }

**Comment by thinkingserious** [comment]
Hi @Angry-Leprechaun,

The first parameter to AddAttachment is the filename and the second is the base64 encoded content.

Here is a full example: https://github.com/sendgrid/sendgrid-csharp/issues/402

I hope that helps!

With Best Regards,

Elmer
