### ISSUE TITLE
phpBB Issue with sendgrid

### ISSUE THREAD

**Issue by Strizzy** [sendgrid/docs#2491]
https://sendgrid.com/docs/Integrate/Open_Source_Apps/phpbb.html

So I followed everything as posted and it's not sending me anything but instead creating this error.

```
Email error
» EMAIL/SMTP
/forum/adm/index.php

Ran into problems sending email at Line 1553. Response: 535 Authentication failed: Bad username / password 
.
Backtrace
Connecting to smtp.sendgrid.net:587
LINE: 1096 <- 220 SG ESMTP service ready at ismtpd0003p1lon1.sendgrid.net 

# EHLO
LINE: 1443 <- 250-smtp.sendgrid.net 

LINE: 1443 <- 250-8BITMIME 

LINE: 1443 <- 250-PIPELINING 

LINE: 1443 <- 250-SIZE 31457280 

LINE: 1443 <- 250-STARTTLS 

LINE: 1443 <- 250-AUTH PLAIN LOGIN 

LINE: 1443 <- 250 AUTH=PLAIN LOGIN 

# STARTTLS
LINE: 1488 <- 220 Begin TLS negotiation now 

# EHLO 
LINE: 1443 <- 250-smtp.sendgrid.net 

LINE: 1443 <- 250-8BITMIME 

LINE: 1443 <- 250-PIPELINING 

LINE: 1443 <- 250-SIZE 31457280 

LINE: 1443 <- 250-STARTTLS 

LINE: 1443 <- 250-AUTH PLAIN LOGIN 

LINE: 1443 <- 250 AUTH=PLAIN LOGIN 

# AUTH PLAIN
LINE: 1546 <- 334 

# Omitting sensitive information
LINE: 1553 <- 535 Authentication failed: Bad username / password 
```

**Comment by thinkingserious** [comment]
Hello @Strizzy,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
