### ISSUE TITLE
Global Unsubscribes

### ISSUE THREAD

**Issue by TimCannady** [sendgrid/docs#2519]
https://sendgrid.com/docs/User_Guide/Suppressions/global_unsubscribes.html

The "Unsubscribe From All Emails" link doesn't link to anything. 🤔

**Comment by thinkingserious** [comment]
Hello @TimCannady,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
