### ISSUE TITLE
Please update for Laravel 5

### ISSUE THREAD

**Issue by phpguru** [sendgrid/docs#2523]
https://sendgrid.com/docs/Integrate/Frameworks/laravel.html

The SendGrid should be updated for Laravel 5

See [Laravel 5.4 Docs](https://laravel.com/docs/5.4/mail#writing-mailables).

**Comment by thinkingserious** [comment]
Hello @phpguru,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
