### ISSUE TITLE
Recommended SMTP settings

### ISSUE THREAD

**Issue by cranesandcaff** [sendgrid/docs#2526]
https://sendgrid.com/docs/Classroom/Basics/Email_Infrastructure/recommended_smtp_settings.html

Does this mean the API key id or the API key secret for the password? Are these three different methods of authenticating SMTP or is it a process of steps?

**Comment by thinkingserious** [comment]
Hello @cranesandcaff,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
