### ISSUE TITLE
Bad/contradictory SPF info in "All You Need to Know About Whitelabeling"

### ISSUE THREAD

**Issue by jamesharvard** [sendgrid/docs#2532]
I believe there are two problems with the SPF part of the ['about whitelabelling'](https://sendgrid.com/docs/Classroom/Deliver/Delivery_Introduction/all_you_need_to_know_about_whitelabeling.html) doc:

> What it should look like:
> 
> TXT (yourdomain) v=spf1 include:uXXXXXX.wl.sendgrid.net -all
> 
> A Sender Policy Framework record states what domains and IPs are allowed to send on your behalf. If SendGrid is not included in your SPF record then we will not be able to send on your behalf and you will probably receive bounces pertaining to authentication issues. If you already have an existing SPF record for your domain then you will just need to append “include:sendgrid.net” to that current record at the end, but before the “all” mechanism.

1. The `uXXXXXX.wl.sendgrid.net` in the suggested/example SPF record does not work for me (presumably should be `v=spf1 (youruserid).wlXXX.sendgrid.net -all`, as per the domain whitelabel CNAMEs).
2. The complete SPF example is at odds with the recommendation to just add `include:sendgrid.net` if an SPF record already exists for the domain.

**Comment by eschallock** [comment]
@jamesharvard Thanks for bringing this to our attention! I'll run this by our Deliverability team to make sure that we get this cleaned up.

**Comment by eschallock** [comment]
Hello @jamesharvard, you're completely correct that the explanation on this page presents some contradictory and confusing information. I've run this by our Deliverability team, and we are working together to improve this content. We will likely redirect this page to the following article, which is much more clear and up-to-date:

https://sendgrid.com/docs/Classroom/Basics/Whitelabel/setup_domain_whitelabel.html 

Unfortunately, this thread isn't the best channel for me to provide you quick and personalized support, but I would love to direct you to our [Support Team](https://support.sendgrid.com/hc/en-us), who would be more than happy to help get your whitelabel up and running.

Thank you so much for brining this to our attention!

**Comment by thinkingserious** [comment]
Hello @jamesharvard,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
