### ISSUE TITLE
Senders API documentation incorrect for verified.

### ISSUE THREAD

**Issue by mrwingate** [sendgrid/docs#2563]
Documentation shows it should be a boolean. I'm seeing an object with status and reason when testing the api.

**Comment by ksigler7** [comment]
Hi @mrwingate, can you please provide a link to the specific documentation you're referring to?

**Comment by thinkingserious** [comment]
Hello @mrwingate,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
