### ISSUE TITLE
Event Webhook

### ISSUE THREAD

**Issue by thesmart** [sendgrid/docs#2631]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Webhooks/event.html

No mention of basic auth or any authentication mechanisms.

**Comment by ksigler7** [comment]
Hey @thesmart, thanks for the feedback! We're no longer updating our old API documentation because we're currently in the process of migrating to new and improved documentation. The new Webhooks doc is here: https://sendgrid.com/docs/API_Reference/api_v3.html and it *does* have authentication.
