### ISSUE TITLE
There are two list of response status codes that disagree with one another

### ISSUE THREAD

**Issue by pugwonk** [sendgrid/docs#2653]
The list at https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/responses.html isn't the same as the list at https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html

**Comment by mbernier** [comment]
Thanks! Merging these would be a great idea. Thank you for the nudge! I will put this on our list to be cleaned up before we go fully over to our new API docs: https://sendgrid.com/docs/API_Reference/api_v3.html
