### ISSUE TITLE
Sending guarantee

### ISSUE THREAD

**Issue by whitsey** [sendgrid/docs#2684]
How do I get a goddamn answer to a sales related question without setting up an account?
Your FAQ is useless and there is no way to ask a question.
I had a question regarding inclusions that are not specifically documented
Good business model - don't provide any sales assistance and watch potential customers find an alternate solution!

**Comment by mikegreen** [comment]
The struggle is real, @whitsey - it takes at least two clicks to get to the contact us page - https://sendgrid.com/contact-us-form/

**Comment by mbernier** [comment]
@whitsey ... I am sorry about that. I shared your comment with our UI/UX people. Were you able to get in touch with our sales team?

@mikegreen thanks for the assist!

**Comment by ksigler7** [comment]
Closing this issue since there's not a specific docs request here. Let us know if you have any other issues!
