### ISSUE TITLE
Bounce Types not explained.

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#2734]
https://sendgrid.com/docs/API_Reference/Webhooks/event.html

Bounces event example shows: "Bounce/Blocked/Expired", but doesn't explain what those differences are. Every where else, these are 3 distinct events, so we need to explain the differences of the 3 Types here.

**Comment by ksigler7** [comment]
@jacobmovingfwd thanks for the issue! I've added this to the internal docs backlog.

**Comment by ksigler7** [comment]
the to do here is to link Bounce/Blocked/Expired in this page to their glossary pages

**Comment by duncanleung** [comment]
@ksigler7 can I take this up?

My understanding is to resolve this issue:

Link **Bounce/Blocked/Expired** terms on [Event Webhook Page](https://sendgrid.com/docs/API_Reference/Webhooks/event.html#-Bounce) to their glossary pages

[Blocks](https://sendgrid.com/docs/Glossary/blocks.html)
[Bounces](https://sendgrid.com/docs/Glossary/bounces.html)
Expired does not yet exist on Glossary ([related to Issue 702](https://github.com/sendgrid/docs/issues/702))

**Comment by ksigler7** [comment]
@duncanleung sure! and yep, that's correct. We can add in for whoever does #702 to link to it from this page too. Thanks for taking this one on!
