### ISSUE TITLE
Universal tag and apple-app-site-association confusion

### ISSUE THREAD

**Issue by dwillislc** [sendgrid/docs#2739]
In your docs on universal links you list an example of the "apple app site association" file with the path being: 
```
  "paths": [
          "/uni/*"
        ]
```
https://sendgrid.com/docs/Classroom/Build/Add_Content/universal_links.html#-What-are-appleappsiteassociation-and-digital-asset-links-files

However, later down in the docs (Flagging Your Universal Links) you mention how you can remove the universal tag "universal=true" from links so that the link redirects to a Web Browser instead of opening the app. The connection between these two points are not clarified and if an integrator doesn't include `/uni/*` but `/*/` in their apple app site association file, then all URLs whether a web or deep link will open the app. We saw a client struggle to get a link to open on a web browser on iOS, even though they removed the universal tag from the URL. 

It would be helpful if you could: 

1. Specify what the universal tag does, which is adding the '/uni/' parameter to the URL that is being sent through SendGrid. It only works if the apple app site association file is setup per the example.
https://sendgrid.com/docs/Classroom/Build/Add_Content/universal_links.html#-Flagging-Your-Universal-Links

2. Specify that integrators should input '/uni/*' into the 'paths' key of their apple app site association file. Given that your file on the docs is listed as an example, integrators are likely to put their own paths, which would cause problems down the line.

**Comment by ksigler7** [comment]
@dwillislc thanks so much for the suggestion! I've added it to our internal docs backlog.
