### ISSUE TITLE
Category Comparison

### ISSUE THREAD

**Issue by Proxay** [sendgrid/docs#2740]
https://sendgrid.com/docs/User_Guide/Statistics/category_compare.html

Hi,

I'm looking to understand how accurate Category Comparison is vs other SendGrid reporting, including homebrew event logging and then counts.
The reason I ask, is Category Comparison reports really positive performance, but other areas of SendGrid and our own reporting provides far lower performance for our email sends.

The most important is simply, how many times an email was viewed.
Category Comparison pegs this at nearly 30k Opens in the reporting period, but our Global Stats page aligns with our own Analytics, which puts the number at around 17k.
This discrepancy is repeated again on the Unique Opens, with Category Comparison leading us to understand we're seeing 65%~, where other reporting is putting the number in the 45% area.

Below is some data for review, I'm leaning towards believing Category Comparison is inaccurate and not a reliable source of reporting data. This isn't good as it was our only way to report email performance until our own service was completed.

-Data for Review-

Review Period: June 21st - June 26th

SendGrid Category Comparison:
![screen shot 2017-06-26 at 10 08 44](https://user-images.githubusercontent.com/22900565/27520896-5c044212-5a58-11e7-85c0-42a1281a2a1d.png)

SendGrid Global Stats
![screen shot 2017-06-26 at 10 11 39](https://user-images.githubusercontent.com/22900565/27520901-71828b76-5a58-11e7-8224-d45bba3e3dbe.png)

Our own Reporting Endpoint, using SendGrid events and aggregating them:
![screen shot 2017-06-26 at 10 09 08](https://user-images.githubusercontent.com/22900565/27520904-82744c9e-5a58-11e7-814d-2e4a86483f13.png)

Best,
Thomas

**Comment by Proxay** [comment]
Also - there are historical emails sent that the Category Comparison would be counting as they're tagged the same. The only reason this is unlikely to explain the spike is that the trend of opens has already dropped off a cliff for the old emails. It's not possible 15k Opens came from a historical send given how long ago they were.

Reference:
![screen shot 2017-06-26 at 10 26 24](https://user-images.githubusercontent.com/22900565/27521005-1c552648-5a5a-11e7-98d5-8b364cc2d081.png)

**Comment by thinkingserious** [comment]
Hello @Proxay,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a docs specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
