### ISSUE TITLE
Define  'Created at' and 'Updated At' 

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#2746]
On this page, we need to define what 'Created at' and 'Updated At' means 
within segmentation. 

https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/lists.html

**Comment by hmbrown64** [comment]
Got this one!

**Comment by hmbrown64** [comment]
Completed #3017

**Comment by ksigler7** [comment]
you rock
