### ISSUE TITLE
Link individual reseller API pages to the Reseller Overview

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#2748]
These are Reseller Only APIs. For more information, see <link to reseller overview page>.

**Comment by krista-southworth** [comment]
I can take this

**Comment by krista-southworth** [comment]
I did this at Hacktoberfest, but do not see my PRs anymore...

**Comment by ksigler7** [comment]
hey @krista-southworth, I know, it's because we're merging them in right now! thanks again for doing this :)
