### ISSUE TITLE
Update Clicks Glossary page

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#2749]
Update with this information:

The “Clicks” percentage is the total number of times your users have clicked on the various links within your emails, divided by the total number of Delivered messages. The “Unique clicks” percentage is the number of unique individuals that have clicked the links in your emails, divided by the total number of Delivered messages. This requires that the Click Tracking app be enabled. 

Users clicking a SendGrid Unsubscribe link will not count as a Click. However, if you use a third-party unsubscribe link, it will be tracked as a Click.

**Comment by hmbrown64** [comment]
https://github.com/sendgrid/docs/pull/2889
