### ISSUE TITLE
Update segmentation documentation

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#2750]
https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/lists.html#-Create-a-Segment

Rewrite with steps instead of a bunch of text. And also needs to be updated to make the functionality of segmentation more clear. What is the order of operations when handling segmentation on lists?

**Comment by seasonguy** [comment]
Hi! I would like to work on this issue!

**Comment by seasonguy** [comment]
Hello! I would like to work on this issue!

**Comment by ksigler7** [comment]
thanks @seasonguy! We're looking at your pull request now!
