### ISSUE TITLE
Get IPs assigned to Subuser undocumented

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#2759]
https://api.sendgrid.com/v3/ips?subuser=:subusername is a valid call, per Developer Tools & tested in my own console. 

Documented, I can see *all* IPs, which will show which Subusers are assigned which IPs, but that's grouped by IP, not user: https://sendgrid.com/docs/API_Reference/Web_API_v3/IP_Management/ip_addresses.html#-GET

I can also `PUT` to Update the IPs assigned to a subuser: https://sendgrid.com/docs/API_Reference/Web_API_v3/subusers.html#Update-IPs-assigned-to-a-subuser-PUT
But that doesn't have a GET equivalent. A `Resource not found`error is returned if I attempt that.

**Comment by ksigler7** [comment]
@jacobmovingfwd did you try the GET/ips/assigned using the `on-behalf-of-<subuser>` header? Here's more info about the header: https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/on-behalf-of

**Comment by jacobmovingfwd** [comment]
Oh, neat, that would do it, yeah.
