### ISSUE TITLE
Can't log in to your account?

### ISSUE THREAD

**Issue by anik786** [sendgrid/docs#2769]
https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/cant_log_in_to_your_account.html

I can't login to my account. Every time I login, I can briefly see my dashboard. I then get logged out and redirected back into the login page. Note this is not a browser issue as I have tried it on both IE and Chrome. And it's clearly not a password issue as I can briefly (for a few seconds) see my dashboard. I also have not received any email on account being banned or bills not being payed!

I read the docs, and there is no mention in how to actually contact support! The only form of support I can find where I can actually talk to someone is the "Login & contact support" option here: https://support.sendgrid.com/hc/en-us

However I CANNOT LOGIN!

There's also this link: https://sendgrid.com/contact/ but despite being the contact page, there is no way for me to contact you, so this was my only hope!

Please help urgently!

**Comment by anik786** [comment]
I can login now, but can we have a feature to contact SendGrid without logging in

**Comment by ksigler7** [comment]
Hi @anik786 - we were having a login issue with our site this past weekend. Here is more information about it: http://status.sendgrid.com/incidents/dv09q5zjqnnh.

If you would like to subscribe to future SendGrid outage status updates, you can at the top of that page.

Since this isn't a docs specific issue, I am going to close this here, but I have let the relevant people know that a feature to contact SendGrid without logging in has been requested.

**Comment by thinkingserious** [comment]
Hello @anik786,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Prasanthkumar1989** [comment]
My Login is not working. Can you please check and resolve this urgently.

**Comment by Mubby09** [comment]
I can't log into my sendgrid account. I get an error message that I am unauthorized to access sendgrid

**Comment by Mubby09** [comment]
Hello, I hope you already found a solution to this problem but if not, I
didn't really do much. I simply contacted them and it was fixed in a
matter of hours if i can remember.

**Comment by Mubby09** [comment]
> > I can't log into my sendgrid account. I get an error message that I am unauthorized to access sendgrid
> 
> Hey dude did u fixed it yet cuz im having the same problem i dont know how to solve it!


Hello, I hope you already found a solution to this problem but if not, I didn't really do much. I simply contacted them and it was fixed in a matter of hours if i can remember.

**Comment by Uhilasb** [comment]
> > > I can't log into my sendgrid account. I get an error message that I am unauthorized to access sendgrid
> > 
> > 
> > Hey dude did u fixed it yet cuz im having the same problem i dont know how to solve it!
> 
> Hello, I hope you already found a solution to this problem but if not, I didn't really do much. I simply contacted them and it was fixed in a matter of hours if i can remember.

Alright thanks

**Comment by vidukapoor** [comment]
i just signed up and trying to login, and getting error, support also not working.
![image](https://user-images.githubusercontent.com/14005853/84225198-2657f300-aafc-11ea-8e2b-2d8d9394e80c.png)

**Comment by safinghoghabori** [comment]
I am facing the same issue as @vidukapoor . Can anyone tell me what should i do ?

**Comment by Mubby09** [comment]
Hi Safin,
I believe you must have verified your email..
If you haven't done that, please do that and try logging in again.
If the problem persists, SendGrid has a very good customer care service and
I believe they would sort this out for you as soon as possible..

**Comment by safinghoghabori** [comment]
@Mubby09 hello, 
Actually i didn't get any email from the SendGrid, i don't know why.
I also mail on their support team but still no any reply.

**Comment by Mubby09** [comment]
I want to believe this is a little glitch as they would reach out to you..
I don't know if this would be of any help to you but you could try sending them a mail here
'support@sendgrid.zendesk.com', if it was not the one you tried contacting them on..

**Comment by Mubby09** [comment]
If you are unable to login to https://support.sendgrid.com:
1. Click "Trouble Logging in?"
2. Then, select "I am having a different login issue."

**Comment by safinghoghabori** [comment]
I already sent my problem on https://support.sendgrid.com and now mailed support@sendgrid.zendesk.com on this address as you told.

**Comment by Mubby09** [comment]
Hi Safin,
Just checking in to see if the issue has been resolved

**Comment by safinghoghabori** [comment]
Yes let me check. 
By the way @Mubby09 i got email from the SendGrid too. It says you are not eligible for our platform. 
So now what should i do ?

**Comment by abhi-dasgupta** [comment]
@Mubby09 Hi, I'm having the same issue, can't login

**Comment by Mubby09** [comment]
Hello, abhi-dasgupta,
You could try reaching out to their customer service.
It's most  likely your account has not been verified by sendgrid
They are very helpful

Best regards.

**Comment by abhi-dasgupta** [comment]
did that, no reply since 2 days, Had no issues while developing, 4 days into staging and and sendgrid does this. Can't demo to clients :(  Will wait till today evening, then move to mailgun

**Comment by Sayalib25** [comment]
Hello,

Facing the login issue, giving message as "You are not authorized to access SendGrid, please contact Support."  I also send message to support yesterday but didn't get any response yet.

**Comment by SAYAN-1997-C** [comment]
Hello,
I can't login my account and when I try to login always get a error message "You are not authorized to access SendGrid,Please contact support."I send message many times to support but didn't get any response.

**Comment by mshimshon** [comment]
+1 same here, sms code constantly invalid 2FA experience is horrible.... whenever i successfully login it says security check failed and kick me out... very bad experience for new customer! no live chat and support process is very counter-productive they cannot do anything about login issues... we were about to use sendgrid natively in our apps and sass but now... im not sure.

thats my 2 cents feedback.

i use Brave Browser with adblocking.
