### ISSUE TITLE
Integrate with SendGrid

### ISSUE THREAD

**Issue by bryan-kramer** [sendgrid/docs#2770]
https://sendgrid.com/docs/Integrate/index.html

1. Page suddenly introduces term SMTPAPI without defining it.
2. It is not clear that when using SMTP, all of the features of sendgrid are available (hooks, reporting, click tracking etc.)

**Comment by ksigler7** [comment]
@bryan-kramer thanks for the issue! Check out the SMTP API Overview page for more information about using it, and it's features: https://sendgrid.com/docs/API_Reference/SMTP_API/index.html
