### ISSUE TITLE
Update partner in threads glossary topic

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#2828]
From @kelseyenglish in https://github.com/sendgrid/docs/pull/2826 - No longer using Threads for triggered messages- we are now partnered with Klaviyo. They are a solution for drip campaigns and triggered series of messages.

So the task is to update the glossary page with this information: https://sendgrid.com/docs/Glossary/triggered_actions.html

**Comment by Divya063** [comment]
Can I take this up?

**Comment by ksigler7** [comment]
hi @Divya063 - thanks for volunteering for this one! it actually looks like this issue has already been fixed though and is a duplicate
