### ISSUE TITLE
add link to next video to MC templates page

### ISSUE THREAD

**Issue by alexroussos** [sendgrid/docs#2829]
The video on https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/templates.html  mentions that it will go into more detail "in the next video". There is no pointer to the next video on the page and it doesn't show up in the suggested video links at the end of the video. I had to go to SendGrid's Vimeo account then look through all the uploads to find Part 5. It should be linked somewhere.

**Comment by ksigler7** [comment]
Task: link to video part 5 under the top video on the marketing campaigns template page.

Video part 5 link: https://vimeo.com/139274837
