### ISSUE TITLE
IP Addresses

### ISSUE THREAD

**Issue by alexroussos** [sendgrid/docs#2831]
The docs adding an IP address to a pool state that `ip` is a URI parameter. It's actually POST data, eg the JSON below

```
{
  "ip": "1.2.3.4"
}
```

https://sendgrid.com/docs/API_Reference/Web_API_v3/IP_Management/ip_addresses.html#----POST

**Comment by ksigler7** [comment]
Thanks for the suggestion! This is actually correct in our new Stoplight documentation: https://sendgrid.api-docs.io/v3.0/ip-pools/add-an-ip-address-to-a-pool 

Even though this is definitely incorrect, I am going to close this issue because we are on the verge of sunsetting our old API docs.
