### ISSUE TITLE
broken link in Apple Mail Docs

### ISSUE THREAD

**Issue by maland** [sendgrid/docs#2833]
https://sendgrid.com/docs/Integrate/Mail_Clients/applemail.html

Mail sometimes attaches images in a way that is incompatible with other email readers, but this is **correctable**.

http://micahgilman.com/play/disable-mac-mailapp-inline-image-attachments/ in not available 

would be kind to get a replacement

**Comment by ksigler7** [comment]
The note should be updated to something like: Mail sometimes attaches images in a way that is incompatible with other email readers, but you can correct this by (updating it to send more traditional non-inline attachments)[https://www.lifewire.com/os-x-mail-conventional-attachments-1172730].

Definitely open to this linking out to a different page if a different page is better though. @maland  - did you ever find a page that explained this that you would recommend we update the link to?

**Comment by vrom911** [comment]
@ksigler7  There is an archived version of this article at [archive.org](https://archive.org/).
Would you mind if I add the latest archived version of Micah Gilman's blog post to the docs and pr it?
