### ISSUE TITLE
add a glossary page for the term "preheader"

### ISSUE THREAD

**Issue by astrohart** [sendgrid/docs#2839]
https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/design_editor.html

Hi,

What is a 'email preheader'?  The docs mention it, and there is this field "Preheader" on the Design Editor, but I've searched both google and the docs, and I can't find out what this thing called a "Preheader" actually is, or what it's used for.  

Mind clearifying?

![pic](https://user-images.githubusercontent.com/8261875/29245901-f84a89e6-7f9d-11e7-8b40-e42c1ced331d.png)

**Comment by ksigler7** [comment]
@astrohart - thanks for the suggestion! The email preheader is the snippit of text that shows up after the subject line of an email:
![image](https://user-images.githubusercontent.com/28788585/30932552-0ca1b6ca-a385-11e7-8a70-dc1727628660.png)

We should definitely have a glossary entry for this! So the task here is to add a new glossary page in the glossary with an explanation of the preheader, and then to link it to this page: https://sendgrid.com/docs/Glossary/subjects.html

**Comment by astrohart** [comment]
Hi Kaylyn,

Thanks for the helpful definition.  And just a help for you -- I believe it is spelled "snippet," not "snippit."

Regards,
 
Brian Hart

**Comment by ksigler7** [comment]
Hi Brian,

Haha, thanks for the typo catch! I updated my comment.

Kaylyn

**Comment by Logan1x** [comment]
i would like to work on this @ksigler7  😊

**Comment by Logan1x** [comment]
@ksigler7 please review it😊

**Comment by ksigler7** [comment]
thanks so much @Logan1x!! Reviewed and merged!
