### ISSUE TITLE
Go

### ISSUE THREAD

**Issue by nad2000** [sendgrid/docs#2840]
https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/go.html

the code sample is out-dated. the go wrapper doesn't support API V2 any more...
I wish there were back-ward compatibility though.

**Comment by ksigler7** [comment]
thanks for this catch! If you want, you can use older versions of the libraries with the v2 API - for more info on doing this with our Go library, see [Continue Using V2 in GO](https://github.com/sendgrid/sendgrid-go/blob/master/TROUBLESHOOTING.md#continue-using-v2)

It's a good suggestion to update these examples with this information though, so the to do here is to update all of the [V2 code example pages]:(https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/index.html)

![image](https://user-images.githubusercontent.com/28788585/30940503-898e6fa2-a39e-11e7-83f6-da11e1f8a7fc.png)

with a note like this:

{% info %}
The <language> library does not officially support the V2 API, but you can use V2 with an older version of the library. For more information, see [Continue Using V2 in <language>](link to section in troubleshooting md file of the specific library)
{% endinfo %}

**Comment by Logan1x** [comment]
@ksigler7  can i work on this?
