### ISSUE TITLE
"Click here" is missing a link.

### ISSUE THREAD

**Issue by toddmoy** [sendgrid/docs#2843]
https://github.com/sendgrid/docs/blob/develop/source/Classroom/Troubleshooting/Account_Administration/teammates.md

4th paragraph, last sentence.

**Comment by ksigler7** [comment]
thanks @toddmoy! 

The todo here is to update: 

If you create a teammate in the UI, but find that it lacks sufficient permissions, then you will have to modify those permissions by making an API call. For more information on how to do this, click here.

to 

If you create a teammate in the UI, but find that it lacks sufficient permissions, then you will have to modify those permissions by making an API call. For more information on updating permissions with the teammates API, see the [`PATCH /teammates/{username}` method](https://sendgrid.api-docs.io/v3.0/teammates/teammates-update-teammate-permissions) in the API Reference.

**Comment by angelinec** [comment]
Hi @ksigler7 , I've created a pull request #2945

**Comment by ksigler7** [comment]
thanks so much @angelinec
