### ISSUE TITLE
add in substitution tag limit to SMTP doc page

### ISSUE THREAD

**Issue by matthieunelmes** [sendgrid/docs#2852]
https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html

Character limit is no specified anywhere in documentation. Might be worth mentioning "Substitutions are limited to 10000 bytes per personalization block."

**Comment by ksigler7** [comment]
@matthieunelmes good catch!

The to do here is to add a note similar to this around line 25 of https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html:

{% info %}
Substitutions are limited to 10000 bytes per personalization block.
{% endinfo %}

**Comment by shovanch** [comment]
@ksigler7 Can I work on this?

**Comment by shovanch** [comment]
@ksigler7 I have created a pull request #2946

**Comment by ksigler7** [comment]
thanks @shovanch!!! Reviewed and merged
