### ISSUE TITLE
add more troubleshooting info to the postfix file

### ISSUE THREAD

**Issue by kiranshashiny** [sendgrid/docs#2861]
https://sendgrid.com/docs/Integrate/Mail_Servers/postfix.html

Please include the folder where the default maillog file is present, so that new users know what to look for in case of other errors.

In my case on a CentOS server, the error was that a lock file was blocking the postfix start. This was reported in the default maillog file.
Documenting this would help in this article.

**Comment by ksigler7** [comment]
@kiranshashiny thanks for pointing this out! Can you add anymore information about where the default maillog file is present?

**Comment by ksigler7** [comment]
The to do here is update the postfix troubleshooting section with a note about where you can find the default maillog file and the type of information this provides.

**Comment by kiranshashiny** [comment]
@ksigler7  - Thanks for taking this up.
 Appreciate it.

On a Centos - it would be in /var/log/maillog - as default.

**Comment by ksigler7** [comment]
perfect, thanks @kiranshashiny!

**Comment by michizhou** [comment]
I would be happy to take this issue!

**Comment by michizhou** [comment]
@ksigler7 Just wanted to let you know that I recently committed some changes to the postfix file and its troubleshooting section that should address this issue.

**Comment by michizhou** [comment]
Hi @ksigler7 I just wanted you to know that I recently created a new PR (#4092) in place of the old one (#4023) to address this issue in light of the recent changes to this repo's file system structure. Let me know if you need me to make any other changes to the docs. Thanks!

**Comment by ksigler7** [comment]
@michizhou - thank you so much for doing this!
