### ISSUE TITLE
Laravel Mail Example is Not Correct

### ISSUE THREAD

**Issue by AdrianB93** [sendgrid/docs#2875]
In Laravel, the `Mail::send()` and `Mail::queue()` methods are no longer available, your docs are out of date. Laravel 5.5 is the new LTS release meaning you don't need to document the old mail methods

See https://laravel.com/docs/5.5/mail#sending-mail

https://sendgrid.com/docs/Integrate/Frameworks/laravel.html

**Comment by ksigler7** [comment]
Thanks @AdrianB93!
To do here is to update the laravel framework page for the latest LTS release. Research and test integrations, or knowledge of an existing integration needed to make these updates.

**Comment by Braunson** [comment]
@thinkingserious @ksigler7 I'll update the docs for this 👍
