### ISSUE TITLE
Broken Table of Contents in Keen - SendGrid Integration Tutorial

### ISSUE THREAD

**Issue by wetzler** [sendgrid/docs#2913]
https://sendgrid.com/docs/Integrate/Tutorials/analytics_with_keen_io.html

it looks like a single paranthesis is missing.
a big launch is happening tomorrow so if anyone knows how to fix, plz help!

![screen shot 2017-09-19 at 3 36 34 pm](https://user-images.githubusercontent.com/1840448/30618747-9fbe0372-9d50-11e7-8e71-ff3da03d7a22.png)

**Comment by ksigler7** [comment]
@wetzler thanks for the catch! I can push this fix to production before your big launch tomorrow

**Comment by wetzler** [comment]
omg thank you. I found another one (less urgent but still would be nice to have). will log separately.

**Comment by ksigler7** [comment]
@wetzler you're welcome! We'll address the other one soon (or someone in our open source community!)

Closing this issue because the links are working correctly now!
