### ISSUE TITLE
Event Webhook duplicates

### ISSUE THREAD

**Issue by alexroussos** [sendgrid/docs#2933]
The docs state that it's _possible_ to receive duplicate events. In reality, it is virtually guaranteed. I receive each event an average of 3 times, and some events I have received as many as *46 times* over a 29 hour period.

A reasonable dev would assume _possible_ means infrequently, and that you might receive an event twice, maybe three times. This has implications when designing an integration with this API. I believe this should be considered a bug, but that's a separate issue; at minimum, the docs should not try to downplay a detail that is relevant for devs integrating with this API. 

https://sendgrid.com/docs/API_Reference/Webhooks/event.html#-Duplicate-Events

**Comment by ksigler7** [comment]
Hello @alexroussos,

This is definitely a bug. Please go ahead and contact our support team to report the bug. They also may be able to help you troubleshoot your specific use case. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by stotlyakov** [comment]
Hi all,
Why is this closed when is not fixed?

**Comment by sstrycker-zspace** [comment]
me too - still seeing duplicates from my webhook...

**Comment by stotlyakov** [comment]
Nope, this does not change anything. I do return 200 ok and still same thing.

**Comment by stotlyakov** [comment]
Hmm, i wander if they can't understand  `new OkResult()` .What exactly did you return?

**Comment by mars-boy** [comment]
Hi @stotlyakov  any update on this. I am getting multiple events I have a requirement where I need to track click count  too showing 3 clicks instead of 1 means its an issue .

**Comment by stotlyakov** [comment]
Yes, sorry for the late response. You have to ensure you return 200 ok to SendGrid
This is the response I give back. this ensures only one event and SendGrid will not try again.

return new OkObjectResult("Email progress logged.") or it could be just empty o 200Ok

**Comment by reezvi** [comment]
@stotlyakov - not quite true. From my web api, I am returning new HttpResponseMessage(HttpStatusCode.OK), yet receiving multiple events for same status (i.e. Processed, Delivered, etc).
