### ISSUE TITLE
Suppressions

### ISSUE THREAD

**Issue by jeyoung** [sendgrid/docs#2950]
## Expected content

What is suppression? When should suppression be used?

## Actual content

Suppression versus unsubscribe

**Link to page**:

https://sendgrid.com/docs/User_Guide/Suppressions/index.html

**Comment by ksigler7** [comment]
Hi @jeyoung,

Thanks for the suggestion! An unsubscribe is a type of suppression. So, if someone unsubscribes from your email list, they are added to your suppression lists. This video will give you more information about it: https://sendgrid.com/docs/Classroom/Deliver/Delivery_Introduction/unsubscribes_explained.html 
If you have any specific questions about setting up global unsubscribes, or other types of suppressions, please reach out to our support team. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
