### ISSUE TITLE
Change all instances of "Delivery Metrics" to "Statistics"

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#2965]
## To Do: 

SendGrid is no longer using the term "Delivery Metrics" and is using "Statistics" instead. Use the following search to replace all instances of 'delivery metrics' in the docs: 

https://github.com/sendgrid/docs/search?utf8=%E2%9C%93&q=delivery+metrics&type=

**Comment by prnvdixit** [comment]
I would like to take this issue :smile: . Please, assign me the same. Thanks.

**Comment by ksigler7** [comment]
sure @prnvdixit, go for it! thanks so much!!

**Comment by prnvdixit** [comment]
@ksigler7 Thanks for assigning the issue :+1: 
A question - Is there any documentation/reference to guide me towards ```Who can ``` and ```How can``` one ```join the organization``` and ```self-assign the issues``` - I looked around but couldn't find one. Thanks. :smile:

**Comment by davedom11** [comment]
I'm gonna take a stab at this!
