### ISSUE TITLE
Write a Glossary entry for "Sends" as it relates to Statistics

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#2969]
## To Do:

Write a Glossary entry for "Sends" as it relates to Delivery Metrics. 

For examples of our glossary pages, see: 
https://sendgrid.com/docs/Glossary/index.html

**Comment by alfredlucero** [comment]
I'd like to try this one out :D.

**Comment by ksigler7** [comment]
awesome! I saw your pull request, so thank you so much @alfredlucero! We will review your pull request in the next couple of days!
