### ISSUE TITLE
Add header to SMTPAPI Categories page

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#2974]
## To do:

On the following page:
https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html

Just before the text: 
"You can assign up to 10 categories per message:" 

Add: 
{% anchor h2%} 
Limitations 
{% endanchor %}

The end.

**Comment by irmattg** [comment]
@Whatthefoxsays I'll take this issue!

**Comment by irmattg** [comment]
@Whatthefoxsays nevermind, having issues installing ruby onto my system. apologies.

**Comment by ksigler7** [comment]
@irmattg you are not the first person to report this, and we think we've figured out the issue, so we are in the process of updating our readme, however, for this one, you don't really need to download our docs locally. 

To edit this page using the github editor, [click on the link to the docs page you want to edit](https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html)
Then click the View and Edit icon on the top right corner of the page - this links you to markdown in github.
Once you're in the github source, click the edit this page pencil icon (right next to the raw, blame and history buttons)
Once you are in edit mode, you can add the requested heading, commit the issue, and then create a pull request.

Let us know if you're still interested!

**Comment by ksigler7** [comment]
this was closed by @ciceropablo in #3030 thanks!
