### ISSUE TITLE
Find/remove all double spaces after periods.

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#2975]
## To do:

Search docs for ".  " and replace with ". "

**Comment by irmattg** [comment]
@Whatthefoxsays hey - ". " and replace with ". " seem the same. Lmk if I'm missing something here?

**Comment by Whatthefoxsays** [comment]
One has two spaces after the period, the other has one. Thanks for checking!

**Comment by ujjwalagrawal17** [comment]
Should we do it in readme or any other doc ?

**Comment by egin10** [comment]
may i try to help you ?

**Comment by BestDanelleEver** [comment]
Can i try this?

**Comment by ksigler7** [comment]
thanks @BestDanelleEver and @egin10, but it looks like we already have a pull request in for this issue: https://github.com/sendgrid/docs/pull/2977
