### ISSUE TITLE
Create a partners landing page for Jelastic

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#2979]
## To do:

Create a partner landing page for Jelastic. Add a brief overview of the service and include any information customers might find useful. 

Include links to the following pages:

http://docs.jelastic.com/sendgrid-php 
http://docs.jelastic.com/sendgrid-java

Don't forget to add a cross-reference link to the Partners Index:

https://sendgrid.com/docs/Integrate/Partners/index.html

**Comment by vigzmv** [comment]
I would like to try this.

**Comment by ksigler7** [comment]
@vigzmv thanks so much! let us know if you have any questions

**Comment by ksigler7** [comment]
@jvogit - thanks for the PR! we haven't forgotten you (we just got overwhelmed with Hacktoberfest), we are going to be able to look at your PR soon
