### ISSUE TITLE
Create Marketing Campaigns Glossary Pages

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#2980]
## To do:

Write brief Glossary entry for each of the following topics on a separate glossary page and link to these topics from the Terminology section of the [Marketing Campaigns Overview Page](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/index.html):

- Campaigns
- Segments
- Lists
- Custom Fields
- Reserved Fields
- System Fields
- Senders

**Comment by alfredlucero** [comment]
I'd like to take this one :D

**Comment by ksigler7** [comment]
@alfredlucero go for it! thank you!

**Comment by alfredlucero** [comment]
Made a PR for it for you all to see :) 👍

**Comment by ksigler7** [comment]
@alfredlucero, you did a really awesome job on this! thanks so much for your help!!

**Comment by alfredlucero** [comment]
no problem glad to help :D.
