### ISSUE TITLE
Combine several existing pages into a new account management page

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#2981]
Currently, we have many different pages about signing up/deleting / and changing your account plan, and resetting username and password:
- https://sendgrid.com/docs/Classroom/Basics/Account/how_do_i_add_more_emails_to_my_account.html
- https://sendgrid.com/docs/Classroom/Basics/Account/account_sign_up_faq.html
- https://sendgrid.com/docs/Classroom/Basics/Account/how_can_i_cancel_my_account.html
- https://sendgrid.com/docs/Classroom/Troubleshooting/dont_know_your_username.html
- https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/dont_know_your_username.html
- https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/recovering_your_username.html
- https://sendgrid.com/docs/Classroom/Basics/Account/resetting_your_password_without_breaking_current_integrations.html
- https://sendgrid.com/docs/Classroom/Basics/Account/resetting_your_password_as_a_teammate.html

The to do:
Create a new page that has no less than these tasks:
- Creating a SendGrid account
- Deleting your SendGrid account
- Changing your SendGrid account plan
- Resetting your account username
- Resetting your account password
- Additional resources - these should include a link to whitelabeling and 2fa

delete the pages listed above and redirect them to your new page, which should be in [User Guide>Settings](https://sendgrid.com/docs/User_Guide/Settings/index.html)

**Comment by debri174** [comment]
I'm gonna take a stab!

**Comment by hmbrown64** [comment]
Got this one!

**Comment by ksigler7** [comment]
you da best @hmbrown64  :)

**Comment by ksigler7** [comment]
After discussion on #2709, I have an additional to do to add onto this item - since we updated password resets to happen through SendGrid instead of letting integrations handle it, these integrations pages also need to redirect to this new page with a note at the bottom of the password reset section, something like:
{% info %}
You can also reset your password here if you're using SendGrid through an integration like AWS, Azure, IBM Cloud Marketplace, OpenShift, Heroku, AppDirect, or SoftLayer.
{% endinfo %}

The files that need deleted and redirected here are these:

- [Heroku Users - Find your SendGrid Credentials](https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/heroku_users_find_your_sendgrid_credentials.html)
- [How to change password when integrated via AppDirect](https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/how_to_change_password_when_integrated_via_appdirect.html)
- [How to change the password for your SendGrid account via SoftLayer](https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/how_to_change_the_password_for_your_sendgrid_account_via_softlayer.html)
- [How to change the password for your SendGrid add-on via Azure](https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/how_to_change_the_password_for_your_sendgrid_add_on_via_azure.html)
- [How to change the password for your SendGrid add-on via OpenShift](https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/how_to_change_the_password_for_your_sendgrid_add_on_via_openshift.html)
- [How to change the password for your SendGrid add-on via the IBM Cloud Marketplace](https://sendgrid.com/docs/Classroom/Troubleshooting/Account_Administration/how_to_change_the_password_for_your_sendgrid_add_on_via_the_ibm_cloud_marketplace.html)

**Comment by thepriefy** [comment]
I would like to do this. Is this available?

**Comment by ksigler7** [comment]
@hmbrown64 are you still planning to work on this?

**Comment by hmbrown64** [comment]
@ksigler7 Yes I am!

**Comment by Whatthefoxsays** [comment]
Creating a new issue that captures the current state of this documentation and the additional updates that need to be made.
