### ISSUE TITLE
Add a note re: timezone in Sending an Email

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#2982]
## To do:

Add a note to the [Sending an Email](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/getting_started.html) page informing the customer that they need to make sure their account is set to the correct timezone to ensure that their emails are indeed sending when they want them to. Add simple instructions for navigating to their timezone in their account settings.

**Comment by hmbrown64** [comment]
Completed in #3010

**Comment by ksigler7** [comment]
@hmbrown64 and @madhurgupta10 - I'm so sorry, but it looks like multiple people submitted pull requests for this issue last night! I really appreciate your efforts on this, but I am accepting the first one (https://github.com/sendgrid/docs/pull/2986) - please do check back for more open issues though! We are adding new ones often.

**Comment by madhurgupta10** [comment]
@Whatthefoxsays - I would love to contribute to other projects.

**Comment by ksigler7** [comment]
@madhurgupta10 awesome! check back here often for issues, because we'll continue to add in new ones often. We also have 7 libraries that you could contribute to as well! https://github.com/sendgrid
