### ISSUE TITLE
combine several existing pages into a new dedicated IP page

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#2983]
Currently, we have many different pages about signing up/deleting / and changing your account plan, and resetting username and password:

- https://sendgrid.com/docs/Classroom/Deliver/Delivery_Introduction/IP_reputation_montoring.html
- https://sendgrid.com/docs/Classroom/Basics/Account/what_is_my_sending_originating_ip_address_with_sendgrid.html
- https://sendgrid.com/docs/Classroom/Basics/Account/adding_an_additional_dedicated_ip_to_your_account.html
- https://sendgrid.com/docs/API_Reference/Web_API_v3/IP_Management/ip_warmup_schedule.html
- https://sendgrid.com/docs/User_Guide/Settings/ips.html

The to do:
Create a new page that has no less than these tasks:

- Adding a dedicated IP
- Warming up a dedicated IP

delete the pages listed above and redirect them to your new page, which should be in User Guide>Settings

**Comment by triphius** [comment]
I'd like to take a stab at this one.

**Comment by ksigler7** [comment]
@triphius, sure, go for it, and thanks!

**Comment by thepriefy** [comment]
Are you still working on this? @triphius

**Comment by triphius** [comment]
@thepriefy Got a little sidetracked, but I am still working on it.

**Comment by thepriefy** [comment]
@triphius If you need any help, let me know. :)

**Comment by triphius** [comment]
@ksigler7 I created a PR into a separate branch for now.  It looks like there are some conflicts since my fork.  I'll take a look at them a bit later.
