### ISSUE TITLE
Navigation improvements

### ISSUE THREAD

**Issue by mbernier** [sendgrid/docs#3051]
## Currently

- The navigation builder that we have for our jekyll build sorts the individual files in a directory above the nested directories. You can see this in the menu [on the left here](https://sendgrid.com/docs/Integrate/index.html) -
 where "libraries" is above Tutorials.
- In each file's frontmatter, there is a way to add "weight" to the file, which will determine the sort.
- We have a file [here](https://github.com/sendgrid/docs/blob/develop/source/_data/folder_weights.yml) that allows the root directories to be weighted (ordered)

## Proposed solution
- **Default**: Sort alphabetically, regardless of whether this is a file or a directory
- **Sorted**: Use the weights from frontmatter and a folder_weights file in the directory, to sort the items in that directory.

**Comment by ksigler7** [comment]
deprecating because it's not relevant to our new site
