### ISSUE TITLE
Add spellchecker to build time

### ISSUE THREAD

**Issue by mbernier** [sendgrid/docs#3053]
Everyone makes mistakes! I can't spell or type well. 

Adding [this utility](https://rubygems.org/gems/spellchecker/versions/0.1.5
) as a check at the beginning of the build (check everything past the frontmatter) would be amazing. 

It should fail the build if a spelling error is found. 

Questions to answer: 

- Can we add ignore words?
- Will it fail on acronyms?
- Can we add words we would like to not publish anymore - e.g. We change the name of a featur and we want to identify every use of the old name

**Comment by mamat-rahmat** [comment]
Nice article related on this
https://blog.codeship.com/improve-documentation-by-automating-spelling-and-grammar-checks/

**Comment by ksigler7** [comment]
@mamat-rahmat I got an email notification that you had added a link to this article (but it looks like you deleted it?): https://blog.codeship.com/improve-documentation-by-automating-spelling-and-grammar-checks/

Adding it back in because I think it's very on point

**Comment by mamat-rahmat** [comment]
@ksigler7 sorry for deleted that. The article talk about node-based tool. I was doubt that it was unrelated.
Btw, is ruby-based package preferred here? or open to others? (like node/python)

**Comment by mamat-rahmat** [comment]
Seems like (spellchecker)[https://rubygems.org/gems/spellchecker/versions/0.1.5] is lack of feature unmaintained.
I am researching about alternative tools. Gonna post about the result soon.

**Comment by ksigler7** [comment]
@mamat-rahmat - I don't think it necessarily needs to be ruby based as long as we can still incorporate it into our build

**Comment by hannahapuan** [comment]
Looking at this. According to the [article](https://blog.codeship.com/improve-documentation-by-automating-spelling-and-grammar-checks/) @mamat-rahmat first posted, markdown-spellcheck with npm could work? I could just add the check in the build scripts in package.json. Is that what you are looking for in this project? @ksigler7
