### ISSUE TITLE
Add an Intro/stub for Labs team with contact info and links to external labs docs

### ISSUE THREAD

**Issue by davelee** [sendgrid/docs#3074]
## Expected content

@ksigler7 and I discussed the possibility of adding a short description of Labs team, The Lab (labs.sendgrid.com), and links to experiment specific docs that are hosted externally. This could help limit noise to support for Labs experiments and help get customers communicating with our team instead of going to sendgrid support.  

## Actual content

Feel free to modify this ticket, add content, voice an opinion about whether it's a good idea or not, etc.

**Comment by riktimmondal** [comment]
I would to work on it.Can you give a brief description on how to get started with it

**Comment by ksigler7** [comment]
@riktimmondal - Thanks so much for the offer! However, this is something that Dave is already working on. Please do check back for other issues though, because we are constantly adding new ones!
