### ISSUE TITLE
Add a table of contents at the top of each User Guide Page

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3088]
## To do:

Add a table of contents of each of the H2 and H3 headers to the top of each user guide page. For an example, please see the [Design Editor](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/design_editor.html) page. Pay special attention to our SendGrid-flavored liquid tag formatting please!

## Actual content

**Link to page**:

**Comment by saideepd** [comment]
### Where is the link to user guide page for contribution ?

**Comment by ksigler7** [comment]
@saideepd thanks for taking this up!

**Comment by saideepd** [comment]
@Whatthefoxsays @ksigler7 Does adding Table of Contents apply to the mentioned files inside all the folders under <a href="https://github.com/sendgrid/docs/tree/develop/source/User_Guide">User_Guide</a> page ?

**Comment by ksigler7** [comment]
@saideepd - yep! We're still missing a few, like https://sendgrid.com/docs/User_Guide/email_activity.html
