### ISSUE TITLE
Add a "Additional Resources" section to each User Guide page

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3089]
The to do here is to add an "Additional Resources" section to each User Guide page that doesn't already have one. "Additional Resources" is an h2 section that contains three to five bullet points with links out to other closely related pages. These pages could be SendGrid blogs or docs pages with information about next steps, use cases, or other things a user should consider when they are completing the task on the page.

Here is an example "Additional Resources" section: https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/design_editor.html#-Additional-Resources

Here is example formatting:

```
{% anchor h2 %}
Additional Resources
{% endanchor h2 %}

- [link text]({{root_url}}/User_Guide/Marketing_Campaigns/design_editor.html#-Using-Custom-HTML)(https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/campaign_stats.html)
- [link text]({{root_url}}/User_Guide/Marketing_Campaigns/design_editor.html#-Using-Custom-HTML)(https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/campaign_stats.html)
- [link text]({{root_url}}/User_Guide/Marketing_Campaigns/design_editor.html#-Using-Custom-HTML)(https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/campaign_stats.html)
```

**Comment by Aonepathan** [comment]
I would like to try out this issue! Could I be assigned to this issue?

**Comment by ksigler7** [comment]
@Aonepathan go for it! Thanks so much!

**Comment by thepriefy** [comment]
Are you working on this? May I help you? @Aonepathan

**Comment by Aonepathan** [comment]
@thepriefy Sure! A lot of the User Guides don't have Additional Resources, so it's been taking a little longer than I thought to link to corresponding guides. I started from the top of User Guides, you can start from the bottom up if you want or pick whichever, I've done the Email Activity, About the User Guide, and finishing up SendGrid for Mobile

**Comment by thepriefy** [comment]
So I'll update what I've done here too. :) @Aonepathan

**Comment by thepriefy** [comment]
What I've done so far
- Transactional Email
- Transactional Templates

I'll continue the rest tomorrow. :) @Aonepathan

**Comment by ksigler7** [comment]
@Aonepathan and @thepriefy thanks so much for all the work you have done on this so far!

**Comment by Aonepathan** [comment]
Thanks @thepriefy , I'll add what I've done so far as well

**Comment by triphius** [comment]
@Aonepathan and @thepriefy, just so you know, one of my merges changed a page that you had already added this content to -- so I circled back and made sure your additions got added to the updated page.  :)

**Comment by triphius** [comment]
Oh... and if you guys need any additional help on this one, let me know.  :)

**Comment by thepriefy** [comment]
oh, thanks so much. :) @triphius

**Comment by Aonepathan** [comment]
Thanks @triphius , feel free to help out! There are a lot of pages that still need Additional Resources added, call dibs if you can so we can avoid conflicts!

**Comment by triphius** [comment]
@thepriefy @Aonepathan Okay, I'll call dibs on the Settings section.  :)

**Comment by Aonepathan** [comment]
@thepriefy @triphius Just added Statistics

**Comment by triphius** [comment]
I haven't gotten that many pages fixed up so far, but there were some other fixes that needed to be done on these pages:

User Guide > Settings > Billing
User Guide > Settings > Subusers > Subusers Overview
User Guide > Settings > Subusers > Impersonation
User Guide > Settings > Subusers > Profile
User Guide > Settings > Subusers > Settings

On the above pages, the Additional Resources content has been added, but I've also fixed some formatting and content issues.  I also converted index.html to index.md (still renders as index.html) and converted native html to markdown.

**Comment by Aonepathan** [comment]
@triphius Thank you!

Just added Legacy Newletter

We're almost there @thepriefy @triphius! 
What should be left: Marketing Campaigns, Suppressions and remaining of Settings

**Comment by Aonepathan** [comment]
@ksigler7 Thank you for the awesome Hacktoberfest event and handling all my PR's, it was really a lot of fun! I was curious if I could still submit to truly finish this issue, I know there are some pages missing Additional Resources and could add it to them. I just wasn't sure this was exclusive to only Hacktoberfest as a event.  And I'm sorry it took so long trying to finish this issue!

**Comment by ksigler7** [comment]
@Aonepathan - it would be amazing if you were to finish this out! I don't think any of us realized quite how much effort this was going to take, and we really really appreciate everything you have put into this and everything else you've worked on for us!

We are open source all year around, so if you ever notice anything else that needs updated in our docs, or any issues that you're interested in working on, please feel free to open a pull request :)

**Comment by vikash1903** [comment]
Hello Guys I need one help

**Comment by thepriefy** [comment]
@vikash1903 Hi! How can I help you?

**Comment by Whatthefoxsays** [comment]
Since we've moved to our new Knowledge Center, this issue has been taken care of.
