### ISSUE TITLE
Delete Settings Overview page and redirect

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3090]
## To Do:

Delete the [Settings Overview](https://sendgrid.com/docs/User_Guide/Settings/index.html) page and redirect to the [Account Details ](https://sendgrid.com/docs/User_Guide/Settings/account.html) page. 

## Actual content

**Link to page**:

**Comment by Aonepathan** [comment]
I would like to try and take a stab at this issue, could you assign me this issue?

**Comment by ksigler7** [comment]
@Aonepathan sure! thanks for taking this up!

**Comment by ksigler7** [comment]
@Aonepathan and @thepriefy - thanks for working together on this!
