### ISSUE TITLE
Rewriting/consolidating 2FA pages

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3091]
Currently, we have two pages about setting up 2FA:
- https://sendgrid.com/docs/User_Guide/Settings/two_factor_authentication.html
- https://sendgrid.com/docs/Classroom/Basics/Security/two_factor_authentication_faq.html

There are two to dos here:
1. Rewrite the `User Guide>Settings>Two-Factor Authentication page` to be jobs to be done style, meaning that it should have a table of contents at the beginning, an "Additional Resources" section at the end, and include no less than these sections with steps for each task: Setting Up Two-Factor Authentication (with a note that says: You can create multiple configurations of Two-Factor Authentication, allowing you to use more than one mobile device to authenticate when logging into your account.), Disabling Two-Factor Authentication, and Regaining access to my account when I've been locked out by Two-Factor Authentication
2. Delete the FAQ page and redirect it to the User Guide page in the redirects.htcaccess file

**Comment by thepriefy** [comment]
I'd like to take this one but I have a question.
- In https://sendgrid.com/docs/User_Guide/Settings/two_factor_authentication.html page, there is no section about 'Regaining access to my account...'. Where can I find the information about this?

**Comment by ksigler7** [comment]
@thepriefy - thanks for picking this one up!

Great question - that info is in the FAQ, which I apparently gave a broken link in the description. Here's the update link: https://sendgrid.com/docs/Classroom/Basics/Security/two_factor_authentication_faq.html

**Comment by ksigler7** [comment]
@thepriefy - thanks for the pull requests! I think the only thing left to be done to close this issue is to delete https://sendgrid.com/docs/Classroom/Basics/Security/two_factor_authentication_faq.html
