### ISSUE TITLE
Update Transactional Templates page into a "jobs to be done" format

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3092]
## To do:

Rewrite the [Create and Edit Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/create_edit.html) page in a "jobs to be done" format. This means numbered steps, clear directions and correct UI workflow. Feel free to replace/remove/move screenshots, and remove any unnecessary words. 

Bonus:
Change the title to be sentence case and put in gerundive form. 

Tips:
Avoid passive voice 
UI components should be labeled as **bold**, e.g., Click **OK**.
Keep it short and sweet. 

For an example of a page already put into a jobs format, see [Sending an Email](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/getting_started.html). 

## Actual content

**Link to page**:

**Comment by ksigler7** [comment]
sure @tulikavijay, thanks!
