### ISSUE TITLE
Add "Settings" panel info to Code Editor Page

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3100]
## To do:

Add descriptions and appropriate steps for functionality found on the **Settings** tab within the [code editor](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/code_editor.html). Feel free to copy any applicable information and/or steps from the [Design Editor ](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/design_editor.html) page. 

Don't forget to update the table of contents at the top of the page!

## Actual content

**Link to page**:

**Comment by DhariniJeeva** [comment]
Can I try this?

**Comment by Whatthefoxsays** [comment]
Absolutely! I'll take the "up for grabs" tag down. Good luck!

**Comment by Sidsharik** [comment]
@Whatthefoxsays can I work on it?

**Comment by Whatthefoxsays** [comment]
@DhariniJeeva Are you still interested, or can @Sidsharik work on this issue?

**Comment by dracowane0** [comment]
@Whatthefoxsays  ,kindly review the pr and lemme know if more content needs to be added as i have kept the content as concise as possible.
Thanks.

**Comment by Whatthefoxsays** [comment]
Hey @dracowane0, I appreciate your effort, but your PR describes the incorrect Settings panel. I was looking for the Settings panel located inside the Marketing Campaigns Code editor as shown in the attachment. 
Sorry for any confusion!

![codeeditorsettings](https://user-images.githubusercontent.com/13628723/31968015-fec10102-b8cc-11e7-9f5c-9973275f6a13.png)

**Comment by DhariniJeeva** [comment]
Hi! I'm sorry I'm caught up with other things. He can work on this. Thanks

**Comment by ksigler7** [comment]
this is still open and incomplete! the original submission did not document the correct panel, so someone else can feel free to pick it up!

@DhariniJeeva @Sidsharik

**Comment by Whatthefoxsays** [comment]
This issue has been resolved.
