### ISSUE TITLE
create an `X-Message-ID`glossary entry

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3103]
This should be a new glossary entry, and then it should be linked on the glossary index page. For information about the `X-Message-ID`, see https://github.com/sendgrid/docs/issues/2797

**Comment by Logan1x** [comment]
I would like to work on this @ksigler7

**Comment by ksigler7** [comment]
sounds good @Logan1x! thanks!

**Comment by sarthak-code** [comment]
Can I take this one up?

**Comment by Logan1x** [comment]
@sarthak-code  I am working on this.

**Comment by Logan1x** [comment]
@ksigler7  https://sendgrid.com/docs/Glossary/message_id.html isn't this same thing?

**Comment by Sarthakagarwal22** [comment]
@ksigler7 thanks a lot for merging, I wanted to ask, why is my score on leader board 0.
