### ISSUE TITLE
update redirect

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3119]
In the redirects.htcaccess file, update https://sendgrid.com/docs/Classroom/Deliver/enabling_custom_dkim.html 
 to redirect here: https://sendgrid.com/docs/Classroom/Deliver/Sender_Authentication/internet_standards_spf_and_dkim_and_deliverability.html

**Comment by dearkathie** [comment]
grab this one

**Comment by ksigler7** [comment]
thanks @dearkathie!

**Comment by Sarthakagarwal22** [comment]
Kindly review my pr please [#3137](https://github.com/sendgrid/docs/pull/3137)
