### ISSUE TITLE
Add library to supported libraries list

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3121]
Add https://packagist.org/packages/godpod/sendgrid to the community libraries list: https://sendgrid.com/docs/Integrate/libraries.html#-Community-libraries

**Comment by jhuang314** [comment]
I'd like to work on this :)

**Comment by hardikjain29** [comment]
I can help with this, if no one else is?

**Comment by hardikjain29** [comment]
Sorry for so many display of commits, was trying to change author from work to own. But the PR contains only one commit. 😄
