### ISSUE TITLE
Add a glossary entry for "unknown user"

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3126]
Unknown User - A hard bounce error indicating the email address (user) does not exist at the organization or domain. 

Link to Delivery Metrics, Link to Bounces, Link to Subscriber List Management 
Link to Deliverability Center

**Comment by kaysiz** [comment]
@ksigler7 any clue on how to tackle this? link to page?

**Comment by ksigler7** [comment]
@kaysiz good question! Here is an example of another glossary page that was recently added that you could use as a template for what to do here: https://github.com/sendgrid/docs/pull/3083/files

**Comment by ng29** [comment]
@ksigler7 .. could you please lemme know what all contents should be added in the glossary entry ?..

**Comment by nalinbhardwaj** [comment]
@ng29 Ah, I'm sorry I didn't claim this issue before, I just started work yesterday and forgot to make a comment here. Hopefully, you hadn't replicated the work yet.
