### ISSUE TITLE
Update Black Hat Sender glossary entry

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3131]
On https://sendgrid.com/docs/Glossary/black_hat_sender.html, change 

"A black hat sender is a sender/company who sends email to recipients who either send to recipients who have not given permission to senders to send to them."

to

"A black hat sender is a sender or company who sends email to recipients that didn't specifically requested to get emails from that sender. It is somebody that delivers unsolicited emails to recipients that never requested them."

**Comment by thepriefy** [comment]
I'd like to take this one :)

**Comment by kaysiz** [comment]
@thepriefy sorry had my eyes on it already. :)

**Comment by ksigler7** [comment]
@thepriefy can confirm, @kaysiz already has a pull request for this one. We really appreciate you're willingness to contribute though! Please check out our other easy issues here: https://github.com/sendgrid/docs/labels/difficulty%3A%20easy
