### ISSUE TITLE
Update the readme.md with more up to date instructions on setting up this repo locally

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3134]
Here are the up to date steps:

### Dependencies

**Required:**

- Git
- Xcode
- Java
- Rvm
- Yaml
- Homebrew
- npm
- git-flow
- bundler gem
- bower

### Setup Steps

**Install Git:** [http://git-scm.com/download/mac](http://git-scm.com/download/mac)

**Install a GitGUI **(if you want it) [http://mac.github.com](http://mac.github.com/)

**Install Xcode** (if you don't have it installed. Go the App Store an download it)

**Install Xcode command line tools** &gt; Xcode &gt; Preferences &gt; Downloads ([These are bundled in Xcode as of OSX 10.9](https://developer.apple.com/library/ios/technotes/tn2339/_index.html))

- Note: You may need to run `$ xcode-select --install`

**Install JDK ** the yui compressor will need the full JDK to run - [http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

**Install RVM **

`$ \curl -L [https://get.rvm.io](https://get.rvm.io/) | bash -s stable --ruby`

Close and reopen your terminal window

Check which version you have installed

`$ ruby -v`

The very latest stable version (2.4.0) isn't compatible with the gems we use for the build, so you'll probably need to download version 2.3.0.

`$ rvm install 2.3.0`

then set that version to be the default version

`$ rvm --default use 2.3.0`

**Install [Homebrew](http://brew.sh/) (if you don't have it)**

`$ ruby -e "$(curl -fsSL` [https://raw.githubusercontent.com/Homebrew/install/master/install](https://raw.githubusercontent.com/Homebrew/install/master/install))"

**Install YAML **

`$ brew install libyaml`

**Install npm **

`$ brew install npm`

**Set your Node version**

`$ npm install -g n`

`$ n 6.10.1`

**install git flow to manage branches** ([http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/)) (optional)

`$ brew install git-flow`

**clone repo **

`$ git clone [https://github.com/sendgrid/docs.git](https://github.com/sendgrid/docs.git)`

**OR use the GitGUI tool to clone the repo**

**switch to develop branch to make changes** 

`$ ls docs`

`$ git checkout develop`

**install bundle (if you don't have this installed)**

`$ sudo gem install bundler`

**Go to your docs directory**

`$ cd docs`

**Install the build tools**

`$ npm install`

to install build tools.

**Install bower**

`$ npm install -g bower`

**Install client-side dependencies (jQuery, bootstrap)**

`$ bower install`

*to install client-side dependencies:*

**Install required Ruby gems**

`$ bundle install`

If the gem installation fails with a message like "An error occurred while installing libv8 (3.16.14.7), and Bundler cannot continue", a few extra steps will be necessary in order to build and install a version of V8 that can be used by the libv8 and therubyracer gems:

 `gem uninstall libv8`

 `brew tap homebrew/versions`

 `brew install --force v8-315`
 `bundle config build.libv8 "--with-system-v8 --with-v8-dir=$(brew --prefix v8-315)"` 
 `sudo gem install therubyracer -v '0.12.2'`

 `bundle config build.therubyracer "--with-v8-dir=$(brew --prefix v8-315)"` 
  `bundle install`

### Configure jekyll

Copy, DO NOT DELETE the _config.sample.yml file - definitely do not commit a delete of this file !

`$ cp _config.sample.yml _config.yml`

Edit the following items in the _config.yml "Jekyll & Plugins" section to match your local environment:

`source: /path_to_your_files/source_ (if you're running locally path_to_your_files will be 

/)_`

`destination: /path_to_your_files/public`

For example:

The source would be: /Users/USERNAME/docs/source

The destination would be: /Users/USERNAME/docs/public

### Running

Do the following instead of Jekyll serve:

`$ bundle exec rake preview`

Note: if you receive an error message similar to "No Java Runtime Present: Requesting Install" please see the following instructions

- Open your Terminal

java -version gives you an error and a popup
- Get the mac download here [https://www.java.com/en/download/faq/java_mac.xml](https://www.java.com/en/download/faq/java_mac.xml)
- Install it
- In your terminal, type: 

`export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"`
- run java -version again
- If that worked, then add the above command to your .bash_profile or .profile file and then run 'source .profile'

> [http://stackoverflow.com/a/19582689](http://stackoverflow.com/a/19582689)

### View your install

Browse to 

[localhost:4000](http://localhost:4000/)

**Comment by ksigler7** [comment]
It would also be good to add a section about jobs-to-be-done format:

Jobs to be done style includes:

- Table of contents at the beginning
- "Additional Resources" section at the end
- Include sections to achieve the goal, with steps for each task (numbered steps, clear directions and correct UI workflow)

For an example, see [Sending a Campaign](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/getting_started.html)

**Comment by thepriefy** [comment]
I'd like to do this one and thank you for updating the step so I can setup this repo locally.

**Comment by thepriefy** [comment]
may I ask some more questions @ksigler7 
- what do you want to include in 'Additional Resources' section?

**Comment by vchrombie** [comment]
Is there anything that I can help you?

**Comment by ksigler7** [comment]
@thepriefy good question! I'm taking this question as a suggestion to add something like a `## Styleguide` section with a `### About Jobs-to-be-done` section, and an `### About Additional Resources` section.

For the `### About Additional Resources` section, I would include something like this:

"Additional Resources" is an h2 section that contains three to five bullet points with links out to other closely related pages. These pages could be SendGrid blogs or docs pages with information about next steps, use cases, or other things a user should consider when they are completing the task on the page. Every page should have an additional resources page, so if it doesn't, feel free to add one!

Here is an example "Additional Resources" section: https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/design_editor.html#-Additional-Resources

Here is example formatting:

```
{% anchor h2 %}
Additional Resources
{% endanchor h2 %}

- [link text]({{root_url}}/User_Guide/Marketing_Campaigns/design_editor.html#-Using-Custom-HTML)(https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/campaign_stats.html)
- [link text]({{root_url}}/User_Guide/Marketing_Campaigns/design_editor.html#-Using-Custom-HTML)(https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/campaign_stats.html)
- [link text]({{root_url}}/User_Guide/Marketing_Campaigns/design_editor.html#-Using-Custom-HTML)(https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/campaign_stats.html)
```

**Comment by ksigler7** [comment]
@thepriefy, I went ahead and merged in your first pull request on this! thank you so much for this update, it's clear that it was really needed. Did you plan on adding the new styleguide section, or did you want @vchrombie s help?

**Comment by thepriefy** [comment]
@ksigler7 @vchrombie can help me for adding Style Guide section. :)

**Comment by thepriefy** [comment]
@ksigler7 I've just created a PR for a minor change in the README.markdown file (some missing back-tic and formatting).

@vchrombie can start adding a style guide section to the file. Thanks for help. :)

**Comment by ksigler7** [comment]
thanks @thepriefy!

**Comment by music-mind** [comment]
Anything else to help with?

**Comment by PAPERPANKS** [comment]
@ksigler7 open this issue there are some fixes to correct

**Comment by PAPERPANKS** [comment]
@ksigler7 thanks i will surely fix some

**Comment by dhruvmalik007** [comment]
Is there any Fixes still left??

**Comment by thepriefy** [comment]
let's wait for @paperpanks and @ksigler7 :)

**Comment by PAPERPANKS** [comment]
@dhruvmalik007 Yes, you can verify the correctness of code snippets or git commands to ensure

**Comment by ksigler7** [comment]
thanks so much for everyones effort on this! it looks much better to me, but I can for sure reopen this issue if anyone notices anything else!
