### ISSUE TITLE
Change these example email addresses

### ISSUE THREAD

**Issue by mbernier** [sendgrid/docs#3180]
Here is a list of email addresses we would like changed to `example@example.com`:

```
doesntmatter@nowhere.com
yourlogin@sendgrid.net
you@youreamil.com
person@youaremailing.com
alice@foo.com
casey@baz.com
john.doe@gmail.com
jane.doe@hotmail.com
your.email@example.com
replyto@example.com
teammate3@example.com
alice@sendgrid.com
example@juno.com
example2@band.la
example3@exampledomain.com
esting@sendgrid.ne
rawest@gmail.co
claims@msp.org
info@bnl.co.uk
richard@hengseng.com
test@brandonmwest.com
isaac@hotmail.comm
isaac@example.com
address@domain.com
grouch@trashcan.com
dominic.may@sendgrid.com
jones@example.com
jones2@example.com
e@example.com
example@example.com
customer@example.com
newcustomer@example.com
stomer@example.com
l1@domain.com
2@domain2.com
email1@domain.com
mail2@domain2.com
er@example.com
1@domain.com
xample@example.com
user2@example.c
le@example.com
user4@example.com
tomer@example.com
destination2@example.com
ion2@example.com
sampleuser@example.com
sampleemail@example.com
example2@yahoo.com
brandon.west@sendgrid.com
emailrecipient@domain.com
test@gmail.com
person@customer.com
dmarc.rua@customdomain.com
anything@parse.yourdomain.com
parse@parse.yourdomain.c
customersuccess@sendgrid.com
person@domain.coom
postmaster@thedomain.com
johndoe@gmail.com
johndoe1@gmail.com
postmaster@domain.com
4798911130a2069f3483fda756b8e81c@www.example.com
alex@email.sendgrid.biz
isaac@email.sendgrid.biz
```

## Expected content
All these emails should be removed and replaced with `example@example.com`

## Actual content

This is pretty pervasive throughout the docs content.

**Comment by andyvh** [comment]
I can do it!

**Comment by andyvh** [comment]
Really? I claimed that...

**Comment by Freda46** [comment]
is it done? I can do it

**Comment by SimonSickle** [comment]
It is completed pending merge & review

**Comment by PAPERPANKS** [comment]
@mbernier the pull request #3206 contains commit [updating email address](https://github.com/sendgrid/docs/pull/3206/commits/85181c5f86aa2015a66aecebdd1f6eeaa5b74224) with the code that you have asked to resolve this issue, can you just add a `difficulty:medium` tag to this pull request

**Comment by ksigler7** [comment]
@PAPERPANKS fixed the messed up label!

@SimonSickle - can you please see my comment in your pull request? There seems to be some duplication in your script.

**Comment by ksigler7** [comment]
OOOOH, I finally see what you did here @PAPERPANKS! Thanks so much for the fix!!

@SimonSickle - never mind - looks like @PAPERPANKS has us both covered!
