### ISSUE TITLE
In-page links may not be correct on 'design editor' page

### ISSUE THREAD

**Issue by mbernier** [sendgrid/docs#3192]
The in-page link for `Drag and Drop Code Examples` is not correct when linked within this page.

It should be: `#-Drag--Drop-Code-Examples` Not `#-Drag-&-Drop-Code-Examples`

Please fix this link and check the other in-page links from the web to make sure they are working properly. 

**Link to page**:
https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/design_editor.html

**Comment by joshuafbarker** [comment]
I will take a look at this.

**Comment by ng29** [comment]
The Drag and Drop Code Examples hyperlink was correct but the Drag & Drop Module Descriptions and Styles was not working. Kindly review my pr. Thank you.
