### ISSUE TITLE
Update Code Editor page to match UI changes

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3207]
## To do:

Looks like there have been some UI changes to the Marketing Campaigns Code Editor that we missed! Your mission is to go through [this page](https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/code_editor.html) and update any steps or images that don't match the current UI. For example, there is no longer an "Image" tab. It has been updated to be an icon, but the steps do not reflect that.

**Comment by juanluischaurant** [comment]
I got this one!

**Comment by cs2425** [comment]
I'll take a crack at this!
