### ISSUE TITLE
Fix typos in transactional template documentation

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3208]
## To do:

Fix typos and broken markdown on [this page](https://sendgrid.com/docs/User_Guide/Transactional_Templates/create_edit.html).

**Comment by juanluischaurant** [comment]
I got this one!

**Comment by akoliyot** [comment]
Hello @Whatthefoxsays Can I work on this?

**Comment by Whatthefoxsays** [comment]
@akoliyot Yup! I'll put an 'in progress' tag on it!

**Comment by afischer12** [comment]
I'll help!
