### ISSUE TITLE
Delete two pages and redirect them

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3209]
delete https://sendgrid.com/docs/User_Guide/dashboard.html and redirect it to https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/getting_started.html

delete https://sendgrid.com/docs/User_Guide/about.html and redirect to https://sendgrid.com/docs/index.html

**Comment by juanluischaurant** [comment]
I got this one!

**Comment by darshansharma** [comment]
I will do it.

**Comment by harishnandan** [comment]
I can help.

**Comment by 0x48piraj** [comment]
Can you please help me to jump-start ?
> I'm new to **SendGrid** community

And, I really want to make a successful PR :blue_heart:

**Comment by PAPERPANKS** [comment]
@ksigler7  done with this issue

**Comment by ksigler7** [comment]
@PAPERPANKS - thanks for taking this up!

**Comment by ksigler7** [comment]
@0x48piraj - I am so sorry I missed your comment the other day. Unfortunately, this issue has already been taken, but I have noticed some grammatical errors in our [main readme](https://github.com/sendgrid/docs/edit/develop/README.markdown) that might be a good way to **jump-start**!

In line 64, `making a contribution` should be `contributing` and there should be a comma after `in this way`
In line 108, `Check which version of Ruby you have ` should be `Check your ruby version:`
There are probably some others, so please feel free to make any other suggestions.

To make changes, go into the [readme.markdown file](https://github.com/sendgrid/docs/blob/develop/README.markdown), click the edit button (
![image](https://user-images.githubusercontent.com/28788585/32145870-fcb6a4ea-bc94-11e7-82ed-46a502669474.png)), make the changes, then fill out the commit message at the bottom of the screen, which will then prompt you to open a pull request. Let me know if you have any questions!

**Comment by PAPERPANKS** [comment]
@ksigler7 if the pull request #3234 resolve this issue, then merge this asap as the deadline for the hacktoberfest is very near

**Comment by ksigler7** [comment]
@PAPERPANKS - thanks for the comment! totally understand your worry here. We are hoping to get everything merged in by the end of the day tomorrow, but know that if that doesn't happen, we are working directly with Github and DigitalOcean to make sure everyone gets the credit they deserve!

**Comment by ksigler7** [comment]
@PAPERPANKS - just wanted to make sure you saw my conflict fix - https://github.com/PAPERPANKS/docs/pull/1

**Comment by kunalvishnoi** [comment]
may i go for this?

**Comment by ksigler7** [comment]
@kunalvishnoi thanks for the offer, but this one should have closed. Auto close didn't work for some reason.
