### ISSUE TITLE
Update Apple Mail Integration Instructions with current iOS

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3210]
## To do:

Update the Apple Mail integration page with updated iOS information, steps, and screen shots. 

**Link to page**: https://sendgrid.com/docs/Integrate/Mail_Clients/applemail.html

**Comment by cs2425** [comment]
I'll take this one!

**Comment by ksigler7** [comment]
thanks for taking this up Colin! @cs2425
