### ISSUE TITLE
Add some more content to the email suppressions page

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3211]
On this page: https://sendgrid.com/docs/User_Guide/Suppressions/invalid_emails.html

Add the following to the end of the first paragraph:

Before you send, SendGrid does a check against the format of the email address to attempt to verify its validity. If the recipient server checks the address and doesn't find it, they will send back a 550 bounce to say that this is an invalid email address.

**Comment by yeshijinsel** [comment]
so just paste the paragraph

**Comment by ksigler7** [comment]
@yeshijinsel yep, at the end of the first paragraph

**Comment by yeshijinsel** [comment]
ok 
i will do this..

**Comment by ksigler7** [comment]
@yeshijinsel thanks for taking this up!

**Comment by yeshijinsel** [comment]
why its been closed

**Comment by yeshijinsel** [comment]
has somebody solve already this issue

**Comment by ksigler7** [comment]
@yeshijinsel, yeah, it looks like it was grabbed in https://github.com/sendgrid/docs/pull/3217 - thanks for being willing to do this though! Please check back often, we are always adding new issues!
