### ISSUE TITLE
Create Invalid Email glossary page

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#3213]
## To do:

Write an "Invalid Email" glossary page. 

Feel free to edit this for content/grammar:

An invalid email occurs when you attempt to send email to an address that is formatted in a manner that does not meet internet email format standards. Examples include addresses without the “@” sign or addresses that include certain special characters and/or spaces. This response comes from our own server since an invalid email is impossible to even attempt to send to its [non-existent] destination.

**Comment by 0x48piraj** [comment]
location ? where to add ?

**Comment by shvmsrma** [comment]
where to add?

**Comment by Whatthefoxsays** [comment]
Hi @0x48piraj and @shvmsrma -  thanks for your question! Here's a really good example of where and how to add a glossary page: https://github.com/sendgrid/docs/pull/3183
