### ISSUE TITLE
Redirect broken links

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3215]
All of these links are broken. In the redirects.htcaccess file, please set up redirects of these pages to existing content that makes sense. Some of these pages may have redirects to them already, please make sure you update those too so there's no double redirects

| url                                                                                             | found_at_url                                                                                                                  |
|-------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------|
| http://sendgrid.com/API_Reference/Web_API_v3/Transactional_Templates/index.html                 | https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/index.html                                                 |
| https://sendgrid.com/docs/User_guide/Settings/index.html                                        | https://sendgrid.com/docs/Apps/gravatar.html                                                                                  |
| https://sendgrid.com/docs/API_Reference/Web_API/Legacy_Features/Customer_Subuser_API/index.html | https://sendgrid.com/docs/API_Reference/Customer_Subuser_API/v1_(deprecated)/automatic_login.html                             |
| http://sendgrid.com/API_Reference/Web_API_v3/Transactional_Templates/smtpapi.html               | https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/smtpapi.html                                               |
| https://sendgrid.com/docs/Integrate/tutorials/event_kit.html                                    | https://sendgrid.com/docs/Utilities/event_kit.html                                                                            |
| https://sendgrid.com/Classroom/Track/Bounces/common_smtp_server_bounce_responses.html           | https://sendgrid.com/docs/Glossary/email_error_messages.html                                                                  |
| http://sendgrid.com/API_Reference/Web_API_v3/Transactional_Templates/versions.html              | https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/versions.html                                              |
| http://sendgrid.com/marketing/request-demo                                                      | https://sendgrid.com/docs/Integrate/Partners/EngineYard.html                                                                  |
| https://sendgrid.com/settings/account                                                           | https://sendgrid.com/docs/API_Reference/Web_API/profile.html                                                                  |
| http://sendgrid.com/blocks                                                                      | https://sendgrid.com/docs/Classroom/Deliver/Sender_Authentication/aol_dmarc_changes_refused_due_to_provided_dmarc_policy.html |

**Comment by Xndr7** [comment]
I'll do it!
