### ISSUE TITLE
Add libraries to our libraries list

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3216]
Audit this list -  http://libraries.io/search?q=SendGrid

Add any missing libraries to the correct place on this page: https://sendgrid.com/docs/Integrate/libraries.html

Please match the format of the existing libraries in the list

**Comment by ns61817** [comment]
I can do it

**Comment by jgrrdnd** [comment]
Hi, I added some libraries. PR #3232

**Comment by ns61817** [comment]
Updates to some #3235

**Comment by ksigler7** [comment]
@ns61817 thanks so much for taking this up!
