### ISSUE TITLE
Update docker build to use docker-compose and volumes

### ISSUE THREAD

**Issue by mbernier** [sendgrid/docs#3239]
As of #3236 we have the docs environment running in docker. This is AMAZING! However, each change to a file means you have to rebuild the docker container and the build files are not necessarily being cached. 

## Expected Result
What would be amazing is:
- docker container setup that mounts a local volume for:
  - node_modules  -- allowing for caching on build
  - ruby gems  -- allowing for caching on build
  - /source/ folder
  - /public/ folder

**Comment by bhavin192** [comment]
I will work on this.
