### ISSUE TITLE
Add instructions for deploying the docker build to the readme.md

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3240]
Recently, @szemek was awesome and dockerized our docs: https://github.com/sendgrid/docs/pull/3236

The to do here is to add instructions to our readme for deploying them with docker!

**Comment by marti1125** [comment]
@ksigler7  I am working in :+1:

**Comment by ksigler7** [comment]
thanks for taking this up @marti1125!

**Comment by marti1125** [comment]
@ksigler7  could you give some instructions

**Comment by ksigler7** [comment]
@marti1125 - I actually don't know how - I've never worked with docker. Maybe @szemek has some suggestions?

**Comment by shriyash** [comment]
Hey @ksigler7 - also confused what you mean with this task, and would love more details! Opening terminal and running these commands should deploy locally. They seem to already be [in the docs](https://github.com/sendgrid/docs#using-docker).
```
docker build -t sendgrid/docs:latest .
docker run --rm -it -p 4000:4000 sendgrid/docs:latest
```

**Comment by ksigler7** [comment]
@shriyash wow, thank you so much! I missed this getting added in. Closing this issue.
