### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by mbernier** [sendgrid/docs#3242]
Create a CONTRIBUTING.md file in this repo. You can see an example of this in our [python repo](https://github.com/sendgrid/sendgrid-python/blob/master/CONTRIBUTING.md). 

Please modify this file to apply to the docs (you can get a lot of what you need from README) and make sure the python specific items are not in CONTRIBUTING.

**Comment by yannbf** [comment]
Can I take this? 💃

**Comment by yeshijinsel** [comment]
Is we have to add our profile in here
