### ISSUE TITLE
Event Webhook smtp-id

### ISSUE THREAD

**Issue by budu** [sendgrid/docs#3265]
The doc says

> An id attached to the message by the originating system

I can't find anything else about this in the docs.

How is this id can be attached to the message?
If we don't have control over it, how do we match the events with anything?

**Comment by budu** [comment]
Is that the `Message-ID`?

**Comment by ksigler7** [comment]
@budu - hmm, can you please link to where the docs say this?

**Comment by budu** [comment]
In the Webhooks event documentation:

https://github.com/sendgrid/docs/search?utf8=%E2%9C%93&q=An+id+attached+to+the+message+by+the+originating+system&type=

**Comment by duncanleung** [comment]
Hi @budu are you still having issues with `smtp-id`?

I see the docs page you are referencing is here:
https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html#-JSON-objects

It doesn't look like `smtp-id` is something you modify, but is a value that is automatically appended by SendGrid when Events are generated when an email is processed.

> Delivery events indicate the status of email delivery to the recipient.
> Engagement events indicate how the recipient is interacting with the email.

@ksigler7

**Comment by mindmat** [comment]
Maybe you're looking for this: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html
You receive the Message-ID in the Header X-Message-Id of the response

**Comment by budu** [comment]
Hi, I got it figured out a while ago but thanks anyway.

Have a great day!
