### ISSUE TITLE
Update the term action cog throughout the doc

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#3285]
Throughout the doc, we use the term "action cog", or in some cases, [this icon](https://github.com/sendgrid/docs/blob/develop/source/images/terms_5.png) to represent an action menu that is common in our UI. All instances of the term "action cog" or instances of the images should be changed to the term "action menu"

**Comment by timtheguy** [comment]
Happy to give this one a try, I'll get on it now!
