### ISSUE TITLE
Hacktoberfest: SendGrid Current Status

### ISSUE THREAD

**Issue by mbernier** [sendgrid/docs#3290]
## Update 11/1/2017

I *believe* that every sendgrid/docs Hacktoberfest PR has been merged and access to our swag form has been granted to those contributors. If you haven't seen this yet, please go to your PR and follow the link to the comment from SendGridDX.

Thank you for your contributions this month, we are overwhelmed and elated at the response.

- [Matt Bernier](https://github.com/mbernier), Developer Experience Product Manager

---

## SendGrid DX team current status:
- Wow
- OMG
- THANK YOU

Hacktoberfest 2017 has completely blown us away. We have had over 900 pull requests from over 300 contributors all in the last 30 days. That is more PRs than we normally get in 2 years! 
We are actively working to review, comment, and/or merge as many PRs as we possibly can as quickly as we can.

We are currently working on “intaking” all the PRs that have come in, oldest first (we have about 400 remaining to go through). We are making sure that each PR we review is one we have a chance of merging - there have been a couple spammy items that came through. Due to the massive influx of requests so far, @thinkingserious, @mbernier, @Whatthefoxsays, and @ksigler7  have been working nights and weekends all month just to keep up! We’re not even mad, this is amazing!  
## Hey, that’s great for you - but what about my shirt!
If you have signed the CLA before 11/1, but haven’t had a PR merged yet, do not despair! We know we are behind on even just commenting on every PR to show you that we received it (something we typically do). If you submitted a mergeable (non-spam, actually adds value to the project) PR during October 2017, we will grant access to [this page](https://dx.sendgrid.com/swag) to redeem your shirt, sticker, and hacker pin. Next year, we will be sure to communicate this information sooner. We are sorry for any confusion we have caused. We appreciate those of you who have reached out to find out what’s going on! 

## What can I do to help move things along?
**Have you signed the CLA yet?** 
We can only merge items from contributors who signed the CLA

**Can you help another contributor?** 
If you can identify potential problems, add suggestions, or even leave a comment with your review of another PR (Looks good to me! Or I approve this change), that would help us review those PRs much faster, making it easier to get to your PR.

**Do you even write tests, friend?** 
If you see a place where we could have a test to validate a piece of functionality, add it in. We know We know! It’s just another PR we have to review and merge. You’re right, it is! However, the more tests we have, the earlier our CI tool can catch issues, saving us a review as well as back and forth time.

**Comment by afischer12** [comment]
I just joined in the issues for hacktoberfest, but I'll try to continue helping with issues!

**Comment by ksigler7** [comment]
thanks so much @afischer12!

**Comment by gelvezz23** [comment]
como pongo una etiqueta

**Comment by ksigler7** [comment]
@gelvezz23 - one of the repo admins has to tag stuff. We are going through now and making sure that everything is tagged as hacktoberfest though! comment in your PR if we've missed yours

**Comment by gelvezz23** [comment]
@ksigler7 soy nuevo en git y no se que hacer la verdad :(

**Comment by ksigler7** [comment]
@gelvezz23 - If you are new to git, you should go to the [central Hacktoberfest list](https://github.com/search?q=label:hacktoberfest+state:open+type:issue), and look for issues tagged with `help wanted` or `good first issue`! Those are usually good ones for beginners.

**Comment by gelvezz23** [comment]
@ksigler7 gracias, muchas gracias por su `colaboracion `echo "!! get lucky"`

**Comment by ksigler7** [comment]
@gelvezz23 you're very welcome!

**Comment by thepriefy** [comment]
Thx for a hard work on reviewing and merging a lot of PRs. I have a lot of fun during the hacktoberfest and I'll continue contributing to your projects. :)

**Comment by mbernier** [comment]
@thepriefy You totally kicked ass for us and we are VERY grateful to you and the work you did. I hope that you saw the fact that you were at the top of our leaderboard for most of the month! https://dx.sendgrid.com/hacktoberfest

**Comment by ksigler7** [comment]
@thepriefy - yeah, thanks for everything you did! We really appreciate it!

**Comment by NexWeb** [comment]
Oh no. Did Sendgrid trick us all into doing a bunch of work for free with the lure of a tshirt? 😄  
Which by the way we never received.
Did anyone get one?

**Comment by mbernier** [comment]
@NexWeb No way! 

We had so many contributors, that we had to order more shirts, pins, and stickers. The fulfillment house has everything and should be sending them all out. Everyone who provided an email address will be getting a notification from them (look for an email from KotisDesigns). There should be a special message in the email from us as well. 

I know it is taking FOREVER, we are embarrassed and sorry about that. We already know how we are going to do things different next year and going forward. We hope that you will get your notification and shirt very soon!!

**Comment by NexWeb** [comment]
👍 Cool. No need to be embarrassed or sorry, it's not your fault. I guess a lot of people just really wanted a Sendgrid tshirt or to be part of the Sendgid experience.

**Comment by mbernier** [comment]
Haha, we are totally [overwhelmed by the response](https://sendgrid.com/blog/hacktoberfest-2017-was-amazing/). It is has been awesome and we are doing whatever we can to catch up!

**Comment by ng29** [comment]
@mbernier .... how much we have to wait for the swag ..
its been too long waiting :(..

**Comment by mbernier** [comment]
@ng29 Our fulfillment house has told us that all the packages have been put into the mail. You should be seeing it soon!!

**Comment by ng29** [comment]
wowaaaa....amazing stuff ..
finally santa coming.. lmao :)

**Comment by mbernier** [comment]
We are hearing from people that they are getting their swag!

**Comment by ng29** [comment]
Yeah I have seen some tweets.
I m loving it :)

**Comment by aleien** [comment]
Hello (: Is it possible to acknowladge, if shirt will be shipped? I certainly did provide e-mail, but didn't receive any email notifications, so don't know if I should already worry or not yet (:
Thank you in advance and sorry for bothering!

**Comment by ksigler7** [comment]
@aleien they are still coming, and you may not have received an email yet! :( They are on backorder AGAIN. We are now working directly with the supplier to resolve this as quickly as possible. Thanks so much for your patience. We have learned a lot from this experience and will for sure do better next year!

**Comment by ng29** [comment]
Again backorder :(
Means have to wait more :(
holy crap..

**Comment by tulikavijay** [comment]
@ksigler7 Whats the status on this? Its March and still no update or email received...

**Comment by ksigler7** [comment]
@tulikavijay - hey there - they have all been mailed now. It can take up to two months to get to India though. I am checking the status on your specific shipment though, and I will followup with you by email.

**Comment by ng29** [comment]
@ksigler7  Whats the status on this? Its March and still no update or email received... :(

**Comment by ksigler7** [comment]
@ng29 - hmm, you should have it by now (or at least it should be on its way). I will look up your specific info and followup with you by email

**Comment by ng29** [comment]
@ksigler7 ...  yaah, many folks near me had got it.  
oohhkk.. thanks alot :)

**Comment by NexWeb** [comment]
![tshirts](https://user-images.githubusercontent.com/3054475/37301380-c934dece-25fe-11e8-920b-8a891b9c823d.png)

Consider any work to have been for your own benefit. Sendgrid and others have a good thing going by getting people to fix their product for free. The only benefit is if you care about their product or enjoyed doing the work to make their product better.

**Comment by ksigler7** [comment]
@NexWeb very true! We for sure have a good thing going, and we had an amazing response to hacktoberfest. My favorite part about hacktoberfest was how many first time github users contributed - helping people learn github really helped us to feel like we were giving back at least a little bit to the community for all of the support we were getting.

We definitely want to make sure folks get the t-shirts we promised though - three backorders later it's become somewhat of a personal mission. We already have a plan in place to not have this sort of mess for this years hacktoberfest.

**Comment by NexWeb** [comment]
Yes well, at this point it's not about the the tshirt, it is about the reliability and management capabilities within the company. DigitalOcean by comparison had their tshirts delivered before the end of the first week of November. What was that, like 239,164 of them?  If you can't take care of the people that are taking care of your product, what's a potential Sendgrid customer to think about the reliability of the company?

**Comment by ksigler7** [comment]
Yeah, we'll be moving to a system very similar to DigitalOcean next year! They did do a really good job.

**Comment by NexWeb** [comment]
I hope you mean this year.

**Comment by ksigler7** [comment]
Okay, closing this because we've reached out to everyone who indicated they didn't receive swag and reshipped packages to anyone who still hadn't arrived. But for sure still let me know if you haven't gotten anything, and we will figure something out!

By the next Hacktoberfest, our distributor will have a distribution center opened up in India, which should really help arrival times for folks contributing from South East Asia. Like I mentioned before, we're moving to a store front like DigitalOcean for ordering and shipping, and we also understand a lot more about what types of addresses are more and less successful for ultimate package arrival. We'll be encouraging people to have the packages shipped to a commercial address when possible (like your work address), because we seem to have had a lot more luck overall with those than residential addresses, particularly when those residential addresses include lines like "Near XXX" and "Across from XXX".

Thanks again everyone for your patience and understanding on this!

**Comment by ng29** [comment]
still waiting for my hacktoberfest package :(
@ksigler7 its been more than 6 weeks and still no response from your side .
Kindly look into this issue as, i dunno wanna lose my package again :(

**Comment by ksigler7** [comment]
@ng29 - I'll followup by email
