### ISSUE TITLE
Bower is deprecated

### ISSUE THREAD

**Issue by cmckni3** [sendgrid/docs#3302]
Bower should be removed and replaced with `npm` packages. From a quick glance everything should be available on npm except for modernizr.

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by tulikavijay** [comment]
I would like to work on this

**Comment by ksigler7** [comment]
sure, thanks @tulikavijay!

**Comment by tulikavijay** [comment]
Can you explain how to go about this? Do I remove it from dependencies (package.json) and develop/build.

**Comment by cmckni3** [comment]
Remove it from `package.json`, remove all setup instructions involving `bower`, and replace all dependencies installed with bower (`bower.json`) with their npmjs.org (`package.json`) equivalent. Then `bower.json` can be removed along with `bower_components` (ignored in .gitignore). You can remove `bower_components` from gitignore as well. Might be a `.bowerrc` file that needs to be deleted as well.

**Comment by daniloff200** [comment]
As I see, this issue was reopened, so, I'm gonna try to work with that

**Comment by daniloff200** [comment]
I think, that issue have to be closed.
I didn't found any bower dependencies, or, any appearance of bower, except .gitignore file cc @ksigler7

**Comment by cmckni3** [comment]
@daniloff200 meh. Seems like the project may have been converted to gatsby since last year?

**Comment by cmckni3** [comment]
Closing
