### ISSUE TITLE
Account Sign Up FAQs

### ISSUE THREAD

**Issue by Lakhwinder** [sendgrid/docs#3327]
https://sendgrid.com/docs/Classroom/Basics/Account/account_sign_up_faq.html
I got the email verification link and within a few minutes when I tried to verify the account, it started giving me "Email confirmation link expired". Not able to login now. Not even able to contact support.

**Comment by ksigler7** [comment]
Hello @Lakhwinder ,

Sorry you're having this issue! You can contact our support team by emailing support(at)sendgrid.com.

SendGrid Docs Team
