### ISSUE TITLE
Substitution and Section Tags

### ISSUE THREAD

**Issue by dle-coursera** [sendgrid/docs#3343]
https://sendgrid.com/docs/Classroom/Build/Add_Content/substitution_and_section_tags.html

Your documentation on substitution tags is incorrect. The tags can be anything as long as it's wrapped in double brackets ex **{{some_tag}}**. Note this does not work **-some_tag-**.

Refer to https://support.sendgrid.com/hc/en-us/requests/1306319 for more details.

**Comment by ksigler7** [comment]
@dle-coursera - good catch! thanks for the suggestion. I've both added it to our internal backlog, and I am opening it up here so maybe one of our external contributors can pick it up.

The to do here is to update the [Substitution and Section Tags page](https://sendgrid.com/docs/Classroom/Build/Add_Content/substitution_and_section_tags.html) examples that use `-some_tag-` to use the correct format, which is `{{some_tag}}`.
