### ISSUE TITLE
New Editing "Experience"? Pain free? no toggle?

### ISSUE THREAD

**Issue by JLuzz** [sendgrid/docs#3356]
https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/beta_editors.html

Bring back the ability to toggle between code view and design view please.

**Comment by ksigler7** [comment]
Hey @JLuzz - thanks for your feedback. We've passed it onto the appropriate team. I am going to close this issue, since this is not specifically docs related and this is a forum for problems with the documentation.
