### ISSUE TITLE
Drops

### ISSUE THREAD

**Issue by tobiasboyd** [sendgrid/docs#3364]
https://sendgrid.com/docs/Glossary/drops.html

Typo here: `You can visit your suppression lists and removing an address from the bounces list.`

(btw, when you remove an address from Bounces the flash message says 'event removed' - which makes it sound more like you are just deleting it out of the log, not actually removing the address)

**Comment by ksigler7** [comment]
@tobiasboyd good catch! Sorry for the delayed response, I somehow missed this one. I'll let the dev team know about the weird error message.

The to do here is this: On line 43 `You can visit your suppression lists and removing an address from the bounces list.` should be `On the suppression list page, you can remove an address from the bounces list.`
