### ISSUE TITLE
Using Custom Fields

### ISSUE THREAD

**Issue by dzwick** [sendgrid/docs#3365]
Two things:

1. When I click "drop us a line" nothing happened.

2. Under "Deleting a Custom Field"

-----

Deleting a custom field deletes all values for that field across your contact database. If you have any campaigns using the data in this field with a substitution tag, those values NOT get replaced when you send the campaign. You cannot delete a custom field that is used in a segment. This deletion process may take several minutes–you continue to see the custom field on this page until the process has completed.

-----

I think it should be "...those values do NOT get replaced...". Right now it's missing the "do" before the "NOT".

https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/custom_fields.html

**Comment by Whatthefoxsays** [comment]
Fixed: 

https://github.com/sendgrid/docs/pull/3368
