### ISSUE TITLE
Account Details

### ISSUE THREAD

**Issue by dzwick** [sendgrid/docs#3370]
https://sendgrid.com/docs/User_Guide/Settings/account.html

Can't see an option for "Billing Email" on my account settings page.

**Comment by ksigler7** [comment]
@dzwick - good catch! There is no billing email anymore. To change where your bills are sent, you need to update your main email address under account settings.

The to do here is to update the *Email address* section to also say that this is where your bills are sent, and then to delete the *Billing email* section.

**Comment by sanvally** [comment]
Hi,
Who can guide me on account/login details information for Sendgrid. Could you confirm if our company CloudMoyo,Inc has an account with you? and which subscription are we on? Could you help me with a # where I could talk ?
