### ISSUE TITLE
Substitution and Section Tags

### ISSUE THREAD

**Issue by Andikki** [sendgrid/docs#3371]
https://sendgrid.com/docs/Classroom/Build/Add_Content/substitution_and_section_tags.html

I think the article is broken. All tags are empty, so there's text like this throughout the article:

> We will be using the tags “”, “”, “” and “” in this example

Checked in Firefox and Chrome.

**Comment by ksigler7** [comment]
@Andikki oh wow, this is a great catch. It looks like our site isn't building things like `{{name}}` correctly.
