### ISSUE TITLE
Universal Links with AWS CloudFront

### ISSUE THREAD

**Issue by iwilsonq** [sendgrid/docs#3384]
Hi, my team is looking to setup universal/deep links in our email newsletter but we are having some difficulty. 

## Expected content
We followed the steps described [here](https://sendgrid.com/docs/Classroom/Build/Add_Content/universal_links.html) exactly; we set up a bucket on S3 to host the `assetlinks.json` and `apple-app-site-association` files and then we set up CloudFront to serve with the proper origin and behaviors. 

## Actual content
When we try to use CloudFront's default origin, which is pointing at sendgrid.net, we are receiving the error 
```
Bad Hostname in Link
You have clicked on a link that contains a bad hostname. Please make sure that you have typed the link correctly.
```
It correctly serves up the files on our S3 bucket, however.

Again, here is that [link](https://sendgrid.com/docs/Classroom/Build/Add_Content/universal_links.html)

**Comment by ksigler7** [comment]
hey @iwilsonq - thanks for the feedback! We will definitely look into troubleshooting the docs for this soon. In the meantime, if you haven't already, please reach out to our support team to help you with your specific problem. You can access support contact options by logging into https://support.sendgrid.com.

**Comment by hmbrown64** [comment]
I can look into this one

**Comment by ramonrovirosa** [comment]
Hi, @hmbrown64 & Sendgrid team, we are having the same exact issue in our mobile app. @iwilsonq did you ever find a work around in order to get  universal/deep links working with sendgrid?

**Comment by ramonrovirosa** [comment]
Update, we got this working. 

Essentially we had to update the `Cache Based on Selected Request Headers` from the default `none` to `all`. The documentation is a little outdated https://sendgrid.com/docs/ui/sending-email/universal-links/ for #17 shows to set the field `Forward Headers` to All which is now called `Cache Based on Selected Request Headers` which should be set to all. Attached is my Default Cache Behavior Settings in case it helps anyone. 

![screen shot 2018-10-10 at 7 09 45 pm](https://user-images.githubusercontent.com/644013/46776541-e7d3ba80-ccc0-11e8-8a3b-f93a7dd92b34.png)

**Comment by hmbrown64** [comment]
https://github.com/sendgrid/docs/pull/4400

**Comment by mattcanty** [comment]
@ramonrovirosa it would be really helpful if you were able to share screenshots of the rest of your CloudFront configuration!

Thanks

**Comment by ramonrovirosa** [comment]
> @ramonrovirosa it would be really helpful if you were able to share screenshots of the rest of your CloudFront configuration!
> 
> Thanks

For the most part, the rest of my config is the same as what can be found in the sendgrid docs https://sendgrid.com/docs/ui/sending-email/universal-links/#setting-up-universal-links-using-cloudfront
