### ISSUE TITLE
SendGrid OEM Process

### ISSUE THREAD

**Issue by daljesin** [sendgrid/docs#3396]
https://sendgrid.com/docs/Classroom/Basics/Misc/sendgrid_oem_process.html

The Contact Us form is not working . So unable to enroll in OEM  process

**Comment by ksigler7** [comment]
@daljesin - hi! What part of the form is not working for you?

**Comment by ksigler7** [comment]
also, closing this issue since it's not related to docs specifically, but please go ahead and answer my question, and hopefully we can get you in touch with the correct people to help out.
