### ISSUE TITLE
Remove Marked Vulnerability

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/docs#3402]
Reported by GitHub:

Known moderate severity security vulnerability detected in marked < 0.3.7 defined in package-lock.json.

package-lock.json update suggested: marked ~> 0.3.7.

**Comment by ksigler7** [comment]
another one:

Known moderate severity security vulnerability detected in hoek < 5.0.3defined in package-lock.json.
--
package-lock.json update suggested: hoek ~> 5.0.3.
