### ISSUE TITLE
Not receiving 2FA SMS messages

### ISSUE THREAD

**Issue by mpselby** [sendgrid/docs#3409]
I use SMS 2FA to access send grind.  I am not receiving SMS 7 digit codes to a number I set up and have used successfully for about six months.  They are no substantially delayed but rather never a arrive. As such I am completely locked out of my account and unable to contact support.  This problem emerged several weeks ago and I have tried several times over that period.

**Comment by ksigler7** [comment]
Hi @mpselby,

Unfortunately, I don't have the correct access to help you get access back to your account. Please send an email to support at sendgrid.com and they can help you!

Also, closing this issue since it's not a docs specific issue.

DX Docs team
