### ISSUE TITLE
Add an Ability to remove Categories from Category Stats List

### ISSUE THREAD

**Issue by orenji88** [sendgrid/docs#3426]
Hi,

I'm opening this new issue, cause i really need this ability for deleting Categories in Category Stats List.
I've contacted the Support Team via Live Chat, and they said that they can't delete it. 
So, please make this happen.
Thanks.

**Comment by ksigler7** [comment]
Hi @orenji88,
Thanks for your product feedback. I've passed it onto the team that handles that functionality - they may reach out to you for more information. I am closing the issue here though, because this repo is specifically for issues related to the documentation.
SendGrid Docs Team

**Comment by krzkrzkrz** [comment]
What is the status of this? I would like to see this feature implemented as well

**Comment by leblancmeneses** [comment]
It should just drop off consistent with the plans EMAIL ACTIVITY HISTORY settings.
