### ISSUE TITLE
Symfony documentation

### ISSUE THREAD

**Issue by bpolaszek** [sendgrid/docs#3443]
Hello there,

[Send Email with Symfony documentation](https://sendgrid.com/docs/Integrate/Frameworks/symfony.html) is way out of date (it's related to Symfony 1.x, which is not maintained anymore since November 2012).

Would you mind to have a look to update the documentation to Symfony 3.* / 4.*? 
There's a great functionnality in Swiftmailer which allows all sent e-mails to be routed to a single e-mail address, which is really useful in non-production environments, and I don't know how to deal with this with Sendgrid.

Thank you,
Ben

**Comment by ksigler7** [comment]
@bpolaszek thanks for pointing this out! We've added it to our internal backlog, but I'll also open it up for one of our open source community.

**Comment by michizhou** [comment]
I would like to take this issue. Please let me know what to do!
