### ISSUE TITLE
How to contact SendGrid support

### ISSUE THREAD

**Issue by JASONCAVNESS** [sendgrid/docs#3463]
https://sendgrid.com/docs/Classroom/Basics/Misc/support.html

For some reason when I try to log in, the page just keeps refreshing the logo over and over. This has been happening to me since Saturday. I can go anywhere else on the site.

I just can't log in anymore.

My email is jasoncavness@cavnessHR.com and the user name is cavnessHR.  

We were  placed on the SendGrid startup accelerator program. So, I don't if that anything to do with this.

Thanks

Jason

**Comment by ksigler7** [comment]
@JASONCAVNESS - hey Jason - It looks like we've been getting reports of issues like this. Can you try clearing out your cache? If that doesn't work, we can get a support ticket opened for you. 

Also, closing this, since it's a support question and not a direct issue in the docs.

**Comment by JASONCAVNESS** [comment]
Karlyn,

It works now after clearing out the cache.

Thanks

Jason
