### ISSUE TITLE
mail/send rate limit inconsistency

### ISSUE THREAD

**Issue by ewirch** [sendgrid/docs#3469]
https://sendgrid.com/docs/API_Reference/api_v3.html (MAIL SEND / Limitations) says:

> 3000 requests/sec is the maximum rate at which you may call v3 Mail endpoint.

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html says:

> 10,000 requests/sec is the maximum rate at which you may call v3 Mail endpoint.

See this related commit: 5903889c36f601e125ad1bced4d0a3770c798043

**Comment by ksigler7** [comment]
@ewirch - great catch, and thanks for the related commit for reference! I've updated it in the swagger docs - this should propagate out to the docs in the next hour or so.
