### ISSUE TITLE
TImezone v3 API call is undocumented

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#3491]
## Expected content
/v3/user/timezone

## Actual content

**Link to page**:

**Comment by ksigler7** [comment]
@jacobmovingfwd - good catch! I am trying to figure out if there's a reason why wouldn't have documented this...

**Comment by jacobmovingfwd** [comment]
Can check with Mako/Jensen, but I can't think of why.

**Comment by techgaun** [comment]
@ksigler7 looks like its still not there in the doc. I can take this one

**Comment by techgaun** [comment]
@ksigler7 doesn't seem like there's a way to edit it. I saw a reference to `https://sendgrid.api-docs.io/` in one of the jsx files. Is this public and somewhere else I should be updating it?

**Comment by ksigler7** [comment]
@techgaun - unfortunately, this one got mislabeled in the hacktoberfest rush. Currently our swagger docs aren't open sourced. Thanks for being willing to take it up though!

**Comment by techgaun** [comment]
@ksigler7 ah cool sounds good. Any plans on open sourcing those as well?

**Comment by Whatthefoxsays** [comment]
Closing because these endpoints don't currently exist in the V3 API

**Comment by Jufflar** [comment]
Why was this issue closed? Are these not the undocumented v3 api endpoints?

// PUT
// https://api.sendgrid.com/v3/user/timezone
// On-behalf-of: subuser-1010
// body: {"code":"Asia/Bangkok"}
// GET
// https://api.sendgrid.com/v3/user/timezone
// On-behalf-of: subuser-1010
// responseBody: {
//     "code": "Australia/Sydney",
//     "name": "Canberra, Melbourne, Sydney",
//     "offset": "GMT+10:00",
//     "offset_seconds": -36000
// }
// GET
// https://api.sendgrid.com/v3/timezones
