### ISSUE TITLE
Substitution Tags don't appear to work in templates when sent at a top level

### ISSUE THREAD

**Issue by ThorArakis** [sendgrid/docs#3492]
https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html

I've been trying to use a sendgrid transactional template with substitution variables and found that I was able to get the variables to work only when passed inside the personalization section. When I tried to pass the substitutions at the top level of the json, it didn't change the content of my email. I have included example post body and associated template below.

Additionally I noticed that the docs at https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html refer to the key as `substitutions` whereas [the substitution page](https://sendgrid.com/docs/API_Reference/SMTP_API/substitution_tags.html) refers to the key as `sub` although neither seem to work.

template copy/pasted from the visual designer:
```
Testing substitution
sub1:
-sub1-
sub2:
-sub2-

body:
<%body%>
```
post body:
```
{
  "template_id": "guid-of-my-template",
  "personalizations": [
    {
      "to": [
        {
          "email": "myemail@mycompany.com"
        }
      ],
      "subject": "Hello subject!",
      "substitutions": {
      	"-username-":"Chris ",
      	"-sub1-":"this substitution works"
      }
    }
  ],
  "from": {
    "email": "noreply@mycompany.com"
  },
  "substitutions": {
    "-sub2-": "this substitution doesnt work"
  }
}
```

Final response:
```
Testing substitution
sub1:
this substitution works
sub2:
-sub2- 
body:
```

**Comment by ksigler7** [comment]
@ThorArakis - thanks for the feedback! We are currently in the middle of updating our substitution tag docs right now and will hopefully be able to address the hole you noticed. In the meantime, to get help with your specific issue, please reach out to our support team. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
