### ISSUE TITLE
Duplicate Vimeo videos show up

### ISSUE THREAD

**Issue by jhweatherly86** [sendgrid/docs#3578]
## Expected content
One vimeo videos shows up on the doc

## Actual content
Two videos show up

**Link to page**:
https://sendgrid.com/docs/User_Guide/Settings/Sender_authentication/How_to_set_up_domain_authentication.html

**Comment by ksigler7** [comment]
@jhweatherly86 thanks for this issue! we're aware of this and should hopefully get a fix in today

**Comment by ksigler7** [comment]
This is fixed! 

I would try to sound smart or impressive, but it really just finally updated and fixed itself.
