### ISSUE TITLE
Global Unsubscribes URL for Delete is incorrect.

### ISSUE THREAD

**Issue by jlamphere-pl** [sendgrid/docs#3599]
The section for deleting [unsubscribes](https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/global_suppressions.html#Remove-all-email-addresses-from-the-Global-Unsubscribes-collection-DELETE) shows the url for DELETEs as '/v3/suppression/unsubscribe' when in reality it's '/v3/suppression/unsubscribes' which matches the conventions in blocks, spam_reports and bounces. The docs need to be updated to include the 's' in the two DELETE url sections.

**Comment by ksigler7** [comment]
Hey @jlamphere-pl - check this out for our latest API documentation - https://sendgrid.api-docs.io/v3.0/suppressions-unsubscribe-groups/delete-a-suppression-group

I'm going to close this bc we're in the process of depreciating the API docs you linked to, so it doesn't make sense to update it.
