### ISSUE TITLE
event webhook heiarchy does not show deferred event

### ISSUE THREAD

**Issue by nquinlan** [sendgrid/docs#361]
Currently, the event webhook's event hierarchy does not display where the deferred event sits. The deferred event should be placed with delivered and bounced.

![image](https://cloud.githubusercontent.com/assets/829864/2713392/19cc53ae-c4e6-11e3-95f8-046bd9b9e3d2.png)

https://sendgrid.com/docs/images/event_1.png

https://sendgrid.com/docs/API_Reference/Webhooks/event.html

**Comment by mbernier** [comment]
This has been rebuilt and updated!
