### ISSUE TITLE
Sendgrid API returns resource not found for template

### ISSUE THREAD

**Issue by narendrasolanke21** [sendgrid/docs#3626]
Trying to get sendgrid template by id for email by authenticating sendgrid using api key but is is showing error as "Request returned status Code 404Body:{"errors":[{"field":null,"message":"resource not found"}]}"

**Comment by leovingi** [comment]
+1 I also get the same response when fetching a template
`curl --request POST --url https://api.sendgrid.com/v3/templates/xxxxxxx-xxxxxxxx-xxxxxx-xxxxx --header 'authorization: Bearer XXXXXXXXXXXXXXXXXXX' --header 'content-type: application/json'`

The template exists and has an ACTIVE version, so not sure what's going on or why it's failing.

**Comment by ksigler7** [comment]
Hey @leovingi and @narendrasolanke21 - please contact our awesome support team - they'll be able to help you solve individual issues like this! You can access support contact options by logging into https://support.sendgrid.com.

**Comment by l3x** [comment]
@apigirl - Thanks for enthusiasm about SendGrid's awesome support team.

However, please refrain from telling people to only post their questions/answers at https://support.sendgrid.com.  

Maybe the awesome support team has access to better backend search interface (which would explain a few things) or perhaps, very few people use that site?

Challenge: Search for `{"errors":[{"field":null,"message":"resource not found"}]} ` and tell me if the results you get at https://support.sendgrid.com are of any use, what-so-ever.

I did and got 5 results, none of which were related to what I was looking for.

Thanks!
