### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by davidbpython** [sendgrid/docs#3633]
https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/python.html
Hi, the example on the above page doesn't seem to match the module's interface any longer...?

this example worked for me:
https://sendgrid.com/docs/Integrate/Code_Examples/v3_Mail/python.html

**Comment by ksigler7** [comment]
@davidbpython - correct, the first one you linked is for our V2 API, and the second one you linked is V3 API. Those examples are still up because we still have people using V2, though we highly encourage everyone to upgrade to our V3.

**Comment by ksigler7** [comment]
This is a good suggestion! We're currently in the process of migrating all of our API docs over into a new experience that will force you to select V2, so we will look at adding a badge there.

Also, you should check out our libraries for much more extensive python code examples - https://github.com/sendgrid/sendgrid-python

**Comment by davidbpython** [comment]
Many thanks!  Just started using Sendgrid and found it very easy to start
(found the V3 example almost immediately).  Will check out examples, def
the best way to learn.
