### ISSUE TITLE
Substituting unsubscription links does not work when using group unsubscribes (ASM)

### ISSUE THREAD

**Issue by Ugenx** [sendgrid/docs#3644]
https://sendgrid.com/docs/User_Guide/Settings/tracking.html

There doesn't seem to be a way to substitute the subscription management links within the content body of our email messages when using the unsubscribe groups functionality. Only the global unsubscribe link can be substituted using a defined tag; as soon as you define an ASM object within the request, the substitute tag is ignored and a generic "Unsubscribe From This List | Manage Email Preferences" footer is appended to the bottom of the email.

Is this intended or am I missing some other functionality to accomplish what I'm looking to do?

**Comment by ksigler7** [comment]
Hey @Ugenx,

This is a really good question. Our support team is much better equipped to help people with specific 
use cases. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
