### ISSUE TITLE
Remove multiple email addresses from the Global Unsubscribes collection URL typo

### ISSUE THREAD

**Issue by Uriil** [sendgrid/docs#3650]
There is a typo in URL for deleting multiple emails.

Instead of https://api.sendgrid.com/v3/suppression/unsubscribe, should be https://api.sendgrid.com/v3/suppression/unsubscribes (missing S at the end)

P.S. maybe it's relevant to Remove all email addresses link as well, but I can't check it

**Comment by ksigler7** [comment]
@Uriil - thank you! good catch
