### ISSUE TITLE
MODX

### ISSUE THREAD

**Issue by StevenReid** [sendgrid/docs#3657]
https://sendgrid.com/docs/Integrate/Open_Source_Apps/modx.html

Should the username be apikey?

**Comment by ksigler7** [comment]
@StevenReid - in this case, it's looking for your username and password that you use to log into your SendGrid account.

If you have more specific questions about getting your implementation working, please reach out to our support team! They are much better at answering than me :) You can access support contact options by logging into https://support.sendgrid.com.
