### ISSUE TITLE
How to set up reverse DNS

### ISSUE THREAD

**Issue by kaizen1** [sendgrid/docs#3664]
Sorry guys, this is really poorly written. "in that, while" 

https://sendgrid.com/docs/User_Guide/Settings/Sender_authentication/How_to_set_up_reverse_dns.html

**Comment by ksigler7** [comment]
Don't be sorry! It's in the process of being rewritten right now :) Closing this since this is an already active internal issue and I wouldn't want someone in the community to pick it up and duplicate effort
