### ISSUE TITLE
For Event Webhook Delivery events of type Bounce, documentation on the Type field is now missing.

### ISSUE THREAD

**Issue by kinetiq** [sendgrid/docs#3675]
Event_Webhook/event.md had details on this field a week ago, I think, but it's missing now.

For the Bounce event only, there is definitely a 'type' field that provides context for the event. Real-world example (it happens to be the last field in this chunk of json):

[{"EmailID":"REDACTED","category":["RecordingConfirmed"],"email":"robinson@REDACTED.com","event":"bounce","ip":"167.89.55.66","reason":"554 5.7.1 Service unavailable; Client host [167.89.55.66] blocked using bl.spamcop.net; Blocked - see http://www.spamcop.net/bl.shtml?167.89.55.66","sg_event_id":"B977-WYeS8uobCjiw3YfEA","sg_message_id":"grsqQC4hRxKgKG-76PtYZw.filter0001p2iad2-19137-5B02FFC3-F.0","smtp-id":"<grsqQC4hRxKgKG-76PtYZw@ismtpd0046p1mdw1.sendgrid.net>","status":"5.7.1","timestamp":1526923399,"tls":1,"type":"blocked"}]

**Comment by ksigler7** [comment]
Hi @kinetiq - this is a really good catch! We've done a huge update on the page and it looks like we missed this. Just to make sure I'm clear, are you looking for something like the section that starts on line 540 in [this old copy of the page](https://github.com/sendgrid/docs/edit/ksigler7-patch-36/source/API_Reference/Webhooks/event.md)?

**Comment by kinetiq** [comment]
Hey, glad to help. :) I am not sure that link takes me to a view where our line numbers will sync up, but yes, that version has the missing content. If I search it for the word "blocked" it comes up exactly once, and that's the line. 

The documentation actually needs quite a bit more around this area... Even the glossary entries for the blocked/expired/bounce terms is a bit lacking if you're trying to write something that alerts people when an email bounces.

What you really want as a developer is a flag saying whether something was a permanent failure or if SendGrid will continue to retry. As it stands, I've figured out that you have to watch for Dropped events and Bounces, and then Bounces actually have three sub-types, one of which is also, get this, Bounce. I wanted two of those three sub-types to be hard bounces and one to be soft bounces, but it isn't divided that way. The only way I've found to do this is to look at the actual status code. However, that can be in multiple formats depending on the mail server. Sometimes the mail server actually returns  both at once, ie: 550 5.1.1.1 

Sorry for the brain dump there. Some way to get at "permanent bounce" or "temporary bounce" would be extremely useful.  Or some sort of guidance here. I imagine this is a common scenario when consuming the notification API. :)
