### ISSUE TITLE
hanging - API calls directly from the API

### ISSUE THREAD

**Issue by asiOnTheWater** [sendgrid/docs#370]
API calls are hanging when testing out the new "API calls directly from the API". Tried Profile and Mail . Got this from the console 

XMLHttpRequest cannot load https://api.sendgrid.com/api/profile.get.json?api_user=******&api_key=*********. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://sendgrid.com' is therefore not allowed access.

**Comment by heycait** [comment]
Is there a solution for this? Not sure what do you mean by using https://sendgrid.com/docs instead @brandonmwest 

I get this same CORS error except when I'm trying to make a post to https://api.sendgrid.com/api/mail.send.json

**Comment by mbernier** [comment]
@heycait are you doing this via the docs or your own code? If it's your code, please submit a support request to support@sendgrid.com and they will jump right in to help! If it's docs, please let me know.

**Comment by heycait** [comment]
I'm still not sure what you guys mean when you said 'via the docs'...

I'm making a direct post to https://api.sendgrid.com/api/mail.send.json via an AJAX request. I assume that's what you meant via my own code?

**Comment by mbernier** [comment]
My apologies, internal lingo. We have functionality to test and use the endpoint directly from our [API page](https://sendgrid.com/docs/API_Reference/Web_API/mail.html).

Thanks for clarifying. Yeah, I would say that this is an issue our support team would need to assist you with. Would you be ok with emailing support@sendgrid.com? They are pretty quick to reply, even on the weekends :)

**Comment by heycait** [comment]
Sure, thanks for the advice!

**Comment by tcdevs** [comment]
@mbernier I have the same problem as @heycait.

Im using the url https://api.sendgrid.com/api/mail.send.json with my custom AngularJS factory to send an email. This **will** work but i still get a CORS error. It will send the email accordingly.

This are the custom settings for the header in the AngularJS $http service:

```
headers: {
    'Content-Type': 'application/json' , 
    'Access-Control-Allow-Origin': 'http://sendgrid.com',
    'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
    'Access-Control-Allow-Headers':'X-Requested-With'	
}
```

or with wildcard

```
headers: {
    'Content-Type': 'application/json' , 
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
    'Access-Control-Allow-Headers':'X-Requested-With'	
}
```
With both of the  example headers i get the following error message:

```
Response to preflight request doesn't pass access control check: 
The 'Access-Control-Allow-Origin' header has a value 'https://sendgrid.com' 
that is not equal to the supplied origin. Origin 'http://192.168.0.25:8031' is 
therefore not allowed access.
```

The problem seems to be the  'Access-Control-Allow-Origin ' header on your domain need to be an wildcard instead of 'http://sendgrid.com'

Can this problem be fixed? Thanks for the help in advance.

**Comment by mgteixeira** [comment]
Same problem here. Is there a way to add my domain to the app so you can add it to the Access-Control-Allow-Origin in the header response ? I guess you would have to generate a specific route to each user to ensure safety. 

Why is this issue closed ? it isn't fixed yet. Right ?

Here is the current header, 
Access-Control-Allow-Origin:https://sendgrid.com
Connection:keep-alive
Content-Length:21
Content-Type:application/json
Date:Thu, 05 May 2016 10:43:52 GMT
