### ISSUE TITLE
Email Activity Feed

### ISSUE THREAD

**Issue by JeanettM** [sendgrid/docs#3700]
https://sendgrid.com/docs/User_Guide/email_activity_feed.html

Some of the Additional Resources links are not linked and lead to a 404 page.

**Comment by ksigler7** [comment]
great catch @JeanettM!!! thanks so much for letting us know. I fixed them in the linked PR, but for your own reference, the broken links are:
- [Getting Started with the Email Activity API](https://sendgrid.com/docs/API_Reference/Web_API_v3/Tutorials/getting_started_email_activity_api.html)
- [Building compound Email Activity queries](https://sendgrid.com/docs/API_Reference/Web_API_v3/Tutorials/getting_started_email_activity_api.html#-Creating-compound-queries)

**Comment by JeanettM** [comment]
Anytime!
