### ISSUE TITLE
Drupal page recommends not using TLS, may not work for newer accounts

### ISSUE THREAD

**Issue by dficker** [sendgrid/docs#3702]
SMTP login information is not exactly correct on this page:

## Expected content

    SMTP Server - smtp.sendgrid.net
    SMTP Port - 587
    Use Encrypted Protocol - Use TLS
    Username - "apikey"
    Password - A valid SendGrid API Key

## Actual content

    SMTP Server - smtp.sendgrid.net
    SMTP Port - 587
    Use Encrypted Protocol - No. If you want encryption choose “Use SSL” and set SMTP Port to 465
    Username - SendGrid Username
    Password - SendGrid Password

**Link to page**:   https://sendgrid.com/docs/Integrate/Open_Source_Apps/drupal.html

This used to work at one time in the past, I believe, when there were multiple usernames.  But the expected also works and it's more secure as TLS is recommended to be used.

**Comment by ksigler7** [comment]
@dficker - cool! thanks for letting us know about this!! and it for sure makes more sense to use your API key here too

**Comment by ksigler7** [comment]
I am going to open this up for anyone in our community who wants to make this update.
The to do here is to update lines 33 through 37 on https://github.com/sendgrid/docs/edit/develop/source/Integrate/Open_Source_Apps/drupal.md with @dficker suggested content above

**Comment by robincher** [comment]
Just to clarify since i have yet to use this module .

The expected port should be 465 if using TLS?

```
SMTP Server - smtp.sendgrid.net
SMTP Port -  **465**
Use Encrypted Protocol - Use TLS
Username - "apikey"
Password - A valid SendGrid API Key
```
