### ISSUE TITLE
Rate Limiting

### ISSUE THREAD

**Issue by greganth** [sendgrid/docs#3706]
https://sendgrid.com/docs/Glossary/rate_limiting.html
"Please visit our pricing page to see the account specific sending limits."

The pricing page does _not_ specify any details or information about rate limiting per different accounts.

**Comment by ksigler7** [comment]
@greganth - great catch! this is for sure outdated.

I'm going to open this one up for the community. 

The to do here is to remove "Please visit our pricing page to see the account specific sending limits." from https://sendgrid.com/docs/Glossary/rate_limiting.html

This would be a great first PR.

**Comment by greganth** [comment]
It would be even better if the rate limits per plan were listed somewhere. That information isn't available anywhere (that I can find).

**Comment by ksigler7** [comment]
Actually, after looking at this more closely, this is not an issue with the docs. The number of emails you can send per plan is on the pricing page. If you select your plan, scroll down, and it tells you how many emails included in that plan and the cost of sending more emails than your plan. Note that there is no actual limit - you can send as many as you want, you just might get overages depending on your plan.
