### ISSUE TITLE
Inbound Email Parse Webhook

### ISSUE THREAD

**Issue by po-jo** [sendgrid/docs#3717]
Hello,

The parse inbound api fails to read diacritics (for instance _é_) for emails coming from outlook (received with charset latin1) : they are displayed as question marks.
When I click on 'send raw', I have the right encodings (for instance _=E9_).

Are you planning to handle latin1 ? Thanks !

**Comment by ksigler7** [comment]
hello @po-jo - sorry for the delayed response here. This is a much better question for our awesome support team! You can access support contact options by logging into https://support.sendgrid.com. I'm going to close this issue since it's not an issue with the actual docs.

SendGrid Docs Team
