### ISSUE TITLE
Microsoft Azure - ARM deployment template

### ISSUE THREAD

**Issue by MaartenKoops** [sendgrid/docs#3721]
https://sendgrid.com/docs/Integrate/Partners/Microsoft_Azure.html

Hi, Can you please send me the full ARM deployment template for the Azure SendGrid connection?

I'm now using this: 
"resources": [
    {
      "type": "Microsoft.Web/connections",
      "name": "'sendGridApiConnectionName'",
      "apiVersion": "2016-06-01",
      "location": "[resourceGroup().location]",
      "scale": null,
      "properties": {
        "displayName": "sendGridApiConnectionName",
        "customParameterValues": {},
        "api": {
          "id": "[concat('subscriptions/', subscription().subscriptionId, '/providers/Microsoft.Web/locations/', resourceGroup().location, '/managedApis/sendgrid')]"
        },
        "parameterValues": {
          "apiKey": "[parameters('sendGridApiKey')]"
        }
      },
      "dependsOn": []
    }
  ]

I want to set the Pricing Tier to "Silver", how to add this in the ARM template? Is there some documentation about this?

**Comment by ksigler7** [comment]
Hey @MaartenKoops - for specific questions like this, please reach out to our awesome support team. You can access support contact options by logging into https://support.sendgrid.com.
