### ISSUE TITLE
Sendgrid email activity API for categories not working,

### ISSUE THREAD

**Issue by ashuomble5** [sendgrid/docs#3724]
I am using sendgrid API for getting the email activity stats.
API LINK : [Sendgrid v3 API](https://sendgrid.api-docs.io/v3.0/email-activity)
One thing I noticed when I try to get the statistics by category its not working.
Also, there is the strange thing that when we want to query the email API we passed the argument in URL encoded format whether the categories argument is not URL encoded.
see this image:-
![2018-07-16-17-42-sendgrid API-docs io](https://user-images.githubusercontent.com/26411777/42758033-af296e58-891f-11e8-9728-88c4e3da6867.png)

Also, I have purchased 30 days email activity addon.
While trying I am getting this kind of error:
![2018-07-16-17-45-sendgrid api-docs io](https://user-images.githubusercontent.com/26411777/42758134-0a1523b6-8920-11e8-8b77-d618a517bbac.png)

Even I tried with using URL encoded format still not able to get the details:
![2018-07-16-17-48-sendgrid api-docs io](https://user-images.githubusercontent.com/26411777/42758238-79a921b4-8920-11e8-87b7-9b871538f303.png)

Does this bug in API or something else?

**Comment by AnkitKachhadiya** [comment]
I am facing same issue

**Comment by ksigler7** [comment]
the awesome @kylearoberts just helped me to test this out and it looks like we have the `categories` query documented incorrectly here. It should be:

`(Contains(categories,"Testing"))` (encoded: `(Contains(categories%2C%22Testing%22))`)

Also, make sure you have sent a mail with that category defined (or else it won't show up in email activity).

Thanks for pointing this out!!! We will get it fixed today.

**Comment by ksigler7** [comment]
okay - updated! You should be able to see it in the next few minutes.

**Comment by ashuomble5** [comment]
Thanks, @ksigler7 and @kylearoberts for feedback. It worked like charm.
