### ISSUE TITLE
Postfix config on Ubuntu / Debian

### ISSUE THREAD

**Issue by lgomezbl** [sendgrid/docs#3735]
https://sendgrid.com/docs/Integrate/Mail_Servers/postfix.html

Dear, 

Please consider those steps for this configuration:

1. Configure Debian / Ubuntu postfix server as "satellite system" (or after install using dpkg-reconfigure postfix)
2. SMTP relay host: SendGrid Info using [address]:port
3. Use your proposal (additional) info

smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous
smtp_tls_security_level = encrypt
header_size_limit = 4096000

4. Follow next steps as appear in your manual.

It works for me!

Regards,

**Comment by ksigler7** [comment]
@lgomezbl - thanks so much for the updated steps! I am going to open this up to the community! The to-do here is to update the page @lgomezbl linked with the steps he suggests.

**Comment by dheeraj135** [comment]
I want to take this issue.
