### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by asi851** [sendgrid/docs#3751]
https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/authentication.html

Discovered the param `-H 'on-behalf-of: subuser_username' \` is case sensitive. The header is ignored and returns the parent account stats instead of the subuser. I was able to get it to work with the snippet below, also provided a screenshot of the location. 

```
curl "https://api.sendgrid.com/v3/stats?start_date=2018-07-01&end_date=2018-08-01&aggregated_by=month" \
     -H 'On-Behalf-Of: subuser_name' \
     -H 'Authorization: Bearer {api key}' \
     -H 'Content-Type: application/json'
```

[Screenshot of doc location](https://cl.ly/0N342O170k43)

**Comment by ksigler7** [comment]
@asi851 - this is a really good catch! Thanks for letting us know about it. 

The to-do here is to double check all of the `On-Behalf-Of` parameter examples and make sure they are all capitalized. Also probably worth adding a note [here](https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/on-behalf-of) specifically calling out that it's case sensitive.

**Comment by ksigler7** [comment]
I'll open this up to the community after [our doc repo freeze](https://github.com/sendgrid/docs/issues/3728) is over!

**Comment by asi851** [comment]
@ksigler7 thanks a bunch. Anything to help out the #grid.

**Comment by AbhyudayaSharma** [comment]
Hi! I'd like to fix this.
