### ISSUE TITLE
Subject Line

### ISSUE THREAD

**Issue by axelcho** [sendgrid/docs#3752]
https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html

One big change that is forced on without any notice:

In old templates, I passed the `subject` as a sub-property of `personalizations`. 

But now I should pass `subject` as part of the `dynamic_template_data`.

This is very big change, also this is bad concept.

Subject is part of mail header, while the handlebar template is building the mail body. You are mixing up things that should NOT be mixed at all.

And this big change is not documented anywhere. 

Old style:

    {
        "personalizations": [
               "to" : [...to array],
               "cc": [...cc array],
               "substitutes": [..substitutes],
               "subject": "SUBJECT LINE"
        ]
    }

New Style:

    {
        "personalizations": [
               "to" : [...to array],
               "cc": [...cc array],
               "dynamic_template_data": [..substitutes + it now includes subject!],
        ]
    }

**Comment by ksigler7** [comment]
hey @axelcho - find the new v3 mail send functionality documented here: https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send

You should still be able to specify a subject in personalizations. However, if you have a subject defined in the dynamic template data, it overwrites what is defined in the personalizations - this has always been the customization/substitution behavior. 

All existing transactional templates are still viable - you can send, create, and edit them, you will just be given the option to switch from substitutions to dynamic data the next time you go in the UI to edit a template.

If you are still having trouble getting this to work, please get in touch with our awesome support team! They can help out with individual implementation issues. You can access support contact options by logging into https://support.sendgrid.com.
