### ISSUE TITLE
Dynamic Template ID is incorrect in docs

### ISSUE THREAD

**Issue by bxm156** [sendgrid/docs#3764]
Regarding https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html

The above document indicates the ```template_id``` is specified on the message.personalization[].{} level, alongside ```dynamic_template_data```.

When I try this on the API, I get the following message:
```The template_id is required when using dynamic templates","field":"template_id","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.template_id"```

When I move ```template_id``` to the top level, as it was before, it works.

**Link to page**:

https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html

**Comment by ksigler7** [comment]
hi @bxm156 - this is a great catch, and has been fixed with this PR - https://github.com/sendgrid/docs/pull/3746

It is getting deployed to production today! Thanks for letting us know.
