### ISSUE TITLE
Why is X-Message-ID different than Message-ID?

### ISSUE THREAD

**Issue by Joshfindit** [sendgrid/docs#3784]
https://sendgrid.com/docs/Glossary/x_message_id.html

There's no explanation on these pages as to why ` X-Message-ID` is in the format `XBg2anf2TqCy6WXKQFhieQ` and `Message-ID` is in the format `XBg2anf2TqCy6WXKQFhieQ.filter0905p1mdw1-4434-59E0C6FF-3.0`

It would also be helpful if https://sendgrid.com/docs/Glossary/message_id.html broke down how a `Message-ID` is built.

**Comment by ksigler7** [comment]
Hey Josh - these are good points! I'll open this up to the community after [our code freeze](https://github.com/sendgrid/docs/issues/3728) is over. In the mean time, you might reach out to our awesome support team for more information on this. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by hmbrown64** [comment]
@ksigler7 I can grab this one

**Comment by ksigler7** [comment]
thanks @hmbrown64 - let me know if you need any help!

**Comment by hmbrown64** [comment]
https://github.com/sendgrid/docs/pull/4120
