### ISSUE TITLE
How to send an email with Dynamic Transactional Templates

### ISSUE THREAD

**Issue by 3lnc** [sendgrid/docs#3790]
https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html#-Send-a-transactional-email

Probably there's mistake in cURL section, `template_id` should be top level in body, not in `personalizations` closure

**Comment by ksigler7** [comment]
hey @3lnc - thanks for the catch. we've updated here: https://github.com/sendgrid/docs/pull/3746

This should hopefully get deployed today
