### ISSUE TITLE
Add info about GoDaddy to the domain auth docs page

### ISSUE THREAD

**Issue by apigirl** [sendgrid/docs#3830]
GoDaddy has a specific domain authentication rule when adding CNAME records that seems to always trip people up. They automatically add domains at the end of records that are input, so customers that put in our SG domain auth records have them fail due to this problem.

Under step 5 [here](https://sendgrid.com/docs/User_Guide/Settings/Sender_authentication/How_to_set_up_domain_authentication.html#-Setting-up-domain-authentication), add in this note:

> GoDaddy automatically adds your domain to the end of any record you input.  Because SendGrid CNAME records are formatted as `sendgrid.domain.com`, GoDaddy interprets this as `sendgrid.domain.com.domain.com` - this fails CNAME validation.  To correct this, input the subdomain of the "host" value from SendGrid into GoDaddy - instead of `sendgrid.domain.com`, enter `sendgrid`.

**Comment by MikeMwambia-TrojanSystem** [comment]
This saved my life...thank you for pointing it out...
