### ISSUE TITLE
Typo in C# documentation

### ISSUE THREAD

**Issue by alex-zwingli** [sendgrid/docs#3831]
https://sendgrid.com/docs/Integrate/Code_Examples/v2_Mail/csharp.html

Current
`myMessage.From = new MailAddress("you@youremail.com", "First Last");`
...
`myMessage.Text = "and easy to do anywhere, even with C#";`

Update
`myMessage.From = new EmailAddress("you@youremail.com", "First Last");`
...
`myMessage.PlainTextContent= "and easy to do anywhere, even with C#";`

**Comment by daniloff200** [comment]
Oh, easy to fix. Gonna do that.
