### ISSUE TITLE
Subuscription Tracking Page, Images Outdated

### ISSUE THREAD

**Issue by hmbrown64** [sendgrid/docs#3917]
https://sendgrid.com/docs/ui/sending-email/subscription-tracking/

Updated images that reflect current subscription tracking UI. For example, On/Off toggle and replacement tag field display.

**Comment by productdana** [comment]
I would like to take up this issue!

**Comment by ksigler7** [comment]
@productdana - thanks so much, we are reviewing your PR soon!

**Comment by kichloo** [comment]
I am new on Github and would like to make a Pull Request. Kindly explain about the same.

**Comment by lumie31** [comment]
Hey @kichloo. This should be helpful: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
Cheers.

**Comment by dagolinuxoid** [comment]
@productdana There is a tip: In order to close an issue automatically you can include `fix #3917` text to your commit message. So next time you'll be aware :). There are some examples [how to close issues using keywords automatically](https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by dagolinuxoid** [comment]
@joshimandar nope it's resolved via #4055 merged pull request. @ksigler7 please close the issue to escape ambiguity for newbies.
