### ISSUE TITLE
Sendgrid Hacktober Fest

### ISSUE THREAD

**Issue by rahulkumaran** [sendgrid/docs#3941]
This is more of a question rather than an issue.
I was just browsing the web about Hacktober Fest and I realised that Sendgrid also had something like a Sendgrid Hacktober Fest last year.

Would something of that sort take place this year too?

**Comment by ksigler7** [comment]
@rahulkumaran - yes! We are pumped!! Check out our blog about it here: https://sendgrid.com/blog/hacktoberfest-2018-hack-on-sendgrid-open-source-projects/
