### ISSUE TITLE
Godaddy video out of date

### ISSUE THREAD

**Issue by jamesheys** [sendgrid/docs#3944]
Hi There, just to let you know that godaddy no longer asks you to enter the whole address for the cname just the subdomain, the video appears to be out of date, Thanks James

## Actual content

**Link to page**:

**Comment by andreathniah** [comment]
@jamesheys I assume you are talking about the "Whitelabeling with GoDaddy" video at [providers.md](https://github.com/sendgrid/docs/blob/bf4c0cb9bd9f09b6d807aa626f489b6896e52201/source/User_Guide/Settings/Sender_authentication/providers.md)? 

@jamesheys I'll do a PR that note the out of date video and add relevant information mentioned by James
