### ISSUE TITLE
Transactional Templates Additonal Resources Link 404

### ISSUE THREAD

**Issue by karltaylor** [sendgrid/docs#3963]
Within the [Additional Resources](https://sendgrid.com/docs/ui/sending-email/create-and-edit-transactional-templates/#additional-resources) section, the Dynamic Templates link returns a 404

## Expected content

🤷🏻‍♂️

## Actual content

**Link to page**:

**Comment by duncanleung** [comment]
Hi @karltaylor, it should link to:
https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/

The issue has been resolved with #3968 and will be fixed soon.
