### ISSUE TITLE
Minor markdown issues in USAGE.md

### ISSUE THREAD

**Issue by anchepiece** [sendgrid/docs#4029]
Hello :wave:

## Expected content
Formatting should place all commands in code blocks, there is one unmatched block. Additionally a small typo was caught.

## Actual content

> ``
> npm run spellcheck
> ```

**Link to page**: https://github.com/sendgrid/docs/blob/develop/USAGE.md

**Comment by duncanleung** [comment]
🦅 👀 ! Great find.

I don't think they use Jekyll anymore though, so I believe that page should be deprecated.

The current docs now runs on Gatsby.
