### ISSUE TITLE
Typo in recipients

### ISSUE THREAD

**Issue by DCzajkowski** [sendgrid/docs#4034]
You guys have a typo in a navbar.

![](https://i.imgur.com/deTdHhR.png)

## Expected content
Search recipients

## Actual content
Search recipents

---

**Link to page**: https://sendgrid.com/docs/api-reference/

**Comment by Niladri24dutta** [comment]
@ksigler7 I am working on this as a PR. Can you guide me to find the correct files for api references ? Is this a React specific change?

**Comment by DCzajkowski** [comment]
The file containing this is not public, as far as I know.

**Comment by duncanleung** [comment]
Their API docs are powered by https://stoplight.io

**Comment by ksigler7** [comment]
yep, thanks everyone, we're working on getting our swagger spec open sourced, but it's not right now. I will still leave this issue open in our backlog though, because this is an ugly typo!

**Comment by ksigler7** [comment]
whew, finally fixed this one
