### ISSUE TITLE
Broken link in Sending Email Category

### ISSUE THREAD

**Issue by arshadkazmi42** [sendgrid/docs#4059]
In this page, 

https://sendgrid.com/docs/ui/sending-email/sendgrid.net-greylisted/

 `Edit this page` this link is broken.

On debugging the issue, I found that the slug returning from the graphql query is different from the name of the file, due to which the url is breaking.

GraphQL Response

```
category: "sending-email"
docType: "ui"
​​​permalink: "/ui/sending-email/sendgrid.net-greylisted/"
​​​slug: "sendgrid-net-greylisted"
​​​title: "Why is sendgrid.net “greylisted”?"
```

So, the replace function written in the codebase, is not able to replace the `slug` from the `permalink`, since the slug in `permalink` is not matching with the `slug`

## Expected content

`Edit this page` link should work

## Actual content

`Edit this page` link  is redirecting to 404 page

## To Fix
I think the slug needs to be updated in the DB.
or I guess renaming file can also fix this, but I am not so sure about it.
Let me know if I can create a PR of this.

**Link to page**:
https://sendgrid.com/docs/ui/sending-email/sendgrid.net-greylisted/

**Comment by ksigler7** [comment]
@arshadkazmi42 - this is a great catch! renaming the file will fix this. we shouldn't have files with anything but a `-` for this exact reason. Thanks for taking on the PR!

**Comment by arshadkazmi42** [comment]
Cool. I will create a PR for this today. Thanks for confirming the issue and the fix
