### ISSUE TITLE
Event Webhook Reference

### ISSUE THREAD

**Issue by andy-scott** [sendgrid/docs#4096]
https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html

this is taken from the webhooktester
"category":["order-confirmation"]
which suggests that category is an Array of strings

The documentation says it is a string

**Comment by hmbrown64** [comment]
I can take this

**Comment by ksigler7** [comment]
thanks @hmbrown64

**Comment by hmbrown64** [comment]
https://github.com/sendgrid/docs/pull/4268

**Comment by dagolinuxoid** [comment]
**Close** the issue.
