### ISSUE TITLE
Update Style Guide to include new head matter

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#4107]
With our new Knowledge Center, our page formatting has changed a little bit. Our new head matter looks like this:

```
---
layout: page
weight: 0
group: 
title: 
seo:
  title: 
  description: 
  keywords: 
navigation:
  show: true
---
```
This information needs to be added into our style guide in the repo. The "group" field in the head matter pertains to the different headers each article resides under in a specific category. The list below outlines all of the different groups. The sections in **Bold** are the categories, and the group designation itself is after the colon. Note that all group designations are lowercase and have no spaces. 

If you think there's a more clear way to get this information across (such as a table) please feel free to do so. 

### UI

**Sending Email**
Building Email: building-email 
Delivery & Optimization: delivery-optimization
Building Email with Marketing Campaigns: marketing-campaigns
Building Transactional Email: transactional-email
Tracking: tracking
Platform Partners: platform-partners

**Managing Contacts**
Managing Contacts with Marketing Campaigns: managing-contacts

**Analytics and Reporting**
Statistics: statistics
Click Tracking: click-tracking
Email Activity Feed: email-activity
SendGrid Partners: partners
Tracking: tracking

**Account and Settings**
Account Managment: account-management
Inbound Parse: inbound-parse
Sender Authentication: sender-authentication
IP Management: ip-management
Teammates & Subusers: teammates-subusers
Troubleshooting: troubleshooting
Security: security
Billing: billing

### For Developers

**Sending Email**
SendGrid v2 API: api-v2
SendGrid v3 API: api-v3
Frameworks: frameworks
Mail Clients: mail-clients
Mail Servers: mail-servers
SendGrid Partners: partners
SendGrid Plugins: plugins
SMTP API: smtp
Tracking: tracking
Open Source Apps: open-source

**Parsing Email**
Inbound Parse: inbound-parse

**Tracking Events**
Code Examples: code-examples
Getting Started: getting-started
SendGrid Partners: partners
Reference & Troubleshooting: reference-troubleshooting

**Partners**
Migration: partner-migration
Platform Partners: platform-partners

**Comment by iampeterbanjo** [comment]
hi, I would like to work on this.
