### ISSUE TITLE
Email activity head matter adjustment

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#4111]
## Expected content

Change the group in the headmatter of this page from "sending-email" to "tracking" 

**Link to page**: https://sendgrid.com/docs/for-developers/sending-email/getting-started-email-activity-api/

**Comment by daniloff200** [comment]
@ksigler7  hey, I think I was confused a little bit with the description of this issue.

![selection_011](https://user-images.githubusercontent.com/13692220/46700962-ebb2fe80-cc26-11e8-9bf5-8372ca6401b8.png)

Do I have to change the route part (as soon as the content in navigation block), or, there's something else here?

**Comment by ksigler7** [comment]
@daniloff200 - great question! I mean in the source of the page, here:
![image](https://user-images.githubusercontent.com/28788585/46701863-6277d980-cbde-11e8-904b-0f074b4c4b12.png)

**Comment by daniloff200** [comment]
So, probably I have to change "tracking" to "sending email" , according to your screenshot, haha :) @ksigler7

**Comment by ksigler7** [comment]
@daniloff200 - yeah, you are completely right. The dyslexia was real with this one.

**Comment by daniloff200** [comment]
@ksigler7 mistakes is a part of human nature :) 

I think, we need to update description for this ticket, and also, I've created #4122 with a fix
