### ISSUE TITLE
Activity Feed API Feedback

### ISSUE THREAD

**Issue by keithpeckagent3** [sendgrid/docs#4142]
Hello,

I am finding the Email Activity Feed API too limited for most purposes. The querying features are very extensive but the fields returned in the /messages endpoint are very limited. In my case, I am querying the messages based on category and unique arguments, but then these fields are not returned in the result set. So I then have to get each message individually to find the unique arguments. The slow API response times and request rate limiting make this a non option for more than a few messages.

I'm aware that using web hooks is an alternative but it's a shame I can't achieve this with the API. It would be useful if I could specify fields I want returned or rate limits were much greater with faster responses.     

Thanks

**Comment by ksigler7** [comment]
hello @keithpeckagent3 - thanks for the feedback! I've passed it onto the product manager in charge of that functionality.
