### ISSUE TITLE
whitelist lock out

### ISSUE THREAD

**Issue by webbgroup** [sendgrid/docs#4173]
And I cant log in to the support portal because the support portal uses the whitelisting capability.

## Actual content

**Link to page**:

**Comment by webbgroup** [comment]
Expected content, that whitelisting would be ONLY for api access ONLY, not for account login and access. What happens if i login from using a new ISP? my ip would have been changed then.

This is a SEVERE security circle of logic that is not warned to us as a customer until AFTER we already locked ourselves out.

Please help ASAP.

**Comment by ksigler7** [comment]
@webbgroup - you can use this link to contact our support team - https://support.sendgrid.com/hc/en-us/requests/new#ipam-lockout
