### ISSUE TITLE
Docs Reorg: Reputation

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#4176]
These two pages are very similar and should be combined into one new page that follows our style guide, called Reputation Monitoring that lives in the Glossary - make sure the new page has the important information from both pages

https://sendgrid.com/docs/ui/sending-email/reputation/
https://sendgrid.com/docs/glossary/reputation-monitoring/ 

[edit: fixing broken link]

**Comment by jidemusty** [comment]
The first page is a 404

**Comment by ksigler7** [comment]
broken link is fixed - thanks for the PR @pushkyn! we will get to it in the next day or so

**Comment by productdana** [comment]
I'd like to take up this issue!
