### ISSUE TITLE
New page: Getting Started with transactional emails

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#4180]
Define and give examples of Transactional emails. Talk about how customers should use SendGrid for Transactional emails, link to the Transactional Email User Guide, and link to the APIs. Create the page in For Developers > Sending Email > V3 API, and use the [API getting started](https://sendgrid.com/docs/for-developers/sending-email/api-getting-started/) page as a model.

**Comment by tanhengyeow** [comment]
@ksigler7 Hi! I wish to be assigned this issue 😃

**Comment by chrislupdx** [comment]
@ksigler7 Hey! Very interested! Marketing Automation background here!

**Comment by ksigler7** [comment]
@tanhengyeow and @chrisbutler - awesome guys! would you want to work together on this? you could hash it out here in the comments
