### ISSUE TITLE
404 not found the font  'icomoon.ttf'

### ISSUE THREAD

**Issue by inyee786** [sendgrid/docs#4211]
## Expected content
this error should not come 

## Actual content

**Link to page**:
![screenshot from 2018-10-13 20-41-31](https://user-images.githubusercontent.com/20504600/46906932-93327880-cf28-11e8-85b7-e48db7f65ec0.png)

**Comment by inyee786** [comment]
i would like to solve it

**Comment by dagolinuxoid** [comment]
**Close** it.
