### ISSUE TITLE
New Page? SMTP API vs v3 API

### ISSUE THREAD

**Issue by duncanleung** [sendgrid/docs#4221]
While looking into issue #1755 I had some questions:
- What are the differences / limitations between the two APIs
- Which protocol should I use to send email, SMTP or REST?

On the [SendGrid main docs page](https://sendgrid.com/docs/) two of the main CTA are:
- API: Use the SendGrid v3 REST API to build and send email.
- SMTP: Use the SendGrid SMTP API to build and send email.

However, there isn't currently material describing the differences on when each should be used.

## Expected content

It may be helpful to summarize the following articles into a docs page:

**Choosing between the Web API and SMTP API**
- [SMTP Service Crash Course](https://sendgrid.com/blog/smtp-service-crash-course/)
- [Web API or SMTP Relay: How Should You Send Your Email?](https://sendgrid.com/blog/web-api-or-smtp-relay-how-should-you-send-your-mail/)
- [Which protocol should I use to send email, SMTP or REST?](https://sendgrid.com/blog/which-protocol-should-i-use-to-send-email-smtp-or-rest/)
- [Email Message Flow 101: How SendGrid Helps Your Email’s Journey to the Inbox](https://sendgrid.com/blog/email-message-flow-101-how-sendgrid-helps-your-emails-journey-to-the-inbox/)
- [SMTP Relay Service 101 [Back to Basics]](https://sendgrid.com/blog/smtp-relay-service-basics/)
- [The SendGrid Email Infrastructure Guide](https://sendgrid.com/resource/the-sendgrid-email-infrastructure-guide-is-it-better-to-build-or-buy/)

**Link to page**:

**Comment by ksigler7** [comment]
@duncanleung - we would like people to use the REST API mainly because it is more secure and offers more functionality. 

Thanks for this feedback though, I think we can take this feedback and update how we present this information on the site to emphasize it.
