### ISSUE TITLE
Rdio is no more

### ISSUE THREAD

**Issue by hugovk** [sendgrid/docs#4228]
## Expected content

Can follow instructions.

## Actual content

Rdio has shut down, this guide can no longer be followed:

> To get your Rdio API Key, which you'll use to create your playlist, follow the “How to get started” instructions here: [http://developer.rdio.com](http://developer.rdio.com).

* https://en.wikipedia.org/wiki/Rdio

**Link to page**:

https://github.com/sendgrid/docs/blob/develop/content/docs/for-developers/partners/azure.md

**Comment by mozebdi** [comment]
I can take this one!

**Comment by mozebdi** [comment]
It looks like we have a more updated Azure page here: https://github.com/sendgrid/docs/blob/develop/content/docs/for-developers/partners/microsoft-azure.md
Do we still need the outdated guide with Rdio?

**Comment by mozebdi** [comment]
I have also updated that page to correct a broken link to the Java web page example.
