### ISSUE TITLE
Subscription Management Overview Clarification

### ISSUE THREAD

**Issue by lpresgrove** [sendgrid/docs#4231]
**Link to page**: https://sendgrid.com/docs/ui/sending-email/index-suppressions/

**Comment by ksigler7** [comment]
@lpresgrove - what's wrong with this page?

**Comment by lpresgrove** [comment]
@ksigler7 Nothing wrong with it grammatically, just wanted to make a small distinction that subscription tracking only works if sending via SMTP/API, not marketing campaigns. That's been a major pain point in customer interactions for me personally
