### ISSUE TITLE
Removing weird links

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#4235]
All of the links under this heading go to the same page that is not really related to the links. 
https://sendgrid.com/docs/Classroom/Deliver/index.html#-List-Management

Remove redundant links, and update this link:

The page linked is about 'how' to manage a list using SendGrid, not about ""tips and tutorials to help guide your recipient, or contact, list management.""
Should be linked to https://sendgrid.com/docs/User_Guide/Marketing_Campaigns/Managing_Contacts/building_your_contact_list.html"

**Comment by hannahapuan** [comment]
I can take this one

**Comment by erindatkinson** [comment]
I can work on this.

**Comment by mattreyuk** [comment]
@ksigler7 I looked at the `List-Management` page and it looks like the links on that page are all valid - did you miss a reference to the parent page that you want to switch `List-Management` to `building_your_contact_list`?

**Comment by dagolinuxoid** [comment]
> Remove redundant links, and update this link:

@ksigler7 Which one? I am not an oracle :)

**Comment by ksigler7** [comment]
this got fixed already @dagolinuxoid and @mattreyuk - sorry we missed getting this issue closed!
