### ISSUE TITLE
Add a note to AWS page

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#4236]
Add a note to the AWS page at line 22 with this content:

<call-out>

If you are using SendGrid through AWS, you cannot change your SendGrid username.

</call-out>

**Link to page**:

**Comment by hannahapuan** [comment]
I can work on this

**Comment by hannahapuan** [comment]
It's this page, correct? content/docs/for-developers/partners/amazon-marketplace.md

**Comment by hannahapuan** [comment]
https://github.com/sendgrid/docs/pull/4242
