### ISSUE TITLE
Update Invalid Emails page

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#4244]
Replace the sentence "This endpoint allows you to retrieve and delete entries in the Invalid Emails list." with a summary at the top of this page that explains what an invalid email is, based on whats in https://sendgrid.com/glossary/invalid-emails/ then link to {{root_url}}/glossary/invalid-emails/ from this summary.

**Comment by hmbrown64** [comment]
got it

**Comment by hmbrown64** [comment]
https://github.com/sendgrid/docs/pull/4266
