### ISSUE TITLE
Change first-timers.md to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Ayush-Rawal** [sendgrid/docs#4294]
The file name first-timers does not, at first glance, indicate what it is for. Generally people look  for a CONTRIBUTING.md file which is a standard name given to the file that holds instructions on contributing

**Comment by buck06191** [comment]
I'd like to take this one if possible.

**Comment by Ayush-Rawal** [comment]
Hi @buck06191,

Sorry but I'm about to submit a PR for this.
