### ISSUE TITLE
Broken image in styleguide.md

### ISSUE THREAD

**Issue by buck06191** [sendgrid/docs#4303]
## Expected content
Should be able to see the image of document structure in styleguide.md

## Actual content
 Instead we see:
`src="https://github.com/sendgrid/docs/blob/develop/static/img/docs-architecture-group.png" width="676" height="386">`

**Link to page**: [styleguide.md]{https://github.com/sendgrid/docs/blob/develop/styleguide.md}

**Comment by saracope** [comment]
Looks like this one can be closed out. @buck06191

**Comment by buck06191** [comment]
Closed by #4304
