### ISSUE TITLE
Move cURL link from v2 to v3 section

### ISSUE THREAD

**Issue by jawn** [sendgrid/docs#4316]
## Expected content

Link to cURL page is in the SendGrid v3 API block.

## Actual content

![image](https://user-images.githubusercontent.com/1705112/47216658-fe0b0600-d3a5-11e8-9107-db8ca88631ef.png)

**Link to page**:
https://sendgrid.com/docs/for-developers/sending-email/

**Comment by laurenziello** [comment]
I will do it!
