### ISSUE TITLE
How can I use fields from my Account Details in transactional emails?

### ISSUE THREAD

**Issue by sheam** [sendgrid/docs#4344]
I have a transaction email with an unsubscribe footer. The foot has fields like sender_name, etc.

I would like to change those fields, or at least populate them from my account details. Otherwise I am forced to add that data via api every time I send, and it never changes.

I also can't seem to find a way to edit the text in that footer.

**Comment by robpaveza** [comment]
@sheam Were you able to get this squared away?  I see that there's a way to add it via Marketing Campaigns - Senders -- https://sendgrid.com/docs/ui/sending-email/senders/#adding-a-sender -- but that area does not seem to be enabled on my account (currently SendGrid Free via Azure).
