### ISSUE TITLE
Your account has been suspended. Please contact Support to regain access. 

### ISSUE THREAD

**Issue by sachinsvk** [sendgrid/docs#4352]
Account Info: NAME Sri Pranapriya Ananda

EMAIL ADDRESS
support@nithyanandauniversity.org

I am getting a message that the account was blocked. Can you please help with the details and what actions are required asap.

**Comment by tomudding** [comment]
You should contact SendGrid Support via one of the methods listed on [their support page](https://sendgrid.com/docs/ui/account-and-settings/support/). This GitHub repository is only for issues related to the documentation (the pages your see).
