### ISSUE TITLE
WordPress Plugin Auto Refreshes with api key

### ISSUE THREAD

**Issue by timbrandon** [sendgrid/docs#4446]
The settings page for the plugin continually reloads when the API key isn't loaded. It just keeps giving an error, and continues to reload. On a Wpengine site. PHP7, WordPress 4.9, making it impossible to fill out the form and use the plugin at all.

**Comment by ksigler7** [comment]
@timbrandon - thanks! I passed this onto the product manager in charge of this product.

**Comment by crobertwatson** [comment]
Why is this issue closed? It's still occurring. Are we not to use the SendGrid plugin anymore in WordPress?

**Comment by SM2018BSA** [comment]
I am having this issue with the latest versions! ?
