### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by mppatil211** [sendgrid/docs#447]
You must also provide facility to delete category. Remove category removes a newsletter from a category. I want to delete category from a category list
https://sendgrid.com/docs/API_Reference/Marketing_Emails_API/categories.html

**Comment by adamcbrewer** [comment]
Is there any feedback or progress with regards to this?

**Comment by jacobmovingfwd** [comment]
We do not have a public endpoint for this at this time, though it's being worked on as part of our core API revamp.

**Comment by acarbonaro** [comment]
@jacobmovingfwd Is there a timeline for the API revamp?

**Comment by jacobmovingfwd** [comment]
We're currently in the midst of it. We have [Categories GET](https://sendgrid.com/docs/API_Reference/Web_API_v3/Categories/categories.html) available, but not deletion at this time. I don't have an ETA on that feature.

**Comment by tiagomatos** [comment]
+1 here for the ability to delete categories from the UI. We'll use the API for now.

**Comment by kbsali** [comment]
I would also like to remove old categories... (api or web-ui)!

**Comment by dwahlqvist** [comment]
+1 
Our list of categories is full off old, no longer used categories. I'd like to do a full reset i.e. delete all categories. Then the ones actually used will be populated as those emails are sent moving forward.

**Comment by krzkrzkrz** [comment]
Same here, would like to see this feature implemented. Been a few years now. Is there any feedback?
