### ISSUE TITLE
Add New Email Insights Reports callouts

### ISSUE THREAD

**Issue by ksigler7** [sendgrid/docs#4577]
We have a new Email Insights Service. We need to add this callout to these pages. Please check off the box for the page when you add the callout (and don't close the issue with the PR). Each callout counts as an Easy for Hacktoberfest - so one callout = 1 point. The more you add, the more points you get! 

Callout:
```
<call-out>

Want deeper data and insights? With [SendGrid Email Insights Reports](https://go.sendgrid.com/Email-Insights-Reports.html?utm_source=docs), you’ll get access to more data about your email performance plus customized insights from a deliverability consultant.

</call-out>
```

Pages and lines to add the callout:
- [ ] [Tracking settings](https://sendgrid.com/docs/ui/account-and-settings/tracking/) - line 85
- [ ] [Email Activity Feed](https://sendgrid.com/docs/ui/analytics-and-reporting/email-activity-feed/) - line 167
- [ ] [Browser Comparison Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/browser-comparison/) - line 37
- [ ] [Browser Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/browser/) - line 39
- [ ] [Category Comparison Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/category-comparison/) - line 53
- [ ] [Category Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/categories/) - line 37
- [ ] [Device Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/device/) - line 71
- [ ] [Geographic Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/geographic/) - line 37
- [ ] [Global Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/global/) - line 28
- [ ] [Google Analytics and SendGrid Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/google-analytics/) - line 37
- [ ] [Mailbox Provider Comparison](https://sendgrid.com/docs/ui/analytics-and-reporting/mailbox-provider-comparison/) - line 38
- [ ] [Marketing Campaigns Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/marketing-campaigns-stats/) - line 88
- [ ] [Statistics Overview](https://sendgrid.com/docs/ui/analytics-and-reporting/stats-overview/) - line 109

**Comment by dhruvhacks** [comment]
@ksigler7 may I take up the [Tracking settings](https://sendgrid.com/docs/ui/account-and-settings/tracking/) page??

**Comment by dhruvhacks** [comment]
I am taking up [Tracking settings](https://sendgrid.com/docs/ui/account-and-settings/tracking/) page! :smiley:

**Comment by yashasingh** [comment]
Thank you @ksigler7 for such precise description! Working on it!

**Comment by ArthurNovaes** [comment]
I'm on [Email Activity Feed](https://sendgrid.com/docs/ui/analytics-and-reporting/email-activity-feed/) page ^^

**Comment by wdharmana** [comment]
Let me take <a href="https://sendgrid.com/docs/ui/analytics-and-reporting/geographic/">Geographic Statistics </a>, <a href="https://sendgrid.com/docs/ui/analytics-and-reporting/google-analytics/">Google Analytics and SendGrid Statistics</a>, and <a href="https://sendgrid.com/docs/ui/analytics-and-reporting/global/">Global statistic</a>

💯

**Comment by ArthurNovaes** [comment]
I'll take [Browser Comparison Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/browser-comparison/), [Browser Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/browser/) and [Category Comparison Statistics](https://sendgrid.com/docs/ui/analytics-and-reporting/category-comparison/) =)

**Comment by wdharmana** [comment]
Aha! Ok i will take Device Statistics and Category Statistics. Lets go :))

**Comment by dagolinuxoid** [comment]
Some PR's are doubled already.

**Comment by ksigler7** [comment]
@dagolinuxoid - you're right. Just so everyone knows, our policy here is to accept the first and best PR for each page. We really appreciate all of the work you all did here though! I am going to post several more issues very similar to this for our new services today - so look for those too!
