### ISSUE TITLE
Incorrect github contributors count in README.md contributors badge

### ISSUE THREAD

**Issue by yashasingh** [sendgrid/docs#4601]
The contributors badge from ```shield.io``` reflects incorrect count.

## Expected content
Contributors count 452

## Actual content
[![GitHub contributors](https://img.shields.io/github/contributors/sendgrid/docs.svg)](https://github.com/sendgrid/docs/graphs/contributors)

**Link to page**:
https://github.com/sendgrid/docs/blob/develop/README.md

**Comment by yashasingh** [comment]
May I update this??

**Comment by ksigler7** [comment]
this is so weird - I can't believe I never noticed it!

I guess we should just remove it for now. The todo here is to remove the contributors badge from the top of the readme.

**Comment by yashasingh** [comment]
@ksigler7 May I remove it??

**Comment by Mumbaikar007** [comment]
Done #4608

**Comment by dhruvhacks** [comment]
@ksigler7 multiple contributors have started taking this up! Who should be assigned?! 😛
