### ISSUE TITLE
Cancellation problem

### ISSUE THREAD

**Issue by dmvvilela** [sendgrid/docs#4722]
I am really hating sendgrid as of now..

I have deleted my account BEFORE the date of the plan and you charged me anyway.. I am using nubank so they cant refund me.. I dont find anywhere a way to get in touch with sendgrid. I deleted my account twice - meaning that you did not deleted it. I demand a refund as i dont want this service anymore and i did cancelled it before the date!!!

My account username is dmvvilela

**Comment by ksigler7** [comment]
Hello @dmvvilela ,

We're so sorry you're having this problem. Our awesome support team can help you get this resolved. Please contact them through this form - https://support.sendgrid.com/hc/en-us/requests/new#login-issue

SendGrid Docs Team
