### ISSUE TITLE
No way to upgrade from free tier to paid tier

### ISSUE THREAD

**Issue by rotten** [sendgrid/docs#4737]
The Contact Support button is disabled in the free tier.

There is no obvious way to upgrade to a paid tier from a free tier - it looks like you have to create an all-new account.

I'm unable to reach support to ask if it is possible.

Please take our money.  If not possible, please update the documentation to state this - on the plan/billing page in the dashboard and in the support portal when you try to click on the disabled support button.

**Comment by Reformant** [comment]
Hey @rotten, Thanks for reaching out. You should see the option to upgrade your account via the [Plan and Billing page](https://app.sendgrid.com/settings/billing) under 'Settings'.

Can you give that a try and let us know if you still have any questions?

**Comment by ksigler7** [comment]
https://app.sendgrid.com/settings/billing

![image](https://user-images.githubusercontent.com/28788585/48432478-a906a980-e731-11e8-8fe6-758732050d77.png)

**Comment by nes123** [comment]
+1

<img width="1488" alt="Screen Shot 2020-05-21 at 18 49 41" src="https://user-images.githubusercontent.com/7921778/82578073-94139d80-9b94-11ea-861e-f3e1c9360975.png">

**Comment by nes123** [comment]
What is going on with this service? it is very annoying.
