### ISSUE TITLE
Missing image in Transactional Templates for the Unsubscribe Module

### ISSUE THREAD

**Issue by brianchirls** [sendgrid/docs#4742]
In the documentation for [Unsubscribe modules for dynamic transactional templates](https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/#unsubscribe-modules-for-dynamic-transactional-templates), there is supposed to be a (presumably) animated gif, but the file is missing. 

It looks like somebody [forgot to check in](https://github.com/sendgrid/docs/pull/4626) the image file or otherwise host it somewhere.

Related to #4450

## Expected content

A visible animated gif showing how to perform the task

## Actual content
<img width="725" alt="image" src="https://user-images.githubusercontent.com/492291/48495579-50511280-e7fe-11e8-9bc3-ed8f3456fa36.png">

**Link to page**:
https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/#unsubscribe-modules-for-dynamic-transactional-templates

**Comment by parima08** [comment]
If someone could get that image up, I would appreciate it - I'm in the process of trying to understand the unsubscription module in transactional emails and it would be great to get that up.

**Comment by Whatthefoxsays** [comment]
Closing this issue since there hasn't been any activity for more than 90 days.

**Comment by astutejoe** [comment]
I just came across this problem and I'm deeply lost. The image doesn't seem to be up and I can't find any documentation on how to do it. (There's a bunch of 404's and 500's in the docs also). Shouldn't we be able to use a sender ID instead, to fill this info? This is awkward.
