### ISSUE TITLE
Incorrect response information in Suppressions

### ISSUE THREAD

**Issue by jolyonb** [sendgrid/docs#4765]
In [this document](https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/suppressions.html), the last entry (`POST https://api.sendgrid.com/v3/asm/groups/:group_id/suppressions/search`) has a response given by an object with parameter `recipient_emails`. When I call this method however, I get back the raw list, not wrapped in an object. I think the documentation needs to be updated.

**Comment by ksigler7** [comment]
thanks for letting us know!

**Comment by astuteape** [comment]
Update here: https://sendgrid.api-docs.io/v3.0/suppressions-suppressions/search-for-suppressions-within-a-group
