### ISSUE TITLE
Unsubscribe / Campaign feedback and suggestions

### ISSUE THREAD

**Issue by NoCopy** [sendgrid/docs#4777]
# Unsubscribe (suppressions) suggestions
Having spent quite some time over the past few weeks dealing with un-subscribe groups and the associated API I would like to suggest some enhancements in the following areas: (to avoid repeating myself, these are all nice to have - nothing major)

## Administration / User Display
(Marketing Campaigns > Unsubscribe Groups settings)

- Ability to specify a custom sorting order in which to display groups on the users preferences page. The list for the user currently seems to be sorted by ID which is not ideal when a large number of groups exist. At the very least a default Alpha sort would be nice. 
- Addition of an extra "frequency" property on the group to indicate to the user the volume of email they might expect on their preferences page. For instance I envision a group setting where you set three inputs:
    - Approximately / Equal To > Drop Down
    - Number > Text Box 
    - Day / Week / Month / Year > Drop Down 
    
    on the user prefernces page it would show title, description then something like "Frequency: (~)3 / week"
- Ability to add a custom disclaimer at the bottom of the user preferences / unsubscribe page. For our purposes, we need to notify the user of certain legal items related to Compliance with the Securities Exchange Commission regarding un-subscribes; however I could see this also being useful for things like links to privacy policy etc (or the full PP / other disclaimer if you don't wish to accept HTML / outside links)
- Ability to default all *new contacts* into one or many un-subscribe groups. The logic here would be that you may wish to provide optional "opt-in only" lists when the volume of email might be higher than the average user threshold. If the user wishes to subscribe they simply visit the preferences page; "We offer additional high volume lists if you are interested to opt-in - please check your preferences"
    - Currently this burden is strictly limited to some custom API solution    
     
  
## API  
- NEW API call to set user preferences in a more logical manner
    - by adding or removing one or multiple emails to one or multiple suppression groups (such as from a preferences form)

Proposed API  
```
POST /asm/suppressions
{
  "recipient_emails": [
    "test1@example.com",
    "test2@example.com"
  ]
  "suppress":[
    {group_id},
    {group_id},
    {group_id}
  ]
  "permit":[
    {group_id},
    {group_id},
    {group_id}
  ]
}
```

## Documentation
- General (non specific to this) but a better indicator of which results can be paged with the paging header and the default "Items Per Page" number

# Campaigns 
To avoid making a separate issue I will just include this here:
- Documentation on why a limit exists in the first place (this isn't clear - probably a technical reason I am sure but that could be better explained)
- Obvious indicator of how many campaigns you have created (to avoid the limit)
- Email sent to admin when limit is approaching (you may already have this so I apologize if that is the case)
- Ability to Auto-Archive old campaigns at a certain threshold (date or max number)
    - Given the uncertainty of the first point, archiving may be practically the same as just increasing the limit; and if that can't be done then Auto-Delete would be a nice to have regardless

**Comment by ksigler7** [comment]
hi @NoCopy - thanks for all of this awesome feedback! I have passed it onto the product manager who is responsible for this, and I have added the docs issues to our backlog. Would you be interested in ever participating in SendGrid user research as we explore expanding our products?
