### ISSUE TITLE
Sendgrid attatchment issue

### ISSUE THREAD

**Issue by rohitshilpkar** [sendgrid/docs#4785]
## Actual content

**Link to page**:

**Comment by rohitshilpkar** [comment]
hi, I am having a problem in sending a pdf attachment through sendgrid, I am trying to do this in dilaogflow. Please anyone help.

 const sgMail = require('@sendgrid/mail');
 sgMail.setApiKey(process.env.SENDGRID_API_KEY);
    
          sgMail.readFile('*fileurl(i am fetching it from bucket)*', function(err, data)
   {
    sgMail.send({ 
        to          : 'user1@gmail.com',
        from        : 'user2@gmail.com',
        subject     : 'Report',
        attachments : [{filename: 'file.pdf', 
                       content: data,
                       type: 'application/pdf',
                       disposition: 'attachment',
                       contentId: 'myId'
        }],
        html        : 'bla bla'
    }); 
    agent.add("mail sent");
   
        console.log("msg--  "+ sgMail);
         return sgMail;
   });

**Comment by vaishnavhiren1993** [comment]
### 

> that is multiple files (pdf) attach with email. if you want to attach one single file then you can remove for loop and index [i] from everywhere.
IF YOU GOT ANY ERROR THAN COMMENT HERE .
THE GITHUB COMMUNITY WILL PROVIDE YOU MORE SATISFIED RESOLUTION.

**Comment by rohitshilpkar** [comment]
@vaishnavhiren1993 thanks vaishnav. I want that in nodejs for dialogflow fulfillment.

**Comment by thinkingserious** [comment]
Hello @rohitshilpkar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by rohitshilpkar** [comment]
I forget my password and not able to reset it....so please help me to send
a pdf file...and the storage i am using is google bucket....

I am using node js

Thanks and regards
Rohit shilpkar
