### ISSUE TITLE
Add ruby+griddler guide to webhook code examples

### ISSUE THREAD

**Issue by brandonmwest** [sendgrid/docs#479]
https://sendgrid.com/docs/Code_Examples/Webhook_Examples/index.html

https://github.com/thoughtbot/griddler

**Comment by mbernier** [comment]
@thinkingserious this is a good target for wrapping up the Ruby examples we'll need for our Inbound Parse project.

**Comment by thinkingserious** [comment]
Hello @brandonmwest,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
