### ISSUE TITLE
"dynamic_template_data" docs lack the feature for raw text substitution

### ISSUE THREAD

**Issue by denver-HJS** [sendgrid/docs#4790]
I ran into the same issue that's documented here: https://github.com/sendgrid/sendgrid-python/issues/602

It looks like this feature's documentation was lost or not carried over into this repository.

Using the `{{{emailSubject}}}` (triple curly braces) solved my issue where apostrophes were being HTML encoded in the subject line.

**Comment by ksigler7** [comment]
Oh cool - thanks for letting us know @denver-HJS! We'll get this added into our backlog too

**Comment by astuteape** [comment]
This issue appears to be resolved and is now being closed. If you have more questions or feel the issue has been closed in error, please open another issue. If you need direct support, please contact our Support team and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
