### ISSUE TITLE
Custom SSL Configurations should specify https, not http

### ISSUE THREAD

**Issue by nelsonenzo** [sendgrid/docs#4794]
## Expected content
1) Prepare a proxy (like web application, nginx, or Amazon API Gateway) to take all traffic for mailing.example.com and forward it to http://sendgrid.net or *https://sendgrid.net* .

## Actual content
1) Prepare a proxy (like web application, nginx, or Amazon API Gateway) to take all traffic for mailing.example.com and forward it to *sendgrid.net.*

...
I'm clearly on this page because I want to use https.  HTTPS://sendgrid.net should at least be mentioned in the first sentence.

**Link to page**:
https://sendgrid.com/docs/ui/account-and-settings/custom-ssl-configurations/

**Comment by ksigler7** [comment]
this is great feedback - thanks!

**Comment by prakashcesinha** [comment]
but the doc remains unchanged

**Comment by nelsonenzo** [comment]
#6433 didn't solve this at all. Docs are still wrong and misleading.  My suggestion above has nothing to do with port numbers.
