### ISSUE TITLE
No way to contact support without account

### ISSUE THREAD

**Issue by devtimi** [sendgrid/docs#4859]
Received spam via sendgrid, trying to figure out how to report it leads me in fucking circles. No way to contact and report illegal spam sent via your service. Fix that. And stop allowing accounts to use sendgrid to send illegal spam emails.

**Comment by ksigler7** [comment]
Hi @devtimi - Please check out this page: https://sendgrid.com/report-spam/. Thanks for letting us know there's an issue!
