### ISSUE TITLE
The image is broken on the webhooks pages

### ISSUE THREAD

**Issue by jonoabroad** [sendgrid/docs#4893]
## Expected content
flow diagram to display

## Actual content

broken image link displayed 
**Link to **page**:
https://sendgrid.com/docs/for-developers/tracking-events/event/

https://github.com/sendgrid/docs/blob/develop/content/docs/for-developers/tracking-events/event.md**

**Comment by ksigler7** [comment]
@jonoabroad - thank you for this. Just by chance, this was already fixed and got deployed this morning
