### ISSUE TITLE
Empty subject while using dynamic template

### ISSUE THREAD

**Issue by Falseclock** [sendgrid/docs#4912]
email addresses are replaced.

Dynamic template is working fine. But mail coming with empty subject. 

![image](https://user-images.githubusercontent.com/3299139/51859694-f58d7880-2361-11e9-8dc8-48a2880394f6.png)

```php
$newLots = [
			[
				'number'    => 1001,
				'name'      => 'Name 1',
				'category'  => 'Category 1',
				'initiator' => 'Initiator 1',
				'value'     => '100001',
				'region'    => 'Region 1',
				'deadline'  => 'Deadline 1',
			],
			[
				'number'    => 1002,
				'name'      => 'Name 2',
				'category'  => 'Category 2',
				'initiator' => 'Initiator 2',
				'value'     => '100002',
				'region'    => 'Region 2',
				'deadline'  => 'Deadline 2',
			],
			[
				'number'    => 1003,
				'name'      => 'Name 3',
				'category'  => 'Category 3',
				'initiator' => 'Initiator 3',
				'value'     => '100003',
				'region'    => 'Region 3',
				'deadline'  => 'Deadline 3',
			],
		];

		$email = new Mail(new From("mp@domain.com", "Test Sendgrid Email"));
		$email->setSubject("Sending with SendGrid is Fun");

		$email->setTemplateId("d-0f5ccfd1a04a466cb21cc01d7caf6343");

		$per = new Personalization;
		$per->addto(new To("102@domain.com", "Account Name 1", [ "id" => 102 ], "Sending with SendGrid is Fun 1"));
		$per->addBcc(new Bcc("foobar@domain.com", "Account Name 2", [ "id" => 1002 ], "Sending with SendGrid is Fun 2"));

		$per->addDynamicTemplateData(new Substitution("totalCount", "!new lots count!"));
		$per->addDynamicTemplateData(new Substitution("totalAmount", "!new lots volume!"));
		$per->addDynamicTemplateData(new Substitution("totalOpen", "!total open!"));
		$per->addDynamicTemplateData(new Substitution("items", $newLots));
		$email->addPersonalization($per);

		$sendgrid = new SendGrid(Info::me()->config->SendGrid->apiKey);
```

**Comment by thinkingserious** [comment]
Hello @Falseclock,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Falseclock** [comment]
Guys...

I found three bugs with your dymamic templates, but you closing issue.

Are you think it is good way for communication through your support?

**Comment by Falseclock** [comment]
1. Subject always empty when using dynamic templates.

2. Personalisation does not support substitution per user while should, according to API doc.

3. Every user in personalisation see to whom this email was sent. But I define all recipients in global context, all users receive "personal email", but in this case dynamic template does not work.
