### ISSUE TITLE
Sending the Same Email to Multiple Recipients new version ?

### ISSUE THREAD

**Issue by hurkan-sert** [sendgrid/docs#4913]
documentation was not enough,
Can you help us with sample code to send an email to multiple people with php api
The example structure used in this link was not very helpful:
https://sendgrid.com/docs/for-developers/sending-email/personalizations/

**Comment by thinkingserious** [comment]
Hello @hurkan-sert,

I believe [this example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-an-email-to-multiple-recipients) may be helpful.

With Best Regards,

Elmer
