### ISSUE TITLE
Event Webhook Reference

### ISSUE THREAD

**Issue by PaulaBurgheleaGithub** [sendgrid/docs#4918]
https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html#-Event-objects
On the Event Object table for unique_args row, there is nothing checked. That means that unique_args are not posted on any of our events.
After reviewing our internal documentation, I have noticed that the unique_args are added to all of our event types.

Thank you,
Paula

**Comment by Whatthefoxsays** [comment]
Closing this issue since there hasn't been any activity in over 90 days. Thanks!
