### ISSUE TITLE
docs/ui/account-and-settings/mail.md is missing POST payload mentioned in docs/for-developers/sending-email/smtp-filters/#filter-spamcheck

### ISSUE THREAD

**Issue by magudb** [sendgrid/docs#4919]
I tried "everywhere" on your docs but I can find a reference to this payload and I could not find it is the git history either.  I would very much appreciate if you could add the payload. 
## Expected content
To find a description of the POST payload from SpamCheck 

## Actual content

A link to the inbound parse
**Link to page**: 
Broken link - https://sendgrid.com/docs/for-developers/sending-email/smtp-filters/%7B%7Broot_url%7D%7D/ui/account-and-settings/mail/#spam-checker
Working Link - https://sendgrid.com/docs/ui/account-and-settings/mail/#spam-checker

**Comment by astuteape** [comment]
Closing now that the spam check filter is removed.
