### ISSUE TITLE
It is possible to use fonts i.e. san serif/gotham and serif/Cheltenham using design editor.

### ISSUE THREAD

**Issue by ruchiordex** [sendgrid/docs#4934]

**Comment by ISHaNT-CHaHaR** [comment]
Yeah, it is possible to do so. In VS code there is a similar font i.e. sans-serif/'franklin Gothic medium'.
You can use that or can refer to some sites https://www.cufonfonts.com/font/gotham. 
But it is not for commercial use. if you want I can solve it in your file?

**Comment by astuteape** [comment]
I believe this is covered here: http://sendgrid.com/docs/ui/sending-email/editor/#adding-custom-fonts-using-the-html-head
