### ISSUE TITLE
501 Syntax error in parameters or arguments

### ISSUE THREAD

**Issue by cbski76** [sendgrid/docs#4944]
about 25% of my outgoing emails are failing with this error today and I don't understand why.  Would this point to a possible issue with sendgrid?  Is there any way to get a log with some actual details in it to help identify what is causing this issue?  Thanks

**Comment by Whatthefoxsays** [comment]
Hello cbski76,

We're sorry you're running into this issue! The best option here is to contact our customer support team. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
