### ISSUE TITLE
Activities table not properly aligned/rendered

### ISSUE THREAD

**Issue by reggiev** [sendgrid/docs#4948]
It seems like that the results page of the activity feed is not properly aligned (Table).

Steps to replicate:

1.) Sign in to SendGrid account
2.) Visit the Activity Feed
3.) Search for any email with activity
4.) The table displaying the results is not rendered properly. To view it you might need to "zoom out" your browser.

I am using Macbook Pro 2015 15 inches.
Latest version of Google Chrome.
And 
![image](https://user-images.githubusercontent.com/26558611/52781237-05f26280-3087-11e9-921f-c22777850f1f.png)

## Actual content
![image](https://user-images.githubusercontent.com/26558611/52780966-60d78a00-3086-11e9-81df-8e9c7c27c948.png)

![image](https://user-images.githubusercontent.com/26558611/52781135-c461b780-3086-11e9-89c9-dcf25a73af80.png)

**Link to page**: https://app.sendgrid.com/email_activity

**Comment by Whatthefoxsays** [comment]
Hi @reggiev,

Thanks so much for your feedback! We've passed this info along to the right people and they're on it!

SendGrid Docs Team
