### ISSUE TITLE
the file I sent to my email is not coming

### ISSUE THREAD

**Issue by hurkan-sert** [sendgrid/docs#4955]
foreach($params as $key => $deger ) {
     $sabit = \GENEL::DOSYA['earsiv'];

   $dosya_adi = $sabit['yol'].$deger['file_name'].'.pdf';
   $pdf_binary=file_get_contents($dosya_adi);
 
   $pdf_base=base64_encode($pdf_binary);

     $data["personalizations"][]["to"][] = ["email" => $deger['eposta'] ];
     $data["subject"] = "E-ARSİV FATURA PDF GÖRÜNTÜSÜ";
      $data["from"]=["email"=>"example@gmail.com"];
       $data["content"][0]=[ "type"=>"text/html", "value"=> "jghjhgj"];
        $data["attachment"][]=["Content" => $pdf_base,"Type" =>"application/pdf","Filename" 
          =>$deger['file_name'].'.pdf,"Disposition"=>"attachment","ContentId"=>"base".$key];
                
                            }

**Comment by Whatthefoxsays** [comment]
Hello hurkan-sert,

We're sorry you're running into this issue! Since this isn't directly documentation related, we recommend you contact our support team. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
