### ISSUE TITLE
Getting Started with the UI link

### ISSUE THREAD

**Issue by PaulaBurgheleaGithub** [sendgrid/docs#5008]
The link for the Getting Started with the UI does not redirect to an actual tutorial of the UI but to a tutorial on how to get started with MC.
The naming of the link is misleading, and it should be "Getting Started with the MC app."
If there was ever a video for the actual UI overview, then that should be the page where a new client should be redirected.

Thank you,
Paula

**Comment by Whatthefoxsays** [comment]
Hi Paula,

Can you please add a link to the Getting Started page you're referring to? Thanks!

The SendGrid Docs Team
