### ISSUE TITLE
Magento 2 Module Does not support Inline Attachments

### ISSUE THREAD

**Issue by chrismshea** [sendgrid/docs#5012]
I'm not sure this is where this belongs, but I was directed here to report the issue by SendGrid support.

## Expected content
Email would send properly with the inline attachment.

## Actual content
Email does not send and produces following error.

{"errors":[{"message":"The content_id parameter is required if disposition = 'inline'.","field":"attachments.0.content_id","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.attachments.content_id";}]}

The details of the issue and how we got around it can be found in the following support request.
**https://support.sendgrid.com/hc/requests/1949534**:

**Comment by riemers** [comment]
28 februari great support, i was just looking if the magento 2 extension supports version 2.3.0.. gues it will take a year too.
