### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#5017]
## Expected content
I expect the links to take me to the pages they're intended to.

## Actual content
They take me to a 404.

**Link to page**: https://sendgrid.com/docs/for-developers/sending-email/scheduling-email/#2-api

**Comment by Whatthefoxsays** [comment]
Thanks @jacobmovingfwd for the feedback. I've fixed the links here:

https://github.com/sendgrid/docs/pull/5026
