### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by joshuazamora** [sendgrid/docs#5018]
Hello, I'm getting this error message when trying to login. "You are not authorized to access SendGrid, please contact Support."

I checked my email to see if there were any notices as to why this may be, but don't see anything. 

I do see that my payment went through just fine a couple days ago, however I did exceed my monthly emails and don't see my account was charged for the excess. 

I'm wondering if this could be the issue. My username is joshuazamora

Thank you 

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @joshuazamora ,

We're sorry you're running into this issue! You can access support contact options by going to https://support.sendgrid.com and clicking on the button that says "Trouble logging in?" and then selecting "I am having a different issue". Once you fill out the form and submit it, a member of our support team should contact you shortly. Hope this helps!

SendGrid Docs Team
