### ISSUE TITLE
Campaign report, clicked links section is broken when the link is long

### ISSUE THREAD

**Issue by alexpov** [sendgrid/docs#5021]
Here is a screenshot
![image](https://user-images.githubusercontent.com/3033993/53758263-39761f00-3ec6-11e9-978b-33de92be8c89.png)

Once the link is long, there is no option to view the click count stats per link

using Google Chrome browser

**Comment by Whatthefoxsays** [comment]
Hello @alexpov,

We're sorry you're having this issue! I've passed this info on to the correct people, however, since this is not a docs-related issue, I'm going to go ahead and close this issue. Thank you for reporting it!

SendGrid Docs Team
