### ISSUE TITLE
sg_event_id length incorrect

### ISSUE THREAD

**Issue by mw-be** [sendgrid/docs#5025]
## Expected content
sg_event_id  - a unique ID to this event that you can use for deduplication purposes. These IDs are 100 characters long.

## Actual content

sg_event_id  - a unique ID to this event that you can use for deduplication purposes. These IDs are either 22 or 48 characters long.

**Link to page**:
https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html#sgeventid

https://sendgrid.com/docs/release-notes/2019-02-25/

**Comment by Whatthefoxsays** [comment]
Hi @mw-be,

Thanks so much for your feedback! The docs have been updated!

SendGrid Docs Team
