### ISSUE TITLE
Is it possible to use if on length of collection?

### ISSUE THREAD

**Issue by b9chris** [sendgrid/docs#5028]
## Expected content
It would help if the if/each documentation covered how to not just iterate over a collection, but check if it exists. For example, if there are items in a list of people, the email might read:
People
Bob
Sally

But if there are none, it's important to not show a People heading. To do that you'd need to use an if statement on the collection itself...

## Actual content

**Link to page**:
https://sendgrid.com/docs/ui/sending-email/using-handlebars/#combined-examples

**Comment by kylearoberts** [comment]
@b9chris 

I made an example for you that we will look to add to our docs.

HTML example:
```
    <html>
    <head>
      <title></title>
    </head>
    <body>
      {{#if people}}
      <p>People:</p>
        {{#each people}}
          <p>{{this.name}}</p>
        {{/each}}
      {{/if}}
    </body>
    </html>
```

Sample payload to get it to populate:
```
{
  "people":[{"name":"Bob"},{"name":"Sally"}]
}
```

Sample payload to get it to not populate:
```
{
  "people":[]
}
```

Please let us know if this does not work for you.

**Comment by b9chris** [comment]
It sort of does, until I use rows in a table - then it implodes. This may be a bug in the Code Editor:

{{#if people}}
<table><tbody>
{{#each people}}
<tr><td>Hi</td><td>{{this.name}}</td></tr>
{{/each}}
</tbody></table>
{{/if}}

Try just saving the above and behold the glory of the chaos the Editor creates for you.

**Comment by kylearoberts** [comment]
@b9chris 

The issue you are having is a bug in the Drag & Drop editor. I would recommend for the time being using the Code Editor for things like this till the engineers can get this fixed.

**Comment by astuteape** [comment]
Closing because this appears to have been addressed
