### ISSUE TITLE
Account immediately suspended

### ISSUE THREAD

**Issue by pvijeh** [sendgrid/docs#5031]
I just created a new account and immediately it was suspended. 

Something tells me your filtering is a little too sensitive... might want to fix that.

**Comment by Whatthefoxsays** [comment]
Hello @pvijeh,

We are very sorry that you are running into this problem. You can access support contact options by logging into https://support.sendgrid.com. If you can't log in, scroll to the "trouble logging in?" link and click there to let us know what's happening without actually having to log in. 

Hope this helps.

SendGrid Docs Team
