### ISSUE TITLE
No account but you taking money from my bank account

### ISSUE THREAD

**Issue by blainep3** [sendgrid/docs#5032]
I have not signed up for an account and have no way to contact support without signing in.  Please stop debiting my bank account.  How can I contact someone to find out why this is happening.  This is obviously a mistake, but I have no way to stop you.  blainep3@gmail.com

If you have a question, please do not ask it here, please [contact our support team](https://support.sendgrid.com).
You can contact SendGrid support from the [SendGrid Support Portal](https://support.sendgrid.com). 
Click **Login & Contact Support**, and then **Contact Support** to see your contact options.

If you're reporting an issue with our docs, thanks for letting us know!
-->

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hi @blainep3,

I'm sorry you're experiencing this issue. If you go to https://support.sendgrid.com/ and scroll down to the "trouble logging in?" section and click on that, you'll see a few options to let us know what's happening without actually logging in. I hope this helps!

SendGrid Docs Team
