### ISSUE TITLE
V3 mail/send not showing proper 202 response

### ISSUE THREAD

**Issue by jacobmovingfwd** [sendgrid/docs#5034]
## Expected content
202 returns a mail-id in the body, allowing senders to track the message all the way through the SG system

## Actual content

The 202 response says `{}`

**Link to page**: https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send

**Comment by arunpypy** [comment]
@jacobmovingfwd This indicates that the response body of type application/json is null but will have the information in request.headers. Hope this helps

**Comment by jacobmovingfwd** [comment]
Yes, I understand that. However, that's not what actually happens. The production system properly responds with the `message_id`, and we need to update our documents to reflect this appropriately.

**Comment by astuteape** [comment]
This now appears to be accurate in the docs
