### ISSUE TITLE
sgmessageid from X-Message-Id

### ISSUE THREAD

**Issue by namrataedulab** [sendgrid/docs#5044]
## Expected content
How do i get complete msg_id like this:-
SendGrid Message ID: XBg2anf2TqCy6WXKQFhieQ.filter0905p1mdw1-4434-59E0C6FF-3.0

As i am getting X-Message-Id in response header like this :- XBg2anf2TqCy6WXKQFhieQ

But i need complete msg id for Email Activitity API request /v3/messages/{{msg_id}}

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @namrataedulab,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
