### ISSUE TITLE
Advanced If

### ISSUE THREAD

**Issue by r3plica** [sendgrid/docs#5050]
The title for "Basic If, Else, Else If" makes it sound like there are some Advanced statements, yet I can not find any documentation for them anywhere.
Either it should be renamed to **If, Else, Else If** or there should be a section for **Advanced If, Else, Else If**

**Link to page**: https://sendgrid.com/docs/ui/sending-email/using-handlebars/#basic-if-else-else-if

**Comment by Whatthefoxsays** [comment]
Hi @r3plica 

Thanks for the feedback! The 'Advanced' section will likely come in the future as we introduce more helpers. Sorry for the confusion. 

The SendGrid Docs team
