### ISSUE TITLE
Status Codes for batch_id

### ISSUE THREAD

**Issue by rtomasso** [sendgrid/docs#5053]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html

The error for batch_id is misleading. Even if you enter a string it still comes back with a 400. The error should remind the sender that a batch_id needs to be generated via the API, it isn't a self-generated string. (The documentation also needs to make this clearer, it's hidden away).

**Comment by Whatthefoxsays** [comment]
Hi @rtomasso ,

Thanks so much for your feedback! We've added this to our internal docs backlog.

SendGrid Docs Team

**Comment by astuteape** [comment]
This has been updated here: https://sendgrid.api-docs.io/v3.0/mail-send/mail-send-errors#-Batch-ID-Errors
