### ISSUE TITLE
For mail/send if the email field is empty, the "bad request" response doesn't tell you.

### ISSUE THREAD

**Issue by rtomasso** [sendgrid/docs#5060]
Posting an email to the mail/send endpoint, inadvertently the to email was blank, but the response didn't note this, like it usually does for missing or invalid fields.

Post Body:
{"personalizations":[{"to":[{"email":FALSE,"name":"Ro Bote"}]}],
"content":[{"type":"text/html","value":"
<html><head></head><body>...</body></html>"}
],
"subject":"welcome",
 "from": {...}, "reply_to" : {...} 
}

The 400 Response body is
{
    "errors": [
        {
            "message": "Bad Request",
            "field": null,
            "help": null
        }
    ]
}

Nothing helpful in the headers either.

**Comment by Whatthefoxsays** [comment]
@rtomasso Thanks for the feedback. I've passed this info along to the appropriate teams so they can investigate further.
