### ISSUE TITLE
Footer doesn't stick to bottom of page

### ISSUE THREAD

**Issue by eddiezane** [sendgrid/docs#508]
![screen shot 2014-08-11 at 2 54 47 pm](https://cloud.githubusercontent.com/assets/959573/3880934/42a83b3a-2189-11e4-8dfa-d090f3a2e264.png)

**Comment by trotha01** [comment]
@eddiezane @mbernier This seems to be fixed as far as I can tell? Can we close this issue?

Are there reproducible steps for this Eddie?

**Comment by eddiezane** [comment]
@trotha01 if it looks good on a thunderbolt display then it's GTG

**Comment by trotha01** [comment]
Ah, I see

**Comment by mbernier** [comment]
I am working with @two24studios to clean up some of the design for docs, this is one of the things we'll fix up.

**Comment by trotha01** [comment]
nice!

**Comment by mbernier** [comment]
This has been fixed
