### ISSUE TITLE
Send response is Accepted but not getting email

### ISSUE THREAD

**Issue by HariSirigouniTest** [sendgrid/docs#5087]
Hi,

Below is my sendgrid account. I am getting response as Accepted but not getting email. Can you please have a look?

UserName : sharidotnet

Thanks,
Hari.

**Comment by Whatthefoxsays** [comment]
Hello @HariSirigouniTest ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
