### ISSUE TITLE
send email through smtp using sendgrid my users get this email in there spam folder, my website run on ip address.

### ISSUE THREAD

**Issue by mrinmoy-ncrts** [sendgrid/docs#5088]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @mrinmoy-ncrts  ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
