### ISSUE TITLE
Sendgrid account creation through Azure ARM template or azure portal throws ResourcePurchaseValidationFailed error

### ISSUE THREAD

**Issue by satyajitmahapatra** [sendgrid/docs#5089]
I am facing issue while trying to create a sendgrid account either through portal or by ARM template deployment. Below is the issue. If someone has any knowledge about this please let me know.

Summary
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"ResourcePurchaseValidationFailed\",\r\n \"message\": \"User failed validation to purchase resources. Error message: 'Offer with PublisherId: Sendgrid, OfferId: sendgrid_azure cannot be purchased due to validation errors. See details for more information.'\"\r\n }\r\n}"}]}

Raw Error
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"ResourcePurchaseValidationFailed\",\r\n    \"message\": \"User failed validation to purchase resources. Error message: 'Offer with PublisherId: Sendgrid, OfferId: sendgrid_azure cannot be purchased due to validation errors. See details for more information.'\"\r\n  }\r\n}"
    }
  ]
}

**Comment by Whatthefoxsays** [comment]
Hello @satyajitmahapatra,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by dannythomas13** [comment]
Hello @satyajitmahapatra,
I am getting the same error, what was the resolution?

**Comment by oviliz** [comment]
+1 ...

**Comment by sayanghosh123** [comment]
I am curious how we can log a support case given we are not being able to create an account / login to that. Underwhelming experience.
