### ISSUE TITLE
As a user I need to apply a custom header to all outboun mail.  For systems that use sendgrid as a smarthost.  

### ISSUE THREAD

**Issue by SquirrelAssassin** [sendgrid/docs#5091]
As a user I need to apply a custom header to all outboun mail.  For systems that use sendgrid as a smarthost.

**Comment by Whatthefoxsays** [comment]
Hello @SquirrelAssassin ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
