### ISSUE TITLE
Got a credit card charge, but I did not sign up

### ISSUE THREAD

**Issue by PaulPion** [sendgrid/docs#5093]
I don't have an account so I can't get in to your support -- very frustrating.

**Comment by Whatthefoxsays** [comment]
Hello @PaulPion,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
