### ISSUE TITLE
A search button should be available on all pages of the site.

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [sendgrid/docs#5095]
Sorry, my suggestion is not for docs, but for the main side. I didn't find better way to contact you. 

## Expected content
A search button should be available on all pages, such as on 
https://sendgrid.com/blog/sendgrid-is-privacy-shield-certified/
It should be moved to the top-level menu

## Actual content
Many pages do not have search button,, e.g.
https://sendgrid.com/policies/tos/

**Comment by Whatthefoxsays** [comment]
@michael-freidgeim-webjet 

Thanks for the feedback! I'll make sure to pass this on to the correct people.

The SendGrid Docs team
