### ISSUE TITLE
Money Refund.

### ISSUE THREAD

**Issue by Letzbank** [sendgrid/docs#5110]
## Expected content
Hi,

I have paid 12 dollars for 10 days subscription. but i don't want further services. i will subscribe when ever needed. but today i see some deduction from my card on sendgrid monthly subscription. please refund my amount. i will subscribe when ever needed.

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @Letzbank,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
