### ISSUE TITLE
I need to cancel our account but don't have access as I don't know what email is associated with the account.

### ISSUE THREAD

**Issue by VoxyAdmin** [sendgrid/docs#5113]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @VoxyAdmin,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
