### ISSUE TITLE
Sendgrid account in "paused" mode

### ISSUE THREAD

**Issue by mariojacobo** [sendgrid/docs#5125]
we have multiple sendgrid accounts (created on Azure cloud) and 1 of them is showing up as "paused". We can't login and we cannot re-activate it. I opened a case with support, however there's been 0 traction on it. Please advise 

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hi @mariojacobo, 

Generally, when this happens, it's paused on the Azure side, not the SendGrid side. If you want us to do some more investigating please send your UID to docs@sendgrid.com and I'll pass it along to the right people.

Thanks,

The SendGrid Docs team
