### ISSUE TITLE
the mails to daum.net ( hanmail.net ) is not delivered

### ISSUE THREAD

**Issue by ParkYongGyu** [sendgrid/docs#5127]
### **the emails to daum.net ( hanmail.net ) are not delivered.**

as of the status "Delivered", the percent is 100 % in my account (  hwasahan ) 
however, the emails to daum.net ( hanmail.net ) are not delivered.

a lot of korean users are using hanmail.net 

## Expected content
should be delivered to the mailbox. 

## Actual content
the mail is not delivered in my mailbox.

Please let us know if email tried to send to the host "daum.net" or "hanmail.net" is working fine.

**Comment by Whatthefoxsays** [comment]
Hello @ParkYongGyu,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
