### ISSUE TITLE
Unexpected bitcointalk domain in documentation

### ISSUE THREAD

**Issue by gareth** [sendgrid/docs#5135]
While browsing the SPF documentation I noticed that a link contained a reference to `bitcointalk.org` - I don't think the Dmarcian SPF survey requires a domain to be passed in the URL so I was surprised to see it prefilled. Is this intentional?

https://github.com/sendgrid/docs/blob/e07060b38afacf58b19240fda8a6966781f81b92/content/docs/glossary/spf.md#L68

**Comment by Whatthefoxsays** [comment]
Note: Make this a generic/sample URL.

**Comment by TomerPacific** [comment]
@Whatthefoxsays , I'd like to help with this issue. 
What do you mean by generic URL?

**Comment by gareth** [comment]
@TomerPacific Take a look at [RFC 2606](https://tools.ietf.org/html/rfc2606) which defines some URLs as safe for documentation:

* example.{com,net,org}
* *.example
* *.test
* *.invalid
* *.localhost

IMO those should be safe and the RFC may have advice about which is best

**Comment by TomerPacific** [comment]
@Whatthefoxsays , 
I have opened a [PR](https://github.com/sendgrid/docs/pull/5591).
According to RFC 2606, example.com was the suggested option in this case.
