### ISSUE TITLE
Submit button not working

### ISSUE THREAD

**Issue by OlafvdSpek** [sendgrid/docs#5153]
The Submit button @ https://support.sendgrid.com/hc/en-us/requests/new#login-issue stays gray for me, so I can't submit the form..
An alternative way to contact support (what's wrong with a normal email address) doesn't appear to be available either.

**Comment by LiYChristopher** [comment]
Hi there! I apologize for the issue with reaching out to SendGrid support through that form. 

The form can be submitted if you input _at least 15 characters in the description input_, and support will be able to follow up with you through the email address provided. It's clear that there needs to be some type of warning or message to indicate this - I've alerted the team that supports the help center to make appropriate changes for the future.

I hope this helps - please let us know if you're still having issues with the form @OlafvdSpek

**Comment by OlafvdSpek** [comment]
Thanks
