### ISSUE TITLE
Login in issues - after fix

### ISSUE THREAD

**Issue by vintrix9935** [sendgrid/docs#5236]
I am still experiencing issues logging in or pushing email via API. STill getting ["Bad username / password"]

I cannot find any support email address, contact phone number, or form anywhere on the site. So, I have no way to reach out to your support. Our systems have been down since yesterday and we need it fixed. Please tell me where I can get support.

**Comment by Whatthefoxsays** [comment]
Hello @vintrix9935,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
