### ISSUE TITLE
Rate Limits - How it works?

### ISSUE THREAD

**Issue by Vanals** [sendgrid/docs#5237]
SOURCE: https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/rate_limits.html

Hi,
I was reading your documentation, and there you speak about a **rate limits** of emails to be sent. So I have some questions.

First question:
1) Using sendGrid, the emails will be actually sent from my email?  The one specified in the  **"from"** key , or you will send them at my name? 
Because for example if I use a @gmail, it has a rate limit of 500 at day, so would not be possible to send many of them ad once.

Second question:

2) If you send them, what is the rate limit? how is that set? and how often does it resets?
I saw this possible response in the doc and I haven't seen ay **500** limit in the web site pricing.
```
HTTP/1.1 200 OK
Content-Type: application/json
X-RateLimit-Limit: 500
X-RateLimit-Remaining: 499
X-RateLimit-Reset: 1392815263

{
  "foo": "bar"
}
```

3) Also.. an Example:
If I would have an "Email API essential account" and I want to send 30k email in one day, would that be possible? Could I just send 30K email in one call? With an object of 30K arrays?

Thank you

**Comment by kylearoberts** [comment]
@Vanals 

> Using sendGrid, the emails will be actually sent from my email? The one specified in the "from" key , or you will send them at my name?

SendGrid would send your emails using the From your specify in your mail send:

`  "from": {
    "email": "your_email@domain.com",
    "name": "Your Name"
  }`

> Because for example if I use a @gmail, it has a rate limit of 500 at day, so would not be possible to send many of them ad once.

Just for your knowledge it is not recommended that you use a gmail address or any email address you do not fully control. You want to use an email address that you fully control. The best thing to do is to use a domain that you bought and have access to DNS records for authentication.

> If you send them, what is the rate limit? how is that set? and how often does it resets?
I saw this possible response in the doc and I haven't seen ay 500 limit in the web site pricing.

Mail send is different on the rate limit from other API calls. With our v3 mail send found [here](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html) you can send up to 1000 emails per API call.

> Also.. an Example:
If I would have an "Email API essential account" and I want to send 30k email in one day, would that be possible? Could I just send 30K email in one call? With an object of 30K arrays?

As I mentioned above you could send 30 API mail send calls with 1000 email addresses each to reach your 30K. On a brand new account I would not recommend this as recipient servers will not like getting this much email from an unknown source. It would be best to break up a send like this over a number of days if not a week or more.

When sending mail it is very important to build up a reputation. To start you will want to authenticate your domain. I would recommend reviewing the documentation [here](https://sendgrid.com/docs/glossary/sender-authentication/). Once you are authenticated you want to warm up your sending by following a sending schedule similar to the one found [here](https://sendgrid.com/docs/ui/sending-email/warming-up-an-ip-address/#automated-ip-warmup-hourly-send-schedule). This is very important as it allows recipient servers to get used to your sending and how your recipients interact with your mail.

If you have further questions, please let us know.

**Comment by Vanals** [comment]
Thank you for your reply kylearoberts! Clear! :)
