### ISSUE TITLE
Typo in v3 pyhton code example

### ISSUE THREAD

**Issue by akhilrj** [sendgrid/docs#5238]
## Expected content
sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))

## Actual content
sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))

**https://sendgrid.com/docs/for-developers/sending-email/v3-python-code-example/#using-sendgrids-python-library**:

**Comment by Whatthefoxsays** [comment]
Hi @akhilrj 

Do you want to go ahead and do a pull request to fix the content? If not, that's okay, it will just get done faster this way rather than ending up on our backlog. 

Thanks!

The SendGrid Docs Team

**Comment by akhilrj** [comment]
Done!!

Please review and merge.

**Comment by Whatthefoxsays** [comment]
Done and done! Thanks for contributing! 🎉
