### ISSUE TITLE
Add 2FA and SSL clicktracking instructions (via cloudflare or fastly)

### ISSUE THREAD

**Issue by brandonmwest** [sendgrid/docs#525]
https://docs.google.com/a/sendgrid.com/document/d/1T-LubhRn3qmJ0hKfmOXtzNhhW39eGsO6krgD0HM5RGk/edit

**Comment by AlphaJuliettOmega** [comment]
?? There aren't enough useful SSL Clicktracking instructions, this ticket should still be open?
