### ISSUE TITLE
Broken link to handlebars documentation

### ISSUE THREAD

**Issue by drewgierach** [sendgrid/docs#5250]
## Expected content

https://sendgrid.com/docs/ui/sending-email/using-handlebars/

## Actual content
Clicking on the link for **Using Handlebars** located in the resources section of the page linked below results in a 404 - Not Found

**Link to page**:
https://sendgrid.com/docs/ui/sending-email/create-and-edit-legacy-transactional-templates/#additional-resources

**Comment by Whatthefoxsays** [comment]
Hey @drewgierach! Thanks for bringing this to our attention. 

We've gone ahead and fixed this issue here https://github.com/sendgrid/docs/pull/5256.
