### ISSUE TITLE
Test account

### ISSUE THREAD

**Issue by murtazaa** [sendgrid/docs#5251]
Hi, 

We have a sendgrid account that is used in our dev environment all the way to production. We want to keep dev/testing account separate from production, how can we manage that with a single sendgrid account? 

Thanks, 
Taz.

**Comment by Whatthefoxsays** [comment]
Hello @murtazaa,

Thanks for your question! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
