### ISSUE TITLE
sendgrid scams me , sendgrid support is bad

### ISSUE THREAD

**Issue by hatim-1** [sendgrid/docs#5266]
this company scam me 
I got an account for 1 month but they block my account after 15 minutes I did not use it . when I ask the support for refund they don't want to refund me.

**Comment by Whatthefoxsays** [comment]
Hello @hatim-1 ,

We're sorry you're having this issue! Since this is not a docs-related issue, you will need to contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
