### ISSUE TITLE
Please, Please, Please Help - Locked out of Contacting Support

### ISSUE THREAD

**Issue by mediasres** [sendgrid/docs#5273]
I really have nowhere else to contact SendGrid. "Support" is only reachable when signed in. I can't sign in because I have forgotten my Username. I have my email. I have my password. I do not have my username. Your UI requires you to have your Username in order to reset your password. So in effect, I am locked out of both accessing Support, and also out of resetting my password. Ugh. 

I wouldn't bother you, the very helpful person who is reading this, but I've soured your site and this is the only pathway to a living person I can find. Please direct me to how to reset my password, or access support in some way. 

My email address is:
kevin.vonduuglasittu@gmail.com 

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @mediasres ,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
