### ISSUE TITLE
Mails are not receiving in inbox 

### ISSUE THREAD

**Issue by asheesharyan** [sendgrid/docs#5276]
I am able to capture email data on the url but my mails are stop working and not going in inbox or anywhere.

**Comment by Whatthefoxsays** [comment]
Hello @asheesharyan,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
