### ISSUE TITLE
Please help, support is not responding to me - this is not supposed to be posted here, I know

### ISSUE THREAD

**Issue by tobiekruger** [sendgrid/docs#5278]
**Please help, support is not responding to me**

Hi, I know this is not the place, I am desperate. Moved premises last week and got a new ip address, been trying to get it whitelisted. First request took 1 day for a response, then got instructed to send screenshot from banking statement for a verification charge, which I did - expected another response a day later but it never came.

Whoever reads these please phone whoever is supposed to check zendesk responses and tell them they are missing queries

**Comment by Whatthefoxsays** [comment]
Hi @tobiekruger, 

We're sorry you're having issues! Can you please share the ticket number associated with your issue? I'll make sure I pass it along to support once I've got it and they'll get you squared away. 

Thanks!

The SendGrid Docs team

**Comment by tobiekruger** [comment]
Thanks for responding, support have resolved my issue.
