### ISSUE TITLE
Error while signing up

### ISSUE THREAD

**Issue by jinhedev** [sendgrid/docs#5296]
Trying to sign up but got error "Cannot sign up..., etc."
A few minutes later try to signup with the same username, but it was taken. I think signup went successfully, but the web was rendering errors for some reason.

## Expected content
Signup success. Get redirected to the home page or whatever page that is NOT signup page.

## Actual content
Signup failed. Errors is render on the top. No redirect. Stayed on the same page.

**Link to page**:
https://signup.sendgrid.com

**Comment by Whatthefoxsays** [comment]
Hello @jinhedev  ,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
