### ISSUE TITLE
validate potential changes to PHP webhook example

### ISSUE THREAD

**Issue by brandonmwest** [sendgrid/docs#531]
via support:

[10:02 AM] I was using code to capture data: 
$[10:03 AM] `$datareceived = $HTTP_POST_DATA;`
whereas I should have used      `$datareceived = file_get_contents("php://input");` 
if you update your example code on the link https://sendgrid.com/docs/API_Reference/Webhooks/event.html  
it will be helpful for others

**Comment by thinkingserious** [comment]
Hello @brandonmwest,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
