### ISSUE TITLE
Sendgrid if statement

### ISSUE THREAD

**Issue by klpnaidu84** [sendgrid/docs#5312]
Hi,
I need solution for comparing two strings in sendgrid.
Please send me the solution ASAP.

Thanks,
Purushottama

**Comment by Whatthefoxsays** [comment]
Hello @klpnaidu84,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
