### ISSUE TITLE
v3 Node JS example shows Kotlin example instead

### ISSUE THREAD

**Issue by RobertoMachorro** [sendgrid/docs#5317]
## Expected content

Usage and example code for SendGrid using Node JS.

## Actual content

Usage and example code for SendGrid using Kotlin.

**Link to page**:

https://sendgrid.com/docs/for-developers/sending-email/v3-nodejs-code-example/

**Comment by joshwooding** [comment]
This seems to work as expected?

**Comment by RobertoMachorro** [comment]
> This seems to work as expected?

Yes, this seems to have been corrected now.
