### ISSUE TITLE
How to Send an SMTP Email

### ISSUE THREAD

**Issue by magestree** [sendgrid/docs#5319]
https://sendgrid.com/docs/API_Reference/SMTP_API/getting_started_smtp.html

Everithing was clear until 12 step, when doc says: Finally, send the email with a period and then press enter: .[Enter]

What exactly it is supposed I need to do here? I mean... what exactly is: "send the email with a period"?
I'm OK until this step, but once here I can press Enter and Enter egain and again, and just increase lines, but never send the email, so never reach: The mail server returns 250 Ok: queued as …

**Comment by kylearoberts** [comment]
@magestree 

Sorry about the trouble. I'll see about making the instructions more clear. What you want to do is something like this:

```
SUBJECT: Testing[ENTER]
[ENTER]
This is the body.[ENTER]
[ENTER]
.[ENTER]
250 Ok: queued as A1AywHK7T_itbGWaASw2YQ
```

Please let us know if this clears things up for you.

**Comment by duncanleung** [comment]
I'll take this issue to update these steps into the docs.
