### ISSUE TITLE
Cant login and there is no way to get help as for help you need to login 

### ISSUE THREAD

**Issue by Angleblade007** [sendgrid/docs#5324]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @Angleblade007 ,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
