### ISSUE TITLE
contact support loop

### ISSUE THREAD

**Issue by maxgod1** [sendgrid/docs#5325]
<!-- 
If you have a question, please do not ask it here, please [contact our support team](https://support.sendgrid.com).
You can contact SendGrid support from the [SendGrid Support Portal](https://support.sendgrid.com). 
Click **Login & Contact Support**, and then **Contact Support** to see your contact options.

When I try to login I get an error asking me to contact the the customer support (probably because I failed to verify my email on time). When I try to contact the customer support I am being asked to login which I cannot do... This is extremely frustrating.

My username: "mgodin"

**Comment by Whatthefoxsays** [comment]
@maxgod1, 

Can you provide more information on the issue you're having? If you're having trouble contacting support, go to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
