### ISSUE TITLE
SendGrid event Notification issue

### ISSUE THREAD

**Issue by Deepa-reddy** [sendgrid/docs#5326]
i'm getting multiple event notification on same event like delivered for 3 to 4 times and open for multiple times even though i opened once only

**Comment by Whatthefoxsays** [comment]
Hello @Deepa-reddy,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
