### ISSUE TITLE
CSV File not being attached

### ISSUE THREAD

**Issue by beni-7E** [sendgrid/docs#5348]
I'm trying to import our existing contacts but the CSV file is not being attached on the page after selecting the file to upload. I've already formatted the file based on the CSV format but it is still not working

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @beni-7E,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
