### ISSUE TITLE
Incomplete section in DMARC documentation

### ISSUE THREAD

**Issue by timcoote** [sendgrid/docs#5388]
This is a documentation error.

## Expected content
A complete section referring to what to do with reverse DNS

## Actual content
In this section `1. Deploy DKIM & SPF by setting up reverse DNS for your SendGrid IP`, the last sentence is incomplete. Unfortunately, I don't know what it should be so I cannot fix it.

**Link to page**:
http://bit.ly/2YBDCjJ

**Comment by Whatthefoxsays** [comment]
Thanks for the feedback @timcoote! We've updated the docs and made the fix [here](https://github.com/sendgrid/docs/pull/5390).
