### ISSUE TITLE
Emails not sent with error: 550 5.7.1 [192.254.117.55 14] Messages missing a valid address in From

### ISSUE THREAD

**Issue by IoanaVisma** [sendgrid/docs#5397]
Our customers experienced one problem when trying to send emails to their customers using our service. The error I see on Sendgrid side is:: 550 5.7.1 [192.254.117.55 14] Messages missing a valid address in From: header, or having no From: header, are not accepted. x56si6451488edb.348 - gsmtp.
From what I read on the internet this issue happened before and I think is not fixed (https://www.drupal.org/project/sendgrid_integration/issues/2997640). 
Nothing changed on how we use your service and when setting the from address we use MailAddress (string address, string displayName).

Looking forward for feedback!

**Comment by Whatthefoxsays** [comment]
Hello @IoanaVisma,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by totalexpert20** [comment]
Hello @IoanaVisma did Sendgrid ever let you know what the issue was? We are seeing this now and not getting any support or response from Sendgrid.  Thanks! Jochen

`550 5.7.1 [149.72.219.28 14] Messages missing a valid address in From: header, or having no From: header, are not accepted. d9si13813edo.391 - gsmtp`

**Comment by totalexpert20** [comment]
Hello @IoanaVisma we are seeing the same issue and wondering what the resolution was? Sendgrid's support lacks major luster at the moment.  

`550 5.7.1 [149.72.219.28 14] Messages missing a valid address in From: header, or having no From: header, are not accepted. d9si13813edo.391 - gsmtp`

**Comment by Vrety** [comment]
I got the same issue and still not finding any solutions.
