### ISSUE TITLE
Document Create New Sub-user guide for DOCS

### ISSUE THREAD

**Issue by brandonmwest** [sendgrid/docs#54]
As a user I would like for a new subuser creation guide to be added to the website to help guide me through the creation process for a subuser from my parent account. This should ideally include a video and or screenshot based walk through for the creation process including whitelabeling the new subuser and the IP assignment process.

**Comment by thinkingserious** [comment]
Hello @brandonmwest,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
