### ISSUE TITLE
Send grid blocking our domain

### ISSUE THREAD

**Issue by karanspeedysingh** [sendgrid/docs#5421]
I used send grid email relay from azure portal for sending mails for a phishing campaign.
send grid banned us without giving any reason.
I am stuck in between a campaign. Sendgrid support is not even helping me.
I am following all the subscription  requirements!

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
@karanspeedysingh, 

Hello <name> ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
