### ISSUE TITLE
Tracking email activity of more than 1000 emails

### ISSUE THREAD

**Issue by himanshuphirke** [sendgrid/docs#5430]
I want to get Email activity by API using my own custom arguments. What if I have sent 3000 emails, how would I get the activity in pages?
Let's say I define the limit as 1000 then how do I know there is 1001th record which I need to retrieve

I have tried: **limit** & **offset** params in query param but result is always same whatever offset I set

**Comment by Whatthefoxsays** [comment]
Hello @himanshuphirke ,

We'd love to help! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by himanshuphirke** [comment]
@Whatthefoxsays - To fetch the email activity by using offset and limit is not documented. It was known after talking with support.
SendGrid which is known for email & tracking in thousands is missing documentation to track those email activity.

Its SendGrid's discretion to mark the issue and close it as invalid but it totally defeats the purpose of having it linked to github and expecting people to contribute.

**Comment by paarth-ally** [comment]
@hphirke Did you find a resolution for this problem?
I have similar problem and could not find a relevant solution in documentation.

**Comment by hphirke** [comment]
> @hphirke Did you find a resolution for this problem?
> I have similar problem and could not find a relevant solution in documentation.

Nope, I was hoping sendgrid team responds since the documented feature was not working
