### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by jakerobers** [sendgrid/docs#5437]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/templates.html

The GET /templates API route now includes an `updated_at` attribute.

**Comment by Whatthefoxsays** [comment]
Hey @jakerobers, 

Looks like it's already on this page: 

![image](https://user-images.githubusercontent.com/13628723/61480743-dd330980-a953-11e9-937e-6d9521f0c79d.png)

Is that what you're referring to?

**Comment by jakerobers** [comment]
Now the structure looks like this:

{
	"id": "some uuid",
	"name": "some name",
	"updated_at": "this is new", <-------
	"versions": [...]

}

Thanks,

Jake

**Comment by Whatthefoxsays** [comment]
We'll make the change, but in the future, I would refer to [this](https://sendgrid.com/docs/api-reference/) API reference. It will definitely be the most up-to-date. We're hoping to deprecate the old one ASAP. 

Thanks for the feedback!
