### ISSUE TITLE
Can't login to support (and therefore can't contact support)

### ISSUE THREAD

**Issue by Roko131** [sendgrid/docs#5471]
Hi

Can't login to support.sendgrid.com. The big 'Login & Contact Support' button doesn't bring up the login fields. Login to app.sendgrid.com works fine. I tried from 3 different browsers and 2 different Computers (Asked my friend from a different city and of course different IP). Turned off addblockers. Tried with browsers without adblockers. Tried from Window & Linux.

More info:
(step 1) At first when you click login & contact support it brings you to 
`https://app.sendgrid.com/login?redirect_to=https%3A%2F%2Fsendgrid.com%2Fsupport%2Fsso%2Flogin%3Freturn_to%3Dhttps%253A%252F%252Fsupport.sendgrid.com` where you enter credentials and then it returns you to `https://support.sendgrid.com/hc/en-us` but still doesn't say you are logged in.

Though you actually are logged in - you can confirm by going to `https://app.sendgrid.com` and see your dashboard.

But at support: `https://support.sendgrid.com/hc/en-us` still not logged in. and then whenever you click(at https://support.sendgrid.com/hc/en-us) Login & Contact Support it redirects you to https://support.sendgrid.com/hc/en-us/signin?return_to=https%3A%2F%2Fsupport.sendgrid.com and then you arrive the same place not logged in.
Since then clicking the login button just return you to same URL,
But if you go to app.sendgrid.com - where you are logged in- if you log out through there and then click `Login & Contact Support` - then you will be back to step 1

https://support.sendgrid.com/hc/en-us/signin?return_to=https%3A%2F%2Fsupport.sendgrid.com

Also tried the 'Trouble Logging In?' > 'I am having a different login issue.' and submit there but I didn't get a confirmation that the message was sent.

Something doesn't work there- maybe the captcha?

Please fix this so I can talk to support about my actual problem. Thank you

p.s. It's not so much as you can't log in to support as much as it's the support page not recognizing you are logged in.

**Comment by Whatthefoxsays** [comment]
Hello @Roko131, 

Sorry you're having this issue and thanks for the feedback. I'll pass this info along and see if we can't get you sorted.

**Comment by Whatthefoxsays** [comment]
Hi @Roko131 

Were you able to get taken care of by support? The response that I got was that it might be a cache/cookies issue on your end. Hopefully this helps!

**Comment by Roko131** [comment]
It was not cache/cookies issue on my end.

The support account was blocked by Sendgrid.

And after 6 days of back and forward messages of them saying it's a problem at my end
They finally acknowledged it and unblocked it.

Thanks for checking on the issue.

**Comment by PierfrancescoElia** [comment]
Hi, I'm having the same problem. I don't know if it's related, but I can't verify my e-mail address, additionally. I always receive the e-mail but the app always return a generic error.
