### ISSUE TITLE
CSS classes breaks when email is forwarded

### ISSUE THREAD

**Issue by aneesshameed** [sendgrid/docs#5487]
Create a dynamic template
Use classes to style some elements in the template.
Send a test email.
Use the email received and forward it to a different email id.
You will see that styles are broken.

Issue is that when emails are forwarded classes will not be copied. What I am looking for is sendgrid to change all those classes in template to inline css.

**Comment by aneesshameed** [comment]
Currently what I am doing is, I design template with classes in sendgrid editor. Later I copy it to https://templates.mailchimp.com/resources/inline-css/ and convert all classes to inline css.

**Comment by Whatthefoxsays** [comment]
Hello @aneesshameed,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by ramonpm** [comment]
@Whatthefoxsays what about all the people that suffer with the same problem? Should everyone open a ticket? If we could just google it would save Sendgrid's support team time, which looks like they need it, 6 weeks to respond is a pretty bad.
