### ISSUE TITLE
Subuser Management

### ISSUE THREAD

**Issue by cemurray** [sendgrid/docs#5499]
https://sendgrid.com/docs/API_Reference/Web_API/Customer_Subuser_API/subusers.html

**Comment by cemurray** [comment]
For recommended steps when creating Subusers using the API, check out this SendGrid Knowledgebase article.

SendGrid Knowledgebase Article links to "page not found"

**Comment by Whatthefoxsays** [comment]
Hi @cemurray, 

Sorry about that! That version of the documentation is soon to be deprecated. Please try this page instead: https://sendgrid.com/docs/for-developers/sending-email/automating-subusers/#how-to-add-a-subuser-via-the-sendgrid-api-and-curl

**Comment by astuteape** [comment]
This page should now redirect to accurate documentation here: https://www.twilio.com/docs/sendgrid/api/v2/customer_subuser_api/subusers
