### ISSUE TITLE
Sending a message using the php loop ends up with only 70 to 74 emails. Finally, the error is 500. What happened?

### ISSUE THREAD

**Issue by burt00** [sendgrid/docs#5504]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @burt00,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
