### ISSUE TITLE
Unable to login, but logging in is REQUIRED to contact support.

### ISSUE THREAD

**Issue by haloween** [sendgrid/docs#5506]
## Expected content
I'd expect to login into support portal and send a support ticket. 

When i try to login i get a message stating: You are not authorized to access SendGrid, please contact Support.

Well unfortunately i'm unable to login. And the wheel repeats.

**Comment by Whatthefoxsays** [comment]
Hello @haloween,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team

**Comment by haloween** [comment]
I'd recommend a fix to that. I was required to add new account and then i was able to do anything. Support system login flow should be separate from app and access denied for app should not result in total lack of access. 

Your login system can mark JWT as support only and allow support access. Fix is preety simple ...

**Comment by Whatthefoxsays** [comment]
Thanks for the feedback! I'll pass that along to our support team.
