### ISSUE TITLE
Email Activity Filter is not working

### ISSUE THREAD

**Issue by Agamenonrs** [sendgrid/docs#5513]
Hi, I'm trying to add query param filters but is not working, just the limit filter is working. I did a test with curl and works perfectly. 

This is my code : 

SendGrid sg = new SendGrid("APY KEY");
Request request = new Request();
request.setMethod(Method.GET);
request.setEndpoint("messages");
request.addQueryParam("limit", "10");
request.addQueryParam("subject", "Teste-Activity");

Response response = sg.api(request);
System.out.println(response.getBody());

Thank you

**Comment by Whatthefoxsays** [comment]
Hello @Agamenonrs,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
