### ISSUE TITLE
Self-referencing doc page

### ISSUE THREAD

**Issue by cjcodes** [sendgrid/docs#5524]
On [How to send an email with Dynamic Transactional Templates](https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/), the "Additional Resources" ([source](https://github.com/sendgrid/docs/blob/ad151e238007ceb02038f05cd90b2b157ceea9e3/content/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates.md#additional-resources)) self-references, which results in the click behavior seeming broken (but really it's because the page is linking to itself, preventing a page reload).

## Expected content
It seems like the standard is to have 3 links in each "Additional Resources" section, so I'm unsure of what _should_ be here instead.

**Comment by Whatthefoxsays** [comment]
Thanks for bringing this to my attention! It *should* be linking [here](https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send#handlebars). I'll go ahead and make the change now.
