### ISSUE TITLE
New marketing: Using merge tag default values break links

### ISSUE THREAD

**Issue by brynek** [sendgrid/docs#5540]
_We've also sent a support request about this but thought it fits here as well._
In the new marketing product, merge tags have suddenly become very error-prone to use in links or styling due to the auto-replacement of `{{ merge_tag | default }}` to `{{ insert merge_tag "default=default" }}`.

Now, wrapping this in an `<a href="https://{{ merge_tag | default}}">` breaks the link due to the auto-replace inserting quotes. Which renders the entire template invalid.

Happens for both single sends and automations. Current workaround is to not use a default value at all `{{ merge_tag }}` however this is not robust at all.

What was wrong with the `[% merge_tag | default %]` syntax? This worked great.

**Comment by ben-grid** [comment]
Hey there. Thanks for the note! 

With the syntax: <a href="https://{{ insert merge_tag "default=acme.com" }}">

While in this state, your <a> tag is pretty broken, that makes sense.

Once the email is sent, and the handlebars replacement is completed, you'll end up with something like:
<a href="https://acme.com">
where acme.com comes from the default (if you don't have a value set for that recipient. Which would be valid, right?

I must be missing something in the description, as I'm sure you realize this. Could you help me understand what I am missing? Thanks!

**Comment by brynek** [comment]
@ben-grid What you are describing, leading to `<a href="https://acme.com">` after substitution is the expected behavior.

However this does not happen. As the handlebars themselves include quotes, the template parser complains that a link containing a handlebar is invalid, which renders the entire template invalid. This makes it impossible to send the e-mail, and the handlebar substitution is never done.

An example, where our merge field is Short_school_link
![image](https://user-images.githubusercontent.com/35373675/65123780-48e92f80-d9f4-11e9-88ed-d931aeea4289.png)

As you see in this picture, the first quote in the handlebar is interpreted as the closing quote of the href, which means that the link ends up as `<a href="https://{{ insert Short_school_link">`, while the link block then gets a `default="google.com }}"` as well.

If you did not auto-substitute the {{ Short_school_link | google.com }} for {{ insert Short_school_link "default=google.com" }} this would probably work as intended, as the former contains no quotes. However we have no control over this auto-substitution and it happens every time we input a merge field with default values in a New Marketing email.

**Comment by ben-grid** [comment]
Ohhhh, gosh. Yeah, this is all messed up. I see what you are saying now. 

I'm gonna get my team working on this fix ASAP this morning.

Thanks for bringing this up!!

**Comment by brynek** [comment]
Awesome, thanks for prompt responses! Looks like you fixed it already?

Btw when setting this up, we encountered an error where an automation template got stuck in invalid mode, even when we cleared the erroneous links and saved it. Upon leaving the designer and re-entering, the template had not been saved.
As this happened to the very first e-mail in our automation we were forced to create an entirely new automation as a workaround. Quite tedious.
Not sure if it's possible to replicate this bug by invalidating the template another way, but thought you should know.

**Comment by ben-grid** [comment]
We haven't fixed it yet or at least we think we haven't :-) but the team is actively working on it now. 

With that issue where it still won't save even after you delete the module, that's because the breaking change is also in the plain text (because we automatically convert HTML to plain text by default) you should be able to get around that by turning off the auto generate plain text, or just empty the plain text and let it regenerate and that should fix the message in automation, if you run into that again.

**Comment by brynek** [comment]
Okay, nice. We got it to work by avoiding default values, so it's on us to make sure all contacts have their custom fields in place for now ;-)
I.e. our merge tags are simply {{ Short_School_Link }} (remember the spaces before/after brackets). If anyone else drops by this thread in search of a temporary solution.

Thanks for the workaround with the template issue, will keep that in mind. Have a great one!

**Comment by ben-grid** [comment]
Just to update here, we got the issue fixed where the editor was breaking when using the default syntax for substitution values within the href= of an <a> tag. Thanks again for reporting this @brynek !

**Comment by brynek** [comment]
Closing this
