### ISSUE TITLE
Suppressions

### ISSUE THREAD

**Issue by bradley-fleming** [sendgrid/docs#5549]
The documentation inaccurately states that the create suppression endpoint expects URI params, when in reality it expects the same json payload described in the "response" section.

![image](https://user-images.githubusercontent.com/12700649/65275993-b58b2980-dadb-11e9-9d9b-8f8c4faaa8f9.png)

https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/suppressions.html

**Comment by Whatthefoxsays** [comment]
Hi @bradley-fleming, 

Thanks for bringing this to my attention. The page you're looking at is an old, soon-to-be-deprecated version of our API documentation. Please use this version going forward: https://sendgrid.api-docs.io/v3.0/suppressions-unsubscribe-groups/create-a-new-suppression-group

**Comment by bradley-fleming** [comment]
Thanks.
