### ISSUE TITLE
Undo unsubscribe action by accident

### ISSUE THREAD

**Issue by jdnichollsc** [sendgrid/docs#5568]
Hello guys,
This makes me very frustrated, it turns out that I opened an unsubscribe link by mistake, and there is nothing in the documentation of how I can undo this action, to reverse it. This made me think that the documentation is currently very optimistic as in Deepwater Horizon, so please keep this in mind.

## Expected content
```
Unsubscribe successful
Your email has been successfully unsubscribed from this list!
If you'd like to subscribe again and start receiving these emails click here.
```

## Actual content
```
Unsubscribe successful
Your email has been successfully unsubscribed from this list!
```

**Link to page**: https://u89128.ct.sendgrid.net/wf/unsubscribe?upn=....

Thanks in advance,
Juan

**Comment by kylearoberts** [comment]
@jdnichollsc 

Thanks for you feedback. We actually offer a subscription preferences option, but the sender has to put it in their email for you to be able to use it. It looks like in this case the sender was using our old method of unsubscribing.

Sorry for the trouble this has caused and hopefully they will use the new method moving forward.
