### ISSUE TITLE
Legacy marketing API not noted as legacy

### ISSUE THREAD

**Issue by ZenPylon** [sendgrid/docs#5573]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html

Hi there!  I think it'd be helpful if the document listed above mentioned that this API is a legacy API.  It's not accessible to newer accounts, and it will return a `403` when queried.  The correct endpoint is now:

`PUT /marketing/contacts`

Thanks, and please let me know if you need clarification.

**Comment by Whatthefoxsays** [comment]
Please use this API reference in the future: 

https://sendgrid.com/docs/api-reference/

We are working on deprecating any pages with API_Reference in them, so unless you're using the V2 API, please use the link above. Thank you!

**Comment by ZenPylon** [comment]
Thanks for linking to the new API docs.  I only knew about the new API docs because I submitted a support request through the SendGrid dashboard.  If the timeline for deprecating the legacy API pages is longer than a week or two, this really needs to be documented.
