### ISSUE TITLE
Removing Tip from 2-FA page

### ISSUE THREAD

**Issue by Whatthefoxsays** [sendgrid/docs#5589]
Remove this text from the following page:

You can create multiple configurations of Two-Factor Authentication, allowing you to use more than one mobile device to authenticate when logging into your account.

https://sendgrid.com/docs/ui/account-and-settings/two-factor-authentication/

This information is no longer accurate.

**Comment by SoldierCorp** [comment]
Hi, I'll take this one.

**Comment by oleksii-s** [comment]
@Whatthefoxsays hi,
Is there anything I can help with in scope of hacktoberfest tasks?

**Comment by Whatthefoxsays** [comment]
@SoldierCorp If you're still up for it, go ahead and take this one. The PR by the other contributor wasn't completed correctly and they haven't returned to sign the CLA.  Thanks!

**Comment by SoldierCorp** [comment]
Sure, assign it to me please.
