### ISSUE TITLE
Dashes in Hyphenated names

### ISSUE THREAD

**Issue by kzutter** [sendgrid/docs#5593]
## Expected content
Many of our clients have hyphenated last names "John Connor-Doe"
Your docs say text fields should not have dashes

## Actual content
Numbers and Text
Format your text fields so that there are no strings of numbers that appear like phone numbers, zip codes, and so on. **They should not contain punctuation characters like a dash,** underscore, parenthesis, or multiple dots

**Link to page**: https://sendgrid.com/docs/ui/managing-contacts/formatting-a-csv/#general-formatting-rules

**Comment by Whatthefoxsays** [comment]
Hello @kzutter,

Thanks so much for your feedback! I've forwarded this issue on to our Product team so they can address this with future releases.

Twilio SendGrid Docs Team
