### ISSUE TITLE
want to refund

### ISSUE THREAD

**Issue by ehashash** [sendgrid/docs#5601]
pls you closed my account after 2 days 
i want to refund my money 
i created over 6 ticket and no response for now 
my email sharkawy.man2017@gmail.com

**Comment by Whatthefoxsays** [comment]
Hello @ehashash

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
