### ISSUE TITLE
Expected CNAME for "s1._domainkey.xxxxx.com" to match "s1.domainkey.xxxxxxx.sendgrid.net".

### ISSUE THREAD

**Issue by RedKickify** [sendgrid/docs#5617]
## Expected content
I get this error when trying to validate DNS:

Expected CNAME for "s1._domainkey.xxxxx.com" to match "s1.domainkey.xxxxxxx.sendgrid.net".

If I look up the exact host on https://www.whatsmydns.net/, I recieve the exact CNAME value which the error is expecting.

Can somebody please help me?

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @RedKickify

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
