### ISSUE TITLE
Duplicate documentation; one is incomplete

### ISSUE THREAD

**Issue by adelespinasse** [sendgrid/docs#5627]
I found [this documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Whitelabel/domains.html#Create-a-Domain-POST) and assumed it was definitive. Based on that, I believed the "Create a Domain [POST]" API call did not support custom DKIM selectors, but I asked about that on support.sendgrid.com. The answer was that I should look at [this documentation](https://sendgrid.api-docs.io/v3.0/domain-authentication/authenticate-a-domain), which lists an additional `custom_dkim_selector`.

So it seems like the documentation on sendgrid.api-docs.io is more complete and up to date than the documentation on sendgrid.com/docs, which is what I found and bookmarked as a reference. I think sendgrid.com/docs should probably forward to sendgrid.api-docs.io instead of continuing to host misleading documentation.

**Comment by Whatthefoxsays** [comment]
@adelespinasse 

Thanks for the feedback! We are actively working on deprecating the documentation you mentioned as out of date and a redirect will be in place soon. Thank you for your patience as we clear up this major source of customer (and writer) pain. 

Twilio SendGrid Docs Team
