### ISSUE TITLE
Integrating with the SMTP API

### ISSUE THREAD

**Issue by ole-kaas-coop** [sendgrid/docs#5634]
https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html

Currently:
`3. Set your username to apikey.
`
Suggestion:
`3. Set your username to "apikey".  (Everyone’s username is "apikey")`

The video here didn't show how to obtain and encode login and password:
https://sendgrid.com/docs/API_Reference/SMTP_API/getting_started_smtp.html

Further down same page I found this, which kind of saved my day:
`Input the API username encoded in Base64. Everyone’s username is apikey, which is YXBpa2V5 in Base64. `

**Comment by Whatthefoxsays** [comment]
Hello @ole-kaas-coop 

Thanks for the feedack! I apologize that you've stumbled on one of our pages that is soon to be deprecated. For future reference, please use the following page: https://sendgrid.com/docs/for-developers/sending-email/getting-started-smtp/

For any V3 API needs, please see this set of documentation: https://sendgrid.com/docs/api-reference/

We're hoping to have proper redirects in place very soon. Thank you for your patience!

The Twilio SendGrid Docs Team
