### ISSUE TITLE
The Web API link at the end of this page results in a 404

### ISSUE THREAD

**Issue by gregveres** [sendgrid/docs#5649]
The last link in the last paragraph says it will take me to the Web API document for sending attachments, but it doesn't. It results in a 404 page
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html 

## Actual content

**Link to page**: https://sendgrid.com/docs/ui/sending-email/attachments-with-digioh/

**Comment by Whatthefoxsays** [comment]
Hi @gregveres, 

Please use this API reference going forward: https://sendgrid.com/docs/api-reference/
