### ISSUE TITLE
Move Templates to different environments

### ISSUE THREAD

**Issue by svgharmode05** [sendgrid/docs#5655]
Hi Team,
I am working on one of the project where we created some templates in one lower environment and now would like to move/copy those templates to upper environments through any automation script. we have separate accounts for different environments.

Thanks,
Sanjeev

**Comment by Whatthefoxsays** [comment]
Hello @svgharmode05

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

The Twilio SendGrid Docs Team
