### ISSUE TITLE
Creating transactional templates with API v3

### ISSUE THREAD

**Issue by bryan-kramer** [sendgrid/docs#5668]
Running `POST https://api.sendgrid.com/v3/templates` creates a legacy template, 
not a transactional template.

The top of the page indicates that the topic is transactional templates.

How does one convince the API to create a transactional template?

https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/templates.html

**Comment by Whatthefoxsays** [comment]
Hi there. Sorry for the confusion. The page you listed below is soon to be deprecated. Please use this API reference going forward. 

https://sendgrid.api-docs.io/v3.0/transactional-templates

Thank you!

The Twilio SendGrid Docs team
