### ISSUE TITLE
smtp send

### ISSUE THREAD

**Issue by izofis** [sendgrid/docs#5672]
Hello,
i am send smtp protocol send mail but i am not setup smtp.
Step 1 
Integrate using our Web API or SMTP relay (Start) Click
Step 2
SMTP Relay ( Chosee )
Step 3
Create an API key
Step 4
i setup my outlook smtp server, port, user, password (api key) all okey Next verify and not finish and stystem massage error try again. Pls help me

Best rergard Ozturk

**Comment by astuteape** [comment]
Hello @izofis 

We're sorry you're having trouble setting up SMTP. If the following documentation isn't helpful, please try reaching out to support by logging into https://support.sendgrid.com.

* https://sendgrid.com/docs/for-developers/sending-email/getting-started-smtp/#sending-a-test-smtp-email-with-telnet
* https://sendgrid.com/docs/for-developers/sending-email/integrating-with-the-smtp-api/

Best,
Twilio SendGrid Docs Team
