### ISSUE TITLE
I already paid invoice no. INV05109295 for December since 2nd Dec 2019 but now can't login and my email alert service is stop. Why? Support me URGENTLY.

### ISSUE THREAD

**Issue by kyawsoemin2019** [sendgrid/docs#5682]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hi @kyawsoemin2019 

Can you please provide your username? I'll forward this on to Support for you, but for them to serve you faster, they need that information. 

Thank you,
Twilio SendGrid Docs team

**Comment by Whatthefoxsays** [comment]
I've forwarded your info on to support, but please try to create a ticket by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
