### ISSUE TITLE
Locate all Azure components using Sendgrid

### ISSUE THREAD

**Issue by ketaanhshah** [sendgrid/docs#5686]
Hi ALl,
We use SendGrid's sendmail module in lots of logic apps and other components in our Azure subscription. I wanted to know if their is an easy way to locate all the Azure components using SENDGRID we have multiple resource groups, multiple apps etc and hence doing it manually is going to be cumbersome any other easy way to locate all components (powershell script or any other way) ?

Thank you

**Comment by Whatthefoxsays** [comment]
Hello @ketaanhshah,

Thanks for taking the time to reach out! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
