### ISSUE TITLE
404 on link

### ISSUE THREAD

**Issue by realfink** [sendgrid/docs#5690]
## Expected content
I expect the link to work

## Actual content
Link returns 404

**Link to page**:
https://sendgrid.com/docs/ui/account-and-settings/inbound-parse/#using-the-api

**Comment by Whatthefoxsays** [comment]
Hi @realfink, 

Please use [this link](https://sendgrid.api-docs.io/v3.0/settings-inbound-parse/) going forward. I will fix the link on the page in question. Thank you!
