### ISSUE TITLE
Issue Summar You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by leoraymond** [sendgrid/docs#5691]
Issue Summar
Hello, I'm sorry when I log in my account it occurs "You are not authorized to access SendGrid, please contact Support.", and my username and password are all right.
my username :leoraymond
email:616716@gmail.com
Please help me!

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @leoraymond,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
