### ISSUE TITLE
Allow download of directory folders as .PDF for offline docs viewing.

### ISSUE THREAD

**Issue by Zaftula** [sendgrid/docs#57]
Allow folders such as 'API Reference' and their child contents to be downloaded locally as .pdf files for offline reference.

**Comment by thinkingserious** [comment]
Hello @Zaftula,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
