### ISSUE TITLE
Can't create a SendGrid account in Azure

### ISSUE THREAD

**Issue by JohanLarsLang** [sendgrid/docs#5700]
![SendGrid](https://user-images.githubusercontent.com/32544465/71016665-c86ec380-20f5-11ea-8f8b-6a7c30f40f96.JPG)
Hi,

Why can't I create a SendGrid account in Azure?

See attached file.

Best regards
Johan Lång

**Comment by Whatthefoxsays** [comment]
Hello @JohanLarsLang,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
