### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by jimmyranson229** [sendgrid/docs#5712]
Hello There,

My account id is 
Jimmy Ranson
jimmyranson229@gmail.com
I am Unable to send email. I copied all the out going settings correctly but unable to send emails please help

Thanks

**Comment by Whatthefoxsays** [comment]
Hello @jimmyranson229, 

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
