### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by Umer-klab** [sendgrid/docs#5721]
Hello !!
I was facing problem while account verification when i try to send verification email its not working and now i not able to even login to my account.
EMAIL: umer@muneektech.com

**Comment by Whatthefoxsays** [comment]
Hello @Umer-klab,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

SendGrid Docs Team
