### ISSUE TITLE
Internal server error - domain authentication 

### ISSUE THREAD

**Issue by levechad** [sendgrid/docs#5725]
Dear sendgrid Team,
my username in sendgrid is lev.tsuella,
I'm to authenticate my domain axe.world but I'm getting an "internal server error" message.
I need help ASAP.
Thanks,
Lev

**Comment by Whatthefoxsays** [comment]
Hello @levechad,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
