### ISSUE TITLE
Hello, I have a troubleshooting to sign in my account. Please check and give me a feedback 

### ISSUE THREAD

**Issue by abdoulciss** [sendgrid/docs#5726]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @abdoulciss,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
