### ISSUE TITLE
Attach Image with SendGrid Mail

### ISSUE THREAD

**Issue by lesafir** [sendgrid/docs#5738]
Hello everybody

I try to add my logo to my mail sent with sendgrid. But the image doesnt appear.

Something wrong on my code ? Please help :(

here is my code :

`  private async Task configSendGridasync(IdentityMessage message)
        {
            var apiKey = ConfigurationManager.AppSettings["BPTEST"].ToString();

            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("no-reply@test.com", "test");
            var subject = message.Subject;
         
            var to = new EmailAddress("test@hotmail.com", "test");
            var plainTextContent = message.Body;
            var htmlContent = message.Body;
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);

          

            msg.AddAttachment(new SendGrid.Helpers.Mail.Attachment()
            {
                Content = "BwdW",
                ContentId = "qrTicket",
                Disposition = "inline",
                Filename ="logo.png",
                Type = "image/png"
               
            });

            msg.HtmlContent = htmlContent + "<img src=\"cid:qrTicket\"></img>";

            var response = await client.SendEmailAsync(msg);

        }`

**Comment by Whatthefoxsays** [comment]
Hello @lesafir,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
