### ISSUE TITLE
Broken link - bounces

### ISSUE THREAD

**Issue by alexbainbridge** [sendgrid/docs#5748]
## Expected content
Base link goes to an error 404 page
"You can also retrieve and edit your list of bounces through our Web API"

## Actual content

https://github.com/sendgrid/docs/blob/develop/content/docs/glossary/bounces.md

**Comment by salil-naik** [comment]
Hi. It's working fine. Please check the following link. 
https://sendgrid.com/docs/glossary/bounces/

When you click on "You can also '**retrieve and edit your list of bounces**' through our Web API.", 
you will be directed to 
https://sendgrid.com/docs/API_Reference/Web_API/bounces.html
