### ISSUE TITLE
how to get message ID from a x-messageid

### ISSUE THREAD

**Issue by munnyraht** [sendgrid/docs#5765]
i have been trying to get the message ID for a mail i sent with sendgrid web api , i only got x-message id from the response, i need the message ID to get analytics for the mail.
Awaiting response.
thank you.

**Comment by astuteape** [comment]
Hello @munnyraht  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
SendGrid Docs Team
