### ISSUE TITLE
I can not access to sendgrid dashboard from GCP

### ISSUE THREAD

**Issue by DanielOsuna** [sendgrid/docs#5766]
I'm trying to access your sendgrid dashboard since Google Cloud Platform:
![image](https://user-images.githubusercontent.com/44901403/73086815-170b3c80-3eb0-11ea-9c31-2d4e25a1cbb4.png)
, and I'm receiving the folllowing error
![image](https://user-images.githubusercontent.com/44901403/73086446-6bfa8300-3eaf-11ea-8812-6ebf084f4af9.png)
Translation ( mi chrome is in spanish) of the error is:
```
The page doesn't work.
api.google-production.sendgrid.net can not process this request at this moment
Error 500
```
Could you please check what is happening ?

Thanks in advance

**Comment by Whatthefoxsays** [comment]
Hello @DanielOsuna,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
