### ISSUE TITLE
Inaccurate MIME type settings guide

### ISSUE THREAD

**Issue by kchau** [sendgrid/docs#5768]
## Expected content
Currently guides you towards Settings -> Mail Settings -> Plain Content. But this section doesn't seem to exist anymore on the settings page.

## Actual content
Updated settings information on how to set MIME type?

**Link to page**: https://sendgrid.com/docs/for-developers/sending-email/send-mime-messages-with-sendgrid/#sending-mime-mail

**Comment by astuteape** [comment]
Closing: Issue fixed by PR #5771
