### ISSUE TITLE
Marketing Campaigns Support needed urgently

### ISSUE THREAD

**Issue by roxybaroxy** [sendgrid/docs#5773]
Hello! 

I have an issue with sendgrid. I am a marketer and I use Sendgrid for the first time so I need so help from you with setting up the marketing campaigns. 

Can you please let me know the following: 

How can I send an automation to a particular segment? 
How can I track link clicks from emails and based on that set rules and start other automations? 
How can I get more data about the users? When they sign up from the website I just get the name and email and nothing else? 
How can I create rules for contacts? For example, if they join one list to be automatically removed from the other one? 

Can this all be set by me or does this needs to be coordinated with a developer? Or Sendgrid’s support can set this up? 

I am looking forward to your reply. 

Best regards, 
Georgia Valant

**Comment by Whatthefoxsays** [comment]
Hello @roxybaroxy,

We're sorry you're having issues! I recommend starting with our documentation, but if you're still stuck after looking through the [Knowledge Center](https://sendgrid.com/docs/),  please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
