### ISSUE TITLE
Issue on email link redirect (chrome not private intereception)

### ISSUE THREAD

**Issue by erwanriou** [sendgrid/docs#5774]
## Expected content
Redirect on the website link as defined in the template email

## Actual content
Url have been intercepted by google as "Your connection is not private" on click in the email link element. (the Link Branding DNS config have been approved and configured to a specific domain)

I suspect that the tracking link feature that rewrite all the email links to not working properly (at least in gmail + chrome Version 79.0.3945.130 (Official Build) (64-bit) and using ubuntu 18.03)

The current temporary fix is to disable the tracking link feature

**Link to page**:
expected link:
https://www.archsplace.com/login

link intercepted at this point
https://url8997.archsplace.com/wf/click?upn=tWyuM6NUj3QlRTjcCl0uK8Z20SbxiPQXLVpRlxcST-2Buq9xI2prRn6HuzL7M1-2F2TpfjvyusB6ZMN4ptu1SYBdqe1GuLPgEOPSnxHfan4hEdgJcTkMaNWdEcYBJ5OoABn1RgQzxIMDij2jqVNPprQN5FM-2FRK5oONiO2-2B8L-2BqrNt3Y-3D_eX5DPq6UdEJRKjV5Uv7lAUZlt-2FI5hEewS8L6uzGNzon7ngMiTZHOV4X-2BYlhEWsG2W1j3zAvfWa9jKiNpna9jUv3OlqSeRH7ZEWKV4brTeh-2FvJN5bQJyWFZROlFRJbP5wUq2gJZXUZuF1g5yVP6PjjPtw7yGT9Ggc7vFrNPvWFFbXDegG-2Bxgc8so7cZpISmpQGztVrvHCrt5BEI5itO0vXd3SMPmtal85eRyPLBpCHbo-3D

**Comment by astuteape** [comment]
Hello @erwanriou 

We're sorry you're having this issue! You might try reading up here: https://sendgrid.com/docs/ui/analytics-and-reporting/click-tracking-ssl/

For direct help, please contact our Support team to file a ticket. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
