### ISSUE TITLE
Handlebar if eq works on template editor but fails API usage

### ISSUE THREAD

**Issue by OpTiCz27** [sendgrid/docs#5779]
**Test code is as follows:**
{{#if (eq sub_01 "1" )}}
     <p>Dear Sir</p>
{{else if (eq sub_01 "2")}}
     <p>Dear Madame</p>
{{else}}
     <p>Dear Customer</p>
{{/if}}

**Test data is as follows:**
{
	"sub_01": "2"
}

When testing via web template editor, change sub_01 from 1, 2, 3 etc results in the expected output in the preview pane. However, when sending through the API, the else condition is always caught. I can confirm the sub_01 field is being passed through correctly as I can return it in the email itself, the if/then logic just never evaluates properly.

**Comment by kylearoberts** [comment]
@OpTiCz27 

Hello,

Looks like you are trying to use a helper we do not support. You can look [here](https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/) at our docs to see what we currently support.

For what you are looking to do I give a current example [here](https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/#basic-if-else-else-if).

If you have further issues or questions please let us know.

**Comment by OpTiCz27** [comment]
Thanks. So it looks like the helper is implemented via template builder but not through the API.
I guess we'll have to transform our json so that each value becomes a key with a value of true.
So rather than something like "gender": "male" or "gender": "female", we'd have to nest it as something like "gender": { "male": true } and say {{#if gender.male}}.

That should work, it'll just become a bit ugly to manage when there are many possible values. Thank you for the input @kylearoberts

**Comment by astuteape** [comment]
This issue appears to be resolved and is now being closed. If you have more questions or feel the issue has been closed in error, please open another issue. If you need direct support, please contact our Support team and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
