### ISSUE TITLE
while creating the account it says my account is flagged as high security risk, and you will not be able to send mail.

### ISSUE THREAD

**Issue by sahil-github29** [sendgrid/docs#5803]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @sahil-github29, 

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team

**Comment by jobayersajal1** [comment]
it seems confusing! I face same issue upon opening new account.I can not even open an account.then the system redirects me to login and contact support!!

**Comment by codebycody** [comment]
If you run across this issue like did, just try submitting again but use a gmail account. Because it seems since I wanted to use my protonmail account I was flagged as a risk.

**Comment by KelvinGits** [comment]
> If you run across this issue like I did, just try submitting again but use a gmail account. Because it seems since I wanted to use my protonmail account I was flagged as a risk.

I submitted my request using a Gmail account and got the same response. It's very frustrating.

**Comment by dmk1111** [comment]
> I submitted my request using a Gmail account and got the same response. It's very frustrating.

Same here... very frustrating experience

**Comment by Preciousomonze** [comment]
Also experienced the same issue today, any known solution to this? 😭

**Comment by KelvinGits** [comment]
Yeah, you may need to submit some more info to their support team.
Fortunately, they are quite responsive. They can sort it out in a day if
you provide all the required info.

**Comment by weefunker** [comment]
You need to stop treating potential customers like criminals. Toddler behavior on sign-up is not a good first impression.

**Comment by varsityhq** [comment]
I also had the same issue and i send them many emails  and they ignored me, they created ticket #6394289 and this guy Alex C from sendgrid only answered a few emails then started ignoring me a lot, and i kept on asking why i was being ignored and still nothing, i'm really disappointed by this service !!!! and even now i haven't received anything for an account that i opened last week and day by day i keep trying to login but nothing !!

**Comment by vijayvishwam** [comment]
Same issue, unable to register for Send Grid Email services even after multiple attempts. Hence planning to switch to other email providers.

**Comment by fintechee** [comment]
+1

**Comment by resqiar** [comment]
Same, urgently needed the service but got the issue which is kinda sad
