### ISSUE TITLE
Heroku App using Sendgrid Addon error 535 account disabled

### ISSUE THREAD

**Issue by zcody95** [sendgrid/docs#5809]
Hello,

I have an app that I have deployed on Heroku. Today through the console I added the Sendgrid addon to my Heroku app. When I tried to add it, a message displayed saying I needed to activate my account. So I went in to Heroku and added a credit card which I believe fully activates your account on Heroku. That worked and let me get the Sendgrid addon into my app, but when i tried sending emails I started getting the error "Net::SMTPAuthenticationError (535 Authentication failed: account disabled". This led me to start digging around on how to fix this and I saw that removing the addon and adding it back might work since I had just activated my Heroku account. When I tried this I received a message in the console that: "An error was encountered when contacting the add-on partner to create sendgrid:starter: Error Provisioning User - User status - banned" 

So I then went on to the Sendgrid website to try and login to submit a ticket but I cannot login using the credentials that were created by my Heroku app. Please help me get my account back online so I can link it up to Heroku and start sending emails!

Thanks.

**Comment by astuteape** [comment]
Hello @zcody95 ,

After digging into this a bit, it sounds like Heroku support may be a better first contact for the issue. It may be a flag that Heroku put in place after the deletion of the add-on initially. I was able to replicate the error on a Heroku setup myself by adding the add-on, deleting it, and trying to add it again. I think this is why you aren't able to login to SendGrid (Heroku couldn't successfully provision an account the second time, so there's no account to authenticate).

If Heroku support doesn't have the solution, I can connect you with SendGrid support for further troubleshooting. I don't want you to get bounced between support orgs; I'm just thinking Heroku may be better suited to fixing the add-on given the error and behavior I was able to replicate.

**Comment by astuteape** [comment]
Hi @zcody95, were you able to get your setup working with Heroku?

**Comment by zcody95** [comment]
Hi Wade,

I appreciate the help and the check in. After spending time trying to get Sendgrid to work on Heroku with no avail I decided to try a different route and was able to get gmail smtp working and will be using that now.

Thanks again.

**Comment by astuteape** [comment]
I'm glad you were able to get things sorted. If you decide to give SendGrid another shot, I hope we can be helpful.
