### ISSUE TITLE
Webhook Retry logic

### ISSUE THREAD

**Issue by ronakvpanchal** [sendgrid/docs#5811]
## Expected content
Currently I can't find any retry logic with Webhook POST url for event tracking. Does send grid support any retry logic if the POST url is down, or when it returns a 4xx and 5xx api response?

There is no documentation around this.

## Actual content
Send Grid event tracking should have a retry logic. 

**Link to page**:

**Comment by astuteape** [comment]
Hi @ronakvpanchal, thanks for making note of this. We do support retry logic, and I'll be sure to add that to the API reference. Currently it's only mentioned here: https://sendgrid.com/docs/for-developers/tracking-events/troubleshooting/

I know that was probably a little tricky to find if you were looking on our API reference. I've added this to our backlog and will update soon.
