### ISSUE TITLE
Your account is temporarily under review. Please contact Support to regain access.

### ISSUE THREAD

**Issue by sonuyos** [sendgrid/docs#5814]
I have opened a ticket for the above issue, and no one is replying, its over 10hours.

Ticket - 3545898

**Comment by astuteape** [comment]
Hello @sonuyos I'm sorry for the issue with your account. Have you received help from support at this time?

**Comment by saqikhan** [comment]
I also have open 3 tickets from 2 days and still i didnt recieve any update regarding the review.

Ticket: 4744491

**Comment by MudassirTufail** [comment]
I am hoping that some one can help me. I have the same issue, it's been 7 days and no response on my ticket yet. Here is my ticket Request #4720224.

Thank You

**Comment by redamsy** [comment]
plz help i have the same issue upon signup

**Comment by rpb99** [comment]
long time i don't use it, and now got same issue

**Comment by jattwood** [comment]
Its been over 24 hours now since I submitted ticket #4980120, all my emails are stuck in "Processing", my account is under review, yet I never received any email from SendGrid indicating that my account is under review, so I have no information as to why my account would be under review! Frustrating!

**Comment by WayneUong** [comment]
Same here. Account goes under review without any notice. Basically halted our entire business.

**Comment by Mpulse1** [comment]
My account is under review,  unusual volumes. None of the messages were delivered because they were suspicious but here I am looking at a massive bill with no messages delivered and an account that doesn't work what's the name of this game?

**Comment by WayneUong** [comment]
Apparently, this is an ongoing problem with Sendgrid terrible customer support: https://www.trustpilot.com/review/sendgrid.com?languages=en
We're looking into Sendinblue now. Much cheaper with more functionalities and better support.

**Comment by besteban1989** [comment]
**I can tell, is the worst support ever !!** No replies in weeks, even to create a ticket it's a nightmare! 
Each account created go "under review". 
I tried upgrading an account some weeks ago, I though maybe payment it's the issue, it didn't let me! it showed  "sendgird verifying your account". 
I really recommend to move to other STMP relay like Mailgun, that's what I'm doing today, I'm working really late today to change the code to use the Mailgun API instead. 

My latest Ticket ID: 5132209 

I'm not hoping any resolution this time, I'm moving to other provider.

**Comment by Arunpaul2020** [comment]
I am getting following message, "Your account is temporarily under review. Please contact Support to regain access. ". My emails are showing as Processed or Blocked, none getting Delivered. I raised 3 tickets already but never got any response from support team for since Nov 4th.

**Comment by aryan29** [comment]
Why is this closed I am facing same issue

**Comment by wahjay** [comment]
I just created an account and my account is instantly under review. I haven't even used the service.

**Comment by stayce** [comment]
Same issue. Account was working and then they changed it to under review. They keep marking my tickets as resolved. I'm moving to mailgun asap. I've wasted 2 days with sendgrid support.

**Comment by vswb** [comment]
Same issue here, my ticket number https://support.sendgrid.com/hc/en-us/requests/6505667
Feeling that SendGrid is very slow to reply to client
