### ISSUE TITLE
Some segmenting fields are not documented

### ISSUE THREAD

**Issue by Jericho** [sendgrid/docs#5820]
The recently published segmentation query language reference contains a list of 10 fields that we can use for segmentation purposes such as `email`, `first_name`, `city`, `postal_code`, etc. However, if you scroll the page down a little bit you will see a few sample queries that use fields that were not listed. Here is an example of one such sample query:
```
(event_source = 'mail' AND event_type = 'delivered' AND event_timestamp >= (NOW() - interval 10 day))
```

As you can see, this sample references the `event_source` and the `event_type` fields which are not documented. This leads me to conclude that there are probably other fields that are available for segmenting purposes but not documented.

Would it be possible to get an exhaustive list of all the fields that are available when segmenting our contacts?

## Expected content
The full list of fields that we can use to segment contacts.

## Actual content
A partial list of 10 fields (probably these are the most commonly used, but certainly not an exhaustive list).

**Link to page**:
https://sendgrid.com/docs/for-developers/sending-email/segmentation-query-language/#fields

**Comment by astuteape** [comment]
Hi @Jericho 
Thank you for bringing this to our attention. We will update the docs to reflect an accurate list of fields soon.

**Comment by astuteape** [comment]
Hi @Jericho thank you for your patience. We know you submitted this some time ago. We are about to push a PR up with a comprehensive list of the available fields. Thank you for bringing it to our attention.
