### ISSUE TITLE
Error Provisioning User -  !    User status - banned after re-adding to Heroku

### ISSUE THREAD

**Issue by Trillo7** [sendgrid/docs#5821]
So I added the SendGrid addon on my app idk my username nor password were Item could not be created: An error was encountered when contacting the add-on partner to create sendgrid:starter: Error Provisioning User - User status - banned

**Comment by astuteape** [comment]
Hello @Trillo7  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
SendGrid Docs Team
