### ISSUE TITLE
The BCC setting deprecated (Still BCC's for every email)

### ISSUE THREAD

**Issue by DudeMason** [sendgrid/docs#5828]
## Expected content
Ability to deactivate BCC

## Actual content
BCC is gone (deprecated) but is still active. There is no option to deactivate it. (At least that I can find.)
**Link to page**:

**Comment by astuteape** [comment]
Hi @DudeMason the UI changes should be in effect now. The API changes will be released 3/9, which is why you're still seeing BCC on the API side. I hope that's helpful.
