### ISSUE TITLE
I cannot Log in My Send Grid Account So I cannot put In a Support Ticket!!! This is a real catch 22!!!

### ISSUE THREAD

**Issue by BitSensei** [sendgrid/docs#5834]
## Actual content

**Link to page**:

**Comment by BitSensei** [comment]
I know you don't want support issues here but I have no choice since the system will not let me log in to put a support ticket! Very frustrating and annoying! I am a paid member!

**Comment by astuteape** [comment]
Hello @BitSensei 

You can submit a ticket without logging in by going to sendgrid.com, scrolling down and choosing "contact support." Then, choose "trouble logging in". You can also submit a password reset request using your username (not your email) in case that's the trouble. I hope this connects you with support, but let me know if you need more help.

**Comment by BitSensei** [comment]
Thanks Wade for your help,
I don't know if you can help me cancel my account with Sendgrid.
I cannot access my account or support.
I don't want to continue paying for this xxxx!!
I hope you can help,
Thanks,
Edwin Cabrera
my email is ed@edwincabrera.com




Edwin Cabrera

CEO | Online Marketing Consultants

mobile: 571-358-8518
site: edwincabrera.com
email: ed@edwincabrera.com
skype: edcabrera7
address: Manassas, Va
<https://facebook.com/edwincabrera27>
