### ISSUE TITLE
Image links broken on DMARC docs page

### ISSUE THREAD

**Issue by datacarl** [sendgrid/docs#5836]
## Expected content
Step 2 and 3 should show images

## Actual content
Step 2 and 3 have images that are not loaded (403)

**Link to page**:
https://sendgrid.com/docs/glossary/dmarc/

**Comment by astuteape** [comment]
Thank you for reporting the issue. I'm going to close this because it appears to be the same issue reported here: #5823

We have it added to our docs backlog and will fix it soon.
