### ISSUE TITLE
Bad links in doc Integrating with the SMTP API

### ISSUE THREAD

**Issue by mallika-b** [sendgrid/docs#5838]
On https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html
hovering over 
TLS connections
or 
SSL connections
shows 
https://sendgrid.com/docs/Classroom/Basics/Email_Infrastructure/ssl_vs_tls.html
but where clicking actually takes you is
https://sendgrid.com/docs/ui/sending-email/deliverability/
which doesn't even mention tls or ssl!

Wouldn't 
https://sendgrid.com/docs/ui/sending-email/ssl-vs-tls/
be a better choice?

**Comment by astuteape** [comment]
Thank you for bringing this to our attention. I have added the issue to our backlog and will update the links as soon as possible.
