### ISSUE TITLE
Can't get into support 

### ISSUE THREAD

**Issue by desa999** [sendgrid/docs#5839]
## Actual content

**Link to page**:

**Comment by desa999** [comment]
Sendgrid has billed me and I have paid. But when I try to login in I get message:
You are not authorized to access sendgrid
![Sendgrid_Main_Screen](https://user-images.githubusercontent.com/44013843/75949457-6eaeb600-5efa-11ea-8d10-706040c8d36a.png)
Program won't allow me to get in to contact support

**Comment by astuteape** [comment]
Hello @desa999 

You can submit a ticket without logging in by going to sendgrid.com, scrolling down and choosing "contact support." Then, choose "trouble logging in". I hope this connects you with support, but let me know if you need more help.
