### ISSUE TITLE
Getting a 404 for a link in the docs in 'Statistics Overview'

### ISSUE THREAD

**Issue by pavan-kalyan** [sendgrid/docs#5845]
This is about the link 'API Statistics Overview' in [Statistics Overview](https://sendgrid.com/docs/ui/analytics-and-reporting/stats-overview/)
## Expected content
link to API statistics overview.

## Actual content
404

**Link to page**: Statistics Overview](https://sendgrid.com/docs/ui/analytics-and-reporting/stats-overview/

**Comment by astuteape** [comment]
Hi @pavan-kalyan ,

I'm sorry you struggled with this issue, but we really appreciate the feedback! We've added this to our internal docs backlog and will hopefully get it resolved shortly.

Twilio SendGrid Docs Team
