### ISSUE TITLE
You are not authorized to access SendGrid, Please contact support  help me  this happend to me while i am sign up then login in again 

### ISSUE THREAD

**Issue by avinashz14** [sendgrid/docs#5849]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @avinashz14 ,
We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!
SendGrid Docs Team
