### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by the7ololnet** [sendgrid/docs#5856]
## Expected content
Helo Dear .
My Username : the7_olol_net
i can' login to my account . when i try that i get this message : You are not authorized to access SendGrid, please contact Support.
 ) .
please explain that for me 
thank you

## Actual content

**Link to page**:

**Comment by the7ololnet** [comment]
Please contact support help me this happend to me

**Comment by astuteape** [comment]
Hello @the7ololnet ,
We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!
SendGrid Docs Team
