### ISSUE TITLE
Unique Link Clicks

### ISSUE THREAD

**Issue by sendgridhelp** [sendgrid/docs#5857]
I have contacted customer support who tell me that while you can track total link clicks in a campaign, you cannot see unique link clicks for any given link. Has anyone else found this a frustration, can offer a solution? In other email marketing packages I've used this view and metric is usually a standard for measuring success. 

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hi @sendgridhelp ,
Thank you for the feedback. We have passed it along to the product team.
Twilio SendGrid Docs Team
