### ISSUE TITLE
Inconsistent information about plan limits.

### ISSUE THREAD

**Issue by pavan-kalyan** [sendgrid/docs#5863]
Number of contacts seems to conflict with the information on the pdf provided on the pricing plan https://sendgrid.com/files/SendGrid-Pricing-Comparison.pdf
## Expected content
https://sendgrid.com/files/SendGrid-Pricing-Comparison.pdf
email: 1mil+/month
contacts: 200k+
## Actual content
email: 200k+/month
contacts: 1mil +
**Link to page**: https://sendgrid.com/docs/ui/account-and-settings/billing/#limits-2

**Comment by astuteape** [comment]
Hello @pavan-kalyan ,
I'm sorry for the confusion. Is there a page where that PDF was provided or linked to?

**Comment by pavan-kalyan** [comment]
https://sendgrid.com/pricing/
In the marking pricing, when you click on 'see full feature breakdown', you get a popup with info and a link 'download pdf'

**Comment by astuteape** [comment]
Thank you for your patience. The PDF is correct, and the docs will be updated shortly.
Twilio SendGrid Docs Team
