### ISSUE TITLE
Cannot login - You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by cinnipatel** [sendgrid/docs#5874]
## Expected content
Hello There, 
I am trying to Login to SendGrid and contact support for one issue I am facing while sending emails using "Sendgrid email API" but it does not allow me to login.
On LOGIN page, after entering username, password and hitting submit, it shows error:  **You are not authorized to access SendGrid, please contact Support.**

Now, on Support page, it again asks to Login to Submit ticket. The issue is, it does not allow me to login even.

Kindly help
Thank you,
A Sendgrid customer.

## Actual content

**Link to page**:

**Comment by Imaginedigitalsignage** [comment]
Hi there. I am also experiencing the same issue. 

I am a new user - setup account yesterday but have yet to even login

Please could you advise (Account name: Imaginesignage)

![image](https://user-images.githubusercontent.com/59468482/76827485-915c9b00-6827-11ea-9845-e4da103f0669.png)

**Comment by munhon86** [comment]
I am also facing the same issue. This is frustrating.

**Comment by frodfigu** [comment]
Same problem here. And I still waiting for the contact support ticket. So frustrating.
Please I need help. All my mailing system is down, nothing works.

**Comment by astuteape** [comment]
Hello all ,
We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!
SendGrid Docs Team
