### ISSUE TITLE
Sendgrid template handlebars  unable to render the conditional  like "eq" "or" "and" operator these operators are working on sendgrid console but in email the content which is inside the conditional is blank

### ISSUE THREAD

**Issue by vishalkumar96** [sendgrid/docs#5875]
Not Working
{{#if (eq email_type "test")}}
//some statement
{{/if}}

Only these kind of statement working
{{#if email_type }}
//some statement
{{/if}}

**Comment by astuteape** [comment]
Hi @vishalkumar96,
Currently, "eq," "or," and "and" do not work in template handlebars. Only the basic conditionals shown here will work: https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/#conditional-statements

Sorry for any confusion, and I hope this is a helpful update.
SendGrid Docs Team
