### ISSUE TITLE
Inbound Parse documentation needs clarification on max attachment size

### ISSUE THREAD

**Issue by osudude** [sendgrid/docs#5876]
**Link to page**:
https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/

## Actual content
"The total message size limit, including the message itself and all attachments, is 20MB. Be aware that other mail handlers will have their own limitations, and some ISPs and companies may either dramatically limit the size and/or type of attachments, or even block them altogether."

## Expected content
I was able to send a 30mb attachment via Inbound Parse so clearly there is no 20mb limit as the documentation states. Is 20mb a recommended limit?  If so, say that.  Documentation should also state the actual attachment size hard limit imposed by Inbound Parse.

**Comment by astuteape** [comment]
Hi @osudude ,
Thank you for bringing this to our attention. We will update the doc with our current recommendations as soon as possible. We recommend a max message size of 30MB.
Twilio SendGrid Docs Team
