### ISSUE TITLE
Broken link at /v3-mail-send-faq/

### ISSUE THREAD

**Issue by asc-adean** [sendgrid/docs#5885]
## Actual content

**Link to page**: https://sendgrid.com/docs/for-developers/sending-email/v3-mail-send-faq/

Link is broken at:

For more general information about the v3 Mail Send endpoint, please visit the **v3 Mail Send Overview**. Below, you will find links to more in depth information about the endpoint.

**Comment by astuteape** [comment]
Hi @asc-adean ,
We're sorry you struggled with this issue, but we really appreciate the feedback! We've added this to our internal docs backlog and will resolve it shortly.
Twilio SendGrid Docs Team
