### ISSUE TITLE
I applied for an account today, and never received an email to verify account. This is what I get when I try to login. "You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by tunmire** [sendgrid/docs#5891]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @tunmire  ,
We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!
Twilio SendGrid Docs Team
