### ISSUE TITLE
Scheduled Cancellation

### ISSUE THREAD

**Issue by DexterWongMRM** [sendgrid/docs#5892]
Hello,

We are currently on the Pro account which will rebill our credit card on April 1st.

When cancelling our account, does it take in affect immediately, or does the services end on March 31st?

thanks 

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @DexterWongMRM ,
Cancellations take full effect on the first day of the next calendar month, at which point your account will still be usable, but will be at the Free package level. We hope this helps.
Twilio SendGrid Docs Team
