### ISSUE TITLE
cant even contact sengrid support

### ISSUE THREAD

**Issue by EMInd1** [sendgrid/docs#5901]
well i followed instructions and went to "(https://support.sendgrid.com).".
it says "Click **Login & Contact Support**, and then **Contact Support** to see your contact options.".

THERE IS NO "contact support" ... ITS JUST "join" sendgrid.

TO ADD FURTHER INSULT ...at the top of the page it says ....
"Due to a high volume of requests, live chat support is currently unavailable. You may still open a support request with us via email ticket. Thank you!"

THEN WHERES THIS SUPPORT CONTACT EMAIL??
I cant find one anywhere!
That's why I have had to post on here!

I have people emailing me who have my permission to email me & I received their email but none of their email links work.

So far Ive wasted 35 minutes trying to deal with an issue that should have taken 2 minutes AND IM STILL NO CLOSER THAN WHEN I FIRST ATTEMPTED TO CONTACT sendgrid!
======================

## Actual content

**Link to page**:

**Comment by iqbalpb01** [comment]
Facing same issue

**Comment by astuteape** [comment]
Hi @EMInd1 and @iqbalpb01 ,
We're sorry you're having this issue. You should be able to submit a support ticket here: https://support.sendgrid.com/hc/en-us. I recommend logging in first, then visiting that link. Once you select "Login & Contact Support," you should be able to scroll down and select "Contact Support." If you are unable to login, please click the "Trouble logging in?" link to submit a ticket without authenticating.
