### ISSUE TITLE
Help DNS issues - and Non profit Billing issue!

### ISSUE THREAD

**Issue by 8241973** [sendgrid/docs#5902]
Hi - Flywheel let us know 1) we have DNS being directed to you - can you let us know if we need to keep this dns on Godaddy?  2) Do we need to update the DNS? 3) We goto spam all the time - could this be an issue?  4) We are a 501c3 non profit - our billing statement does not reflect this? Can you check?  Thankyou see below for details from flywheel 

FROM FLYWHEEL for you to answer
1)	Sure, looking at the IP address associated with the new2016 A record, that is pointing to GoDaddy: https://who.is/whois-ip/ip-address/50.62.71.73 I'd recommend checking with them before removing the record
2)	Yep, the other strange A record that is associated with the IP address 167.89.7.72 is actually pointing to Sendgrid
https://who.is/whois-ip/ip-address/167.89.7.72

It is certainly a busy time! That's right, checking those strange A records (one with GoDaddy and one with Sendgrid), 

Thank you!

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @8241973  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
