### ISSUE TITLE
SendGrid v3 nodejs api does not support adding preheader text to the email using the send POST api. Is there a way to do this somehow?

### ISSUE THREAD

**Issue by ronakvpanchal** [sendgrid/docs#5915]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @ronakvpanchal  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
