### ISSUE TITLE
DNS Link 404's

### ISSUE THREAD

**Issue by bobzilladev** [sendgrid/docs#5917]
#5597  Expected content

Link to more content when clicking on "The SendGrid Email Infrastructure Guide"

## Actual content

"Quoth the Raven - 404"

https://github.com/sendgrid/docs/blob/develop/content/docs/glossary/dns.md

**Comment by astuteape** [comment]
Hi @bobzilladev ,
We're sorry you struggled with this issue, and we appreciate the feedback! We've added this to our internal docs backlog and will resolve the issue as soon as possible.
Twilio SendGrid Docs Team
