### ISSUE TITLE
Email Infrastructure guide Link is broken.

### ISSUE THREAD

**Issue by pradeep864** [sendgrid/docs#5935]
## Expected content
Email Infrastructure guide Link is broken.

**Link to page**:
https://sendgrid.com/docs/glossary/sender-id/

**Comment by astuteape** [comment]
Hi @pradeep864 ,
We're sorry you struggled with this issue, and we appreciate the feedback! We've added this to our internal docs backlog and will resolve the issue as soon as possible.
Twilio SendGrid Docs Team
