### ISSUE TITLE
This issue is not necessarily with Sendgrid, but authentication to the host site. I believe the site does not check to see if username already exists, and therefore will create two users with the same username. 

### ISSUE THREAD

**Issue by kima111** [sendgrid/docs#5938]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @kima111 ,

We're sorry you're having an issue with the site. You shouldn't be able to register a username that has already been taken, but you can file a support ticket if you're having authentication or registration issues. You can access support contact options by logging into https://support.sendgrid.com. If you are unable to login, you can still submit a ticket by clicking "Trouble Logging in?".

Twilio SendGrid Docs Team
