### ISSUE TITLE
Laravel 7 issue in sending email using api key: Failed to authenticate on SMTP server with username "some_user_name" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 250 but got an empty response. Authenticator PLAIN returned Expected response code 250 but got an empty response.

### ISSUE THREAD

**Issue by jdacones120** [sendgrid/docs#5941]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @jdacones120  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
