### ISSUE TITLE
A new api key is generated in Sendgrid. but it throws Forbidden while sending mail

### ISSUE THREAD

**Issue by ShamiliJ** [sendgrid/docs#5943]
A new api key is generated in Sendgrid. but it throws Forbidden while sending mail. 

FYI, the key has full access.

**Comment by astuteape** [comment]
Hello @ShamiliJ 
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
