### ISSUE TITLE
HI, I have trouble getting my account set up, the message i get is being identify as a high risk. Have been trying to set up for days. Kindly Advice. Thanks

### ISSUE THREAD

**Issue by mmchoong88** [sendgrid/docs#5953]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @mmchoong88 ,
We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!
Twilio SendGrid Docs Team
