### ISSUE TITLE
Notifications aren't working in Marketing campaign

### ISSUE THREAD

**Issue by dinesh1218** [sendgrid/docs#5958]
I added an Email in Notifications of Marketing Campaign to receive notifications when a contact is being added into my account. When I add a contact into my list, contact got added successfully but I didn't receive any notification email.

Can anyone help me how to set up Notifications email in Marketing Campaign?

**Comment by astuteape** [comment]
Hello @dinesh1218  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
