### ISSUE TITLE
Hi I've set up my email notification and I am not receiving them. Not even in my spam account. So right now I can't see when a lead is generated through clickfunnels.

### ISSUE THREAD

**Issue by trcross1** [sendgrid/docs#5964]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @trcross1 ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
