### ISSUE TITLE
Overview » Request Body exaymple: please add a headers section

### ISSUE THREAD

**Issue by schittli** [sendgrid/docs#5965]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Hello
#### Can you please offer a Request Body example in the Docs containing the headers element?

A working jsoon example would help a lot so that we do not have to ask google to get ideas about the errors.
For example, we would like to prioritize E-Mails (high and low), which is a very common use case.

Thanks a lot, kind regards,
Thomas

**Comment by astuteape** [comment]
This should now be up to date here: https://sendgrid.api-docs.io/v3.0/mail-send/v3-mail-send
