### ISSUE TITLE
unable to add DNS record in the cloudfare DNS setting

### ISSUE THREAD

**Issue by bidhi108** [sendgrid/docs#5966]
I created the CNAME fields and values and trying to add it in cloudfare CNAME but it is not autheticating it for SENDGRID email
Can you please help

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @bidhi108  ,
We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
