### ISSUE TITLE
Hi, I cannot add sendgrid addons to my heroku account

### ISSUE THREAD

**Issue by haropedro** [sendgrid/docs#5970]
Hi, I cannot add sendgrid addons to my heroku account. Every time I run this command:
heroku addons:create sendgrid:starter

I get an error and I cannot access sendgrid:

Creating sendgrid:starter on ⬢ harold-saas-app... !
 !    An error was encountered when contacting the add-on partner to create sendgrid:starter: Error Provisioning User - User status - banned

Thanks

**Comment by astuteape** [comment]
Hello @haropedro ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
