### ISSUE TITLE
Auto reviewed my account 

### ISSUE THREAD

**Issue by mouradove12** [sendgrid/docs#5979]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @mouradove12  ,
We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!
Twilio SendGrid Docs Team

**Comment by mouradove12** [comment]
support don't answer don't reply don't resolve

Le sam. 9 mai 2020 à 00:06, Wade Christensen <notifications@github.com> a
écrit :
