### ISSUE TITLE
unable to connect with sendgride with codeigniter.

### ISSUE THREAD

**Issue by telitofik** [sendgrid/docs#5980]
i'm trying to use SendGrid email API with my CodeIgniter code.
but got a connection timeout error.

    $this->email->initialize(array(
      'protocol' => 'smtp',
      'smtp_host' => 'smtp.sendgrid.net',
      'smtp_user' => 'apikey',
      'smtp_pass' => 'generatedPassword',
      'smtp_port' => 587,
      'crlf' => "\r\n",
      'newline' => "\r\n"
    ));

    $this->email->from('your@example.com', 'Your Name');
    $this->email->to('someone@example.com');
    $this->email->cc('another@another-example.com');
    $this->email->bcc('them@their-example.com');
    $this->email->subject('Email Test');
    $this->email->message('Testing the email class.');
    $this->email->send();

    echo $this->email->print_debugger();

but got this error.
    
    Message: fsockopen(): unable to connect to smtp.sendgrid.net:587 (Connection timed out)

when i replace,
    
    protocol =>'smtp' to 'ssmpt' and everything with extra 's' like 'ssmtp_user' , 'ssmtp_pass'.
the error goes but mail sent from server not from sendgrid.

help me please, thank you.

**Comment by astuteape** [comment]
Hello @telitofik ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
