### ISSUE TITLE
Unsubscribe Tag not Working

### ISSUE THREAD

**Issue by DarkArcZ** [sendgrid/docs#5981]
## Expected content
Adding the global unsubscribe tags <%asm_global_unsubscribe_url%> to my url. Expected it to link to a page for users to unsubscrube

## Actual content
![image](https://user-images.githubusercontent.com/18695269/80942199-c8f2c700-8e16-11ea-8835-6838da40cf56.png)

When I send a test email and I click on the unsubscribe link, it tells me that I cannot open the link.

**Comment by astuteape** [comment]
Hello @DarkArcZ,

We're sorry you're having this issue! Please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
