### ISSUE TITLE
Submitting Questionnaire for Sendgrid.com  

### ISSUE THREAD

**Issue by seth-davis74** [sendgrid/docs#5982]
I am submitting this here because I can't get into our account. Enviroadmin is our user name. The account was flagged when we signed up and we had to answer questions. Since I can't get in I can't submit the answers. Please contact me at sethd@enviromerica.com My number is (650) 209-8946
<!
Please avoid submitting support questions here. You can contact our support team at https://support.sendgrid.com.

If you are able to login to https://support.sendgrid.com:
1. Click "Login & Contact Support."
2. Then, select "Contact Support" to see your contact options.

If you are unable to login to https://support.sendgrid.com:
1. Click "Trouble Logging in?"
2. Then, select "I am having a different login issue."

If you are reporting an issue with our docs, thanks for letting us know!
-->

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @seth-davis74  ,

We're sorry you're having this issue. Unfortunately, the documentation team is unable to assist with account and login Issues. We have passed your request to the support team, and they should be reaching out soon. Again, we apologize for the delay and understand that the wait is less than ideal.

Twilio SendGrid Docs Team

**Comment by seth-davis74** [comment]
Why did you close my ticket? You never answered me.




__________________________


Best Regards,



Seth Davis
Head of IT

[cid:image002.png@01D4FB88.1628E590]

­­­­­CMA’s Exclusive P<https://enviromerica.com/company-information/cma-partnership/>artner in Compliance and Medical Waste since 2013



EnviroMerica, Inc.

4906 El Camino Real, Suite 206

Los Altos, CA  94022

Wk: 650-655-2045

Desk: 650-209-8946

Fax: 650-523-8507

Email: sethd@enviromerica.com<mailto:billing@enviromerica.com>

It Support: itsupport@enviromerica.com

www.enviromerica.com<http://www.enviromerica.com/>


CONFIDENTIAL: This e-mail and any attachments thereto, is intended only for the use of the addressee(s) named herein and may contain legally privileged and/or confidential information.  If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution or copying of this e-mail, and any attachment thereto, is strictly prohibited.  If you have received this e-mail in error, please notify me via return e-mail and via telephone at 408-656-9999 and permanently delete the original, any copy, and any printout thereof.

________________________________

**Comment by astuteape** [comment]
Hello @seth-davis74 ,

I've closed the issue because it is not a docs-specific issue. I have also reached out to the support team to try and help prioritize your issue and asked them to reach out to you. You should be hearing from them shortly if you have not already.

Twilio SendGrid Docs Team

**Comment by seth-davis74** [comment]
Wade,
Thank you. You guys should have a way for users that can't log in be able to send you guys a message.

Seth




__________________________


Best Regards,



Seth Davis
Head of IT

[cid:image002.png@01D4FB88.1628E590]

­­­­­CMA’s Exclusive P<https://enviromerica.com/company-information/cma-partnership/>artner in Compliance and Medical Waste since 2013



EnviroMerica, Inc.

4906 El Camino Real, Suite 206

Los Altos, CA  94022

Wk: 650-655-2045

Desk: 650-209-8946

Fax: 650-523-8507

Email: sethd@enviromerica.com<mailto:billing@enviromerica.com>

It Support: itsupport@enviromerica.com

www.enviromerica.com<http://www.enviromerica.com/>


CONFIDENTIAL: This e-mail and any attachments thereto, is intended only for the use of the addressee(s) named herein and may contain legally privileged and/or confidential information.  If you are not the intended recipient of this e-mail, you are hereby notified that any dissemination, distribution or copying of this e-mail, and any attachment thereto, is strictly prohibited.  If you have received this e-mail in error, please notify me via return e-mail and via telephone at 408-656-9999 and permanently delete the original, any copy, and any printout thereof.

________________________________
