### ISSUE TITLE
Your account is temporarily under review. Please contact Support to regain access. 

### ISSUE THREAD

**Issue by soniccheung** [sendgrid/docs#5985]
Noted I should not leave this kind of inquire here but I have no way as I could not get any support reply since last Friday (1st May 2020) until now...

I could not receive any email about the reason of the under review status of my account, and I have already done the domain authentication and make sure I have chosen the right price plan on Azure Portal.

Can the here administrator to help? Many thanks.

## Expected content
Let me know the reasons and I could resolve one by one.

## Actual content
No email mentioned the reason and no response from SendGrid support after around 5 days.

**Link to page**: https://support.sendgrid.com/hc/en-us

**Comment by astuteape** [comment]
Hello @soniccheung  ,
We're sorry you're having this issue. Unfortunately, the documentation team is unable to assist with account and login Issues. We have passed your request to the support team, and they should be reaching out soon. Again, we apologize for the delay and understand that the wait is less than ideal.
Twilio SendGrid Docs Team
