### ISSUE TITLE
You are not authorized to access SendGrid, please contact

### ISSUE THREAD

**Issue by djsoul86** [sendgrid/docs#5989]
I'm trying to login since yesterday and i got an error "You are not authorized to access SendGrid, please contact" and the Contact Support don't give me a response. I need use the service.

**Comment by astuteape** [comment]
Hello @djsoul86 ,

We're sorry you're having this issue. Unfortunately, the documentation team is unable to assist with account and login Issues. We have passed your request to the support team, and they should be reaching out soon. Again, we apologize for the delay and understand that the wait is less than ideal.

Twilio SendGrid Docs Team
