### ISSUE TITLE
I can't able to login on Sendgrid account.

### ISSUE THREAD

**Issue by Workingportals** [sendgrid/docs#5991]
I have purchase plan for sending mail through API. But after 2 days, sendgrid make my account under review. Even i can't login on the Sendgrid. It's always showing "You are not authorized to access SendGrid, please contact Support."

It's really frustrating for me! i purchased plan and now my account block. I have contact their support 2-3 times in last few days. But still i have not received single response.

I hope that Sendgrid support team will solve my issue ASAP.

**Comment by astuteape** [comment]
Hello @Workingportals ,

We're sorry you're having this issue. Unfortunately, the documentation team is unable to assist with account and login Issues. We have passed your request to the support team, and they should be reaching out soon. Again, we apologize for the delay and understand that the wait is less than ideal.

Twilio SendGrid Docs Team
