### ISSUE TITLE
Unable to login to SendGrid after accidental whitelisting of wrong IP.

### ISSUE THREAD

**Issue by ritamgaur** [sendgrid/docs#5992]
Hi,

My company has an account with SendGrid, and we are currently unable to access the account due to an inadvertent addition of an invalid IP to the whitelist via an API call.

Now, we are unable to log into the account, and all our Emails are down. I have filled the support form, but so far, have not received any update except for the acknowledgement email. Neither there is a phone number to reach out to - as this is a **PROD ISSUE.**

Can someone help me with this problem. This is a major issue for us, and definitely not a very good customer experience.

Thanks,

Ritam.

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @ritamgaur ,

We're sorry you're having this issue. Unfortunately, the documentation team is unable to assist with account and login Issues. We have passed your request to the support team, and they should be reaching out soon. Again, we apologize for the delay and understand that the wait is less than ideal.

Twilio SendGrid Docs Team
