### ISSUE TITLE
Unsubscribe link is broken

### ISSUE THREAD

**Issue by tenitski** [sendgrid/docs#5994]
When using {{unsubscribe}} in campaign email template the inserted url has a space in front which breaks the link in some email clients (browsers are more tolerant and link still works).

So example:
```
<a href="{{unsbuscribe}}">click here to unsubscribe</a>
```
gets translated into
```
<a href=" https://long.url.here">click here to unsubscribe</a>
```
It should instead be 
```diff
-<a href=" https://long.url.here">click here to unsubscribe</a>
+<a href="https://long.url.here">click here to unsubscribe</a>
```

**Comment by astuteape** [comment]
Hi @tenitski ,

Thank you for reporting the issue. The team has deployed a fix. If you have more questions or feel the issue has been closed in error, please open another issue. If you need direct support, please contact our Support team and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.
Twilio SendGrid Docs Team
