### ISSUE TITLE
Integrating with the SMTP API

### ISSUE THREAD

**Issue by thelem** [sendgrid/docs#6005]
https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html

The links to TLS Connections and SSL connections are dead. I can't think what they refer to, because TLS is basically SSL v4, so they are the same thing. Do you mean STARTTLS vs SSL/TLS, which are the options in Thunderbird?

**Comment by astuteape** [comment]
Hello @thelem ,

Thanks for bringing this to our attention. We're sorry for the confusion, but the links on this page appear to be better: https://sendgrid.com/docs/for-developers/sending-email/integrating-with-the-smtp-api/. We'll get the page you linked redirected to the current page.

Best,
Twilio SendGrid Docs Team

**Comment by thelem** [comment]
Thanks. Your new link doesn't really clarify anything though. I've done a bit of searching and it's all a bit confusing. The clearest article I found was https://blog.mailtrap.io/starttls-ssl-tls/

My understanding from that is that if I connect on port 25, 2525, or 587 then I can optionally use TLS (STARTTLS).
If I connect on port 465 I must use TLS.

SSL itself is now obsolete, and I imagine you have disabled it on all ports. It may however be helpful to use the term "SSL/TLS" or "TLS (formerly SSL)" to help readers who are familiar with the term SSL but not TLS.

**Comment by astuteape** [comment]
I see. I misunderstood the docs issue; thank you for clarifying.

We will add this issue to our backlog to clarify between SSL and TLS. It is confusing that SSL is used around the internet to mean both, and we can be clearer in our docs. We can also add some better links and clarifying explanations to explain the protocols used and how they relate to the ports used.

There is some material on our blog that you may find helpful.

* https://sendgrid.com/blog/whats-the-difference-between-ports-465-and-587/
* https://sendgrid.com/blog/what-is-starttls/

The "What is StartTLS article" has a few sections that I think address your questions better. I've added them below as well.

> ### TLS vs SSL
>
> Even though “TLS” is in its name, StartTLS works with both encryption protocols, TLS and SSL. 
>
> While StartTLS works with both protocols, we recommend using TLS over SSL. SSL is an older protocol and is not as secure as its successor, TLS. SSLv2 and SSLv3 have both been deprecated.
>
> For reference, here’s a list of SSL and TLS protocols from oldest to newest: 
>
> SSLv2, SSLv3, TLSv1.0, TLSv1.1, TLSv1.2, TLSv1.3 
>
> Both the email client and email server need to agree on what connection to use. The email client may support TLSv1.3, but the email server may only support up to TLSv1.2. This means that both parties will need to use TLSv1.2 to proceed with the encryption.
>
> ### How does Twilio SendGrid use StartTLS?
>
> Twilio SendGrid supports TLS v1.1 and higher. Unencrypted and TLS connections are accepted on ports 25, 587, and 2525. Or, you can connect through SSL on port 465. 
>
> We follow Opportunistic TLS and send on the highest encryption level the recipient server accepts. We also offer Enforced TLS. It is your choice whether or not you require your email to be sent over an encrypted connection. If the recipient server does not accept encrypted messages, the message is dropped and we send a block event.

I hope this is more helpful, and thanks again for bringing the issue to our attention.
