### ISSUE TITLE
Liquid Build issue on Partners/EngineYard.md

### ISSUE THREAD

**Issue by mbernier** [sendgrid/docs#601]
We get an error in Travis ci every once in a while that says

```
Liquid Exception: undefined method `match' for nil:NilClass
```

**Comment by thinkingserious** [comment]
Hello @mbernier,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
