### ISSUE TITLE
Email Status

### ISSUE THREAD

**Issue by parura** [sendgrid/docs#6015]
## Actual content

**Link to page**:

**Comment by parura** [comment]
Hi All,
I have issue with email send , Most of the customers are receiving the email but one customer is saying that they are not receiving the email, when i go to activity and checked the status of the email delivery it says that it is delivered.

How can i find the reason for this issue ?

Thanks

**Comment by astuteape** [comment]
Hello @parura  ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
