### ISSUE TITLE
Docs Feedback

### ISSUE THREAD

**Issue by matejkramny** [sendgrid/docs#6045]
Hi there,

I've some feedback to share.

The docs are very hard to read, I need to squint to read the text properly. It's due to the contrast difference of the white page and light grey text.

Thanks

**Comment by astuteape** [comment]
Hi @matejkramny ,

Thank you for the feedback, and we're sorry you're having trouble with the site. We aim to make the docs as accessible as possible and will see what we can do to improve contrast.

Twilio SendGrid Docs Team
