### ISSUE TITLE
Issue with creating account. 

### ISSUE THREAD

**Issue by bannerpeakmarketing** [sendgrid/docs#6052]
trying to create account and it says contact support, I answered the required questions not a single email came back to me :( . Any way this can be fixed, I mean its a new account why would i be dismissed from creating an account?

**Comment by astuteape** [comment]
Hello @bannerpeakmarketing ,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

Twilio SendGrid Docs Team
