### ISSUE TITLE
i got a phishing email pretending to be you. no where to report this properly.

### ISSUE THREAD

**Issue by Rachel-Amos** [sendgrid/docs#6053]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hi @Rachel-Amos ,

Thank you for letting us know. Could you please report this to our support team and include the address that sent you the message. We want to be sure to track this down. Again, thank you for letting us know.

You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team

**Comment by astuteape** [comment]
Hello @Rachel-Amos ,

I have asked support to look into your issue and follow up. They will be reaching out soon. Unfortunately, the documentation team does not have the ability to retrieve support tickets that would help contextualize issues reported here, so I apologize if directing you to support felt dismissive; that was not my intention. I'm sorry for the hassle, and I appreciate your patience. Again, support will be reaching out directly to follow up.

Best,
Twilio SendGrid Docs Team
