### ISSUE TITLE
Webhoook Event URL offset details

### ISSUE THREAD

**Issue by Aridjar** [sendgrid/docs#6054]
Hello,

Cody S from the escalation team sent me here after they couldn't answer our questions about ticket number 4414242.

## Introduction

We want to be able to map each clicks on our URL in our mail template to provide more visual statistics to our marketing team.

But after trying to reverse engineer we couldn't find any easy way to do it using the url offset, though it looks like the perfect params to do it.

The example email we used as 23 url, confirmed by counting them and using the following JS command : 

```js
document.body.querySelectorAll('a:not([href^="mailto:"]').length
```

But the `url_offset` go up to 37.

1. Why does the URL offset goes up to 37 ?
2. We also have some URL (say the 5th, 6th and 7th) where the URL offset would be 12, 13 then 16 (a jump of one or multiple url). Why does it happens?
3. We also observed an `url_offset` having two URLs. How can this happens?
4. Finally, why the first `url_offset` is associated with a link which isn't present in the template?

## Expected content

More information on the logic behind the url offset generation, so we can create an accurate mapping of the clicks in an associated email template.

## Actual content

```
<a name="urloffset"`urloffset` - if there is more than one of the same links in an email, this tells you which of those identical links was clicked.
```

**Link to page**: https://sendgrid.com/docs/for-developers/tracking-events/event/#json-objects

**Comment by astuteape** [comment]
Hello @Aridjar ,

Thank you for bringing this to our attention, and we're sorry you're having trouble. We've added it to our docs backlog and will reach out to the product team to better understand the URL offset or if there may be another way to approach the problem given the data we return. Thank you for your patience.

Twilio SendGrid Docs Team

**Comment by astuteape** [comment]
Hello @Aridjar ,

Is your template setup to include both plain/text and html/text? If so, do you have click tracking set for both? A template set that way may explain the "jump" behavior. Let us know, and we can provide more details if needed.

**Comment by Aridjar** [comment]
Hello @astuteape 

The template setup is to include both `plain/text` and `html/text` and the click tracking is set for both.

**Comment by astuteape** [comment]
Hello @Aridjar 

We increment URL offset indexes from top down in the mime file. This means if a mime has one text part and one html part, both containing click-tracked links, the text part will start the index at 0 (we place text/plain before text/html when the mime is created). When we rewrite the links for click tracking the html part, the index is NOT reset and continues the index from where it left off with the previous text/plain mime part. This may be why you are seeing a “jump.” We hope this is helpful information, but let us know if you need more info.

Twilio SendGrid Docs Team

**Comment by Aridjar** [comment]
Hello @astuteape 

Thanks for your answer. After your response, I did check another set of click events in another mail and wrote every data I though might be of interest for you. 

### List of URL in the template

| URLs in the template | html url_offset | text url_offset |
|---|---|---|
| URL n°1 | 0 | none |
| URL n°2 | 1 | none |
| URL n°3 | 2 | none |
| URL n°4 | 3 | 9 |
| URL n°5 | 4 | 10 |
| URL n°6 | 5 | 11 |
| URL n°7 | 6 | none |
| URL n°8 | 7 | 12 |
| URL n°9 | 8 | none |

### Data from the Sendgrid Event, json format:

```json
[{
    "url_offset": { "index" : 0, "type": "html" },
    "urls": [ "URL n°1" ]
}, {
    "url_offset": {  "index" : 1, "type": "html" },
    "url" : [ "URL n°2" ]
}, {
    "url_offset" : { "index" : 2, "type": "html" },
    "url" : [ "URL n°3" ]
}, {
    "url_offset" : { "index" : 3, "type": "html" },
    "url" : [ "ULR n°4" ]
}, {
    "url_offset" : { "index" : 4, "type": "html" },
    "url" : [ "URL n°5" ]
}, {
    "url_offset" : { "index" : 5, "type": "html" },
    "url" : [ "URL n°6" ]
}, {
    "url_offset" : { "index" : 6, "type": "html" },
    "url" : [ "URL n°7" ]
}, {
    "url_offset" : { "index" : 7, "type": "html" },
    "url" : [ "URL n°8" ]
}, {
    "url_offset" : { "index" : 8, "type": "html" },
    "url" : [ "URL n°9" ]
}, {
    "url_offset" : { "index" : 9, "type": "text" },
    "url" : [ "URL n°4" ]
}, {
    "url_offset" : { "index" : 10, "type": "text" },
    "url" : [ "URL n°5" ]
}, {
    "url_offset" : { "index" : 11, "type": "text" },
    "url" : [ "URL n°6" ]
}, {
    "url_offset" : { "index" : 12, "type": "text" },
    "url" : [ "URL n°8" ]
}]
```

As you can observe, the 4 first urls don't have click of type "text", which aren't taken in account by the index of the url offset. Then, the counter don't count the 7th url either.

Why does it happen ?

If you are interested by more data, I can do the same work for the first set of data we used and on which I opened a ticket.
Also, let me know if I can be of any other kind of help.

**Comment by astuteape** [comment]
Hi @Aridjar ,

I apologize for the delay. I will ask our team about why this might be happening. Thank you for passing the information along and for your patience.

Best,

Twilio SendGrid Docs Team

**Comment by astuteape** [comment]
Hi @Aridjar ,

Our team is wondering if you can send a full payload to us. This seems like less of a docs issue and something we may want to move to support. Would you mind opening a support ticket and passing me the support ticket number. I can then include our support team on the context we have here to get you more direct support.

Best,

Twilio SendGrid Docs Team

**Comment by Aridjar** [comment]
Hi @astuteape ,

I would love to send you a full payload, but I don't want to display any data on a public page, as they might contain private informations. Which way would you prefer ?

Thank you for proposing to contact the support about this problem, unfortunately I came from there, as stated in the second line of the first message:

> Cody S from the escalation team sent me here after they couldn't answer our questions about ticket number 4414242

Have a nice day,

**Comment by astuteape** [comment]
Hi @Aridjar ,

We definitely don't want you to post anything with private information. That's why I think support will be a better venue for the conversation. If you pass me the support ticket number, I can follow up with support and engineering internally to continue the conversation we've started here. That way you're not starting from scratch with the support team. I just need the support ticket number and can facilitate from there.

Best,
Twilio SendGrid Docs Team

**Comment by Aridjar** [comment]
Hello @astuteape

The ticket number is #4414242 .
I replied to Cody and the escalation team so they can be prepared to reopen the ticket at your signal.
 
Have a nice day,

**Comment by astuteape** [comment]
Thank you @Aridjar ,

I'm going to close this issue and follow up internally with support.

Best,
Twilio SendGrid Docs Team
