### ISSUE TITLE
doc shows port 465, probably should be 587

### ISSUE THREAD

**Issue by petebytes** [sendgrid/docs#6080]
https://sendgrid.com/docs/for-developers/sending-email/rubyonrails/#configure-actionmailer-to-use-sendgrid

**Comment by hungmi** [comment]
I also found it should be "password" instead of "api_key".
The guide here is more correct: https://app.sendgrid.com/guide/integrate/langs/smtp

**Comment by petebytes** [comment]
@hungmi I think password is if you are using a user.  If using API as the password then the user is apikey.
At least it is what is working for me.

**Comment by hungmi** [comment]
@petebytes Thank you.
I am talking about the second key of the smtp settings, which is:
```ruby
ActionMailer::Base.smtp_settings = {
  :user_name => "apikey",
  :password => ENV['SENDGRID_API_KEY'], # this one
  :domain => 'example.com',
  :address => 'smtp.sendgrid.net',
  :port => 587,
  :authentication => :plain,
  :enable_starttls_auto => true
}
```
The doc shows "api_key" as the second key, but I need to change it to "password" to make it work.

**Comment by petebytes** [comment]
Perhaps because I am using 
`authentication: :login,` instead of :plain

**Comment by astuteape** [comment]
Hello All, my apologies for the confusion. The user_name should be "apikey" when using the API key as the password. A fix will be pushed up shortly.

Twilio SendGrid Docs Team
