### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by asimsheikhviion** [sendgrid/docs#6095]
Issue Summary
Hello, I'm sorry when I log in my account it occurs "You are not authorized to access SendGrid, please contact Support.", and my username and password are all right.

Steps to Reproduce
My email is asim@viiontech,com
After I sign up, it shows error as mentioned in title
I am unable to login and cannot launch ticket.
I have a paid account
i have already submitted the issue on below link last week and this week also but no response
very poor support from send grid

https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by astuteape** [comment]
Hello @asimsheikhviion ,

The support team has been contacted and will be reaching out shortly if they have not done so already. I'm closing the docs Issue, as you should now be able to follow up with support directly. Thank you for your patience, and we're sorry for the trouble.

Twilio SendGrid Docs Team
