### ISSUE TITLE
My account has been banned

### ISSUE THREAD

**Issue by gustavobonfim** [sendgrid/docs#6102]
Hi there!
I created an Sendgrid addons at my Heroku account, but I has some issues. So I removed the addons and now, when I try to created again, I receive this error saying that my account is banned.

> An error was encountered when contacting the add-on partner to create sendgrid:starter: Error Provisioning User - User status - banned

What should I do?

Thanks!
Regards,
Gustavo Bonfim

**Comment by astuteape** [comment]
Hello @gustavobonfim  ,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

Twilio SendGrid Docs Team
