### ISSUE TITLE
error when incoming email comes from gmail provider

### ISSUE THREAD

**Issue by ipehimanshu** [sendgrid/docs#6108]
Hello sir

we have set incoming parse api and also MX record set but issue comes when some one send reply or incoming email comes from gmail provider then no hook comes, 

we have checked with server log with server support guy and we get this type log

167.89.117.35 - - [21/Jun/2020:20:47:47 -0500] "POST /testing/test.php HTTP/1.0" 400 1393 "-" "Sendlib/1.0 mx0033p1mdw1.sendgrid.net"

167.89.117.69 - - [22/Jun/2020:23:44:34 -0500] "POST /testing/test.php HTTP/1.0" 400 1393 "-" "Sendlib/1.0 mx0064p1mdw1.sendgrid.net"

so after that i have set that testing php code with 3 different server but all have same type error shows, 

so can you please help us to make it done, 

in php script i have just added logic to save all post data as log file, not more logic for testing,

also as per server guy post data comes with malware or other thing that is why server return 400 error, 

So please help us

Thanks

**Comment by astuteape** [comment]
Hello @ipehimanshu  ,

We're sorry you're having this issue! Since this is not a docs-related issue, please contact our Support team directly and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
