### ISSUE TITLE
Codeigniter setup problem in documentation

### ISSUE THREAD

**Issue by wildercuba** [sendgrid/docs#6115]
Hello:
The problem it's simple, in this URL: https://sendgrid.com/docs/for-developers/sending-email/codeigniter/
You have an error, please change: 'smtp_api_key' => 'sendgridapikey' for 'smtp_pass' => 'sendgridapikey'.
This simple error can be fustrating.
Thanks.

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @wildercuba 

Thanks so much for your feedback! Sorry for the frustration. In the future, if you'd like, you can always submit a PR on our docs by clicking the "Edit this page" link at the bottom of each page. 

I've gone ahead and made the fix [here](https://github.com/sendgrid/docs/pull/6127).

The Twilio SendGrid Docs Team
