### ISSUE TITLE
Can't Login and Can't Login Support sorry

### ISSUE THREAD

**Issue by proof-by-accident** [sendgrid/docs#6116]
Hi, I'm trying to create a SendGrid account but receive the following error:
"Please provide further information

You will not be able to send email through SendGrid until you provide more information. Please contact Support to answer a few more questions.
"

But I can't contact support without logging in, and my issue isn't addressed in the FAQS. What should I do?   

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @proof-by-accident  ,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

Twilio SendGrid Docs Team
