### ISSUE TITLE
Integration Guide / NodeJS: example email with from: 'test@example.com' always results in error

### ISSUE THREAD

**Issue by Twisterking** [sendgrid/docs#6124]
I am new to sendgrid and want to complete the integration guide to finish my account. I am using nodeJS, I start the "Integration Guide", the guide tells me to do the following:

```js 
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);
const msg = {
  to: 'test@example.com',
  from: 'test@example.com',
  subject: 'Sending with Twilio SendGrid is Fun',
  text: 'and easy to do anywhere, even with Node.js',
  html: '<strong>and easy to do anywhere, even with Node.js</strong>',
};
sgMail.send(msg);
```

## Expected content

The code in the guide should work without errors, so I can complete the guide.

## Actual content

ERROR: `The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements`

Thus I can not complete the guide and "unlock" my account completely. 

Please help! What am I missing here? this seems to be a very stupid mistake, either on my end or on sendgrid's end.

**Comment by astuteape** [comment]
Hello @Twisterking ,

`test@example.com` is a placeholder value. You'll need to replace it with the email address you used when completing sender verification. If you still need to verify your email address, you can find instructions here: https://sendgrid.com/docs/for-developers/sending-email/sender-identity/

We hope this helps you troubleshoot, and thanks for getting started with SendGrid.

Best,

Twilio SendGrid Docs Team

**Comment by astuteape** [comment]
We hope the information above solved your issue. We're closing this GitHub Issue for now. If you encounter more trouble related to the above issue, please reopen the Issue.

Thank you,
Twilio SendGrid Docs Team

**Comment by Twisterking** [comment]
Yes well it kinda helped. Thank you! :)

If you could tell your colleagues in the support team to finally answer my tickets (especially #4774650), that would be great.

There seems to be no way to reach your support team, which is really a bummer since I pay 90 USD per month for the Pro plan!

**Comment by astuteape** [comment]
Sorry for the delay. I know our support team has been very busy. I have passed that ticket number to them.

**Comment by Twisterking** [comment]
Got a reply - finally! Thank you!
