### ISSUE TITLE
Global Stats

### ISSUE THREAD

**Issue by ShohanRahman** [sendgrid/docs#6125]
https://sendgrid.com/docs/API_Reference/Web_API_v3/Stats/global.html

Hello.

For the statistic API; we don't have any information about the authentification. What are the parameters to add ? Do we need a username ? An API Key ? Etc.

**Comment by Whatthefoxsays** [comment]
Hi there, 

Please use this documentation for the SendGrid V3 APIs going forward: https://sendgrid.api-docs.io/v3.0/stats

You'll need an API key to use the stats API. Please let us know if you need additional information. 

Thanks!

**Comment by astuteape** [comment]
This should be addressed by the updated docs linked in the previous comment. The reported page is removed and redirected.
