### ISSUE TITLE
Adding a link to setting up Sendgrid specific SPF records from the glossary page

### ISSUE THREAD

**Issue by dinc5150** [sendgrid/docs#6131]
## Expected content
After googling Sendgrid SPF and the first result reaches the SPF glossary page. I was expecting to get the SPF include details for sendgrid. It would be good to have a link to a page that describes what sendgrid server to include in your SPF records

## Actual content

**Link to page**: https://sendgrid.com/docs/ui/account-and-settings/spf-dkim/

**Comment by astuteape** [comment]
Thanks for the feedback. We'll update the links on that /spf-dkim page. I think this page may be what you were looking for: https://sendgrid.com/docs/ui/account-and-settings/spf-records/

Sorry it wasn't easier to find, and, thanks again for the feedback.

Best,

Twilio SendGrid Docs Team
