### ISSUE TITLE
Can't access my account, while username and password that i entered is correct

### ISSUE THREAD

**Issue by balikcode** [sendgrid/docs#6144]
### Can't access my account, while username and password that i entered is correct

Hello Support team Sendgrid, I hope you've had your coffee already today. 

I want to ask something about my account, I can't access or log in to my dashboard after inserting username and password. the response after inserting my username password system informs me **"Your username or password is invalid."**. so I reset my password, and after resetting my password. this problem happens again.

I've reset my password up to three times. unfortunately, I still can't log in.

what happens with my account ? can you check it for me?

**Comment by Whatthefoxsays** [comment]
Hello @balikcode,

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. To expedite this process, once you've got a ticket number, leave it here in the comments and I'll try and help move it along for you. Hope this helps!

The Twilio SendGrid Docs Team

**Comment by balikcode** [comment]
Hello @Whatthefoxsays 

yes, I was open support ticket before open this issue. unfortunately, the ticket is not replied for 2 days. its make me very confused. how to login and use my account, i was paid the bill but the system can't use. can you give me another options how to contact the support team ? 

Cheeers

**Comment by Whatthefoxsays** [comment]
Hi @balikcode, 

 Unfortunately I cannot unlock your account for you. I'll need a ticket number or an account ID/email associated with the account to be able to help you.

**Comment by balikcode** [comment]
Hey @Whatthefoxsays 

Should i share my ticket number here ?

**Comment by Whatthefoxsays** [comment]
Hi @balikcode, 

You can do that or share the email address you use to sign into your account with, we can find your information.

Thanks!

**Comment by johnnyperdomo** [comment]
this happens to me all the time as well! i have no idea why, after a few hours, i enter the same password and username and it works. seems to be a problem on sendgrid's servers

**Comment by chitampopo** [comment]
Hi @Whatthefoxsays 

Technically this is the root cause, the resource /tokens were rejected requests come.
![image](https://user-images.githubusercontent.com/9018326/89027903-9002b980-d355-11ea-9361-1fbcc74f533f.png)

After a few minutes, I'll be logged out and have to log in again.
I faced with this issue 3, 4 times per day but every time it happens all status at the link https://status.sendgrid.com/ are green 
A little bit worry because we are going to go live the application

**Comment by balikcode** [comment]
hi @chitampopo @johnnyperdomo 

i am accessing sendgrid today, and also try to log in. now I can access my account, idk what happens with my account a few days ago as long as my design library and contact in my account doesn't lost its okay. 

have you tried to log in today?

i want to close this issue, please report me if you're successful to access your account

**Comment by johnnyperdomo** [comment]
It works for me yeah.
