### ISSUE TITLE
Email not working in Codeigniter with SMTP

### ISSUE THREAD

**Issue by balvinder1005** [sendgrid/docs#6145]
I used below code in codeigniter 3 and getting error 

 fsockopen(): unable to connect to smtp.sendgrid.net:587(Connection refused)

I tried Ports 25,465 and 587 and getting same error every time.

```
<?php 

$this->load->library('email');

$this->email->initialize(array(
  'protocol' => 'smtp',
  'smtp_host' => 'smtp.sendgrid.net',
  'smtp_user' => 'sendgridusername',
  'smtp_pass' => 'sendgridapikey',
  'smtp_port' => 587,
  'crlf' => "\r\n",
  'newline' => "\r\n"
));

$this->email->from('your@example.com', 'Your Name');
$this->email->to('someoneexampexample@example.com');
$this->email->subject('Email Test');
$this->email->message('Testing the email class.');
$this->email->send();

echo $this->email->print_debugger();
?>

```

**Comment by astuteape** [comment]
Hello @balvinder1005 

Thank you for bringing this to our attention. Does it work with the string "apikey" as the smtp_user? I believe that's the problem. I'll update the documentation to correct this.
