### ISSUE TITLE
email not sending

### ISSUE THREAD

**Issue by abhishek-web-dev** [sendgrid/docs#6162]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @abhishek-web-dev 

We're sorry you're having trouble! Can you please provide more details about the issue. Is there information missing from the docs that may have helped you? For direct support, please contact our Support team, and they can help you out. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
