### ISSUE TITLE
Invalid SPF record examples

### ISSUE THREAD

**Issue by lyyder** [sendgrid/docs#6163]
The SPF example records start with an unnecessary closing bracket. Also, it's not quite clear what should be the value in place of `u123456.wl.sendgrid.net`. The docs refer to "the value provided to you during the domain authentication process" but the sender authentication UI does not point out what value should be placed there. Should it be the value of the topmost CNAME record value?

## Expected content
```
v=spf1 include:u123456.wl.sendgrid.net -all
```

## Actual content

There's an unnecessary closing angle bracket in the beginning of each SPF record example.

```
>v=spf1 include:u123456.wl.sendgrid.net -all
```

**Link to page**: https://sendgrid.com/docs/ui/account-and-settings/spf-records/

**Comment by astuteape** [comment]
Hi @lyyder 

Thank you for bringing this to our attention. We'll get the exta `>` symbols out of there.

SendGrid provides automated security and will give you a CNAME record to add to your DNS config. If you use the automated security, you don't need to add a separate SPF TXT record. You can just add the CNAME records to your DNS.

However, if you select "Advanced Settings" below "Domain you Send From" and uncheck "Use automated security" during the domain authentication process, you will be given TXT records. One of those is the SPF record you should add. We'll update the docs to make this clear. Thanks again for bringing it to our attention.

Best,
Twilio SendGrid Docs Team

**Comment by lyyder** [comment]
Thanks for explaining this @astuteape. I had totally missed this information about automated security. Good to know that setting the CNAME records is enough.

**Comment by astuteape** [comment]
Happy to help. If you select the automatic security and add all the records provided, SendGrid should validate that your records have been added correctly. You'll see this in the last step of the domain authentication process. At that point, you should be good to go.

I'll leave this Issue open for now and close it once we've made our docs clearer.

**Comment by maximivanov** [comment]
Hello @astuteape it wasn't clear from the docs and I found this Github issue.

How does automated security play with existing authentication headers?
Let's say I have a Gmail set up for mydomain.com. There are TXT records for SPF and DKIM to authenticate Gmail when sending emails.

Now I want to use Sendgrid to send email from the same domain.
Can I use the automated security option or should I go with manual configuration?
I'm not sure how those 3 CNAMEs Sendgrid gives me during the automated setup play with the existing TXT records.

Can you please clarify?

**Comment by pitsevich** [comment]
@astuteape Having the same question here as @maximivanov.

**Comment by maximivanov** [comment]
@pitsevich in short you don't need to make any changes to the record at the root domain. Sendgrid manages SPF under a subdomain of your domain. I've shared my understanding here: https://stackoverflow.com/a/66284499/2579733
