### ISSUE TITLE
Sendgrid, worst ever

### ISSUE THREAD

**Issue by blopa-star** [sendgrid/docs#6164]
## Actual content

**Link to page**:

This sendgrid thing seems a joke, there is no way to contact this sendgrid thing. Ridiculous to say the least.
Then, they do as amazon, I haven't sent any email, but they dared to 'flagg' me ?
How do they know?
Its stupid, ridiculous and discriminatory, I should report you to the FTC.
I don't do business with stupid people like you, lose yourself.

**Comment by astuteape** [comment]
Hello @blopa-star 

We're sorry you're having trouble with our signup process. If you decide you would like to try and work with SendGrid, you can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

Twilio SendGrid Docs Team
