### ISSUE TITLE
If you send 5 support tickets to sendgrid in a week and no replies - how else to you contact someone in the support department ?

### ISSUE THREAD

**Issue by nalcro** [sendgrid/docs#6173]
## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @nalcro 

We are sorry for the delay. Do you have a support ticket number? If so, I can ask our support team to follow up.

Best,
Twilio SendGrid Docs Team

**Comment by adriancable** [comment]
Same issue here - account is adrian@starlinghome.io - how do I proceed? Support tickets are not being responded to.

Tickets #4943393, #4915507, #4926784 ... is Sendgrid simply dead? Is anyone reading tickets any more?

**Comment by astuteape** [comment]
Hello @adriancable 

Thank you for your patience. We have asked support to look into your tickets.

**Comment by adriancable** [comment]
@astuteape - please be more joined up at Sendgrid. One of your support guys did get back to me on Github last week with a promise to look at the tickets, and he actually did. So nothing for you to do for me, but lots to do for others that are having tickets neglected.

I recommend for example you look into the OP's tickets. @nalcro
