### ISSUE TITLE
Which API key permissions needed for SMTP sending?

### ISSUE THREAD

**Issue by nhnicwaller** [sendgrid/docs#6183]
This page explains how to authenticate an SMTP connection, but does not explain which permissions need to be granted to the API key in order to permit email sending.

https://sendgrid.com/docs/API_Reference/SMTP_API/getting_started_smtp.html

I assume that **Mail Send:Full Access** is both necessary and sufficient. Is that correct? If yes, it would be great to add that to the docs.

**Comment by astuteape** [comment]
Hello @nhnicwaller 

Our apologies, that looks like an old page. Mail Send Full access is sufficient. These pages should help:
* https://sendgrid.com/docs/for-developers/sending-email/integrating-with-the-smtp-api/
* https://sendgrid.com/docs/ui/account-and-settings/api-keys/

For a full list of API permissions that can be set using the API, our reference here should help:
* https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/api-authorization

We hope this helps. Let us know if you have any other questions.

Best,

Twilio SendGrid Docs Team

**Comment by nhnicwaller** [comment]
That's helpful, thanks!
