### ISSUE TITLE
Come On People

### ISSUE THREAD

**Issue by smockensturm** [sendgrid/docs#6193]
What is going on with SendGrid support?

You have dead links all over the place, redirects to nowhere. 404's

support.sendgrid.com/hc/requests/4915181

That's a 404.

What gives, man? We are locked out because (from your docs): "It is possible to remove your own IP address from your list of allowed addresses, thus blocking your own access to your account. "

Why is that even possible? Give me a phone number please. This is ridiculous.

**Comment by astuteape** [comment]
Hello @smockensturm 

We're sorry you ran into this issue. Support indicated that they've been in touch and resolved the issue yesterday. We're going to close this issue as it appears to be fixed, but let us know if you need more assistance. Thank you for your patience.

Best,
Twilio SendGrid Docs Team
