### ISSUE TITLE
WebAPI doc correction

### ISSUE THREAD

**Issue by gnickell** [sendgrid/docs#620]
The document is not correct in this URL(https://sendgrid.com/docs/API_Reference/Web_API/mail.html)
"Files to be attached. The file contents must be part of the multipart HTTP POST. Ex: 

```
files[file1.jpg]=file1.jpg&[file2.pdf]=file2.pdf"
```

The example is wrong, it should be 

```
files[file1.jpg]=file1.jpg&files[file2.pdf]=file2.pdf
```

I have a full correct .net demo here:
https://github.com/justrun1983/sendgrid-csharp-webapi

Sent to me by a current customer 
-Garrett

**Comment by dhruvJaiswal** [comment]
I wanted to send multiple Attachment. But when i kept in for loop it was sending only one pdf and other didn't got send

**Comment by thinkingserious** [comment]
Hello @dhruvJaiswal,

Which library were you using for this? If it is the C# library, could you please post your issue along with the relevant source code here: https://github.com/sendgrid/sendgrid-csharp/issues

Thank you!

With Best Regards,

Elmer
