### ISSUE TITLE
Incorrect documentation for C#

### ISSUE THREAD

**Issue by johansuperstar** [sendgrid/docs#6200]
Hi!

I have a SendGrid account created through the Azure Portal. I followed the instructions on 
https://sendgrid.com/docs/for-developers/sending-email/v2-csharp-code-example/#using-nets-built-in-smtp-library, but couldn't get it to work. Using the word "apikey" as username instead of the actual SendGrid username worked. Is this something special for accounts created through Azure or is the documentation incorrect?

## Expected content
Mentioning something about using "apikey" instead of the SendGrid username as username, even if its only applicable for accounts created through Azure.

## Actual content
Using "apikey" as username is not mentioned.

**Link to page**:
https://sendgrid.com/docs/for-developers/sending-email/v2-csharp-code-example/#using-nets-built-in-smtp-library

**Comment by astuteape** [comment]
Thank you for calling this out. We will have a fix shortly.
