### ISSUE TITLE
Errors and Troubleshooting

### ISSUE THREAD

**Issue by benbspiceworks** [sendgrid/docs#6202]
https://sendgrid.com/docs/API_Reference/SMTP_API/errors_and_troubleshooting.html

bad link on this page

**Comment by Whatthefoxsays** [comment]
@benbspiceworks 

Thanks for the feedback! FYI, anything with an API_Reference is old and outdated. (I promise we're THISCLOSE to turning that site off and redirecting). Please visit https://sendgrid.com/docs/api-reference/ or more specifically, https://sendgrid.api-docs.io/v3.0/mail-send/mail-send-errors for more up-to-date information.
