### ISSUE TITLE
I need to contact someone that can sign documents 

### ISSUE THREAD

**Issue by gustawdaniel** [sendgrid/docs#6209]
I created ticket #4639048 but support can't sign documents, so they sent me to sales. 

It is of course mistake because I have a correction note to sign by the issuer of invoice. So this is typical problem for support.

Where should I find help form SendGrid to solve my issue?

```
Nathan (SendGrid)

Jun 30, 2020, 7:34 AM PDT

Hello,

Thank you for contacting Twilio SendGrid support via chat.

Unfortunately, we as a Support team are unable to sign any documents for customers. 

Please reach out to our Sales team for any questions regarding our plans or local tax needs:

https://sendgrid.com/contact-us-form/

If you have any other issues or questions, please don't hesitate to reach out!
Best,
```

I created a new request:

> https://support.sendgrid.com/hc/en-us/requests/4963785?page=1

because of my #4639048 was ignored.

**Comment by astuteape** [comment]
Hi @gustawdaniel 

Because this is not a documentation issue, we have asked support to follow up. They are looking into options to solve the issue. We're going to close the issue here on GitHub now that support is on the task. Thank you for your patience.

Best,
Twilio SendGrid Docs Team
