### ISSUE TITLE
Send Grid failing on multiple levels

### ISSUE THREAD

**Issue by Supertroop6** [sendgrid/docs#6210]
Issue number one can't login to sendgrid.com with valid credentials created in the Azure portal. Why?

When I first started using Send Grid several years ago, it work perfectly. Now it very cumbersome and only 50% reliable. 

I also have an existing ticket that I have not heard back from two weeks now about not being able to authenticate my domain. I'm not sure if the issue with GoDaddy or you guys.

**Comment by astuteape** [comment]
Hello @Supertroop6 

Thank you for your patience. This does appear to be a support issue more than a docs issue. Do you have a support ticket number? We can ask support about following up.

Best,
Twilio SendGrid Docs Team

**Comment by astuteape** [comment]
Hello @Supertroop6 

We hope you've made progress with your issue. If you still need assistance, please add more details and feel free to reopen this Issue.
