### ISSUE TITLE
email.sendgrid.com has SSL cert problem

### ISSUE THREAD

**Issue by MayamaTakeshi** [sendgrid/docs#6219]
Hi,
I received an email with an invitation to join a team at SendGrid.
When I click "Set up your Profile" in the email, the browser opens a link at https://email.sendgrid.com/*.

However, both firefox and chrome complain about SSL certs:

Firefox:
```
Warning: Potential Security Risk Ahead

Firefox detected a potential security threat and did not continue to email.sendgrid.com.
If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

What can you do about it?

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.
```

Chrome:
```
Your connection is not private
Attackers might be trying to steal your information from email.sendgrid.com (for example, passwords, messages, or credit cards).
Learn more
  NET::ERR_CERT_COMMON_NAME_INVALID
```

So since i can't login, I can't inform this problem via support portal. So I'm trying here.

Regards,
Takeshi Mayama

**Comment by astuteape** [comment]
Hi @MayamaTakeshi 

We're sorry you're having this issue. I followed up internally, and it looks like a fix for this is now in place. You may need to have the links resent to you to address the issue.

In the future, you can submit a support ticket without logging in by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

Twilio SendGrid Docs Team

**Comment by MayamaTakeshi** [comment]
Hi @astuteape,
Understood.
Thank you.

**Comment by AlphaJuliettOmega** [comment]
@astuteape can you elaborate on what the issue was, please?

**Comment by astuteape** [comment]
Hi @AlphaJuliettOmega,

I'm sorry, I don't remember the exact issue, but I think it was something about the certs having been updated. If you are seeing this issue, please don't hesitate to submit a support ticket at https://support.sendgrid.com.

Twilio SendGrid Docs Team
