### ISSUE TITLE
parse incoming webhook url is not working for live site

### ISSUE THREAD

**Issue by v-grant** [sendgrid/docs#6220]
Hi, This is Vernon.
I've registered the ngrok url for the local to test the parse incoming webhook functionality.
And it works well.
So I've deploy my source into live, then change the webhook url with live one in sendgrid.
But it seems it does not work, it doesn't call new url.
It doesn't leave any log, even I've implemented the logging function.
How can I check that the sendgrid call our live url in sendgrid?

**Comment by astuteape** [comment]
Hi @v-grant 

We're sorry you're having trouble with Parse. I think support is the more appropriate avenue to help you troubleshoot this specific setup issue. You can contact our Support team directly, and they can help you out. You can access support contact options by logging into https://support.sendgrid.com. If you find that there's information missing from the Parse docs, feel free to reopen this Issue.

Twilio SendGrid Docs Team
