### ISSUE TITLE
Specification of Default values for substitution tags

### ISSUE THREAD

**Issue by thoufer** [sendgrid/docs#6221]
It appears that the format for the specification of default values in substitution tags has changed from 

{{ first_name | "default value" }}  to {{ insert first_name "default=default value }

The original format is still specified in the "TIP" block under "Using substitution tags" at [https://sendgrid.com/docs/ui/sending-email/editor/](https://sendgrid.com/docs/ui/sending-email/editor/)

**Comment by astuteape** [comment]
Thank you for bringing this to our attention. We'll push a fix shortly.
