### ISSUE TITLE
Where is the support when "Your account is temporarily under review." ??? ( Request #5043135)

### ISSUE THREAD

**Issue by loginformweb** [sendgrid/docs#6234]
Request #5043135

I have a very strong problem with the support of SendGrid, The button "Continue" under the text "What can we help you with?" doesn't work, in this way my account is temporarily under review, my web-store cannot send important notifications, and the support where is???

I sent an email to the support 1 day ago to ask some strange activity I looked on Activity Feed, They didn't reply yet! 

Please support me!!!

## Actual content

**Link to page**:

**Comment by astuteape** [comment]
Hello @loginformweb 

We're sorry for the trouble. Do you have a support ticket number I can reference?

**Comment by loginformweb** [comment]
yes dure the support ticket is #5043135

**Comment by astuteape** [comment]
I have contacted Support, and they are looking into the issue. Thank you for your patience.

**Comment by loginformweb** [comment]
Please, let me know about my ticket #5043135
