### ISSUE TITLE
My emails have stopped and you are not responding to my complaints

### ISSUE THREAD

**Issue by drrishab** [sendgrid/docs#6238]
I am Dr. Rishab Sharma Co-Founder Thydoc Private Limited. And I have paid for your Email delivering services. Despite that, you have stopped my emails since 06/09/2020.
I have been complaining about this issue to your customer service since 8/9/2020 and nobody is responding to my complaints. Because of your incompetency, I am losing a lot of my business. My SendGrid Account Number is 15712676. Start my service otherwise we have to take the legal route and sue you to pay for compensation for our losses.
I am attaching my Invoice and the screenshot of the tickets I have raised.

Dr. Rishab Sharma 
Sendgrid account No. 15712676 
Website : https://www.thydoc.com/
Email   : info@thydoc.com
Mobile : +91-9610011223, +91-9116877364
![Screenshot 2020-09-13 23 19 54](https://user-images.githubusercontent.com/70575474/93044597-e6f8ef80-f672-11ea-94f9-9355e2b9bb1c.png)
[sendgrid billing.pdf](https://github.com/sendgrid/docs/files/5216159/sendgrid.billing.pdf)

**Comment by tparkersendgrid** [comment]
Hello,

Thank you for reaching out here with context related to open issues for stopped mail on the account "thydoc".  I confirmed that all communications from our support team have been merged into the ticket 5043227.  Our support team replied there, and if you have any outstanding questions, please direct your questions to them there.

Apologies for the disruption and delays related to these inquiries.

Nathan P

**Comment by astuteape** [comment]
Thank you @tparkersendgrid 

As this issue is being handled by support, we will close it here in the docs. Thank you for your patience and understanding @drrishab
