### ISSUE TITLE
web api v3 documentation error.

### ISSUE THREAD

**Issue by komkom** [sendgrid/docs#6247]
The documentation in  https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Request-Body-Parameters
states wrongly that "subject" is not required.
But it is required.

**Comment by komkom** [comment]
Or here another way to see it.
https://github.com/sendgrid/docs/blob/old-master/source/API_Reference/Web_API_v3/Mail/index.html#L107
 {% api_table_param subject string No "" "The subject line of your email." 1 %}

**Comment by Whatthefoxsays** [comment]
Hi @komkom, 

The API reference shown above is out dates and soon-to-be deprecated. I apologize for the inconvenience. Please refer to this set of [documentation](https://sendgrid.com/docs/api-reference/) in the future.  

The optional subject you're looking at is nested under [Personalizations](https://sendgrid.com/docs/for-developers/sending-email/personalizations/), and if there's a subject specified within the personalization it is not required in the request body. Please let me know if you have any additional questions. 

Thank you,

The Twilio SendGrid docs team
