### ISSUE TITLE
Broken link to "segment" (404) on "Getting Started with Automation" page

### ISSUE THREAD

**Issue by adamalton** [sendgrid/docs#6259]
On this page: https://sendgrid.com/docs/ui/sending-email/getting-started-with-automation/ under the [Create a Custom Automation section](https://sendgrid.com/docs/ui/sending-email/getting-started-with-automation/#create-a-custom-automation), item 4 in the bullet list contains a link to ["segment"](https://sendgrid.com/docs/managing-contacts/segmenting-your-contacts/) which gives a 404 page.

I think that the URL is missing `/ui/`, and should link to here: https://sendgrid.com/docs/ui/managing-contacts/segmenting-your-contacts/

**Comment by Whatthefoxsays** [comment]
Hi @adamalton, 

Thanks for the feedback! We'll get this fixed right away, but for future reference, you can always click the "edit this page" link at the bottom of any of our docs pages and do a PR if you're up for it. 

Thanks again!

The Twilio SendGrid docs team

**Comment by adamalton** [comment]
Thanks Carly. I was a newbie to that areas of the docs, so wasn't 100% sure of the fix, and hence decided to let someone else fix it 🙂 .
