### ISSUE TITLE
Upgrade uncertainty: Our apologies for the delay in your ability to upgrade.

### ISSUE THREAD

**Issue by plamber** [sendgrid/docs#6271]
Dear SendGrid team,
we moved our subscription from a SendGrid Subscription hosted in Azure to a direct subscription taken from your Website recently. We are mainly using this subscription for our application to send notifications to our users. I am not sure if this is the right channel to give this feedback. I believe that this situation could be improved by doing some minor changes to the documentation.

We would like to change the plan from free to pro to obtain a dedicated IP address not shared with other senders. However, we are still receiving this error message:

> `Our apologies for the delay in your ability to upgrade.
To enhance security for all of our users, we do not allow immediate upgrade upon signup.
We recommend continuing to use your free account during this time to enable account security features, set up and authenticate any additional sending domains, and begin to send wanted communications slowly within your free plan allotment as you build your domain reputation.
We will be in touch with more information about your ability to upgrade.`

It is not immediately clear what exactly has to happen for this upgrade to be unlocked. After doing some research I found this article: https://sendgrid.com/docs/ui/account-and-settings/upgrading-your-account/. The section 'To unlock your Twilio SendGrid account' provides the hints that are required to unlock the account. Nevertheless, it is still not clear how long it takes to unlock the necessary upgrade. I would expect to see a link to this document directly in the application.

We also opened a ticket (#5157400) a week ago hoping to get some better insights or finding a way to upgrade sooner. The ticket remained unanswered so far. I understand that you might be overwhelmed with requests. On the other hand, having the ticket unanswered so long increases the uncertainty on a customer end.

This uncertainty makes it difficult to do some planning from our service. We would like to use SendGrid as a platform but are not sure if we should proceed this path due this lack of information and transparency. I think this problem could be fixed by providing a slightly updated information flow to new customers. 

Thank you for your feedback,
Patrick

**Comment by plamber** [comment]
Hi,
I just wanted to share an update. 

I was contacted by the SendGrid support. I have been told that the time for waiting is 30 days. I haven't seen this information anywhere on the homepage or app. Maybe it would be helpful to add this in the message above.

br,
Patrick

**Comment by astuteape** [comment]
Hi @plamber 

Thank you for the the update. I'm glad Support has been in touch. Thank you for your patience and that suggestion. I will pass that suggestion along to the team. I'm going to close the issue in the docs, but feel free to reopen it if I've missed anything.

Best,
Twilio SendGrid Docs Team
