### ISSUE TITLE
unable to send email via sendgried 550 error 

### ISSUE THREAD

**Issue by pramod375** [sendgrid/docs#6283]
## Expected content
Sendgried unable to send email to receive email from the website order but If I tried via terminal I am able to get an email.

## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @pramod375

We're sorry you're experiencing this issue! Since this isn't a documentation issue, please contact our Support Team. You can access support contact options by logging into https://support.sendgrid.com.

Twilio SendGrid Docs Team
