### ISSUE TITLE
We are unable to login

### ISSUE THREAD

**Issue by ganapathinuvem** [sendgrid/docs#6301]
![SendGrid1](https://user-images.githubusercontent.com/33618916/96664571-ba6e7c80-1370-11eb-8212-a1af9b1091e7.JPG)

## Expected content

We are unable to login , error" Your IP address is not whitelisted. See http://send.gd/1PemvHz for more details." 

## Actual content
1 We are unable to login , error" Your IP address is not whitelisted. See http://send.gd/1PemvHz for more details." 
2. We have reset the password still same issue
3. Supporting team not responding, all business emails not delivered
4. With out able to login, we can not reach support team, but we are unable to login from last 24 hours. Emails not delivered form last 30 hours too poor service from SendGrid
**Link to page**:
https://app.sendgrid.com/login

**Comment by ganapathinuvem** [comment]
We have facing problem since Yesterday, We have raised ticket , not good response from SengGrid supporting Team,  very poor service, We do not recommend SendGrid We will look into good provider for "sending emails"
Thank you!

**Comment by Whatthefoxsays** [comment]
Hi @ganapathinuvem, 

Can you please provide a support ticket number so I can try and follow up for you?

**Comment by ganapathinuvem** [comment]
they have respond after 3 days, very poor service from them. We never recommand SendGrid
support.sendgrid.com/hc/requests/5280238
support.sendgrid.com/hc/requests/5276698
support.sendgrid.com/hc/requests/5276644
support.sendgrid.com/hc/requests/5273749
support.sendgrid.com/hc/requests/5276464
support.sendgrid.com/hc/requests/5276642
support.sendgrid.com/hc/requests/5277616
