### ISSUE TITLE
Can't receive the Single Sender Verification email

### ISSUE THREAD

**Issue by RichardSunMS** [sendgrid/docs#6302]
Hi Support team, I am trying to add a single sender in my account, email like "***@outlook.com", but I am not getting the email in my mailbox for this sender verification email, can you help check what is wrong? 

Thanks.
Richard.

**Comment by Whatthefoxsays** [comment]
Hello @RichardSunMS,

We're sorry you're having this issue! This is the docs repo, so unfortunately you have to open a support ticket on our Support site to get some help looking into what's up with your account. You can access support contact options by logging into https://support.sendgrid.com.

The Twilio SendGrid Docs Team
