### ISSUE TITLE
Unable to Access my Sendgrid Account, as no text message received for two factor  authentication

### ISSUE THREAD

**Issue by mayank304** [sendgrid/docs#6322]
Hi, 
On 28th October, 2020 I made account in SendGrid in the name of Mayank (email id : mayank@omniwi.com).  I have send mailer through this account.

Today i am unable to login through this account as it required two factor authentication. But I am not receiving text message on my mobile.

Either i have put wrong mobile no by mistake or sms is not coming,  My correct mobile no is 91 9899435895.

Please send me authentication on my email id and close the two factor authentication option. 

Please help me in this regards on priority.

Mayank khare
Mob: +91 9899435895
![Screen shot](https://user-images.githubusercontent.com/73899818/98010634-ebdd5280-1e1c-11eb-9c8e-de37c1673c1f.png)

**Comment by astuteape** [comment]
Hello @mayank304 

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

Twilio SendGrid Docs Team

**Comment by mayank304** [comment]
> Hello @mayank304
> 
> We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in, and one of our fantastic support people will get back to you. Hope this helps!
> 
> Twilio SendGrid Docs Team

Hi I tried but could not get success.

Please help me, i have to download report on priority.

**Comment by astuteape** [comment]
Do you have a support ticket number? I can ask support to look into it.

**Comment by mayank304** [comment]
Hi , 

I can not get the option to raise a ticket with out login. 

Whatever detail required, tell me i will give. 

Please help me in this matter. 

Regards 
Mayank khare

**Comment by mayank304** [comment]
Hi, 
I am unable to raise ticket. 

Please find below detail and raise the ticket from my end. 
On 28th October, 2020 I made account in SendGrid in the name of Mayank (email id : [ mailto:mayank@omniwi.com | mayank@omniwi.com ] ). I have send mailer through this account. 

Today i am unable to login through this account as it required two factor authentication. But I am not receiving text message on my mobile. 

Either i have put wrong mobile no by mistake or sms is not coming, My correct mobile no is 91 9899435895 . 

Please send me authentication on my email id and close the two factor authentication option. 

Please help me in this regards on priority. 

Regards 
Mayank khare

**Comment by astuteape** [comment]
Hello @mayank304 

You can create a support ticket without logging in. You need to go to https://support.sendgrid.com and click "Trouble Logging in?". That link will allow you to create a ticket without logging in. It's below the blue box with the search bar.

<img width="1625" alt="Screen Shot 2020-11-04 at 8 53 19 AM" src="https://user-images.githubusercontent.com/3976196/98141508-8d938c80-1e7b-11eb-8697-5af5e9ba07c9.png">

I hope this is helpful. If it's still unclear, please reply to this thread.

Best,
Twilio SendGrid Docs Team

**Comment by mayank304** [comment]
Hi , 

I tried but could not get the option to raise the ticket. 

Its humble request to sort out the issue on priority. 

Regards 
Mayank khare

**Comment by mayank304** [comment]
Hi, 

My problem still exist, i am unable to login due to 2FA, as i am not receiving the test message. 

Regards 
Mayank khare

**Comment by mayank304** [comment]
Hi sir, 

My problem still not resolved. 

Regards 
Mayank khare

**Comment by mayank304** [comment]
Hi, 
Please resolve the issue. 

Regards 
Mayank khare

**Comment by astuteape** [comment]
Support has indicated that they have an open ticket for you and will reach out again in case you have not received it.
