### ISSUE TITLE
Single Sender authentications is not available for our account

### ISSUE THREAD

**Issue by tbskishanp** [sendgrid/docs#6330]
HI There,

We have several account for Sendgrid, and this account doesn't have option to add the single sender authentication. So  if we don't provide information for single sender authentication then will it work or any further steps are required from our end.

Please let us know the steps to verify the single sender authentication.

**Comment by Whatthefoxsays** [comment]
Hello @tbskishanp,

The best thing you can do to get this fixed is to create a support ticket. You can access support contact options by logging into https://support.sendgrid.com. 

Thank you,

Twilio SendGrid Docs Team

**Comment by tbskishanp** [comment]
Thanks for your reply,

I have already created a support ticket for the same,
But I am not getting any reply from the SendGrid support team.

Is there any email where I can send mail to the sendgrid support team?


K Parmar
*Team Lead | B.E. IT*
<https://magnusminds.net/>
