### ISSUE TITLE
Spelling mistakes in the term Handlebars 

### ISSUE THREAD

**Issue by acorncom** [sendgrid/docs#6354]
Reading through the docs, I noticed a number of tabs that had a slight misspelling

## Expected content
Handlebars

## Actual content
Hanblebars

**Link to page**:
https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/

![image](https://user-images.githubusercontent.com/802505/101029609-26581d80-358a-11eb-969a-b0fd0c8dbf3c.png)

**Comment by Whatthefoxsays** [comment]
@acorncom, 

Thanks for reporting this issue. The docs have been updated!

https://github.com/sendgrid/docs/pull/6361
