### ISSUE TITLE
Add required API keys Access rights for endpoints

### ISSUE THREAD

**Issue by matthieusieben** [sendgrid/docs#6357]
Which authorizations do I need to add to an API token to be able tu use:

https://sendgrid.com/docs/API_Reference/Web_API_v3/Whitelabel/domains.html

**Comment by Whatthefoxsays** [comment]
Hi there @matthieusieben, 

You can find the list of API Key permissions [here](https://sendgrid.api-docs.io/v3.0/api-key-permissions/api-key-permissions#Domain-Authentication). Please use this API reference going forward. We're working hard on getting the other site deprecated and redirected. I apologize for the inconvenience. 

Thank you,

Twilio SendGrid Docs team
