### ISSUE TITLE
API Reference Index

### ISSUE THREAD

**Issue by stephenrjr** [sendgrid/docs#6382]
https://sendgrid.com/docs/API_Reference/index.html

Near the bottom of this page are 2 links under 'Reseller APIs'

Both links refer to the same page as the link itself.

**Comment by astuteape** [comment]
Hi @stephenrjr 

We apologize for the confusion. That page is outdated and will soon be removed. Again, we apologize for the confusion. In the near future, that page should redirect to https://sendgrid.com/docs/api-reference/, which you can visit now for our current v3 API reference.

Best,
Twilio SendGrid Docs Team
