### ISSUE TITLE
SMTP apikey upgrade docs don't warn about base64 linewrap

### ISSUE THREAD

**Issue by michaelabuckley** [sendgrid/docs#6385]
## Expected content
When submitting base64 encoded apikey values, be careful that your base64 libraries do not insert line breaks, or remove them after base64 encoding.  SMTP is a line-oriented protocol, and linefeed chars will break the login.

## Actual content
none.

**Link to page**:
https://sendgrid.com/docs/for-developers/sending-email/upgrade-your-authentication-method-to-api-keys/

**Comment by astuteape** [comment]
Hi @michaelabuckley 

Thank you for the note. That's a good call-out. We'll update the doc.

Best,
Twilio SendGrid Docs Team
