### ISSUE TITLE
Cancel Account

### ISSUE THREAD

**Issue by danilogo** [sendgrid/docs#6386]
I want the full and complete cancellation of the two accounts below: - You can end any service or charges from today.

danilo.gomes@vianovabeneficios.com.br
danilo.gomes@rhfacil.com.br

The site had problems when I tried to withdraw my credit card when accessing the option "my products" - I cannot cancel following its documentation. So I blocked the card so there will be no more charges, but I need your cancellation too.

The reason is the difficulty implemented with the steps in two factors, keeping me stuck off the site when I needed to carry out a campaign for the company.
That way we are migrating our systems to other services.

Your ticket system is also very confusing, when I try to open a ticket, I'm directed to the FAQ, and in the FAQ when I don't resolve the issue, I go back to the ticket link, getting stuck in a loop without the possibility of opening a ticket.

**Comment by astuteape** [comment]
Hello @danilogo 

We're sorry you're having this issue. The documentation team cannot cancel an account. We're sorry you're having issues opening a ticket. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can tell us a little more about your problem without having to log in. Once your ticket is submitted, the support team should be able to help you from there. Thank you for your patience, and we hope this is helpful.

Twilio SendGrid Docs Team
