### ISSUE TITLE
Integrating with the SMTP API

### ISSUE THREAD

**Issue by artisticcheese** [sendgrid/docs#6387]
https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html

Please change wording to explicitly say that key name is `apiKey` exactly as it's written shall be put in username field. I imagine I'm not the only one which assumed `apiKey` reference was to reference a key name which was created in API rather then explicit term `apiKey` which is required instead.

**Comment by astuteape** [comment]
Hi @artisticcheese

Thank you for the note. We'll add some text to make that clear.

Best,
Twilio SendGrid Docs Team
