### ISSUE TITLE
Azure does not offer free tier SendGrid option

### ISSUE THREAD

**Issue by timvandenhof** [sendgrid/docs#6398]
Please notice on the documentation that the Free option is no longer available on Azure.

Free option is mentioned:
- Screenshot on the Azure documentation
- In the description on the Azure marketplace
- On the website.

The screenshot in the documentation could also use a screenshot of the current Azure Portal UI. The current one is quite outdated.

## Expected content
A notice/warning that the Free tier is no longer available on Azure.

## Actual content

Documentation:
![azure_account_error](https://user-images.githubusercontent.com/2083464/104208680-0f320880-5431-11eb-9878-ee5e07855417.png)
(See selected pricing tier.)

Description in Azure marketplace:
![Screenshot 2021-01-11 at 16 06 15](https://user-images.githubusercontent.com/2083464/104208030-c7ab7c80-5430-11eb-970e-eb8c2ce15a7b.png)

Website:
![Screenshot 2021-01-11 at 17 12 34](https://user-images.githubusercontent.com/2083464/104208534-ec9fef80-5430-11eb-9c53-3308a7f84ff6.png)

Actual experience in Azure:
![Screenshot 2021-01-11 at 16 07 22](https://user-images.githubusercontent.com/2083464/104208291-db56e300-5430-11eb-8028-7d04a509d250.png)

**Link to page**: https://sendgrid.com/docs/for-developers/partners/microsoft-azure/
**Source file**: https://github.com/sendgrid/docs/blob/develop/content/docs/for-developers/partners/microsoft-azure.md

**Comment by timvandenhof** [comment]
There are some questions going on on the Microsoft forums as well: https://docs.microsoft.com/en-us/answers/questions/203531/azure-free-sendgrid-not-available.html

Sendgrid confirmed on Twitter that the Free tier is indeed discontinued, and that new pricing plans will be anounced somewhere in 2021 Q1.

![image](https://user-images.githubusercontent.com/2083464/104216260-1c9fc080-543a-11eb-9866-574ab34810ef.png)

https://twitter.com/SendGrid/status/1346167374907662338

**Comment by Whatthefoxsays** [comment]
Hi @timvandenhof! 

Good news! There is now a free tier option with SendGrid and Microsoft Azure. You can find details [here]https://azuremarketplace.microsoft.com/en-us/marketplace/apps/sendgrid.tsg-saas-offer?tab=PlansAndPricel).
