### ISSUE TITLE
How to login if I don't have or I've lost smartphone to receive 7 codes Two-Factor Authentication

### ISSUE THREAD

**Issue by diegohdez90** [sendgrid/docs#6424]
## Expected content

I don't have my old smartphone to login in my dashboard and the page require Two-Factor Authentication, so How can I login to my sendgrid dashboard?

## Actual content

In this moment I don't have my smartphone to login my dashboard and the page required my 7 codes Two-Factor Authentication

Would you like to support me an disabled Two-Factor Authentication or send me 7 codes to email, please.

Username: it.starnet.pue.mx
Email: diegohdez12@gmail.com

**Link to page**:

**Comment by astuteape** [comment]
Hello @diegohdez90 

We're sorry you're having this issue. You can access support contact options by going to https://support.sendgrid.com and clicking "Trouble Logging in?". From there, you can get help without having to log in, and one of our fantastic support people will get back to you. Hope this helps!

Twilio SendGrid Docs Team
