### ISSUE TITLE
Your Single Sender Verification documentation states the following: //////////////////// Adding a Sender  1. Under Settings in the navigation bar, click Sender Authentication.  2. Proceed with Single Sender Verification by selecting Get Started under Verify an Address. ////////////////////  The problem is there is no 'Single Sender Verification' option on the page.  What now??

### ISSUE THREAD

**Issue by Garhag** [sendgrid/docs#6425]
## Actual content

**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hi @Garhag, 

Can you please attach a screenshot?

**Comment by Garhag** [comment]
Hi Carly,

Thanks for getting back with me!!

I'm not the end user so I don't have a screen shot. I know that's not at all helpful to you, but the issue is with a customer of ours who is also a customer of yours. She mentioned she was going to open a ticket with your support team, but didn't get a response from her after that so I called her. She said she's going to be out of the office for a few days, but will get one of her team members to contact me. Once that happens I'll let them know it's going to be easier to have them work directly with your support team since I can't provide you with their account information for SendGrid. If they do open a ticket with your support team though (and I expect they will), then I can join any support calls you have with them if you want me to and if you can provide me with enough advanced notice of the call.

At any rate, I'll reply again once I know whether they've opened a support ticket with you.

One last thing, I've also got another SendGrid ticket open for this same issue and it's being worked by Andreea C. (Twilio SendGrid Support) support@twiliosendgrid.zendesk.com<mailto:support@twiliosendgrid.zendesk.com>

Have a great day,


Gary Hagen
Advanced Cloud Engineering
Customer Engineer 2

Office: +1-469-775-4774
GarHag@microsoft.com<mailto:GarHag@microsoft.com>
Working hours: Mon - Fri  7am - 4pm CST
Azure Identity A.C.E  Manager - Nicolas Souza (nsouza@microsoft.com<mailto:nsouza@microsoft.com>) +1 469-775-2900
