### ISSUE TITLE
Couple links don't work on setting-up-the-inbound-parse-webhook

### ISSUE THREAD

**Issue by erikt9** [sendgrid/docs#6434]
## Expected content
Working links

## Actual content
The "Parse API" and "Parse Webhook Stats" links at the bottom of the page give 404s.

**Link to page**:
https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/

**Comment by thinkjrs** [comment]
These seem to be working for me, see below.

![image](https://user-images.githubusercontent.com/16545607/114188410-bd552d80-990e-11eb-8172-503fca001421.png)

I did experience a cold start ~ 30 seconds long on first load, however.

**Comment by erikt9** [comment]
The links now work for me as well.
