### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by wagnercateb** [sendgrid/docs#6440]
Hi,
The Web API link at https://sendgrid.com/docs/for-developers/sending-email/django/ is broken.
Besides, I followed the instructions but keep receiving error 111 connection refused from a PythonAnywhere project (among others).
Regards,

**Comment by Whatthefoxsays** [comment]
The link has been fixed. I'll add an issue to the backlog to review the doc and verify accuracy. Thanks for your feedback!
