### ISSUE TITLE
godaddy

### ISSUE THREAD

**Issue by jensysantana** [sendgrid/docs#6469]
## Actual content

**Link to page**:

**Comment by jensysantana** [comment]
hi i have error when i try to register my dns in godaddy.
Add all of these records to GoDaddy's DNS section.

but i have error because they not seens like dns

**Comment by Whatthefoxsays** [comment]
Hello @jensysantana

We're sorry you're having this issue! 

Make sure you're only entering the host name minus the domain at the end. 

**For example:** `url0007` and not `url0007.domain.com` or `s1._domainkey` and not `s1._domainkey.domain.com`. 

Points to* - Enter the value as provided by SendGrid.

If this doesn't work for you, please log into https://support.sendgrid.com and file a ticket. 

SendGrid Docs Team
