### ISSUE TITLE
Sendgrid locked me out from my account with its two-factor authentication

### ISSUE THREAD

**Issue by Terefic** [sendgrid/docs#6482]
Sendgrid locked me out from my account with its two-factor authentication.

I went to the login page. I entered my password. I was prompted then to enter a two-factor code. That's where the nightmare begins...

- I don't have Authy. I tried to send the code via text message. I didn't receive anything.
- I downloaded Authy from the App Store. It's asking me to login to scan the QR code. I cannot login.
- I tried to https://support.sendgrid.com. But it's asking me to login to create a support ticket. I cannot login.
- I tried to call. Nobody answers.

Does anyone know what to do? How can I get access to my Sendgrid account?

**Comment by Whatthefoxsays** [comment]
Hi @Terefic,

We're sorry you're having this issue! You can create a support ticket without logging in by going to https://support.sendgrid.com and clicking "trouble logging in" link. 

![image](https://user-images.githubusercontent.com/13628723/110040462-1de5bf00-7d00-11eb-8b5f-28c61f1e2006.png)

The other consideration is once you get logged in to make sure that your mobile phone is the number on record with the account so you get your access codes in the future. Make sure your personal data is up to date to avoid getting locked out again. 

Twilio SendGrid Docs team

**Comment by gatos-cc** [comment]
I'm in the same boat.  I already have Authy, and have been using it for years.  And my phone number is correct.  But I'm not getting any texts from Sendgrid with a code to enter.

Why wouldn't you guys just present a QR code like every other site?  If you want to validate that we have a valid phone number, fine - but locking us out as part of an MFA setup is ridiculous.
