### ISSUE TITLE
Whole web app stops if one email id is wrong in the array send to node.js app in send grid api and returns an error 

### ISSUE THREAD

**Issue by Gaurvendra** [sendgrid/docs#6507]
## Expected content
The whole web app stops if one email id is wrong in the array to send to node.js app in send grid API and returns an error

## Actual content
The whole web app stops if one email id is wrong in the array to send to node.js app in send grid API and returns an error
**Link to page**:

**Comment by Whatthefoxsays** [comment]
Hello @Gaurvendra,

Thanks so much for your feedback! We're sorry you're having this issue. You can access support contact options by logging into https://support.sendgrid.com.

SendGrid Docs Team
