### ISSUE TITLE
Documentation is out of date/inaccurate

### ISSUE THREAD

**Issue by JoelMacKenzie** [sendgrid/docs#6516]
Looking at documentation here: https://sendgrid.com/docs/for-developers/tracking-events/getting-started-event-webhook/

Under Getting Started, the fourth step says: "Turn on Event Notification".  I don't see anything labeled "Event Notification".

**Comment by Whatthefoxsays** [comment]
Hi @JoelMacKenzie, 

Thank you for the feedback! I've updated the doc in this [PR](https://github.com/sendgrid/docs/pull/6523) and we'll take a closer look at all the steps listed.
