### ISSUE TITLE
SendGrid login issue 

### ISSUE THREAD

**Issue by mnajmi** [sendgrid/docs#6519]
when i enter the login username and password in response i recived error **You are not authorized to access SendGrid, please contact [Support](https://support.sendgrid.com/hc/en-us).** and support link redirected to this url "https://support.sendgrid.com/hc/en-us" and when i reached this page view this text **"Login & Contact Support"**.

what's this.

**Comment by Whatthefoxsays** [comment]
Hi @mnajmi, 

You don't actually need to log into the support console to create a ticket. From the support page that you linked above, you can click "Trouble logging in?" and create a ticket from there. 

![image](https://user-images.githubusercontent.com/13628723/116321790-006d2880-a778-11eb-8667-411ecfce1318.png)

Hope this helps!
