### ISSUE TITLE
Signup Form Documentation?

### ISSUE THREAD

**Issue by SeanSith** [sendgrid/docs#6521]
## Expected content
When attempting to navigate to information about [Integrating a Signup Form](https://sendgrid.com/docs/ui/sending-email/getting-started-with-automation/#create-a-signup-form/) after creating a Signup Form, we are directed to a page with a missing anchor.

There is no mention of 'forms' on the page to which we are directed.

**Comment by Whatthefoxsays** [comment]
Hey @SeanSith,
 Thanks for the feedback! Was that link in the app itself? Or from another place in the docs?

**Comment by SeanSith** [comment]
It was in app.sendgrid.com just after we created a Signup Form through the Marketing section.

**Comment by Whatthefoxsays** [comment]
@SeanSith, 

I've reported this to our product team and they're fixing the link in the app. Thank you for the feedback!
