### ISSUE TITLE
Login to contact Support

### ISSUE THREAD

**Issue by remydev** [sendgrid/docs#6525]
Please avoid submitting support questions here. You can contact our support team at https://support.sendgrid.com.

If you are able to login to https://support.sendgrid.com:
1. Click "Login & Contact Support."
2. Then, select "Contact Support" to see your contact options.

It's  crasy !

You ask to login to contact support, but i can't login and you ask to contact support !
![image](https://user-images.githubusercontent.com/10176486/116544059-f588d400-a8ee-11eb-88c7-85a6bf3ed01a.png)

**Comment by Whatthefoxsays** [comment]
Hi @remydev, 

You don't need to log in in order to open a ticket. Go to https://support.sendgrid.com and click the "trouble logging in?" link to file a ticket. 

![image](https://user-images.githubusercontent.com/13628723/119554087-82417900-bd59-11eb-8972-aa197ea00585.png)
