### ISSUE TITLE
Missing closed paren

### ISSUE THREAD

**Issue by philipkiely** [sendgrid/docs#6538]
## Expected content

content = Content("text/plain", "and easy to do anywhere, even with Python")

## Actual content

content = Content("text/plain", "and easy to do anywhere, even with Python"

Note the missing close paren

**Link to page**:

https://sendgrid.com/docs/for-developers/sending-email/quickstart-python/

**Comment by Whatthefoxsays** [comment]
Hi @philipkiely, 

I did a search in the doc and didn't find a missing parenthesis so I'm going to close this issue. 

Thanks for taking the time to reach out!
