### ISSUE TITLE
typo on page

### ISSUE THREAD

**Issue by ArnelPManalo** [sendgrid/docs#6540]
Typo in this link: https://sendgrid.com/blog/smtp-service-crash-course/

"Today, we’re re-visiting Simple Mail Transfer Protocol (SMTP) basics including the benefits of using SMTP, who should be leveraging STMP in their email programs, and some common questions that email clients ask when getting set up."

Typo STMP should be SMTP.

**Comment by Whatthefoxsays** [comment]
Hi @ArnelPManalo,

I've reported this to our blog team and they'll get it fixed asap. Thank you for the feedback!
