### ISSUE TITLE
Weird encoding while receiving mail from old clients

### ISSUE THREAD

**Issue by Cerceis** [sendgrid/docs#6555]
Sever Environment: NodeJS

Issue : Encoding problem on Japanese characters from some old client

While i am able to get inbound parse working fine. From Gmail/Hotmail and all other sorts of client (All types of languages works, no encoding problem). There is a specific client that in my company use to send emails has this problem of weird Japanese encoding.

This could be a problem of our old client has no charset encoding selected. But emails from our old client sent to other client  (Gmail/Outlook/Others) does not have this issue. It means the problem only persist after it went through SendGrid.

Also, characters on email titles has no issue, it only happens in the email content.

Example:

Original Email from old client:

```
<Title>
This is Japanese title 日本語です
<Content>
This emails contain Japanese content
日本語です 
```

Below is the raw body received from my Nodejs Api end point:

```
{
  dkim: 'none',
  envelope: '{"to":[<new email client>],"from":<old email client>}',
  subject: 'This is Japanese title 日本語です',
  charsets: '{"to":"UTF-8","subject":"UTF-8","from":"UTF-8","text":"iso-2022-jp"}',
  SPF: 'none',
  headers: <omitted>
  to: <new email client>,
  from: <old email client>,
  text: 'This emails contain Japanese content\n\x1B$BF|K\\8l$G$9\n',
  sender_ip: <omitted>,
  attachments: '0'
}
```
I tried to decode the string with "utf-8" / "iso-2022-jp", still it does not work.
Other clients(Gmail etc) have no issue displaying this email, so i assume this is a problem due to SendGrid parsing.

**Comment by awwa** [comment]
It seems your received body is not a raw body. Because Inbound Parse Webhook is supposed to POST with [multipart/form-data](https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/). But your body is JSON format. I recommend to check a raw payload that Nodejs received from SendGrid. 
Here is a useful tool for debugging.
https://requestbin.com/

**Comment by Cerceis** [comment]
> It seems your received body is not a raw body. Because Inbound Parse Webhook is supposed to POST with [multipart/form-data](https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/). But your body is JSON format. I recommend to check a raw payload that Nodejs received from SendGrid.
> Here is a useful tool for debugging.
> https://requestbin.com/

I am using "multer" to process multiform data. API is as simple as:
```
router.post("/" , multer.any(), (req,res)=>{
    const body = req.body
    console.log(body)
    res.status(200).end()
})
```
Would try to check out the data before it went through multer.

**Comment by Cerceis** [comment]
Fixed by using npm package "encoding-japanese" **before** saving the text into local file
The problem seems to be persist on text-only emails. Html emails works fine without conversion.

```
const Encoding = require('encoding-japanese');  
const result = Encoding.convert(body.text)
// Save result into desired location
```
