### ISSUE TITLE
Using Template Engine with SMTP API

### ISSUE THREAD

**Issue by argon** [sendgrid/docs#837]
The documentation does not state that for HTML templates to work the `html` property _must_ be set on the payload. If the `text` property is set without `html` it will only send email with the Text template.

I started with the [nodejs example](https://github.com/sendgrid/sendgrid-nodejs/blob/master/README.md#usage)

```javascript
var payload   = {
  to      : 'to@example.com',
  from    : 'from@other.com',
  subject : 'Saying Hi',
  text    : 'This is my first email through SendGrid'
}
```

Then I created a template with the correct HTML content and following the [template documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/smtpapi.html), I added the correct template filter to the SMTP API payload:

```json
{
  "filters": {
    "templates": {
      "settings": {
        "enable": 1,
        "template_id": "<my template id>"
      }
    }
  }
}
```

Invoking the API with my code I only received plain text messages based on the text template. As I was initially only testing HTML templates, the Text template only contained `<%body%>` so it was not obvious that templating was working at all. Only much later did I realise I needed to supply the `html` property for sendgrid to send an HTML email.

https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/smtpapi.html

**Comment by mbernier** [comment]
I am trying to track this issue down for you. In the meantime, can you please verify that your [Global Settings](https://sendgrid.com/account/global-settings) "Don't convert plain text emails to HTML" checkbox is unchecked?

**Comment by argon** [comment]
I can confirm the checkbox is unchecked.

**Comment by mbernier** [comment]
We can make an adjustment to the docs to make sure this is explicitly mentioned. Thanks for the heads up!

**Comment by trotha01** [comment]
@argon Are these changes sufficient: https://github.com/sendgrid/docs/pull/942/files

They can be seen in the docs here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Template_Engine/smtpapi.html

Let us know if you would like anything clarified further, and thank you for helping out with our docs!

**Comment by argon** [comment]
I think it would be better if it mentioned some more detail:

Both the `html` and the `text` properties should contain content. The `text` property is substituted into the `<%body%>` of the `text` template and `html` is substituted into the `<%body%>` of the HTML template. If the `text` property is present, but not `html`, then the resulting email will only contain the text version of the template, not the HTML version. The  `subject` property is used for both Text and HTML templates.

**Comment by mbernier** [comment]
I actually dig what you wrote, please check the following change: https://github.com/sendgrid/docs/pull/955/files

**Comment by argon** [comment]
That looks good to me, definitely would have saved me the confusion when I was working on it.

**Comment by mbernier** [comment]
Thank you so much for your thoughts and help on this!
