### ISSUE TITLE
Update Subuser Username Error

### ISSUE THREAD

**Issue by asiSendGrid** [sendgrid/docs#861]
### Overview
 ---
Looks like on [Update Subuser Username](https://sendgrid.com/docs/API_Reference/Customer_Subuser_API/subusers.html#-Update-Subuser-Username) a type is on the ***"task"*** param. Right now it appears as ***"setusername"***, when it should be ***"setUsername"***. The typo is currently resulting in the error below. 

```
{
  "error": {
    "code": 404,
    "message": "Not found"
  }
}
```

**Comment by mbernier** [comment]
This change will be live this afternoon.
