### ISSUE TITLE
SMTP API Overview

### ISSUE THREAD

**Issue by benburkhart1** [sendgrid/docs#901]
https://sendgrid.com/docs/API_Reference/SMTP_API/index.html

has a misspelling of "Requirements" (It's misspelled as "Requirments").

**Comment by trotha01** [comment]
Nice catch @benburkhart1!

It looks like @mbernier fixed this typo: https://github.com/sendgrid/docs/commit/04604b3a836b7d11e12e37d8a8a7d294eb8c1e28#diff-4909ab66a5f0d3f29e80b6937b349b39

**Comment by mbernier** [comment]
Thanks!!
