### ISSUE TITLE
Request URL incorrect of Parse API Web API v3

### ISSUE THREAD

**Issue by awwa** [sendgrid/docs#913]
I got an error when I send a request to [Parse API](https://sendgrid.com/docs/API_Reference/Web_API_v3/Webhooks/parse.html) of Web API v3.

```text
{"errors":[{"field":null,"message":"resource not found"}]}
```

Is the URL incorrect?

**Comment by amolbhandari** [comment]
did u get any answer on this?

**Comment by mbernier** [comment]
The v3 docs have been updated, @awwa can you please confirm?
