### ISSUE TITLE
error Subuser API "getsettings" for click tracking

### ISSUE THREAD

**Issue by asiSendGrid** [sendgrid/docs#916]
Looks like when you make the call below, it will return a empty string rather than a **_"0"**_ when click tracking **_"enable_text"**_ is disabled. 

```
curl -X "POST" "https://api.sendgrid.com/apiv2/customer.apps.json" \
    -F "api_user=***" \
    -F "api_key=***" \
    -F "task=getsettings" \
    -F "name=clicktrack" \
    -F "user=AnthonySendGrid"
{"settings":{"enable_text":""}
```

**Comment by thinkingserious** [comment]
Hello @asiSendGrid,<br /><br/>Thanks for your suggestion or question!<br />                                              <br />In an attempt to clear out our backlog,                                              we are closing out issues over 90 days old.                                             If this is still an issue, please feel free to reopen it.                                             <br /><br />Team SendGrid DX-Docs
