### ISSUE TITLE
Update sendgrid logo to svg

### ISSUE THREAD

**Issue by eddiezane** [sendgrid/docs#953]
Can't attach svg's to issues, but I have it locally.

Also an old one here https://sendgrid.com/assets/sendgrid-logo-596dfafabbe984409178ea912706a58d.svg

We'll have to nurse the css to fit. No rush on this one

**Comment by mbernier** [comment]
@two24studios Can we add this to the work you're doing?

**Comment by two24studios** [comment]
@mbernier absolutely!

**Comment by mbernier** [comment]
Thank you sir!
