### ISSUE TITLE
SendGrid for iPhone and iPad Email Activity

### ISSUE THREAD

**Issue by joflynn** [sendgrid/docs#968]
https://sendgrid.com/docs/User_Guide/SendGrid_for_Mobile/email_activity.html

Unlike the web interface, the search box does not currently work with a partial email address.  My typical use case is to search for all addresses at a given domain.  The web interface does this great, but the iOS app seems to only find exact matches.  It also fails without a message, the loading graphic shows briefly then disappears without updating the list.
Thanks

**Comment by mbernier** [comment]
adding @Reformant
