### ISSUE TITLE
Live API demo does not work with https://sendgrid.com, no CORS headers

### ISSUE THREAD

**Issue by umireon** [sendgrid/docs#996]
The API in api.sendgrid.com does not return CORS headers with sendgrid.com.
That makes the live API demo not working.

**Comment by brandonmwest** [comment]
Where are you located? I think we have a small group of API servers that is missing the CORS headers.

**Comment by umireon** [comment]
I have tried Blocks and Bounces API.
https://sendgrid.com/docs/API_Reference/Web_API/blocks.html
https://sendgrid.com/docs/API_Reference/Web_API/bounces.html

**Comment by mbernier** [comment]
It seems to be working fine for me from the US.  @umireon, where are you located in the world?

![](https://www.evernote.com/shard/s208/sh/7f832159-f88d-43c5-972c-8691b913b56b/a0ab2063e001e96ed3ea115d59b72dbb)

**Comment by marksomnian** [comment]
I'm also experiencing this. I'm located in Luxembourg.

**Comment by mbernier** [comment]
Thanks for following up, I am looking into this and will hopefully get it fixed soon.

**Comment by mbernier** [comment]
Sorry for slow response here. EPICALLY SLOW RESPONSE.

This is duplicated here https://github.com/sendgrid/docs/issues/1417 and there is an update there!
