### ISSUE TITLE
Not all available apps are documented

### ISSUE THREAD

**Issue by someone1** [sendgrid/docs#997]
Forward Spam, Return Path, etc. are not documented in the Web API Filter settings https://sendgrid.com/docs/API_Reference/Web_API/filter_settings.html

**Comment by mbernier** [comment]
Return Path is not an app that is available but forward spam is. 

Forward Spam is documented here: https://sendgrid.com/docs/User_Guide/Apps/forward_spam.html  It is confusing that we have it documented in two places, however I believe that with some work that I am currently doing, this confusion should be alleviated.

Thank you!
